Made microsoft session address non-readonly
Azure/azure-sdk-for-net pull request #10199
Opened 2020-02-27 20:37 UTC by rileymckenna

Made microsoft session address non-readonly

2020-02-28 04:54 UTC, isra-fel requested changes
Hi @rileymckenna  please see my inline comments, and the file `sdk/peering/Microsoft.Azure.Management.Peering/src/Generated/code-model-v1` I suppose it's checked in by accident?

2020-02-28 04:54 UTC, isra-fel commented on src/SDKs/_metadata/peering_resource-manager.txt
> +2020-02-27 20:33:18 UTC
This file should be in `/eng/mgmt/mgmtmetadata/` and seems to be in old format. Please follow the guide to [update your build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools) then generate again.
Thanks

2020-02-28 04:54 UTC, isra-fel commented on sdk/peering/Microsoft.Azure.Management.Peering/src/Microsoft.Azure.Management.Peering.csproj
> +
Please keep the CDATA tag
```suggestion
    <PackageReleaseNotes><![CDATA[
- Made microsoft session address non-readonly
]]>
```

2020-03-05 18:31 UTC, rileymckenna commented
@isra-fel ive fixed the build issues and updated the meta data properly

2020-03-06 02:35 UTC, isra-fel approved these changes
There's a known limitation of latest `autorest` that it would produce an extra (redundant) file `code-model-v1`. If you see it you can just remove it next time. Thanks

2020-03-06 17:45 UTC, rileymckenna commented
@isra-fel Ready to merge

2020-03-09 01:57 UTC, merged