CMK support for VMware migration and addition of few properties for VMware DR monitoring
Azure/azure-sdk-for-net pull request #10477
Opened 2020-03-10 07:05 UTC by anmolbhatia289

SDK for net changes corresponding to the changes in PR : https://github.com/Azure/azure-rest-api-specs/pull/8390

2020-03-10 07:05 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-03-11 03:19 UTC, isra-fel requested changes
Hi @anmolbhatia289 , could you
- Check in the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
    - In case you have trouble running `generate.ps1`, please update the autorest version in it from `latest` to `2.0.4413`
- Update release notes in csproj
- Write tests to cover new operations

Thanks

2020-03-11 17:25 UTC, anmolbhatia289 commented
We are planning to add tests related to all migration item operations in a separate PR.

2020-03-12 11:26 UTC, isra-fel approved these changes
OK. Looks good.

2020-03-12 11:26 UTC, merged