Allow the caller to pass IsCertRolloverEnabled for !net452 builds
Azure/azure-sdk-for-net pull request #10696
Opened 2020-03-19 00:06 UTC by manish1604

Allow the user to pass IsCertificateRollOverEnabled flag to be passed while acquiring token.

2020-03-19 00:32 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-03-19 07:07 UTC, shahabhijeet commented on sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/ApplicationTokenProvider.cs
> +#if !net452
Is this formatting change and rearranging of regions?
Or am I missing the change here?

2020-03-19 16:03 UTC, AlexGhiondea approved these changes
Approved, pending the answer to @shahabhijeet's question.

2020-03-19 16:04 UTC, AlexGhiondea requested changes
Actually -- we need to bump the package version for this.

2020-03-19 18:17 UTC, shahabhijeet commented on sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/ApplicationTokenProvider.cs
> +#if !net452
Sorry I was not able to figure out the diff, now I can :)
There is no harm in adding an overload, but you can still achieve the same using an existing overload on line 573 (new up AuthenticationProvider with your certificate and the additional flag)
The only downside to taking this change is to release this package and then update dependent packages and release them as well.
And if you can use the overload on line 573, we can avoid releases of these packages.
I will let @AlexGhiondea decide this.

2020-08-24 21:42 UTC, AlexGhiondea commented
@manish1604 could you take a look here and let me know if this is still needed? Thank you!

2020-09-18 16:14 UTC, jsquire commented
@manish1604 - Would you please be so kind as to let us know if this is still an active work stream or if we should close out the PR?

2020-09-18 16:51 UTC, manish1604 commented
This can be closed.

2020-09-18 16:52 UTC, closed without merging