Use configurable KnownAuthorityHosts for smoke tests (includes dynamic resource provisioning)
Azure/azure-sdk-for-net pull request #10880
Opened 2020-03-26 21:28 UTC by danieljurek

Maps the environment variable `AZURE_AUTHORITY_HOST_ALIAS` to the various `KnownAuthorityHosts` when using `DefaultAzureCredential` 

This also has support for the China Cloud and dynamic resource provisioning built in. The two efforts happened to dovetail.

2020-03-26 21:28 UTC, danieljurek commented
/azp run net - smoke-tests

2020-03-26 23:26 UTC, danieljurek commented
/azp run net - smoke-tests

2020-03-27 02:30 UTC, danieljurek commented
/azp run net - smoke-tests

2020-03-28 00:28 UTC, weshaggard approved these changes

2020-03-31 00:02 UTC, danieljurek commented on common/SmokeTests/SmokeTest/KeyVaultTest.cs
> +            var authorityHost = GetAuthorityHost(Environment.GetEnvironmentVariable("AZURE_AUTHORITY_HOST_ALIAS"), KnownAuthorityHosts.AzureCloud);
Use `AZURE_CLOUD` instead (from @jongio)

2020-03-31 03:46 UTC, danieljurek commented
/azp run net - smoke-tests

2020-03-31 16:27 UTC, jongio requested changes

2020-03-31 16:27 UTC, jongio commented on common/SmokeTests/SmokeTest/test-resources.json
>              "value": "[parameters('authorityHostAlias')]"
Would be good to update the param name too.

2020-03-31 16:28 UTC, jongio commented on eng/pipelines/smoke-tests.yml
> +      azureCloudArmParameters: "@{ storageEndpointSuffix = 'core.windows.net'; authorityHostAlias = 'AzureCloud'; }"
Same here - Update param name?

2020-03-31 22:33 UTC, jongio approved these changes

2020-03-31 23:38 UTC, merged