[ContainerRegistry] v5.0.0-preview
Azure/azure-sdk-for-net pull request #10902
Opened 2020-03-28 22:33 UTC by northtyphoon

Update container registry management sdk with latest api spec package-2019-12-preview

2020-04-02 16:03 UTC, isra-fel requested changes
Hi, please see my inline comments. Thanks

2020-04-02 16:03 UTC, isra-fel commented on src/SDKs/_metadata/containerregistry_resource-manager.txt
> +2020-03-25 06:26:44 UTC
This metadata file is in a wrong place and in an old format.
Please [update build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools) and generate again. Thanks

2020-04-02 16:03 UTC, isra-fel commented on sdk/containerregistry/Microsoft.Azure.Management.ContainerRegistry/src/Microsoft.Azure.Management.ContainerRegistry.csproj
> +		<Version>5.0.0-preview</Version>
Please update the versions in `AssemblyInfo.cs` as well

2020-04-02 16:03 UTC, isra-fel commented on sdk/containerregistry/Microsoft.Azure.Management.ContainerRegistry/src/Generated/SdkInfo_ContainerRegistryManagementClient.cs
> +                new Tuple<string, string, string>("ContainerRegistry", "Operations", "2019-12-01-preview"),
Since you are adding new api versions, please update the api tags in `AzSdk.RP.props`

2020-04-03 01:30 UTC, northtyphoon commented
@isra-fel I addressed your comments. Thanks. Can you take another look?

2020-04-07 02:51 UTC, isra-fel approved these changes
Looks great!

2020-04-07 02:51 UTC, merged