Regenerating sdk and renamed cosmos-db to cosmosdb
Azure/azure-sdk-for-net pull request #10999
Opened 2020-04-02 19:40 UTC by MehaKaushik

temporary fix for AdditionalProperties failure

Updated tests and deleted extra SdkInfor file

Temp Fix for failing Long Running Operations

Updating the version and release notes

Rephrasing the release notes

minor addition in release notes

2020-04-02 22:06 UTC, MehaKaushik commented
@isra-fel Can you please re-run the CI

2020-04-03 04:31 UTC, MehaKaushik commented
@erich-wang @isra-fel Please review/merge this at your earliest convenience.

2020-04-03 04:32 UTC, MehaKaushik commented
CI is successful, but on github UI it shows as in progress: 
![image](https://user-images.githubusercontent.com/11769687/78324405-7d07e600-7529-11ea-8dc9-45fa4b7dc4bf.png)

2020-04-06 06:05 UTC, MehaKaushik commented
Ping @isra-fel @erich-wang

2020-04-07 02:03 UTC, isra-fel commented
Yes I confirmed the checks all passed in ADO

2020-04-07 02:19 UTC, isra-fel requested changes
Hi @MehaKaushik sorry for the late response. I am just back to work from the holiday.
A few suggestions:
- Please edit your generate.ps1 to replace autorest version "latest" with "V2" and run it to generate again. This is because we found out the latest version didn't work well with C# generator.
- Please remove the redundant file src/Generated/code-model-v1 . This was also do to the latest autorest
- Please make sure you check in the metadata txt file under /eng/mgmt/mgmtmetadata , which is generated when you run `generate.ps1`
- I saw some models were removed, e.g. `AzureEntityResource` . Was that intentional? Cause if it is, then it's a breaking change, and we'll need to bump the major version, i.e. to 2.0.0 (as  well as `AssemblyVersion` in `AssemblyInfo.cs`

Thanks

2020-04-07 19:03 UTC, MehaKaushik commented
Hey @isra-fel when I call the generate script with v2, the autorest generation takes forever. This is stuck for more than 15 minutes now. I have tried on two different machines, but the same outcome.

Please suggest an alternative solution.

![image](https://user-images.githubusercontent.com/11769687/78708898-ae850680-78c7-11ea-9949-07d4538deeee.png)

2020-04-07 20:31 UTC, MehaKaushik commented
> Hey @isra-fel when I call the generate script with v2, the autorest generation takes forever. This is stuck for more than 15 minutes now. I have tried on two different machines, but the same outcome.
> 
> Please suggest an alternative solution.
> 
> ![image](https://user-images.githubusercontent.com/11769687/78708898-ae850680-78c7-11ea-9949-07d4538deeee.png)

It generates the code, but after 15-20 minutes. Was able to eventually do it.

2020-04-08 05:11 UTC, isra-fel commented on eng/Packages.Data.props
> +    <PackageReference Update="Microsoft.Azure.Management.CosmosDB" Version="1.1.0" />
I'm not familiar with this props file. Could you explain why cosmosdb was added here?

2020-04-08 05:45 UTC, isra-fel commented on eng/Packages.Data.props
> +    <PackageReference Update="Microsoft.Azure.Management.CosmosDB" Version="1.1.0" />
Talked with Meha offline. This file was for maintaining dependencies in the repo. CosmosDB's manamagement plane SDK isn't for now used in mulptiple projects, so it's not necessary.

2020-04-08 06:03 UTC, isra-fel approved these changes

2020-04-08 07:17 UTC, MehaKaushik commented
/azp run

2020-04-08 07:17 UTC, MehaKaushik commented
@isra-fel please re-run the CI

2020-04-08 07:21 UTC, merged