Correct .md files inconsistency and unclear content, fix hyper link.
Azure/azure-sdk-for-net pull request #11268
Opened 2020-04-13 08:03 UTC by wantedfast

1.Correct all 'Key Vault' to 'Azure Key Vault'
2.Fix content hyper link.

2020-04-13 15:45 UTC, jongio requested changes

2020-04-13 15:45 UTC, jongio commented on sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md
> +* Use the returned credentials above to set  **AZURE_CLIENT_ID** (appId), **AZURE_CLIENT_SECRET** (password) and **AZURE_TENANT_ID** (tenantId) environment variables. The following example shows a wa
oxford comma

2020-04-13 15:45 UTC, jongio commented on sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md
> +* Grant the above mentioned application authorization to perform certificate operations on the Azure key vault:
capital K and V

2020-04-13 18:36 UTC, heaths requested changes
Same comments as on other PRs in sdk\keyvault (please combine these in the future, but thanks for taking the time to make them).

2020-04-13 18:36 UTC, heaths commented on sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md
> +The Azure Key Vault Certificates client library enables programmatically managing certificates, offering methods to create, update, list, and delete certificates, policies, issuers, and contacts. The
"Certificates" is not a proper noun and should be lowercase.

2020-04-13 18:36 UTC, heaths commented on sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md
> +When you interact with the Azure Key Vault Certificates client library using the .NET SDK, errors returned by the service correspond to the same HTTP status codes returned for [REST API][keyvault_res
Not a proper noun and should be lowercase.

2020-04-13 18:36 UTC, heaths commented on sdk/keyvault/Azure.Security.KeyVault.Certificates/samples/Sample2_GetCertificates.md
> +[DefaultAzureCredential]: ../../../identity/Azure.Identity/README.md/#DefaultAzureCredential
Same comment here as on other PRs.

2020-04-14 06:58 UTC, wantedfast commented on sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md
> +* Use the returned credentials above to set  **AZURE_CLIENT_ID** (appId), **AZURE_CLIENT_SECRET** (password) and **AZURE_TENANT_ID** (tenantId) environment variables. The following example shows a wa
All comments resolved in New PR #11295

2020-04-14 17:20 UTC, heaths commented
Should this be closed now?

2020-04-15 01:25 UTC, closed without merging