Azure Digital Twins 0.1.0 SDK
Azure/azure-sdk-for-net pull request #12538
Opened 2020-06-05 03:07 UTC by c-ryan-k

Includes support for 2020-03-01-preview API

2020-06-05 03:38 UTC, isra-fel commented
Hi @c-ryan-k  please leave a link to your openapi spec PR, thanks

2020-06-05 04:28 UTC, c-ryan-k commented
> Hi @c-ryan-k please leave a link to your openapi spec PR, thanks

@isra-fel 

https://github.com/Azure/azure-rest-api-specs/pull/9667

2020-06-05 05:16 UTC, isra-fel commented
/azp run net - core - ci

2020-06-05 05:21 UTC, isra-fel approved these changes
This PR LGTM. Let me make the checks pass and merge.

2020-06-08 14:19 UTC, c-ryan-k commented
@isra-fel - is there anything holding this back from being merged?

Once it's merged, how soon until we can get it released?

2020-06-09 00:40 UTC, weshaggard commented on sdk/digitaltwins/Microsoft.Azure.Management.DigitalTwins/src/Microsoft.Azure.Management.DigitalTwins.csproj
> +		<Version>0.1.0-preview</Version>
Why version 0.1.0-preview? I would suggest 1.0.0-preview.1

2020-06-09 06:03 UTC, isra-fel commented
@c-ryan-k my bad, sorry
And Wes is right, the versioning guideline requires the first preview version to equal `1.0.0-preview.1`: see https://github.com/Azure/azure-sdk-for-net/blob/master/doc/dev/Versioning.md

2020-06-09 06:03 UTC, isra-fel requested changes

2020-06-09 06:03 UTC, isra-fel commented on sdk/digitaltwins/Microsoft.Azure.Management.DigitalTwins/src/Microsoft.Azure.Management.DigitalTwins.csproj
> +		<Version>0.1.0-preview</Version>
```suggestion
		<Version>1.0.0-preview.1</Version>
```

2020-06-10 08:00 UTC, isra-fel approved these changes
LGTM

2020-06-10 08:00 UTC, merged