SDK - Support SAP Open Hub Message Server
Azure/azure-sdk-for-net pull request #13215
Opened 2020-07-03 05:59 UTC by wenbof

Swagger Change: https://github.com/Azure/azure-rest-api-specs/pull/10029

2020-07-03 06:04 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-07-07 05:22 UTC, isra-fel requested changes
Hi @wenbof please
- Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update api tag in `AzSdk.RP.props`, release notes in csproj
- Update versions in csproj and `assemblyinfo.cs`

Thanks

2020-07-07 05:22 UTC, isra-fel commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/CHANGELOG.md
> +- Added support of Message server connecting from SAP Open Hub
4.9.0 was already released. You need to bump up the version.

2020-07-20 04:51 UTC, isra-fel commented
Kindly ping @wenbof

2020-07-20 06:13 UTC, wenbof commented
@isra-fel , thanks for your kind reminder. There was some issue with my account so the SDK of this was got checked in via my collague's PR:  https://github.com/Azure/azure-sdk-for-net/pull/13493

I will abort this one. Much appreciated for your attention.

2020-07-20 06:13 UTC, closed without merging