[Do not merge] DiskRp sdk changes for version 2020-06-30
Azure/azure-sdk-for-net pull request #14224
Opened 2020-08-14 01:27 UTC by laurawu19

2020-08-17 17:44 UTC, laurawu19 commented
Swagger changes:  https://github.com/Azure/azure-rest-api-specs/pull/10208

2020-08-24 18:07 UTC, haagha approved these changes
Looks good from Cplat side

2020-08-24 22:12 UTC, allenjzhang requested changes
Please update version tag in the Azure.RP.props.

2020-08-24 22:41 UTC, allenjzhang approved these changes

2020-08-24 23:38 UTC, merged