Update track 2 template, changelog and readme
Azure/azure-sdk-for-net pull request #14464
Opened 2020-08-21 17:55 UTC by allenjzhang

So generated project can pass PR checks out of box.

2020-08-21 21:21 UTC, weshaggard approved these changes

2020-08-21 21:51 UTC, markcowl requested changes
One minor textual change - feel free to merge and note that we want to change this later once the ci passes.

2020-08-21 21:53 UTC, markcowl approved these changes

2020-09-25 20:18 UTC, jsquire commented
Hi @allenjzhang.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

2020-10-02 20:56 UTC, jsquire commented
Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

2020-10-02 20:56 UTC, closed without merging