Azure SDK updates for Microsoft.Sql ImportExport private link
Azure/azure-sdk-for-net pull request #14844
Opened 2020-09-03 04:43 UTC by brandong-ms

Updating Azure SDK with changes for Microsoft.Sql ImportExport API to support private link

2020-09-04 19:08 UTC, allenjzhang requested changes
Could you:

 - Add a link to the openapi spec review PR here

 - Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
 
Thanks

2020-09-04 19:33 UTC, brandong-ms commented
> Could you:
> 
> * Add a link to the openapi spec review PR here

Sure, there were two associated spec PRs. Adding to the description. 

> * Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

I did not see any metadata.txt file generated, and the link you provided is dead - did you mean to provide a different link?

2020-09-05 04:34 UTC, allenjzhang requested changes
Looks like version info in csproj and assemblyinfoc.cs needs to be updated.

2020-09-07 17:05 UTC, allenjzhang approved these changes

2020-09-07 17:05 UTC, merged