[KeyVault] Regen with "package-preview-2020-04"
Azure/azure-sdk-for-net pull request #15445
Opened 2020-09-25 07:56 UTC by isra-fel

Merged swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/10872 (FYI @riteshchitlangia1 )

Thanks

2020-09-25 07:57 UTC, isra-fel commented on sdk/keyvault/Microsoft.Azure.Management.KeyVault/src/Microsoft.Azure.Management.KeyVault.csproj
>  				- Support CRUD operations to managed HSM
I didn't remove release notes from last release because I want to keep it until the stable release 3.1.0

2020-09-25 22:22 UTC, YalinLi0312 requested changes
Could you update versions in `AssemblyInfo.cs`?

2020-09-27 04:16 UTC, isra-fel commented
Hi @YalinLi0312 I just changed the revision part of the version `3.1.0-preview.1` -> `3.1.0-preview.2`. Assembly version is already `3.1.0.0`, so there's no need to change.

Thanks

2020-09-29 01:01 UTC, YalinLi0312 commented
> Hi @YalinLi0312 I just changed the revision part of the version `3.1.0-preview.1` -> `3.1.0-preview.2`. Assembly version is already `3.1.0.0`, so there's no need to change.
> 
> Thanks

What I found is `AssemblyVersion("3.0.0.0")` in master: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Microsoft.Azure.Management.KeyVault/src/Properties/AssemblyInfo.cs#L12

2020-09-29 02:05 UTC, isra-fel commented
Ah good catch! Thank you very much :)

2020-10-05 18:00 UTC, YalinLi0312 approved these changes

2020-10-05 18:00 UTC, merged