remove invalid samples products
Azure/azure-sdk-for-net pull request #15825
Opened 2020-10-09 07:52 UTC by daxianji007

2020-10-09 08:40 UTC, mitchdenny commented
/azp run net - communication - ci

2020-10-09 16:19 UTC, RezaJooyandeh approved these changes
I am guessing this is to unblock sample publishing?

2020-10-09 16:31 UTC, heaths requested changes
Removing these won't achieve the desired effect.

@christothes who can we tag about metrics-advisor?

Someone is already on the hook to get a product ID for communication.

2020-10-09 19:11 UTC, kinelski requested changes

2020-10-09 19:11 UTC, kinelski commented on sdk/metricsadvisor/Azure.AI.MetricsAdvisor/samples/README.md
> -- azure-metrics-advisor
I'm not following. Why is removing this needed?

2020-10-09 20:05 UTC, kinelski approved these changes
Metrics Advisor change LGTM.

2020-10-09 20:05 UTC, kinelski commented on sdk/metricsadvisor/Azure.AI.MetricsAdvisor/samples/README.md
> -- azure-metrics-advisor
Let's go with `azure-cognitive-services` for now. I can update it again once we have the `azure-metrics-advisor` ID.

2020-10-30 14:20 UTC, jsquire commented
Hi @daxianji007.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

2020-11-06 14:37 UTC, jsquire commented
Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

2020-11-06 14:37 UTC, closed without merging