Prevent template run for sync builds, Update SetTestPipelineVersion.ps1
Azure/azure-sdk-for-net pull request #16104
Opened 2020-10-20 00:58 UTC by chidozieononiwu

Prevent template pipeline run triggered by eng/common changes.
Update SetTestPipelineVersion.ps1

2020-10-20 02:05 UTC, weshaggard commented on eng/scripts/SetTestPipelineVersion.ps1
> +$newVersion = "1.0.3-beta.$PreviewVersionNumber"
Why are we hardcoding `1.0.3`?

2020-10-20 02:06 UTC, weshaggard commented on eng/scripts/SetTestPipelineVersion.ps1
> +$newVersion = "1.0.3-beta.$PreviewVersionNumber"
We should be able to use your package parsing methods to get the version and the ChangeLog path.

2020-10-20 18:40 UTC, mikeharder requested changes

2020-10-20 18:40 UTC, mikeharder commented on sdk/template/ci.yml
> +      - eng/common/
Do you need to exclude `eng/common`?  I think it would be sufficient to just not include it.

2020-10-27 16:51 UTC, closed without merging

2020-10-27 17:19 UTC, chidozieononiwu commented on eng/scripts/SetTestPipelineVersion.ps1
> +Set-TestChangeLog -TestVersion $newVersion -changeLogFile $changeLogFile -ReleaseEntry "Test Release Pipeline"
Am working on another PR.