Add Management Group Registration Capabilities
Azure/azure-sdk-for-net pull request #16566
Opened 2020-11-04 01:06 UTC by tjegbejimba

2020-11-06 00:00 UTC, shenglol commented on sdk/resources/Microsoft.Azure.Management.Resource/src/Generated/DeploymentsOperations.cs
> +                _requestContent = Rest.Serialization.SafeJsonConvert.SerializeObject(parameters, Client.SerializationSettings);
@tjegbejimba Restore these lines should fix the test errors.

2020-11-10 05:46 UTC, markcowl requested changes
Please provide a link to the swagger PR in the comments.  To release this change, you will need to update the version (in the .csproj and assemblyinfo.cs files).  Also, if this change involves a new api-version, then you will need to update the Az.Sdk.RP.props file in this directory to update the api-version tag

2020-11-10 19:11 UTC, tjegbejimba commented
> Please provide a link to the swagger PR in the comments. To release this change, you will need to update the version (in the .csproj and assemblyinfo.cs files). Also, if this change involves a new api-version, then you will need to update the Az.Sdk.RP.props file in this directory to update the api-version tag

This is not a new api-version. The assemblyinfo.cs and .csproj files are now updated

2020-11-14 01:11 UTC, markcowl approved these changes

2020-11-14 01:12 UTC, merged