[Do-Not-Merge]Generating SDK from extended loc swagger specs
Azure/azure-sdk-for-net pull request #16780
Opened 2020-11-09 19:17 UTC by pavanrachapudy

Generating SDK for extended location swagger specs into compute 2020-12 branch.
Added Do Not Merge Tag as tests need to be added for this change. Since it's a change to new api version, other files with api change are also being shown up in the committed files. This PR is just to make sure the SDK can be generated from Swagger Specs.

2020-11-09 19:23 UTC, pavanrachapudy commented
@Sandido @viananth

2020-11-11 06:12 UTC, DwayneNeed requested changes

2020-11-11 06:12 UTC, DwayneNeed commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/ExtendedLocation.cs
> +        public static string Type { get; private set; }
I don't understand why this is static.  What did we do in the swagger to cause it to generate this way?  Both the type and the name should be instance properties.

2020-12-11 14:07 UTC, jsquire commented
Hi @pavanrachapudy.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

2020-12-11 19:49 UTC, Sandido commented
@jsquire , There have been a couple of blockers preventing the underlying Rest API from releasing as scheduled. This PR will be used in the near future. Please leave it as open for now.

2020-12-30 00:45 UTC, YalinLi0312 commented
@pavanrachapudy If no updates, will close it next week. Thanks

2021-01-04 22:58 UTC, closed without merging