Customer Assigned Fault Domain on VM referencing VMSS - SDK Generation
Azure/azure-sdk-for-net pull request #16844
Opened 2020-11-10 22:33 UTC by shpa-microsoft

Api pull request https://github.com/Azure/azure-rest-api-specs/pull/11409

Do not merge, this PR is to confirm that .Net SDK code can be generated from Swagger change.

2020-11-14 01:30 UTC, markcowl requested changes
The code changes look OK, but there are some things that are missing:
- Please add in a reference to the corresponding Swagger PR for this change
- running the generation script produces an updated metadata file in the eng directory, please add this in to the PR
- When api versions change, you need to update Az.Sdk.RP.props to change the tag to match the new api-version
- You sill need to re-record the tests and add in new tests for any new functionality

2020-11-14 01:30 UTC, markcowl commented
@shpa-microsoft Also, please ensure you update this branch by pulling in the latest from master.

2020-11-16 21:00 UTC, shpa-microsoft commented
@markcowl Addressed your comments with some questions on offline chat.

2020-11-17 19:19 UTC, shpa-microsoft commented
Can't perform tests due to ARM API release issues. Spoke offline about it.

2020-12-11 14:10 UTC, jsquire commented
Hi @shpa-microsoft.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

2020-12-16 20:25 UTC, markcowl requested changes

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/GalleriesOperations.cs
> +        public async Task<AzureOperationResponse<Gallery>> GetWithHttpMessagesAsync(string resourceGroupName, string galleryName, string select = default(string), Dictionary<string, List<string>> cus
Need a customization to fix this breaking change - essentially you need a method that implements the old parameters, with 'customHeaders' being non-optional, like the following:

```
public partial class GalleriesOperations {

    public async Task<AzureOperationResponse<Gallery>> GetWithHttpMessagesAsync(string resourceGroupName, string galleryName, Dictionary<string, List<string>> customHeaders, CancellationToken cancellationToken = default(CancellationToken))
    {
         return GetWithHttpMessagesAsync(resourceGroupName, galleryName, null, customHeaders, cancellationToken);
    }
}
```

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/GalleriesOperationsExtensions.cs
> +            public static async Task<Gallery> GetAsync(this IGalleriesOperations operations, string resourceGroupName, string galleryName, string select = default(string), CancellationToken cancellat
same comment as above

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/IVirtualMachineScaleSetVMExtensionsOperations.cs
> -        Task<AzureOperationResponse<VirtualMachineExtension>> CreateOrUpdateWithHttpMessagesAsync(string resourceGroupName, string vmScaleSetName, string instanceId, string vmExtensionName, VirtualMa
need to compensate for these breaking changes:

(1) ensure that the return type has all the properties of the previous return type
(2) add method overloads through customizing thre partial interface using the old signature

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/IVirtualMachinesOperations.cs
> +        Task<AzureOperationResponse> DeleteWithHttpMessagesAsync(string resourceGroupName, string vmName, bool? forceDeletion = default(bool?), Dictionary<string, List<string>> customHeaders = null,
Need to add overloads as above to fix these breakign changes

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/GalleryApplicationVersionPublishingProfile.cs
> +        public UserArtifactManage ManageActions { get; set; }
This is a breaking change - you will have to maintain a ContentType property, even if unused

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/GalleryImage.cs
> +        public GalleryImage(string location, OperatingSystemTypes osType, OperatingSystemStateTypes osState, GalleryImageIdentifier identifier, string id = default(string), string name = default(stri
Need to add a method overload to fix the breaking change, as above

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/GalleryImageUpdate.cs
> +        public GalleryImageUpdate(OperatingSystemTypes osType, OperatingSystemStateTypes osState, GalleryImageIdentifier identifier, string id = default(string), string name = default(string), string
Need to add an additional overload through customizations to fix this issue

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/UserArtifactSource.cs
> -        public string FileName { get; set; }
Cannot trmoeve this property - must maintain the property

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/VirtualMachineScaleSetVMExtensionsOperations.cs
> +        public async Task<AzureOperationResponse<VirtualMachineScaleSetVMExtension>> CreateOrUpdateWithHttpMessagesAsync(string resourceGroupName, string vmScaleSetName, string instanceId, string vmE
Same issues as above:
(1) Need to verify that return tyoe contains all the properties of the previous return type
(2) Need to add a customization to implement the old parameter set, as above.

This applies for all the similar breaking method signature changes in this file

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/VirtualMachineScaleSetVMExtensionsOperationsExtensions.cs
> +            public static VirtualMachineScaleSetVMExtension CreateOrUpdate(this IVirtualMachineScaleSetVMExtensionsOperations operations, string resourceGroupName, string vmScaleSetName, string insta
Same as in previous file - need to add customizations to fix these breaking changes

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/VirtualMachinesOperationsExtensions.cs
> +            public static async Task DeleteAsync(this IVirtualMachinesOperations operations, string resourceGroupName, string vmName, bool? forceDeletion = default(bool?), CancellationToken cancellat
need to add an overload to fix this breaking change

2020-12-16 20:25 UTC, markcowl commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/VirtualMachinesOperationsExtensions.cs
> +            public static async Task BeginDeleteAsync(this IVirtualMachinesOperations operations, string resourceGroupName, string vmName, bool? forceDeletion = default(bool?), CancellationToken canc
need to add an overload to fix this breaking change

2020-12-16 20:25 UTC, markcowl commented
@shpa-microsoft Marked the breaking changes that need to be fixed through customization

2021-01-06 01:16 UTC, markcowl commented
@shpa-microsoft It looks like this PR is out of date, can you fix the merge conflicts?

2021-01-06 01:36 UTC, shpa-microsoft commented
@markcowl all the comments made for breaking changes are unrelated to my changes; and generated automatically with autorest. Is there a way I only regenerate my code for this PR?

2021-01-12 22:31 UTC, markcowl commented
@shpa-microsoft  There is a discussion about these API changes, and a proposed resolution on the compute team.  Please contact @Sandido for details.

2021-01-26 07:30 UTC, closed without merging