adding yml files to add code coverage reports to .net pipeline
Azure/azure-sdk-for-net pull request #17058
Opened 2020-11-18 23:52 UTC by seankane-msft

Adding code coverage report to the pipelines

2020-11-19 00:42 UTC, heaths commented
Thank you for your contribution. I'm actually about to publish a PR that not only adds code coverage to our Azure Pipelines, but develop builds as well. We'll be expanding on that to cover more scenarios. I can add you to the PR I'll be creating very soon if you'd like.

2020-11-19 00:44 UTC, heaths requested changes
Thank you for your contribution. I'm actually about to publish a PR that not only adds code coverage to our Azure Pipelines, but develop builds as well. We'll be expanding on that to cover more scenarios. I can add you to the PR I'll be creating very soon if you'd like.

2020-11-19 00:44 UTC, heaths commented on eng/pipelines/templates/jobs/archetype-sdk-tests-jobs.yml
> +  default: ne(varaibles['CoverageArg'], '--disablecov')
`variables`

2020-11-19 00:44 UTC, heaths commented on eng/pipelines/templates/steps/publish-coverage.yml
> +  - task: PublishCodeCoverageResults@1
What's generating the actual report file? We disabled coverlet currently but I'm about to re-enable it.

2020-11-19 01:26 UTC, weshaggard commented
/azp where

2020-11-19 02:30 UTC, heaths commented
See #17067

2020-12-11 14:14 UTC, jsquire commented
Hi @seankane-msft.  There hasn't been recent engagement on this PR and it looks to have been superseded by Heath's changes .  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

2020-12-14 15:59 UTC, seankane-msft commented
@jsquire My apologies, I intended to close this PR.

2020-12-14 15:59 UTC, closed without merging

2020-12-14 16:27 UTC, jsquire commented
> @jsquire My apologies, I intended to close this PR.

Thanks for the quick response, and no need for apologies;  we're just working to keep things from getting stale.  😄