Deleted Obselete exception and added a scenario test to check for it
Azure/azure-sdk-for-net pull request #17558
Opened 2020-12-15 23:03 UTC by TarunSunkaraneni

This is a subtle change that was not addressed in 
https://github.com/Azure/azure-sdk-for-net/pull/15620

Renaming  `DefaultErrorResponse` and `DefaultErrorResponseException`  to `TemplateSpecsError` and `TemplateSpecsErrorException` generates new C# classes when autorest command is run, however, I had forgotten to remove the old exception as part of my pull request.

As such, I have added a Scenario test to ensure that the exception rename is functionality is tested properly

2020-12-16 20:36 UTC, markcowl requested changes
Is this change the result of regenrationg the SDK?  If so, please include the swagger PR that contains these changes, and the '.txt' file updated in the '/eng' folder as part of generation.

If not, manual changes to generated code are generally not allowed.

2021-01-05 18:29 UTC, TarunSunkaraneni commented
https://github.com/Azure/azure-rest-api-specs/blame/b5851f013e3e954c7356e7d7384ae5188f6944ca/specification/resources/resource-manager/Microsoft.Resources/preview/2019-06-01-preview/templateSpecs.json#L88 
shows it is https://github.com/Azure/azure-rest-api-specs/pull/9778

I do not know that txt file you are referring to, but I think you want 
azure-sdk-for-net/eng/mgmt/mgmtmetadata/resources_resource-manager.txt
which is 
```
﻿Installing AutoRest version: v2
AutoRest installed successfully.
Commencing code generation
Generating CSharp code
Executing AutoRest command
cmd.exe /c autorest.cmd https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/readme.md --csharp --version=v2 --reflect-api-versions --tag=package-resources-2020-10 --csharp.output-folder=C:\azure-sdk-for-net\sdk\resources\Microsoft.Azure.Management.Resource\src\Generated\Resources
2020-12-09 21:02:18 UTC
Azure-rest-api-specs repository information
GitHub fork: Azure
Branch:      master
Commit:      398e3bedc3802997271f6f000e677fde43117e46
AutoRest information
Requested version: v2
Bootstrapper version:    autorest@2.0.4413
```

2021-01-06 01:11 UTC, markcowl requested changes

2021-01-06 01:11 UTC, markcowl commented on sdk/resources/Microsoft.Azure.Management.Resource/src/Generated/Models/DefaultErrorResponse.cs
> -// <auto-generated>
Since this change is not functional (meaning this is an orphaned class in the SDK), you should simply not include this change in the PR.

2021-01-06 01:11 UTC, markcowl commented on sdk/resources/Microsoft.Azure.Management.Resource/src/Generated/Models/DefaultErrorResponseException.cs
> -// <auto-generated>
Since this change is not functional (meaning this is an orphaned class in the SDK), you should simply not include this change in the PR.

2021-01-06 01:15 UTC, markcowl commented
@TarunSunkaraneni There doesn't seem to be a lot of reason to make the generated code change, so lets skip it, and just add the test items in this PR. Technically, removing these classes is a breaking change, even though they are orphaned.

If you think it is very important to include the generated code change, you will need to include the update to `azure-sdk-for-net/eng/mgmt/mgmtmetadata/resources_resource-manager.txt`  and you will also need to update the package version in the csproj file.

2021-01-13 18:38 UTC, TarunSunkaraneni commented
Hey @markcowl, I have updated the source code, bumped up the version and updated the text file to go forth with the file removal.

2021-01-20 22:34 UTC, markcowl approved these changes
Approving because the previous SDK was recently released, and this breaking change is covered by the previous breaking change approval.

2021-01-20 22:35 UTC, merged