Used string.IsNullOrEmpty() in EnvironmentCredential
Azure/azure-sdk-for-net pull request #18032
Opened 2021-01-18 02:50 UTC by abatishchev

Probably resolves #18031.

2021-01-19 22:06 UTC, chamons reviewed
Change seems reasonable, but no test?

2021-01-19 22:37 UTC, abatishchev commented
@schaabs please suggest how I can add a test to [DefaultAzureCredentialTests.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/tests/DefaultAzureCredentialTests.cs)?

2021-01-20 01:31 UTC, abatishchev commented
Here's another way to fix it (not just for 1 credential but several). [Validations.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/Validations.cs#L21) when validates tenantId throws exception on `""`.

2021-01-20 20:34 UTC, abatishchev commented
A workaround that worked for me:

```c#
public static async Task Main(string[] args)
{
     if (!IsLocal())
     {
          ResetEnvironmentVariable("AZURE_CLIENT_ID");
          ResetEnvironmentVariable("AZURE_TENANT_ID");
     }

     // the rest of the main entry point code
}

private static bool IsLocal()
{
    // your logic to determine whether the code is running locally or not
}

private static void ResetEnvironmentVariable(string name)
{
    var value = Environment.GetEnvironmentVariable(name);
    if (string.IsNullOrEmpty(value))
    {
        Environment.SetEnvironmentVariable(name, null);
    }
}
```

2021-01-20 21:02 UTC, schaabs requested changes
@abatishchev Thanks for the contribution! I like the approach your taking in this PR. 'Validations.ValidateTenantId` actually needs to assert that the value is not empty for other reasons so what you have currently would be preferable to updating that. There's one more place that needs to be updated, but other than that, the fix looks good. Let's follow up offline to discuss the test coverage needed.  Thanks again for this fix!!!

2021-01-20 21:11 UTC, abatishchev commented on sdk/identity/Azure.Identity/src/EnvironmentCredential.cs
>              if (tenantId != null && clientId != null)
Done.

2021-01-21 01:01 UTC, schaabs approved these changes
LGTM @chamons did you want to take another look?

2021-01-21 15:25 UTC, chamons approved these changes
Not a expert in the area, but LGTM. 

❤️ there being tests now.

2021-01-21 18:24 UTC, merged