New 2020-12-01 api for backup sdk
Azure/azure-sdk-for-net pull request #18222
Opened 2021-01-27 10:34 UTC by arpja

Adding the new swagger api version 2020-12-01 for SDK.

2021-01-27 17:59 UTC, allenjzhang commented
Please rerun generate.ps1. Ensure after generation the output shows the csharp autorest version is 2.3.82.

`Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)`

2021-01-27 20:10 UTC, markcowl requested changes
Per the ci failure, it looks like you may not have used the latest version of autorest when regenerating this file.  Here is a link to the error, with diffs between generating with the latest version versus the changes in this PR: https://dev.azure.com/azure-sdk/public/_build/results?buildId=705380&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=50b9345f-2a7f-5980-cb0f-1a8f9fb09dd0&l=1373

2021-01-28 12:45 UTC, arpja commented
Thanks @markcowl.
I was able to resolve the validation failures, please the PR now.

2021-01-28 18:49 UTC, markcowl approved these changes

2021-01-28 18:49 UTC, merged