Release of Device Update for IoT Hub control-plane SDK library for .NET
Azure/azure-sdk-for-net pull request #19159
Opened 2021-03-03 03:03 UTC by dpokluda

# All SDK Contribution checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] **Please open PR in `Draft` mode if it is:**
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md).**

### [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code. (Track 2 only)
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK. Please double check nuget.org current release version.

## Additional management plane SDK specific contribution checklist: 
Note: Only applies to `Microsoft.Azure.Management.[RP]` or `Azure.ResourceManager.[RP]`
 
- [x] Include updated [management metadata](https://github.com/Azure/azure-sdk-for-net/tree/master/eng/mgmt/mgmtmetadata).
- [x] Update AzureRP.props to add/remove version info to maintain up to date API versions.

### Management plane SDK Troubleshooting
- If this is very first SDK for a services and you are adding new service folders directly under /SDK, please add `new service` label and/or contact assigned reviewer.
- If the check fails at the `Verify Code Generation` step, please ensure:
	- Do not modify any code in generated folders.
	- Do not selectively include/remove generated files in the PR.
	- Do use `generate.ps1/cmd` to generate this PR instead of calling `autorest` directly.
	Please pay attention to the @microsoft.csharp version output after running generate.ps1. If it is lower than current released version (2.3.82), please run it again as it should pull down the latest version,

### Old outstanding PR cleanup
 Please note:
	If PRs (including draft) has been out for more than 60 days and there are no responses from our query or followups, they will be closed to maintain a concise list for our reviewers.

2021-03-03 03:10 UTC, m-nash requested changes, later dismissed

2021-03-03 03:10 UTC, m-nash commented on sdk/deviceupdate/Microsoft.Azure.Management.DeviceUpdate/src/Microsoft.Azure.Management.DeviceUpdate.csproj
> +    <Version>1.0.0</Version>
I think this should be 1.0.0-beta.1

2021-03-03 03:10 UTC, m-nash commented on sdk/deviceupdate/Microsoft.Azure.Management.DeviceUpdate/tests/Microsoft.Azure.Management.DeviceUpdate.Tests.csproj
> +</Project>
nit: missing newline

2021-03-03 03:10 UTC, m-nash commented on sdk/deviceupdate/Microsoft.Azure.Management.DeviceUpdate/src/Properties/AssemblyInfo.cs
> +[assembly: NeutralResourcesLanguage("en")]
nit: missing newline

2021-03-03 03:10 UTC, m-nash commented on sdk/deviceupdate/Microsoft.Azure.Management.DeviceUpdate/AzSdk.RP.props
> +</Project>
nit: missing newline

2021-03-03 03:12 UTC, m-nash commented
/azp run prepare-pipelines

2021-03-03 03:13 UTC, dpokluda commented on sdk/deviceupdate/Microsoft.Azure.Management.DeviceUpdate/src/Microsoft.Azure.Management.DeviceUpdate.csproj
> +    <Version>1.0.0</Version>
Rigth, fixing it.

2021-03-03 03:23 UTC, m-nash commented on sdk/deviceupdate/Microsoft.Azure.Management.DeviceUpdate/Microsoft.Azure.Management.DeviceUpdate.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution items", "Solution items", "{D1057B40-2779-4320-A41F-8380CDEB3400}"
this shouldn't be needed as a solution item

2021-03-04 05:29 UTC, allenjzhang commented
/azp run

2021-03-04 05:54 UTC, allenjzhang approved these changes

2021-03-04 06:28 UTC, allenjzhang commented
/azp run

2021-03-04 06:30 UTC, allenjzhang commented
/azp run net - mgmt - ci

2021-03-04 07:13 UTC, merged