Updates to enable live testing in sovereign clouds for multiple services
Azure/azure-sdk-for-net pull request #21436
Opened 2021-05-28 02:27 UTC by zedy-wj

We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

Using this RR to trace and fix issues we encounter in the tests. Will close it once we finish all the tests and send PR per services.

Updated list:
Text analytics
Core
Extensions
Event hubs
Identity
key vault
Search
Storage account
Form recognizer
Service bus
Event grid
Tables

2021-05-28 13:08 UTC, jsquire requested changes

2021-05-28 13:08 UTC, jsquire commented on sdk/storage/tests.yml
> +    Clouds: 'Preview,UsGov,China'
We should not be running `China` and `UsGov` in the nightly runs, only the weekly runs.  Please discuss with @benbp if confirmation is needed.

Leaving one comment, but this applies to all services.

2021-06-02 00:39 UTC, benbp commented on sdk/storage/tests.yml
> +  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
Please leave this as the absolute path so that we don't have to do anything if we ever move this file around.

2021-06-02 00:40 UTC, benbp commented on sdk/storage/tests.yml
> +        SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview-test)
For all these `SubscriptionConfiguration` values, the `-test` suffix should be removed. That was a testing/migration keyvault secret that's very out of date now.

2021-06-02 00:46 UTC, benbp commented on sdk/storage/tests.yml
> -      - Pool=(.*)-general/$1-storage
All the code removed here needs to stay (not sure whether you removed it for testing or intended for it to make it to the PR). A few reasons:

1. Storage has a custom agent pool with higher memory VMs, which is why we do this `MatrixReplace` to switch the pool.
2. Storage needs to test all service versions, but we've decided in the past to keep the cross-version testing only on the weekly builds.

Are there functional issues with either of the above configurations that you are seeing when testing sovereign clouds? If so, perhaps I can help?

2021-06-04 19:35 UTC, benbp commented
Looks good from a config standpoint. @jsquire can you weigh in again and/or route for review on the code changes?

2021-06-04 21:23 UTC, pakrym commented on sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClient.cs
> +        private readonly string DefaultCognitiveScope = TextAnalyticsClientOptions.GetDefaultCognitiveScope(Environment.GetEnvironmentVariable("AZURE_AUTHORITY_HOST"));
This is a product change we need to make sure we are doing the right thing here. cc @schaabs

2021-07-05 07:20 UTC, zedy-wj commented
Hi, @benbp! Shall we add `Preview` in SupportedClouds, I remember that you asked me to delete it in other services before. Why do we do that？

2021-07-07 00:37 UTC, benbp commented
@zedy-wj `Preview` is added as a pre-defined cloud only for services that need to use a separate subscription with additional ARM feature flags enabled. Originally, the tests-weekly behavior was set up to include all defined `CloudConfig` clouds by default. Typing this out, I'm realizing it would be better for us to change the default set of clouds for weekly in the `archetype-sdk-tests.yml` template, rather than requiring you to specify them in `tests.yml`. For now though, `Preview` should be excluded since there's no added value in testing it along with `Public`.

2022-09-22 07:02 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-11-01 17:37 UTC, weshaggard commented on sdk/formrecognizer/tests.yml
> +        SubscriptionConfiguration: $(sub-config-gov-test-resources)
```suggestion

```

2024-11-01 17:37 UTC, weshaggard commented on sdk/formrecognizer/tests.yml
> +        SubscriptionConfiguration: $(sub-config-cn-test-resources)
```suggestion

```

2024-11-05 06:14 UTC, zedy-wj commented
This PR has been stored for too long, we will close it and open a new draft PR for sovereign cloud testing.

2024-11-05 06:14 UTC, closed without merging