Update Microsoft.Azure.Management.Authorization to 2020-08-01-preview
Azure/azure-sdk-for-net pull request #21837
Opened 2021-06-12 17:02 UTC by sneivandt

Update Microsoft.Azure.Management.Authorization to 2020-08-01-preview. 

- Code regenerated
- Updated session records
- Minor updates in tests

I did not update the api spec. This version was already present.

2021-06-15 23:14 UTC, dagoroz commented
/azp run

2021-06-16 01:31 UTC, sneivandt commented
@m-nash please take a look when you have some time. i think the merge validation finally looks ok. please make sure i have not missed something since this is my first update in this repo.

2021-06-25 18:32 UTC, m-nash commented
Can you link the swagger PR that corresponds to this change?

2021-06-27 18:05 UTC, sneivandt commented
I think this is the change you are referring to: https://github.com/Azure/azure-rest-api-specs/pull/13119

2021-07-27 17:25 UTC, m-nash requested changes

2021-07-27 17:25 UTC, m-nash commented on sdk/authorization/Microsoft.Azure.Management.Authorization/src/Generated/ClassicAdministratorsOperations.cs
> +        /// <exception cref="ErrorResponseException">
this will result in a breaking change

2021-07-27 22:22 UTC, m-nash approved these changes

2021-07-27 22:23 UTC, merged