Notification Hub SDK change
Azure/azure-sdk-for-net pull request #2369
Opened 2016-09-19 19:51 UTC by amolr

This includes the recently added SKU change for namespace and also the patch operation supported for NH namespaces

2016-09-19 19:51 UTC, azuresdkci commented
Can one of the admins verify this patch?

2016-09-19 19:52 UTC, azurecla commented
Hi __@amolr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

2016-09-19 23:57 UTC, cormacpayne commented
@azuresdkci test this please

2016-09-19 23:57 UTC, azuresdkci commented
Can one of the admins verify this patch?

2016-09-20 16:55 UTC, shahabhijeet commented
@amolr seems tests are failing for notificationhub.

2016-09-21 19:44 UTC, cormacpayne commented
@azuresdkci add to whitelist

2016-09-26 22:07 UTC, markcowl commented on src/ResourceManagement/NotificationHubs/Microsoft.Azure.Management.NotificationHubs/Generated/Models/CheckAvailabilityParameters.cs
> -    public partial class CheckAvailabilityParameters : Resource
Why does this no longer extend resource?

2016-09-26 22:10 UTC, markcowl commented on src/ResourceManagement/NotificationHubs/NotificationHubs.Tests/project.json
>    "buildOptions": {
Note that this contains breaking changes, you will need to update your version accordingly (if the library is not -preview or -prerelease)

2016-09-26 22:10 UTC, markcowl requested changes
A couple of comments

2016-09-29 18:57 UTC, markcowl approved these changes

2016-09-29 18:59 UTC, merged

2016-09-29 18:59 UTC, markcowl commented on src/ResourceManagement/NotificationHubs/NotificationHubs.Tests/project.json
> +    "Microsoft.Azure.Test.HttpRecorder": "[1.6.7-preview,2.1.0)",
WHy did you change this?

2016-09-29 18:59 UTC, markcowl commented on src/ResourceManagement/NotificationHubs/NotificationHubs.Tests/project.json
> +    "Microsoft.Rest.ClientRuntime.Azure.TestFramework": "[1.3.5-preview,2.1.0)",
should not be changed