adding GroupableParentResource implementation to the fluent Resource core
Azure/azure-sdk-for-net pull request #2386
Opened 2016-09-23 00:24 UTC by martinsawicki

2016-09-23 00:25 UTC, azuresdkci commented
Can one of the admins verify this patch?

2016-09-23 00:25 UTC, azurecla commented
Hi __@martinsawicki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (marcins). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-09-23 17:39 UTC, hovsepm commented
@azuresdkci add to whitelist

2016-09-23 18:15 UTC, hovsepm requested changes

2016-09-26 17:05 UTC, martinsawicki commented on src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Core/GroupableParentResource.cs
> +/**
corrected in the next commit

2016-09-26 20:57 UTC, hovsepm approved these changes

2016-09-26 20:58 UTC, merged