Adding ManageVMInParallel sample and fixing the DAG so that all compa…
Azure/azure-sdk-for-net pull request #2397
Opened 2016-09-28 00:50 UTC by anuchandy

…risions are case-insensitive

2016-09-28 00:50 UTC, azurecla commented
Hi __@anuchandy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anuchan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-09-28 01:23 UTC, hovsepm commented on src/ResourceManagement/Azure/Azure.sln
> +EndProject
please revert changes to this file

2016-09-28 17:46 UTC, hovsepm requested changes

2016-09-28 17:46 UTC, hovsepm commented on src/ResourceManagement.Samples/Compute/ManageVirtualMachinesInParallel2/Program.cs
> +﻿// Copyright (c) Microsoft Corporation. All rights reserved.
Please change this project name to ManageVirtualMachinesInParallelWithNetwork

2016-09-29 06:11 UTC, anuchandy commented on src/ResourceManagement.Samples/Compute/ManageVirtualMachinesInParallel2/Program.cs
> +﻿// Copyright (c) Microsoft Corporation. All rights reserved.
@hovsepm  thanks, please take a look at the updated sample.

2016-09-29 19:45 UTC, hovsepm approved these changes

2016-09-29 19:45 UTC, merged