KV Sample fixes
Azure/azure-sdk-for-net pull request #2415
Opened 2016-09-30 20:35 UTC by amitbapat

Fixed sample scripts
Fixed README

2016-09-30 20:36 UTC, amitbapat commented
@pomortaz please review

2016-09-30 20:36 UTC, azurecla commented
Hi __@amitbapat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ambapat). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-10-04 16:30 UTC, cormacpayne commented
LGTM

@pomortaz any comments?

2016-10-04 16:43 UTC, pomortaz requested changes

2016-10-04 16:43 UTC, pomortaz commented on src/KeyVault/Microsoft.Azure.KeyVault.Samples/README.md
> +3. Azure PowerShell version 2.1.0 or newer
The latest version of the PowerShell is 3.x

2016-10-04 16:43 UTC, pomortaz commented on src/KeyVault/Microsoft.Azure.KeyVault.Samples/scripts/GetServiceConfigSettings.ps1
> +$storageName         = 'demo9218sa'
Use generic names and validate them.

2016-10-04 19:54 UTC, amitbapat commented on src/KeyVault/Microsoft.Azure.KeyVault.Samples/README.md
> +3. Azure PowerShell version 2.1.0 or newer
Minimum version is 2.1, users can use any newer version.

2016-10-05 06:13 UTC, pomortaz approved these changes

2016-10-05 16:17 UTC, merged