SecurityProfile parameter place changes
Azure/azure-sdk-for-net pull request #2437
Opened 2016-10-06 01:33 UTC by jaisrajms

We have changed place and parameter names for Security Profile. This Change will make sure that SDK is as per new change.

2016-10-06 01:33 UTC, azurecla commented
Hi __@jaisrajms__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rjaiswal). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-10-06 01:40 UTC, shefaliv commented
Approved.

2016-10-06 19:25 UTC, cormacpayne requested changes
@jaisrajms please bump the major version if you are going to make these breaking changes

2016-10-06 19:25 UTC, cormacpayne commented on src/ResourceManagement/HDInsight/HDInsight/Generated/Models/SecurityProfile.cs
> -        public ActiveDirectoryConfiguration ActiveDirectoryConfiguration
@jaisrajms this is a breaking change, please bump the major version

2016-10-06 19:25 UTC, cormacpayne commented on src/ResourceManagement/HDInsight/HDInsight/Generated/Models/SecurityProfile.cs
> -        public string RoleAdminGroupDN
@jaisrajms this is a breaking change

2016-10-06 19:25 UTC, cormacpayne commented on src/ResourceManagement/HDInsight/HDInsight/Generated/Models/SecurityProfile.cs
> +        public string Domain
@jaisrajms this is a breaking change

2016-10-06 19:25 UTC, cormacpayne commented on src/ResourceManagement/HDInsight/HDInsight/Generated/Models/Role.cs
> -        public SecurityProfile SecurityProfile
@jaisrajms this is a breaking change

2016-10-06 19:25 UTC, cormacpayne commented on src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ActiveDirectoryConfiguration.cs
> -//
@jaisrajms removing this entire file is a breaking change

2016-10-08 01:47 UTC, jaisrajms commented
@cormacpayne as discussed over email. Can you please merge this PR.

2016-10-10 23:44 UTC, markcowl commented
@jaisrajms @shefaliv Before we can merge this we need to know if the highlighted  breaking changes will affect the API surface of your PowerShell cmdlets and whether you plan to mitigate these changes in powershell.

2016-10-11 02:15 UTC, jaisrajms commented
@maekcowl, We have plan to release PowerShell cmdlet for SecurityProfile later this month. Currently we do not accept SecurityProfile parameter in powershell, so these change will not affect powershell cmdlet. This is an optional parameter for .net sdk.

2016-10-11 19:21 UTC, markcowl commented
@jaisrajms You have also removed proeprties from the ```Role`` model and removed the ```ActiveDirectoryConfiguration``` model.  If these are represented either in output types or parameters of poqwershell cmdlets, then you will need to mitigate these changes in powershell.  Please indicate whether these are unused in your powershell cmdlets or you will need to mitigate.

2016-10-13 03:46 UTC, jaisrajms commented
@markcowl Powershell does not use SecurityProfile currently. So removing proeprties from the Role`` model and removed theActiveDirectoryConfiguration``` model will not create problem with powershell or other clients. Currently SecurityProfile is only used in .Net SDK.

2016-10-13 16:57 UTC, markcowl commented
@jaisrajms SOunds good.  This has merge conflicts due to marging the previous HDInsight changes, please update (please use git pull --rebase and force push or a similar mechanismto your branch to avoid a merge commit)

2016-10-16 22:52 UTC, jaisrajms commented
@markcowl resolved the conflict and update the tests json file as well. Please merge this PR.

2016-10-17 18:36 UTC, merged