switch rsa provider for full framework, to avoid not supported exception
Azure/azure-sdk-for-net pull request #2451
Opened 2016-10-07 23:33 UTC by r22016

RSA.Create returning a implementation not supported on windows, switched to using RSACryptoProvider for full framework.

2016-10-07 23:33 UTC, azurecla commented
Hi __@r22016__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rameshr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-10-10 19:03 UTC, markcowl commented
@r22016 This doesn't seem to impact the test coverage.  Is there a test for this scenario, if not, please add one, or explain why that is not possible.

2016-10-10 19:03 UTC, markcowl requested changes
Please add test coverage for the change

2016-10-13 17:04 UTC, markcowl commented
@vkc12uec Can you verify this PR and respond about testing?

2016-10-17 16:49 UTC, shahabhijeet commented
@azuresdkci test this please

2016-10-17 21:12 UTC, shahabhijeet reviewed
@vkc12uec can you please comment if losing the #else part of the code (proposed change) is fine with you.

2016-10-17 21:12 UTC, shahabhijeet commented on src/ResourceManagement/ServerManagement/Microsoft.Azure.Management.ServerManagement/Utility.cs
> +#if NET45
Can we make something like below, this way we do not lose the existing Else part code.
#if NET45
#elseIf Portable
#else

2016-10-21 23:26 UTC, r22016 commented on src/ResourceManagement/ServerManagement/Microsoft.Azure.Management.ServerManagement/Utility.cs
> +#if NET45
switched to using above pattern for preprocessor directive
updated to latest swagger spec to include support for new installerDownload property and related test

2016-10-24 17:59 UTC, markcowl approved these changes

2016-10-24 17:59 UTC, markcowl commented
@rss016 please update the library version in project.json and in AssemblyInfo.cs

2016-10-24 18:00 UTC, markcowl reviewed
Need to update versions, otherwise LGTM

2016-10-24 18:00 UTC, markcowl commented on src/ResourceManagement/ServerManagement/Microsoft.Azure.Management.ServerManagement/Generated/Models/GatewayExpandOption.cs
> -        Status
You will need to update the version in project.json and assemblyinfo.cs to release this change.

2016-10-24 19:35 UTC, r22016 commented on src/ResourceManagement/ServerManagement/Microsoft.Azure.Management.ServerManagement/Generated/Models/GatewayExpandOption.cs
> -        Status
updated version info

2016-10-25 20:48 UTC, merged