Added RecoveryServices.Backup module
Azure/azure-sdk-for-net pull request #2453
Opened 2016-10-10 13:02 UTC by dragonfly91

Corresponding Swagger PR is in review: https://github.com/Azure/azure-rest-api-specs/pull/584

2016-10-10 19:04 UTC, markcowl commented
@dragonfly91 We cannot merge this PR until the Swagger change has been merged.  Please update the title when that occurs.

2016-11-03 18:17 UTC, markcowl commented
@dragonfly91 Please clean up the commits - there should not be merge commits ot multiple commits with the same comment in the history.  You cna follow this advice: https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md for cleaning up commits.

2016-11-03 18:18 UTC, markcowl requested changes
@dragonfly91 Please clean up the commits - there should not be merge commits ot multiple commits with the same comment in the history. You cna follow this advice: https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md for cleaning up commits.

2016-11-04 13:24 UTC, dragonfly91 commented
@markcowl I've simplified the commits. Can you continue with the review?

2016-11-05 00:26 UTC, markcowl requested changes

2016-11-05 00:26 UTC, markcowl commented on src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Customizations/Client.Customizations.cs
> +﻿using Microsoft.Azure.Management.RecoveryServices.Backup.Models;
project.json
'- This version should be a preview.  Please append -prview to the version in Newtonsoft.Json
- Consider wither this should be a new library with new namespaces and a new name,m or if it shoudl use the same name as the previous library.


generate.cmd
- broken link to your swagger spec.  Your link should us e a particular commit, and not a link to the branch, like this:
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/188c597d6e87fede4a3b0048ddff3fbfdb7cfd4c/arm-recoveryservicesbackup/compositeRecoveryServicesBackupClient.json

Tests - Your tests are dependnt on pre-created artifacts.  You should have all necessary setup in the test setup.  If this is not possible for some reason, then you need to describe in detail how to create the Azure structures necessary to run the test
SceanrioTests.cs
-= it looks like you are setting the test fixture in each test run.  Please follow the pattern - per-test setup can happen in the test class constructor, per suite setup should happen in a test fixture.

2016-11-07 10:12 UTC, dragonfly91 commented on src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Customizations/Client.Customizations.cs
> +﻿using Microsoft.Azure.Management.RecoveryServices.Backup.Models;
Regarding the comment about generate.cmd, can you give more clarity about which commit should it be? Also, we've tried to follow the Compute project as they've just specified the link to the composite JSON spec: https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/generate.cmd

Why is this guideline different?

2016-11-12 00:42 UTC, markcowl reviewed
Required changes in text fixture per xunit practices for per test / per class / per collection text fixtures.  Also, please augment your instructions on creation

2016-11-12 00:42 UTC, markcowl commented on src/ResourceManagement/RecoveryServices.Backup/RecoveryServices.Backup.Tests/RecoveryServicesBackupTestBase.cs
> -        public RecoveryServicesBackupTestBase(MockContext context)
This is not what I meant.  See the discussion of class and collection fixtures here: https://xunit.github.io/docs/shared-context.html

2016-11-12 00:42 UTC, markcowl commented on src/ResourceManagement/RecoveryServices.Backup/RecoveryServices.Backup.Tests/TestHelpers/BackupDefinition.cs
> +    /// For the recovery services backup tests, need some test artifact to be created manually for the tests to run:
This is not sufficient.  You are using particular names for these resources, so you need to specify what they are, or provide a mechanism for a user to provide resource names and details without changing the code.

2016-11-15 14:46 UTC, dragonfly91 commented on src/ResourceManagement/RecoveryServices.Backup/RecoveryServices.Backup.Tests/RecoveryServicesBackupTestBase.cs
> -        public RecoveryServicesBackupTestBase(MockContext context)
We've followed the per-test setup pattern (first model) as suggested in the link.

2016-11-15 14:46 UTC, dragonfly91 commented on src/ResourceManagement/RecoveryServices.Backup/RecoveryServices.Backup.Tests/TestHelpers/BackupDefinition.cs
> +    /// For the recovery services backup tests, need some test artifact to be created manually for the tests to run:
I've moved the test artifact related values to a json file and have included this detail in the comment.

2016-11-15 14:47 UTC, dragonfly91 commented
Addressed the comments, please review / merge!

2016-11-15 18:53 UTC, markcowl commented
@dragonfly91 Still need a correct reference to your swagger document

2016-11-16 09:49 UTC, dragonfly91 commented
Addressed the comments, please review / merge!

2016-11-16 18:07 UTC, markcowl approved these changes

2016-11-16 18:07 UTC, merged