[CLU] Regenerate SDK with 2021-11-01-preview swagger
Azure/azure-sdk-for-net pull request #24891
Opened 2021-10-24 12:53 UTC by AhmedLeithy

The main change in this PR is the regeneration of the SDK using the 2021-11-01-preview swagger. Other changes that were made are as follows:
- Removing unneeded transformations from autorest.md
- Renaming instances of 'DeepStack' in samples to Conversation
- Renaming AnalyzeConversationOptions -> ConversationAnalysisOptions (Change originated from swagger)
- Rerecording test session records

2021-10-25 19:40 UTC, heaths requested changes

2021-10-26 09:41 UTC, Sude3347 approved these changes

2021-10-27 00:54 UTC, heaths reviewed
Looks good, but still a few open issues for @ChongTang

2021-10-27 17:20 UTC, heaths approved these changes

2021-10-27 17:21 UTC, merged