Fix KeyVault core reference to runtime and add constructor with httpclient
Azure/azure-sdk-for-net pull request #2526
Opened 2016-11-03 20:00 UTC by pomortaz

- When key vault users are getting KeyVault.Core nuget package, they get an error related to GAC and System.Runtime. The dependency is unnecessary for net451.
- There is an ask by developers regarding exposing HttpClient in the constructor.

2016-11-03 20:05 UTC, pomortaz commented
@herveyw please review

2016-11-03 20:15 UTC, herveyw commented
@pomortaz Looks fine, I think you'll need to bump the KeyVault package version if you want the new NuGet description and release notes to be published.

2016-11-03 20:26 UTC, pomortaz commented
@herveyw we are going to bump the SDK package version soon with new API version. I'll let it handle the new package creation.

2016-11-03 22:39 UTC, kunalcha commented
:shipit:

2016-11-04 23:27 UTC, markcowl commented
@pomortaz Please fix merge conflicts

2016-11-08 01:18 UTC, pomortaz commented
@markcowl can you please pull the changes?

2016-11-08 22:27 UTC, hovsepm requested changes

2016-11-08 22:27 UTC, hovsepm commented on src/KeyVault/Microsoft.Azure.KeyVault.Core/project.json
> +  "version": "2.0.3-preview",
Please also update AssemblyFileVersion in AsseblyInfo.cs file

2016-11-08 22:51 UTC, pomortaz commented on src/KeyVault/Microsoft.Azure.KeyVault.Core/project.json
> +  "version": "2.0.3-preview",
Thanks. Added the AssemblyFileVersion.

2016-11-08 23:08 UTC, hovsepm approved these changes

2016-11-09 00:01 UTC, merged