Update to some Custom Analyzers API model classes
Azure/azure-sdk-for-net pull request #2528
Opened 2016-11-03 23:44 UTC by Yahnoosh

Marking EdgeNGramTokenFilter, NGramTokenFilter, KeywordTokenizer and StandardTokenizer as obsolete and adding V2 versions for all of them.

2016-11-03 23:44 UTC, azurecla commented
Hi __@Yahnoosh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jlembicz). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-11-04 03:00 UTC, brjohnstmsft commented
@Yahnoosh Please prefix all SDK commits and pull requests with "Search SDK: "

2016-11-04 03:19 UTC, brjohnstmsft commented on src/Search/Search.Tests/Tests/CustomAnalyzerTests.cs
> +            IEnumerable<Type> allAnalysisComponentTypes = typeof(Index).GetTypeInfo().Assembly.ExportedTypes.Where((Type type) => IsAnalysisComponentType(type) && !IsDeprecatedType(type));
You don't need to type lambda parameters, and if there's only one, you don't need parentheses either.

2016-11-04 03:20 UTC, bitsforthought requested changes
I left some comments on the corresponding Swagger review. You'll need to regenerate the code and maybe re-apply some tweaks. See the Swagger review for details.

2016-11-04 16:52 UTC, Yahnoosh commented
@brjohnstmsft thanks, I'll update this PR once I get a sign of on the Swagger changes. A new CR is out.

2016-11-07 23:48 UTC, closed without merging