Redis patch schedule supports "Everyday" and "Weekend" as valid DayOfWeek
Azure/azure-sdk-for-net pull request #2529
Opened 2016-11-07 22:46 UTC by SiddharthChatrolaMs

2016-11-07 22:46 UTC, azurecla commented
Hi __@SiddharthChatrolaMs__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sichatro). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-11-08 21:36 UTC, hovsepm commented
@SiddharthChatrolaMs please update assemblyinfo.cs file as well with the new version.

2016-11-08 21:56 UTC, hovsepm requested changes

2016-11-08 21:56 UTC, hovsepm commented on src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Redis/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("4.1.0.0")]
this should remain 4.0

2016-11-08 22:04 UTC, SiddharthChatrolaMs commented
Fixed all code review comments

2016-11-08 22:23 UTC, hovsepm approved these changes

2016-11-08 23:08 UTC, merged