Fix null deserialization in JsonConverters
Azure/azure-sdk-for-net pull request #2551
Opened 2016-11-17 00:40 UTC by olydis

- fixes #2550
- fixes #2501

2016-11-17 00:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2016-11-17 00:40 UTC, azurecla commented
Hi __@olydis__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jobader). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-11-17 00:44 UTC, cormacpayne commented
@markcowl can you take a look?

2016-11-17 19:09 UTC, cormacpayne commented
@azuresdkci add to whitelist

2016-11-19 00:23 UTC, markcowl requested changes
A couple of minor ni9ts - once these are fixed, this can be merged.

Nice work.

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure/CloudErrorJsonConverter.cs
>              JObject jObject = JObject.Load(reader);
Need vertical space after ending brace

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure/ResourceJsonConverter.cs
>                  JObject resourceJObject = JObject.Load(reader);
Same comment - vertical space after ending brace

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Tests/JsonTransformationConverterTest.cs
> +            //deserializeSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<SampleResourceChild>("dType"));
Remove commented code

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Tests/JsonTransformationConverterTest.cs
> +  ""properties"": {""name"": null, ""child"": null},
nice

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime/Serialization/PolymorphicDeserializeJsonConverter.cs
>              JObject item = JObject.Load(reader);
vertical space after end brace

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime/Serialization/TransformationJsonConverter.cs
>              JObject jsonObject = JObject.Load(reader);
vertical space after end brace

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Tests/JsonTransformationConverterTest.cs
> +
remove extra vertical space

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Tests/JsonTransformationConverterTest.cs
> +            deserializeSettings.Converters.Add(new TransformationJsonConverter());
vertical space after end of block

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Tests/JsonTransformationConverterTest.cs
> +            serializeSettings.Converters.Add(new TransformationJsonConverter());
vertical space after end of block

2016-11-19 00:23 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Tests/JsonTransformationConverterTest.cs
> +            sampleResource.Tags = new Dictionary<string, string>();
vertical space after end of block

2016-11-19 01:17 UTC, olydis commented
Thanks!

2016-11-21 21:13 UTC, hovsepm commented
@olydis please update affected project version in project.json and AssemblyInfo.cs files.

2016-11-22 03:37 UTC, markcowl requested changes

2016-11-22 03:37 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure/CloudErrorJsonConverter.cs
>                  throw new ArgumentNullException("serializer");
Per Hovsep's comment, please update the version in project.json and assemblyinfo.cs so that a new version can be published.

2016-11-22 04:17 UTC, olydis commented
like this? :)

2016-11-22 17:35 UTC, markcowl approved these changes

2016-11-22 17:36 UTC, merged