[Fluent] Traffic Manager fluent interfaces and implementation
Azure/azure-sdk-for-net pull request #2573
Opened 2016-11-22 17:41 UTC by anuchandy

2016-11-22 17:41 UTC, azurecla commented
Hi __@anuchandy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anuchan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-11-22 23:46 UTC, hovsepm commented on src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager.Fluent/TrafficManager.cs
> +using Microsoft.Azure.Management.Resource.Fluent.Core;
Got you here! :))) License header.

2016-11-23 17:44 UTC, anuchandy commented on src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager.Fluent/TrafficManager.cs
> +using Microsoft.Azure.Management.Resource.Fluent.Core;
again :) .. will fix this.

2016-11-29 00:54 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2016-11-29 18:47 UTC, hovsepm commented on src/ResourceManagement/gulpfile.js
> +        'dir': 'Cdn/Microsoft.Azure.Management.Cdn.Fluent',
Please remove the CDN entry that you've added. It already exists on line 70.

2016-11-29 18:48 UTC, hovsepm commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/TrafficManager/TrafficManagerTests.cs
> +                        // Assert.Equal(Region.US_EAST, endpoint.SourceTrafficLocation);
> // Assert.Equal(Region.US_EAS [](start = 23, length = 30)

why is this Assert commented?

2016-11-29 18:48 UTC, hovsepm commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/TrafficManager/TrafficManagerTests.cs
> +                        // Assert.Equal(Region.US_EAST2, endpoint.SourceTrafficLocation);
>// [](start = 24, length = 2)

same question "why is this Assert commented?"

2016-11-29 18:49 UTC, hovsepm commented on src/ResourceManagement/Azure.Fluent/Microsoft.Azure.Management.Fluent/project.json
> +    "Microsoft.Azure.Management.TrafficManager.Fluent": "1.0.0-beta3"
>Fluent": "1.0.0-beta3" [](start = 47, length = 22)

please fix the version reference by following the same pattern as the libraries above.

2016-11-29 18:50 UTC, hovsepm commented
>     "Microsoft.Azure.Management.Dns.Fluent": "1.0.0-beta3",

same here. please use version reference range as we have it for other packages. 

---
Refers to: src/ResourceManagement/Azure.Fluent/Microsoft.Azure.Management.Fluent/project.json:25 in b0609d4. [](commit_id = b0609d4f59839b5f5175fda6aeb7e180fa83b5d7, deletion_comment = False)

2016-11-29 18:52 UTC, hovsepm requested changes
Please address above comments

2016-11-29 21:30 UTC, hovsepm approved these changes

2016-11-29 21:31 UTC, merged

2016-11-29 21:48 UTC, anuchandy commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/TrafficManager/TrafficManagerTests.cs
> +                        // Assert.Equal(Region.US_EAST, endpoint.SourceTrafficLocation);
@hovsepm Fixed in the PR https://github.com/Azure/azure-sdk-for-net/pull/2595