Add cascade parameter, update Uploader version
Azure/azure-sdk-for-net pull request #2576
Opened 2016-11-22 20:15 UTC by begoldsm

Update ADLS upload/download package to use latest released version.
Explicitly add the ability to specify the cascade parameter (which
defaulted to false when not present) to allow for deletion of
credentials and all things that depend on them (similar to a recursive
delete).

2016-11-23 00:08 UTC, begoldsm commented
@markcowl @cormacpayne could you guys take a quick look at this PR. It is a version bump + improvement for catalog and the upload logic.

2016-11-23 02:28 UTC, markcowl requested changes

2016-11-23 02:28 UTC, markcowl commented on src/ResourceManagement/DataLake.Analytics/Microsoft.Azure.Management.DataLake.Analytics/Generated/CatalogOperations.cs
> +        public async Task<AzureOperationResponse> DeleteCredentialWithHttpMessagesAsync(string accountName, string databaseName, string credentialName, DataLakeAnalyticsCatalogCredentialDeleteParamet
Test coverage for the new API parameter?

2016-11-28 18:07 UTC, begoldsm commented on src/ResourceManagement/DataLake.Analytics/Microsoft.Azure.Management.DataLake.Analytics/Generated/CatalogOperations.cs
> +        public async Task<AzureOperationResponse> DeleteCredentialWithHttpMessagesAsync(string accountName, string databaseName, string credentialName, DataLakeAnalyticsCatalogCredentialDeleteParamet
Good call. I will add it now.

2016-11-28 20:07 UTC, merged