Add identity-based connection to SignalR multiple endpoint doc
Azure/azure-sdk-for-net pull request #25867
Opened 2021-12-10 07:13 UTC by Y-Sindo

2021-12-10 19:03 UTC, scottaddie requested changes

2021-12-10 19:03 UTC, scottaddie commented on sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/docs/sharding.md
> +> Under `Transient` mode, `Newtonsoft.Json` library is used to serialize arguments of hub methods, however, under `Persistent` mode, `System.Text.Json` library is used as default on Azure Functions r
```suggestion
> Under `Transient` mode, the `Newtonsoft.Json` library is used to serialize arguments of hub methods. However, under `Persistent` mode, the `System.Text.Json` library is used as default on Azure Functions runtime v3. `System.Text.Json` has some key differences in default behavior with `Newtonsoft.Json`. If you want to use `Newtonsoft.Json` under `Persistent` mode, you can add the configuration item `"Azure:SignalR:HubProtocol": "NewtonsoftJson"` in the `local.settings.json` file or `Azure__SignalR__HubProtocol=NewtonsoftJson` in the Azure portal.
```

2021-12-10 19:03 UTC, scottaddie commented on sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/docs/sharding.md
> +### 1. Use `Persistent` transport type.
```suggestion
### 1. Use `Persistent` transport type
```

2021-12-30 06:13 UTC, Y-Sindo commented on sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/docs/sharding.md
> +    "Azure:SignalR:Endpoints:Endpoint1:tenantId": "..."
Currently this is not supported by Azure Functions.

2022-01-04 17:44 UTC, scottaddie approved these changes

2022-02-19 14:58 UTC, merged