[ACR] Add SDK for Azure container registry
Azure/azure-sdk-for-net pull request #2592
Opened 2016-11-29 04:36 UTC by djyou

SDK is generated from approved [swagger spec for Azure container registry](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-containerregistry/2016-06-27-preview/swagger/containerregistry.json).

2016-11-29 04:36 UTC, azuresdkci commented
Can one of the admins verify this patch?

2016-11-29 04:36 UTC, azurecla commented
Hi __@djyou__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (doyou). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-11-29 05:20 UTC, djyou commented
/cc @SajayAntony @sivagms

2016-11-29 18:53 UTC, hovsepm commented
@azuresdkci add to whitelist

2016-11-29 19:41 UTC, djyou commented
Swagger link https://github.com/Azure/azure-rest-api-specs/blob/master/arm-containerregistry/2016-06-27-preview/swagger/containerregistry.json

2016-12-02 06:46 UTC, shahabhijeet commented on src/ResourceManagement/ContainerRegistry/ContainerRegistry.Tests/Helpers/ContainerRegistryTestUtilities.cs
> +namespace ContainerRegistry.Tests
@djyou I don't see any tests that have been enabled, also I don't see anything in the logs for the tests being run.

2016-12-02 06:51 UTC, djyou commented on src/ResourceManagement/ContainerRegistry/ContainerRegistry.Tests/Helpers/ContainerRegistryTestUtilities.cs
> +namespace ContainerRegistry.Tests
Is there another place we need to enable tests? Tests have been recorded in ResourceManagement/ContainerRegistry/ContainerRegistry.Tests/SessionRecords

2016-12-02 18:51 UTC, markcowl requested changes
A few minor changes, otherwise LGTM

2016-12-02 18:51 UTC, markcowl commented on src/ResourceManagement/ContainerRegistry/ContainerRegistry.Tests/Helpers/ContainerRegistryTestUtilities.cs
> +        public static string DefaultLocation = "southcentralus";
Please do not encode a static default location.  It is best to query ARM for an appropriate location during test setup.  Using a static location causes maintenance problems when tests are run later - many environments do not contain this location, checking ARM for locations containing the needed RPs *always* works in every environment.

2016-12-02 18:51 UTC, markcowl commented on src/ResourceManagement/ContainerRegistry/ContainerRegistry.Tests/project.json
> +    "Microsoft.Rest.ClientRuntime.Azure.TestFramework": "[1.3.5-preview,2.0.0)",
Please use latest versions of runtime and test framework

2016-12-02 18:51 UTC, markcowl commented on src/ResourceManagement/ContainerRegistry/Microsoft.Azure.Management.ContainerRegistry/project.json
> +        "Microsoft.Rest.ClientRuntime.Azure": "[3.3.1,4.0.0)"
Why not have a single runtime dependncy for all targets, since the dependency is the same.  Also, please update to the latest runtime version

2016-12-02 18:51 UTC, markcowl commented on src/ResourceManagement/ContainerRegistry/ContainerRegistry.Tests/Helpers/ContainerRegistryTestUtilities.cs
> +namespace ContainerRegistry.Tests
tests are included

2016-12-02 18:55 UTC, markcowl commented on src/ResourceManagement/ContainerRegistry/ContainerRegistry.Tests/Helpers/ContainerRegistryTestUtilities.cs
> +namespace ContainerRegistry.Tests
10 tests show as passed in the log for ContainerRegistry

2016-12-06 22:55 UTC, djyou commented
@markcowl Thanks for you feedback. We have made requested changes.

2016-12-09 17:33 UTC, djyou commented
@markcowl Can we have this merged if there is no more comment?

2016-12-09 18:09 UTC, SajayAntony commented
:shipit:

2016-12-12 18:52 UTC, merged