[Fluent] Ported SQL to NET from Java.
Azure/azure-sdk-for-net pull request #2596
Opened 2016-11-30 02:42 UTC by anudeepsharma

2016-11-30 02:42 UTC, azurecla commented
Hi __@anudeepsharma__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ans). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-12-05 19:05 UTC, cormacpayne commented
@hovsepm Hey Hovsep, can you assign this to someone working on fluent?

2016-12-05 21:11 UTC, hovsepm commented
> using Microsoft.Azure.Management.Resource.Fluent.Authentication;

Please add license header. 

---
Refers to: src/ResourceManagement/Sql/Microsoft.Azure.Management.Sql.Fluent/SqlManager.cs:1 in 2797994. [](commit_id = 2797994c8887161dd4d76e42ecfe4e3215fbfbec, deletion_comment = False)

2016-12-05 21:14 UTC, hovsepm commented on src/ResourceManagement/Sql/Microsoft.Azure.Management.Sql.Fluent/Domain/InterfaceImpl/ElasticPoolActivityImpl.cs
> +                return this.Name() as string;
>as string [](start = 35, length = 9)

no need to convert string to string.

2016-12-05 21:14 UTC, hovsepm commented on src/ResourceManagement/Sql/Microsoft.Azure.Management.Sql.Fluent/Domain/InterfaceImpl/ElasticPoolActivityImpl.cs
> +            }
no need to convert string to string.

2016-12-05 21:14 UTC, hovsepm commented on src/ResourceManagement/Sql/Microsoft.Azure.Management.Sql.Fluent/Domain/InterfaceImpl/ElasticPoolActivityImpl.cs
> +            }
no need to convert string to string.

2016-12-05 21:15 UTC, hovsepm commented on src/ResourceManagement/Sql/Microsoft.Azure.Management.Sql.Fluent/Domain/InterfaceImpl/ElasticPoolActivityImpl.cs
> +            }
no need to convert string to string.

2016-12-05 21:15 UTC, hovsepm commented on src/ResourceManagement/Sql/Microsoft.Azure.Management.Sql.Fluent/Domain/InterfaceImpl/ElasticPoolActivityImpl.cs
> +            }
no need to convert string to string.

2016-12-05 21:21 UTC, hovsepm requested changes
Please fix license header comment. The rest should be addressed on the converter side. I've created an issue there https://github.com/Microsoft/java-to-csharp-api-generator/issues/29

2016-12-06 18:51 UTC, hovsepm approved these changes

2016-12-06 18:51 UTC, merged