[Storage] Address comments in PR on azure-rest-api-specs
Azure/azure-sdk-for-net pull request #2598
Opened 2016-11-30 09:36 UTC by JasonYang-MSFT

This is a related pr to https://github.com/Azure/azure-sdk-for-net/pull/2562.
After resolve comments in swagger(https://github.com/Azure/azure-rest-api-specs/pull/742), changes need to be updated to .Net sdk.

2016-12-02 05:43 UTC, JasonYang-MSFT commented
PR to azure-rest-api-specs is already merged: https://github.com/Azure/azure-rest-api-specs/pull/742

2016-12-02 06:50 UTC, shahabhijeet commented
@JasonYang-MSFT I don't see any version bump of SDK assembly due to this change?

2016-12-02 08:11 UTC, JasonYang-MSFT commented
Hi @shahabhijeet 
Version bump is already in PR https://github.com/Azure/azure-sdk-for-net/pull/2562 and already merged.

This PR is reflect swagger changes after https://github.com/Azure/azure-sdk-for-net/pull/2562 merged.

2016-12-02 19:22 UTC, markcowl requested changes
@JasonYang-MSFT One needed change in generation

2016-12-02 19:22 UTC, markcowl commented on src/ResourceManagement/Storage/Microsoft.Azure.Management.Storage/generate.cmd
> +set autoRestVersion=1.0.0-Nightly20161122
This should be updated to the latest (201612001)  this will make type declarations more readable by removing the usage of fully qualified type names

2016-12-03 04:12 UTC, JasonYang-MSFT commented
Hi @markcowl,

Updated autorest to build 1201

2016-12-03 04:12 UTC, JasonYang-MSFT commented on src/ResourceManagement/Storage/Microsoft.Azure.Management.Storage/generate.cmd
> +set autoRestVersion=1.0.0-Nightly20161122
Resolved.

2016-12-07 02:11 UTC, markcowl commented
@JasonYang-MSFT Wow, no that didn't work, it also created a bunch of breaking changes.  Please revert to the previous version and we will file an issue on that nightly build of AutoRest

2016-12-07 02:49 UTC, JasonYang-MSFT commented
Hi @markcowl 

Upgrade autorest is in commit https://github.com/Azure/azure-sdk-for-net/pull/2598/commits/915fdd6fc11313eebb846025997850515bfdb4fa. 

There are some breaking changes introduced by swagger(See in https://github.com/Azure/azure-sdk-for-net/pull/2598/commits/579714894e53a4e039c041032d1ea8e08927eda4?diff=unified). Like change StorageManagementClient to StorageManagement, which is because swagger needs to generate document besides client libraries. Also change permission value FULL, READ to Full, Read to align the value in response.

2016-12-10 05:55 UTC, markcowl requested changes
You are missing a project.json update to update the version fo the package.  Otherwise, this LGTM

2016-12-10 16:00 UTC, JasonYang-MSFT commented
Hi @markcowl,

Not sure which project.json you are referring to.

For project.json in Storage SDK folder, the version is already updated to 6.0.0-preview in PR #2562 .
And for project.json in Storage.Test folder, the version is just updated to [6.0.0-preview, 7.0).

2016-12-14 19:54 UTC, merged