Update compute to latest.
Azure/azure-sdk-for-net pull request #2614
Opened 2016-12-05 21:18 UTC by brendandburns

2016-12-05 21:18 UTC, azuresdkci commented
Can one of the admins verify this patch?

2016-12-05 21:18 UTC, azurecla commented
Hi __@brendandburns__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bburns). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-12-08 19:14 UTC, cormacpayne commented
@azuresdkci add to whitelist

2016-12-08 19:17 UTC, cormacpayne commented
@brendandburns Hey Brendan, could you update the generate.cmd file with the version of AutoRest and spec you are using?

2016-12-08 20:04 UTC, cormacpayne requested changes
@brendandburns left a few comments that will need to be addressed

You will also need to update the `project.json` and `AssemblyInfo.cs` files with the appropriate version bump for these changes

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ComputeManagementClient.cs
> +        public virtual IContainerServicesOperations ContainerServices { get; private set; }
@brendandburns where is the file for `IContainerServicesOperations`?

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ContainerServiceOperations.cs
> -// Copyright (c) Microsoft Corporation. All rights reserved.
@brendandburns I'm assuming that this file was deleted for `ContainerServicesOperations.cs`, but that file does not exist

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ContainerServiceOperationsExtensions.cs
> -// Copyright (c) Microsoft Corporation. All rights reserved.
@brendandburns I'm assuming this file was deleted for `ContainerServicesOperationsExtensions.cs`, but that file does not exist

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/IComputeManagementClient.cs
> +        IContainerServicesOperations ContainerServices { get; }
@brendandburns same comment

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/IContainerServiceOperations.cs
> -// Copyright (c) Microsoft Corporation. All rights reserved.
@brendandburns I'm assuming this file was deleted for `IContainerServicesOperations.cs`, but that file does not exist

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerService.cs
> +        public ContainerService(string location, ContainerServiceMasterProfile masterProfile, System.Collections.Generic.IList<ContainerServiceAgentPoolProfile> agentPoolProfiles, ContainerServiceLin
@brendandburns this is a breaking change - parameters have been added to the constructor and the order of some of the last parameters have changed

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerServiceAgentPoolProfile.cs
> +        public ContainerServiceAgentPoolProfile(string name, int count, string vmSize, string dnsPrefix, string fqdn = default(string))
@brendandburns this is a breaking change - the order of the parameters in the constructor has changed and default values for parameters have been removed

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerServiceAgentPoolProfile.cs
> +        public int Count { get; set; }
@brendandburns this is a breaking change - this property is no longer nullable

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerServiceOrchestratorProfile.cs
> +        public ContainerServiceOrchestratorProfile(ContainerServiceOchestratorTypes orchestratorType)
@brendandburns this is a breaking change - the default value for a parameter has been removed

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerServiceOrchestratorProfile.cs
> +        public ContainerServiceOchestratorTypes OrchestratorType { get; set; }
@brendandburns same comment about changing nullable type

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerServiceSshConfiguration.cs
> +        public ContainerServiceSshConfiguration(System.Collections.Generic.IList<ContainerServiceSshPublicKey> publicKeys)
@brendandburns same comment about removing default value

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerServiceVMDiagnostics.cs
> +        public ContainerServiceVMDiagnostics(bool enabled, string storageUri = default(string))
@brendandburns same comment about removing default value

2016-12-08 20:04 UTC, cormacpayne commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/ContainerServiceVMDiagnostics.cs
> +        public bool Enabled { get; set; }
@brendandburns same comment about changing nullable type

2016-12-09 23:18 UTC, brendandburns commented
@cormacpayne thanks for the feedback.  Added the missing files (I forgot to `git add ...` *sigh*)

What is the policy on breaking changes?

2016-12-13 17:05 UTC, shahabhijeet commented
@brendandburns please address the feedback on the PR. We will close the PR by EOW. You can either open a new PR or reopen the existing one once the feedback has been addressed.

2016-12-28 18:03 UTC, cormacpayne commented
@brendandburns Hey Brendan, since there hasn't been any activity in this PR in a couple of weeks, I'm going to close it. Feel free to re-open it when comments can be addressed.

2017-01-04 20:22 UTC, brendandburns commented
Re-opening

@cormacpayne I think this is ready to go since I re-added the files. Are there any other comments you need me to address?

2017-01-04 20:22 UTC, azurecla commented
Hi __@brendandburns__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bburns). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2017-01-04 20:25 UTC, brendandburns commented
Looks like I need to update tests, I will address later to day.

2017-01-21 00:39 UTC, markcowl commented
@brendandburns Two VM tests are failg in this check-in, please take a look

2017-01-23 23:02 UTC, markcowl commented
It has been 19 days since this PR was changed.  Closing for now Please open a new PR when you are ready to proceed.

2017-01-23 23:02 UTC, closed without merging