update description for all properties, new autorest client and vnet get on vnet peering from vnet
Azure/azure-sdk-for-net pull request #2621
Opened 2016-12-07 01:54 UTC by DeepakRajendranMsft

This is a continuation of https://github.com/Azure/azure-sdk-for-net/pull/2530. I have generated the sdk with the latest autorest client
@cormacpayne  @markcowl

2016-12-07 01:55 UTC, azurecla commented
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

2016-12-07 23:13 UTC, cormacpayne requested changes

2016-12-07 23:13 UTC, cormacpayne commented on src/ResourceManagement/Network/Network.Tests/Tests/VirtualNetworkTests.cs
> +
@DeepakRajendranMsft what new functionality are you trying to test here?

2016-12-08 00:11 UTC, cormacpayne commented on src/ResourceManagement/Network/Network.Tests/Tests/VirtualNetworkTests.cs
> +
Discussed offline

2016-12-08 00:12 UTC, cormacpayne approved these changes

2016-12-08 00:56 UTC, merged