[Fluent] synching virtual machine, scale set and availability set
Azure/azure-sdk-for-net pull request #2628
Opened 2016-12-08 21:10 UTC by anuchandy

2016-12-08 21:10 UTC, azurecla commented
Hi __@anuchandy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anuchan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-12-09 00:31 UTC, hovsepm commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/ComputeUsageImpl.cs
> +        public int Limit()
>() [](start = 24, length = 2)

this sounds like a property and not a method

2016-12-09 01:11 UTC, hovsepm commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/VirtualMachineScaleSetVMInstanceExtensionImpl.cs
> +            //$ return null;
>/$ return null; [](start = 13, length = 15)

this seems to need implementation.

2016-12-09 01:11 UTC, hovsepm commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/VirtualMachineScaleSetVMInstanceExtensionImpl.cs
> +        public VirtualMachineExtensionInstanceView InstanceView()
>InstanceView() [](start = 51, length = 14)

same comment across this file - consider properties instead of methods.

2016-12-09 01:13 UTC, hovsepm commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/Domain/InterfaceImpl/VirtualMachineExtensionsImpl.cs
> +}
this file should be deleted

2016-12-09 01:15 UTC, hovsepm requested changes
Please address comments.

2016-12-11 23:25 UTC, anuchandy commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/ComputeUsageImpl.cs
> +        public int Limit()
For each model interface, there are two partial implementation classes

1. Impl class generated by the converter that explicitly implements the interface and reside in Domain/InterfacesImpl directory

2. Impl class generated by the converter but we need to modify method bodies.

The Impls that belongs to 2nd category contains ONLY methods (including members those can be properties), the corresponding partial impl in category 1 correctly exposes these members as either methods or properties.

So `Limit()` method is a member of category 2 partial class

and `Limit` property in category 1 impl class wrap the above property 

see https://github.com/Azure/azure-sdk-for-net/blob/4d62a3cdc423259d0ca5050c50dd22153d7d9394/src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/Domain/InterfaceImpl/ComputeUsageImpl.cs#L14

2016-12-11 23:25 UTC, anuchandy commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/ComputeUsageImpl.cs
> +        public Models.UsageName Name()
no, see above comment

2016-12-11 23:26 UTC, anuchandy commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/ComputeUsageImpl.cs
> +        public int CurrentValue()
see above comment

2016-12-11 23:28 UTC, anuchandy commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/VirtualMachineScaleSetVMInstanceExtensionImpl.cs
> +        public VirtualMachineExtensionInstanceView InstanceView()
please see above comment

2016-12-11 23:29 UTC, anuchandy commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/VirtualMachineScaleSetVMInstanceExtensionImpl.cs
> +            //$ return null;
thanks, missed it, will fix and update the PR.

2016-12-11 23:31 UTC, anuchandy commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute.Fluent/Domain/InterfaceImpl/VirtualMachineExtensionsImpl.cs
> +}
its a left over of converter output, will delete it - thanks.

2016-12-12 18:38 UTC, hovsepm approved these changes

2016-12-12 18:38 UTC, merged