app gateway unit test conversion and passing (+ bug fixes)
Azure/azure-sdk-for-net pull request #2643
Opened 2016-12-14 21:50 UTC by martinsawicki

2016-12-14 21:50 UTC, azurecla commented
Hi __@martinsawicki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (marcins). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-12-14 21:56 UTC, hovsepm commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/AzureTests.cs
> +        public void TestAppGatewaysPublicComplex()
you will need to skip this test as well or CI build will fail.

2016-12-14 21:58 UTC, hovsepm commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/Network/ApplicationGateway/PublicComplex.cs
> +            //    // Create an application gateway
please remove these comments.

2016-12-14 21:58 UTC, hovsepm commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/Network/ApplicationGateway/PublicComplex.cs
> +            // Thread.Sleep(30 * 1000);
these comments are also useless.

2016-12-14 22:00 UTC, hovsepm requested changes
Please address comments.

2016-12-14 23:31 UTC, martinsawicki commented
all comments addressed in the latest commit (i pushed beforer replying to comments so it seems i can't get to the comments directly anymore)

2016-12-15 00:49 UTC, martinsawicki commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/AzureTests.cs
> +        public void TestAppGatewaysPublicComplex()
done

2016-12-15 00:50 UTC, martinsawicki commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/Network/ApplicationGateway/PublicComplex.cs
> +            //    // Create an application gateway
ok. (commented out because this trick should work, but for an inexplicable reason it doesn't in this specific test. Anyway....)

2016-12-15 00:51 UTC, martinsawicki commented on src/ResourceManagement/Azure.Fluent/Fluent.Tests/Network/ApplicationGateway/PublicComplex.cs
> +            // Thread.Sleep(30 * 1000);
yep, just a continuation of the previous

2016-12-15 00:51 UTC, hovsepm approved these changes

2016-12-15 00:51 UTC, merged