Adding a way to publish single nuget package when a scope is provided…
Azure/azure-sdk-for-net pull request #2646
Opened 2016-12-14 23:08 UTC by shahabhijeet

1) Adding a way to publish single nuget package when a scope is provided.
2) This change will also allow publishing multiple packages from the same scope (only NetCore projects are supported as this stage). Due to restrictions on how we have enabled non-NetCore project imports and the way msbuild builds it's build graph.
3) Adding test collateral and tests to test publishing one project

2017-01-05 00:37 UTC, hovsepm commented on build.proj
> +                            Condition=" ('$(Scope)' == 'all' or '$(Scope)' == 'Authentication') and Exists('$(LibrarySourceFolder)\Authentication\Authentication.sln')" />
please uncomment or delete this line.

2017-01-05 00:44 UTC, hovsepm commented on tools/Microsoft.WindowsAzure.Build.Tasks/FilterOutAutoRestLibraries.cs
> +                }
you should Split using IgnoreWhiteSpaces parameter. if there will be 2 spaces or more in the passed parameter this part may not work correct

2017-01-05 00:49 UTC, hovsepm commented
> using System;

add license header. 

---
Refers to: tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectMultiSln/CSProjTestPublish/Class1.cs:1 in e476727. [](commit_id = e476727f99b8f31bc6c6d3efe35a18c5fa571505, deletion_comment = False)

2017-01-05 00:50 UTC, hovsepm commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectMultiSln/CSProjTestPublish/Class1.cs
> +    }
please add at least a method that returns "hello published world!" :)

2017-01-05 00:50 UTC, hovsepm commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectMultiSln/CSProjTestPublish/Properties/AssemblyInfo.cs
> +using System.Reflection;
License header missing

2017-01-05 00:51 UTC, hovsepm commented
Is this PR intended to be merged?

2017-01-05 23:42 UTC, shahabhijeet commented on build.proj
> +                            Condition=" ('$(Scope)' == 'all' or '$(Scope)' == 'Authentication') and Exists('$(LibrarySourceFolder)\Authentication\Authentication.sln')" />
done

2017-01-07 01:37 UTC, shahabhijeet commented
@hovsepm all the feedback is addressed and yes this is intended to be merged.

2017-01-23 23:15 UTC, markcowl requested changes

2017-01-23 23:15 UTC, markcowl commented on build.proj
> +	<NuGetCommand>&quot;$(LibraryToolsFolder)\nuget.exe&quot;</NuGetCommand>
fix indentation

2017-01-23 23:15 UTC, markcowl commented on build.proj
> +	<ClientRuntimeRootDir Include="%(ClientRuntimeProjects.RootDir)"/>
Indentation

2017-01-23 23:15 UTC, markcowl commented on build.proj
> +		<NonAutoRestLibraries Include="$(LibrarySourceFolder)\Authentication\Authentication.sln"
Indentation

2017-01-23 23:15 UTC, markcowl commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectMultiSln/CSProjTestPublish/Class1.cs
> +    }
@shahabhijeet Please address this feedback

2017-01-23 23:15 UTC, markcowl commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectSingleSln/RP1_DataPlane/Class1.cs
> +        }
Include a method

2017-01-23 23:15 UTC, markcowl commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectSingleSln/RP1_MgmtPlane/Class1.cs
> +        }
At least a dummy method for this class.

2017-01-23 23:15 UTC, markcowl commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectSingleSln/RP2_Sdk/RP2_SDK.Test/Class1.cs
> +        }
same comment

2017-01-23 23:15 UTC, markcowl commented on tools/Microsoft.WindowsAzure.Build.Tasks/FilterOutAutoRestLibraries.cs
> +            if (NugetPackagesToPublish != null)
Why not simply call String.IsNullOrWhitespace here?

2017-01-23 23:15 UTC, markcowl commented on tools/Microsoft.WindowsAzure.Build.Tasks/FilterOutAutoRestLibraries.cs
> +                            nonNetCoreAutoRestLibraries.Add(solution);
Always use brackets for the then clause

2017-01-25 00:54 UTC, shahabhijeet commented on tools/Microsoft.WindowsAzure.Build.Tasks/FilterOutAutoRestLibraries.cs
> +            if (NugetPackagesToPublish != null)
thank you, good suggestion, will incorporate that.

2017-01-25 01:45 UTC, shahabhijeet commented on tools/Microsoft.WindowsAzure.Build.Tasks/FilterOutAutoRestLibraries.cs
> +                            nonNetCoreAutoRestLibraries.Add(solution);
done

2017-01-25 01:48 UTC, shahabhijeet commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectMultiSln/CSProjTestPublish/Class1.cs
> +    }
Ok I will add it now :)
I am still not sure, the purpose of adding methods to empty classes. These projects are not meant to be consumed by anyone, they are test assets, whose sole purpose is to get packaged and used in testing publishing functionality.

2017-01-25 02:19 UTC, shahabhijeet commented
I will add empty methods :)
But I am not sure the purpose of adding empty methods on test assets whose sole purpose is to get packaged and get used in testing publishing functionality. These test nugget packages will never be consumed by anyone.

2017-01-25 02:19 UTC, shahabhijeet commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectSingleSln/RP1_DataPlane/Class1.cs
> +        }
I will add empty methods :)
But I am not sure the purpose of adding empty methods on test assets whose sole purpose is to get packaged and get used in testing publishing functionality. These test nugget packages will never be consumed by anyone.

2017-01-25 02:19 UTC, shahabhijeet commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectSingleSln/RP1_MgmtPlane/Class1.cs
> +        }
done

2017-01-25 02:19 UTC, shahabhijeet commented on tools/Microsoft.WindowsAzure.Build.Tasks/Build.Tasks.Tests/TestPublishProjects/MultiProjectSingleSln/RP2_Sdk/RP2_SDK.Test/Class1.cs
> +        }
done

2017-01-25 02:20 UTC, shahabhijeet commented on build.proj
> +		<NonAutoRestLibraries Include="$(LibrarySourceFolder)\Authentication\Authentication.sln"
I don't see any indentation issue when I open this file locally.

2017-01-27 22:10 UTC, markcowl approved these changes

2017-01-27 22:11 UTC, merged