Update naming rules for network
Azure/azure-sdk-for-net pull request #27072
Opened 2022-02-17 07:19 UTC by ArcturusZhang

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-02-17 08:11 UTC, m-nash requested changes

2022-02-17 08:11 UTC, m-nash commented on sdk/network/Azure.ResourceManager.Network/src/Generated/SubnetData.cs
> +        /// <param name="iPConfigurations"> An array of references to the network interface IP configurations using subnet. </param>
This should be ipConfiguration

2022-02-24 09:54 UTC, Yao725 approved these changes
Checked the updated API and the changes LGTM

2022-02-25 07:37 UTC, ArcturusZhang commented
Close in favor of https://github.com/Azure/azure-sdk-for-net/pull/27139

2022-02-25 07:37 UTC, closed without merging