Migrate HDInsight Management SDK to use the new data-plane URL recommended by Azure Data Lake
Azure/azure-sdk-for-net pull request #2739
Opened 2017-01-19 10:14 UTC by srsiva

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-01-19 10:15 UTC, azurecla commented
Hi __@srsiva__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sisankar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2017-01-20 23:32 UTC, shefaliv approved these changes

2017-01-21 00:49 UTC, markcowl requested changes

2017-01-21 00:49 UTC, markcowl commented on src/ResourceManagement/HDInsight/HDInsight/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("2.1.0.0")]
AssemblyVersion should not change, for backward compatibility

2017-01-23 12:58 UTC, srsiva commented on src/ResourceManagement/HDInsight/HDInsight/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("2.1.0.0")]
fixed.

2017-01-24 00:36 UTC, markcowl requested changes

2017-01-24 00:36 UTC, markcowl commented on src/ResourceManagement/HDInsight/HDInsight/CustomizationModels/ServicePrincipal.cs
> +            this.ResourceUri = new Uri("https://datalake.azure.net/");
Please provide at least one updated test recording using the new resource uri

2017-01-24 00:36 UTC, markcowl commented on src/ResourceManagement/HDInsight/HDInsight/Microsoft.Azure.Management.HDInsight.nuget.proj
> +      <PackageVersion>2.1.0</PackageVersion>
Package version should be 2.0.1

2017-01-24 10:20 UTC, srsiva commented on src/ResourceManagement/HDInsight/HDInsight/Microsoft.Azure.Management.HDInsight.nuget.proj
> +      <PackageVersion>2.1.0</PackageVersion>
fixed

2017-01-24 11:38 UTC, srsiva commented on src/ResourceManagement/HDInsight/HDInsight/CustomizationModels/ServicePrincipal.cs
> +            this.ResourceUri = new Uri("https://datalake.azure.net/");
fixed

2017-01-24 18:49 UTC, markcowl approved these changes

2017-01-24 18:51 UTC, merged