Upgraded ClientRuntimes to latest coreCLR package
Azure/azure-sdk-for-net pull request #2746
Opened 2017-01-20 18:55 UTC by hovsepm

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-01-20 18:55 UTC, hovsepm commented
sign job: http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-sign/1358/

2017-01-21 00:49 UTC, brjohnstmsft commented on src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/project.json
> -    "Microsoft.Rest.ClientRuntime.Azure": "[3.3.1, 4.0)"
Shouldn't the version number of the libraries be bumped?

2017-01-21 01:05 UTC, hovsepm commented on src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/project.json
> -    "Microsoft.Rest.ClientRuntime.Azure": "[3.3.1, 4.0)"
Good catch! Thanks! :)

2017-01-21 01:07 UTC, hovsepm commented on src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/project.json
> -    "Microsoft.Rest.ClientRuntime.Azure": "[3.3.1, 4.0)"
since I have no idea when this PR will be merged and published I do not want to touch that part

2017-01-21 01:14 UTC, hovsepm commented
sign job with all the packages: http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-sign/1362/

2017-02-01 00:25 UTC, hovsepm commented
new Sign job: http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-sign/1373/

2017-02-13 23:43 UTC, shahabhijeet commented on src/ResourceManagement/Authorization/Microsoft.Azure.Management.Authorization/project.json
> +        "define": [ "NETSTANDARD15", "PORTABLE" ],
@hovsepm if we are moving to Net Standard 1.6, do we still need net standard 1.5 monikers?

2017-02-13 23:43 UTC, shahabhijeet commented on src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/project.json
> +        "define": [ "NETSTANDARD11", "PORTABLE" ],
@hovsepm do we need net standard 1.1 monikers?
Also we should completely remove all "portable" monikers. The term portable is confusing and not sure what exactly it means.

2017-02-13 23:43 UTC, shahabhijeet commented on src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/project.json
> +        "define": [ "NETSTANDARD11", "PORTABLE" ],
@hovsepm we should remove all non compatible defines from under the corresponding frameworks.

2017-02-13 23:44 UTC, shahabhijeet requested changes
Suggested fixes

2017-02-13 23:59 UTC, hovsepm commented on src/ResourceManagement/Authorization/Microsoft.Azure.Management.Authorization/project.json
> +        "define": [ "NETSTANDARD15", "PORTABLE" ],
This is still in the investigation. We do not have the list of the monikers that we should support. I've just used whatever we currently ship.

2017-02-13 23:59 UTC, hovsepm commented on src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/project.json
> +        "define": [ "NETSTANDARD11", "PORTABLE" ],
Please see my previous answer.

2017-02-14 00:00 UTC, hovsepm commented on src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/project.json
> +        "define": [ "NETSTANDARD11", "PORTABLE" ],
First we need to fix AutoRest not to generate PORTABLE definition in code. Then remove it
e.g. https://github.com/Azure/azure-sdk-for-net/blob/7c79d8a0930c93917b3c1029ec2936423719ae15/src/ClientRuntime/Microsoft.Rest.ClientRuntime/RestException.cs#L12

2017-02-28 18:53 UTC, markcowl commented
No longer needed

2017-02-28 18:53 UTC, closed without merging