Gallery 01 03 SDK
Azure/azure-sdk-for-net pull request #27466
Opened 2022-03-10 01:27 UTC by kangsun-ctrl

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-03-10 18:44 UTC, grizzlytheodore commented
/azp run net - mgmt - ci

2022-03-17 05:43 UTC, fengzhou-msft approved these changes

2022-04-18 17:27 UTC, Sandido requested changes

2022-04-18 17:27 UTC, Sandido commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/CommunityGalleryImage.cs
> +        public CommunityGalleryImage(OperatingSystemTypes osType, OperatingSystemStateTypes osState, GalleryImageIdentifier identifier, string name = default(string), string location = default(string
No need for a customization.

2022-04-18 17:27 UTC, Sandido commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/CommunityGalleryImageVersion.cs
> +        public CommunityGalleryImageVersion(string name = default(string), string location = default(string), string type = default(string), string uniqueId = default(string), System.DateTime? publis
No need for customization.

2022-04-18 17:27 UTC, Sandido commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/SharedGalleryImage.cs
> +        public SharedGalleryImage(OperatingSystemTypes osType, OperatingSystemStateTypes osState, GalleryImageIdentifier identifier, string name = default(string), string location = default(string),
no need for customization

2022-04-18 17:27 UTC, Sandido commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/SharingProfileGroupTypes.cs
> -        public const string Community = "Community";
Is this expected?

2022-04-18 17:32 UTC, Sandido commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/SharingProfileGroupTypes.cs
> -        public const string Community = "Community";
based on this change, https://github.com/Azure/azure-rest-api-specs/pull/17985/files#diff-2861a3a31f910fbcb3cbc0af6f313527001ff65e8360cfcc566ae280a27b8bf9L1849 , looks like it is.

2022-04-18 17:36 UTC, Sandido approved these changes

2022-04-18 17:39 UTC, merged