[phone number sdk] Adds environment variable AZURE_USERAGENT_OVERRIDE, that overrides x-ms-useragent
Azure/azure-sdk-for-net pull request #27509
Opened 2022-03-11 17:06 UTC by automagically

Change needed to fix test pipelines

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-03-11 17:16 UTC, azure-sdk commented
API changes have been detected in `Azure.Communication.PhoneNumbers`. You can review API changes [here](https://apiview.dev/Assemblies/Review/e99a11a1278f40319e97929b17c7e3cb?diffOnly=True&diffRevisionId=5d31b6f89e7c435b8908dd155ca6f6e0)

**API changes**
```diff
+     public class MSUserAgentPolicy : HttpPipelinePolicy {
+         public MSUserAgentPolicy();
+         public override void Process(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline);
+         public override ValueTask ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline);
+     }
```

2022-03-11 20:24 UTC, danielortega-msft requested changes

2022-03-11 20:24 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClientOptionsExtensions.cs
> +    /// Summary description for Class1
Please update this to describe the purpose of this class.

2022-03-11 21:21 UTC, whisper6284 commented on sdk/communication/Azure.Communication.PhoneNumbers/src/MSUserAgentPolicy.cs
> +    /// Summary description for Class1
Update summary.

2022-03-11 21:24 UTC, whisper6284 commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClientOptionsExtensions.cs
> +            return HttpPipelineBuilder.Build(options, authPolicy, msUserAgentPolicy);
Double-checking that this is how it gets called in ClientOptions?

2022-03-11 21:24 UTC, lucasrsant commented
Could you please provide a more detailed description to this pull request? What was happening, the proposed solution, etc.

2022-03-11 21:25 UTC, lucasrsant requested changes
Could you please provide a more detailed description to this pull request? What was happening, the proposed solution, etc.

2022-03-11 21:30 UTC, lucasrsant requested changes

2022-03-11 21:30 UTC, lucasrsant commented on sdk/communication/Azure.Communication.PhoneNumbers/src/MSUserAgentPolicy.cs
> +        /// Processed message adding the HTTP header x-ms-useragent if applicable.
nit: Processes

2022-03-11 21:30 UTC, lucasrsant commented on sdk/communication/Azure.Communication.PhoneNumbers/src/MSUserAgentPolicy.cs
> +        /// Processed message asynchronously adding the HTTP header x-ms-useragent if applicable.
nit: Processes

2022-03-14 17:00 UTC, whisper6284 commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClientOptionsExtensions.cs
> +            return HttpPipelineBuilder.Build(options, authPolicy, msUserAgentPolicy);
Verified that this is the same as ClientOptionsExtensions.

2022-03-14 17:01 UTC, whisper6284 approved these changes

2022-03-14 17:03 UTC, lucasrsant approved these changes

2022-03-14 18:36 UTC, danielortega-msft approved these changes

2022-03-15 17:04 UTC, merged