Update Compute SDK to latest (including ACS)
Azure/azure-sdk-for-net pull request #2754
Opened 2017-01-24 22:37 UTC by colemickens

## Description
This finishes @brendandburns's efforts to get the Compute SDK regenerated.

I took his commit, verbatim, and simply fixed what needed to be fixed to get the tests passing.

Commits:

1. @brendandburns's update commit verbatim (other than rebasing)

2. Fix `Set-TestEnvironment` so that it sets `AZURE_TEST_MODE`. The code in `azure-sdk-for-net` that sets the TestMode based on the connection string **is never called**, at least not during the ACS tests. This was the only way I could get the tests infra to work correctly.

3. Update the username used for ACS (since our Swagger spec is overly strict, apparently) and then update the SSH public key as well. These were the two validation failures that were preventing test records.

4. Update the recorded tests for the above commits.

Let me know if this needs to be squashed (as is, certain commits don't pass tests, since I've got the test updates in a separate commit).

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

Per the last discussion, it does introduce a breaking change, but the version is bumped accordingly.

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-01-24 22:37 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-01-24 22:37 UTC, azurecla commented
Hi __@colemickens__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (colemick). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2017-01-24 22:46 UTC, cormacpayne commented
@azuresdkci add to whitelist

2017-01-26 23:52 UTC, shahabhijeet requested changes

2017-01-26 23:52 UTC, shahabhijeet commented on src/ResourceManagement/Compute/Compute.Tests/ContainerServiceTests/ContainerServiceTestsBase.cs
> +        private const string DefaultSshPublicKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDorij8dGcKUBTbvHylBpm5NZ2MtDgn1+jbyHE8N4dCS4ZoIl6Pdoa1At/GjXVhIRuz1hlyT2ey5BaC8iQnQTh/f2oyNctQ5+2KX1sgFlvaQAJ
nit: moving forward have long string collapsed for readability as well GitHub UI is not good when it comes horizontal scrolling.
This is fine as reading SSH keys do not make sense, but to maintain consistency across all long strings will be good.

2017-01-26 23:52 UTC, shahabhijeet commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ComputeManagementClient.cs
> +        public virtual IContainerServicesOperations ContainerServices { get; private set; }
This is breaking change. So please bump up the major version for your package.

2017-01-27 00:24 UTC, shahabhijeet requested changes

2017-01-27 00:24 UTC, shahabhijeet commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ContainerServicesOperations.cs
> +        public async System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<Microsoft.Rest.Azure.IPage<ContainerService>>> ListWithHttpMessagesAsync(System.Collections.Generic.Dictio
Seems you are using an older version of AutoRest. Also I do not see generate.cmd getting updated.
Now that AutoRest is out of preview, you should be using the latest version 1.0.xxx
With the new version you should not see fully qualified names of types in the generated code.

2017-01-27 00:24 UTC, shahabhijeet commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachine.cs
> +        /// <param name="id">Resource ID.</param>
nit: Id instead of ID

2017-01-27 00:24 UTC, shahabhijeet commented on tools/Repo-Tasks.psm1
> +    $env:AZURE_TEST_MODE=$RecordMode
This is really good idea.

2017-01-27 00:24 UTC, shahabhijeet commented on tools/Repo-Tasks.psm1
> +export-modulemember -Function Set-TestMode
are you missing adding a function, seems you have exported the function, but I am not sure if that function is implemented.

2017-01-27 04:04 UTC, colemickens commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachine.cs
> +        /// <param name="id">Resource ID.</param>
Is this not derived from the Swagger?

2017-01-27 04:05 UTC, colemickens commented on tools/Repo-Tasks.psm1
> +export-modulemember -Function Set-TestMode
Not sure why this is there. I don't remember where I was going with it. Will be removed.

2017-01-27 04:06 UTC, colemickens commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ContainerServicesOperations.cs
> +        public async System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<Microsoft.Rest.Azure.IPage<ContainerService>>> ListWithHttpMessagesAsync(System.Collections.Generic.Dictio
How can I most easily discover the latest available working nightly? Since the other RPs seem to be on nightly revs from December?

2017-01-27 04:08 UTC, colemickens commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ContainerServicesOperations.cs
> +        public async System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<Microsoft.Rest.Azure.IPage<ContainerService>>> ListWithHttpMessagesAsync(System.Collections.Generic.Dictio
Never mind, found it on myget: https://www.myget.org/gallery/autorest

2017-01-27 04:14 UTC, colemickens commented on src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/ContainerServicesOperations.cs
> +        public async System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<Microsoft.Rest.Azure.IPage<ContainerService>>> ListWithHttpMessagesAsync(System.Collections.Generic.Dictio
So I bumped the version and ran `Start-Build`. Nothing changed.

2017-01-27 22:32 UTC, markcowl commented
@colemickens How does this PR relate to this PR in compute:  https://github.com/Azure/azure-sdk-for-net/pull/2751

If your changes are necessary, please work with Hyonho on getting them incorproarted into his PR.

2017-01-27 22:42 UTC, colemickens commented
It would appear that that PR does basically the same things as mine, and then a few more. I'll comment on that issue to see if my PR can simply be dropped... Thanks for the heads up.

2017-01-27 22:44 UTC, colemickens commented
(though the AZURE_TEST_MODE commit will be preserved - I wasted a large amount of time on that)

2017-01-28 00:12 UTC, colemickens commented
cc: @markcowl @hyonholee

I feel strongly that this PR should be preferred:

1. It includes additional fixes to make the ContainerServices tests really pass
2. Separate commits for the various bumping of things
3. Includes a fix for `AZURE_TEST_MODE` problem which cost a lot of time

More concerningly, the other PR is created by manually updating the contents of the test recordings and by my measure could be (and likely is) masking failure cases.

Case in point, my latest push has changes to the test record files, but only a subset. There are a set of Compute tests that are reliably failing - including failures that look like potential regressions or indicate problems with the Compute tests.

I have updated this PR with the latest. The test record files included in the most recent commit are the ones that work. The ones that remain, and need investigation by Compute are:

* Compute.Tests.ExtensionTests.TestVMExtensionOperations
* Compute.Tests.ListVMTests.TestListVMInSubscription
* Compute.Tests.OSProfileTests.TestVMWithLinuxOSProfile
* Compute.Tests.UsageTests.TestListUsages
* Compute.Tests.VMDataDiskTests.TestVMDataDiskScenario
* Compute.Tests.VMDiagnosticsTests.TestVMBootDiagnostics
* Compute.Tests.VMDiskSizeTests.TestVMDiskSizeScenario
* Compute.Tests.VMMarketplaceTest.TestVMBYOL
* Compute.Tests.VMMarketplaceTest.TestVMMarketplace
* Compute.Tests.VMNetworkInterfaceTests.TestEffectiveRouteAndAcls
* Compute.Tests.VMNetworkInterfaceTests.TestMultiIpConfigForMultiNICVM
* Compute.Tests.VMNetworkInterfaceTests.TestMultiNicVirtualMachineReference
* Compute.Tests.VMNetworkInterfaceTests.TestNicVirtualMachineReference
* Compute.Tests.VMOperationalTests.TestVMOperations
* Compute.Tests.VMOperationalTests.TestVMOperations_Redeploy
* Compute.Tests.VMScenarioTests.TestVMScenarioOperations

2017-01-28 00:13 UTC, colemickens commented
(and note, I've fixed all of the things requested by @shahabhijeet)

2017-01-28 00:14 UTC, colemickens commented
There is one thing I'm unclear about. I'm unsure whether I actually pulled the Compute swagger up to the latest in any of these commits. How is that done? I couldn't easily discern this from the other PR as the commits are too big to review easily on GitHub.

2017-01-28 00:23 UTC, colemickens commented
Offline discussion with @shahabhijeet has quelled my concerns. I have indeed generated for the latest available compositeComputeSwagger, since the Compute `generate.cmd` just pulls from master and the composite compute swagger is... unversioned...

2017-01-28 02:08 UTC, colemickens commented
(BTW: @hyonholee the cred scanner was correctly complaining. The ssh public key in the code now is actually a private key...)

2017-02-02 01:59 UTC, closed without merging