[LogicApp Integration Accounts] [Bug Fix] : Code generated as per the latest RP updates.
Azure/azure-sdk-for-net pull request #2769
Opened 2017-01-31 01:33 UTC by pankajsn

## Description
1) Swagger spec updated as per the latest changes in the RP definitions
2) LogicApp and Integration account spec are merged (2015-08-01-preview with 2016-06-01) as both are in GA.

https://github.com/Azure/azure-rest-api-specs/pull/891
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x]  **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-01-31 01:33 UTC, azurecla commented
Hi __@pankajsn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pankajsn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2017-01-31 17:14 UTC, cormacpayne commented
@pankajsn adding the "Do Not Merge" label until the corresponding Swagger spec has been merged

2017-02-14 20:07 UTC, cormacpayne commented
@pankajsn Hey Pankaj, can you update your `generated.cmd` file with the swagger spec you are using to generate this SDK? It should be the following link below that includes the commit ID

```
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/ecc34b75fe5aecebd148b74392b67e85070e0fc5/arm-logic/2016-06-01/swagger/logic.json
```

2017-02-14 20:17 UTC, pankajsn commented
Updated

From: Cormac McCarthy [mailto:notifications@github.com]
Sent: Tuesday, February 14, 2017 12:08 PM
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Pankaj Singh Negi <Pankaj.Negi@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] [LogicApp Integration Accounts] [Bug Fix] : Code generated as per the latest RP updates. (#2769)


@pankajsn<https://github.com/pankajsn> Hey Pankaj, can you update your generated.cmd file with the swagger spec you are using to generate this SDK? It should be the following link below that includes the commit ID

https://raw.githubusercontent.com/Azure/azure-rest-api-specs/ecc34b75fe5aecebd148b74392b67e85070e0fc5/arm-logic/2016-06-01/swagger/logic.json

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/Azure/azure-sdk-for-net/pull/2769#issuecomment-279820644>, or mute the thread<https://github.com/notifications/unsubscribe-auth/APZfcy-ea8LJ4miyyCVBFyZoi3TayY6Wks5rcgmhgaJpZM4LyIy5>.

2017-02-14 21:18 UTC, shahabhijeet commented
@pankajsn credscan faild, can you check in your test if you have used any password or serviceprincipal secrets.

2017-02-15 01:46 UTC, pankajsn commented
Credscan warnings are fixed. (http://azuresdkci.cloudapp.net/job/sdk-for-net/4440)

From: Abhijeet [mailto:notifications@github.com]
Sent: Tuesday, February 14, 2017 1:19 PM
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Pankaj Singh Negi <Pankaj.Negi@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] [LogicApp Integration Accounts] [Bug Fix] : Code generated as per the latest RP updates. (#2769)


@pankajsn<https://github.com/pankajsn> credscan faild, can you check in your test if you have used any password or serviceprincipal secrets.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/Azure/azure-sdk-for-net/pull/2769#issuecomment-279838995>, or mute the thread<https://github.com/notifications/unsubscribe-auth/APZfc5NnGUud4W3gSYRiBlwGW3tC3Eumks5rcho7gaJpZM4LyIy5>.

2017-02-15 16:37 UTC, shahabhijeet requested changes

2017-02-15 16:37 UTC, shahabhijeet commented on src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/project.json
> +  "version": "2.0.0",
@pankajsn can you do same version bump in AssemblyInfo.cs in order to be consistent
otherwise looks good.

2017-02-15 17:54 UTC, pankajsn commented
fixed

From: Abhijeet [mailto:notifications@github.com]
Sent: Wednesday, February 15, 2017 8:38 AM
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Pankaj Singh Negi <Pankaj.Negi@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] [LogicApp Integration Accounts] [Bug Fix] : Code generated as per the latest RP updates. (#2769)


@shahabhijeet requested changes on this pull request.

________________________________

In src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/project.json<https://github.com/Azure/azure-sdk-for-net/pull/2769#pullrequestreview-22046137>:

> @@ -1,5 +1,5 @@

 ﻿{

-  "version": "1.0.0",

+  "version": "2.0.0",

@pankajsn<https://github.com/pankajsn> can you do same version bump in AssemblyInfo.cs in order to be consistent
otherwise looks good.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/Azure/azure-sdk-for-net/pull/2769#pullrequestreview-22046137>, or mute the thread<https://github.com/notifications/unsubscribe-auth/APZfc71SNE6PDPM6dgiYgExRfslu8ZETks5rcynlgaJpZM4LyIy5>.

2017-02-15 23:20 UTC, merged