CDRP SDK
Azure/azure-sdk-for-net pull request #27726
Opened 2022-03-23 23:42 UTC by haagha

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-03-30 22:18 UTC, haagha commented
@m-nash can you help with the CI failure? Also this is generated from preview Swagger, should we merge it to main?

2022-04-19 09:44 UTC, archerzz requested changes
Need to change the API tag in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/compute/Microsoft.Azure.Management.Compute/AzSdk.RP.props

2022-04-19 09:44 UTC, archerzz commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("54.1.0")]
Keep the `AssemblyVersion`, unless it's a major change. See: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=signing-and-publishing-nuget-packges

2022-04-19 14:37 UTC, haagha commented
> Need to change the API tag in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/compute/Microsoft.Azure.Management.Compute/AzSdk.RP.props

@archerzz This is supposed to be preview SDK, if I change API tag it will show in consequent stable SDK's. Is that fine?
2nd question: When I publish the SDK should I do it from main or cdrpsdk branch?

2022-04-20 06:13 UTC, archerzz commented
> > Need to change the API tag in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/compute/Microsoft.Azure.Management.Compute/AzSdk.RP.props
> 
> @archerzz This is supposed to be preview SDK, if I change API tag it will show in consequent stable SDK's. Is that fine? 2nd question: When I publish the SDK should I do it from main or cdrpsdk branch?

@haagha It's OK to have preview api tag. You can see them in other SDKs as well, like [this](https://github.com/Azure/azure-sdk-for-net/blob/35eb8d55e6e37fb02b4422f3a65419b3ed3ac1cd/sdk/authorization/Microsoft.Azure.Management.Authorization/AzSdk.RP.props).
It's recommended to release from `main`. You can specify specific commit in the release job, if necessary.

2022-04-21 05:48 UTC, archerzz approved these changes

2022-04-21 05:49 UTC, archerzz commented
/check-enforcer evaluate

2022-04-21 05:50 UTC, archerzz commented
/check-enforcer reset

2022-04-21 05:51 UTC, merged