Remove policy exemption and tweak some model names
Azure/azure-sdk-for-net pull request #27865
Opened 2022-03-31 02:03 UTC by ArcturusZhang

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-03-31 02:15 UTC, ArthurMa1978 approved these changes

2022-03-31 02:15 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager`**

API changes have been detected in `Azure.ResourceManager`. You can review API changes [here](https://apiview.dev/Assemblies/Review/c3901c823d67425c8a9c895c663a18aa?diffOnly=True&diffRevisionId=95ac350e013c406188c3f299c067e43b)

2022-03-31 02:16 UTC, Yao725 approved these changes
LGTM, but please also disable the corresponding tests.

2022-03-31 16:39 UTC, m-nash requested changes

2022-03-31 16:39 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/Models/CreateManagementGroupData.cs
> +    public partial class CreateManagementGroupData
We should not use the suffix Data unless it inherits from one of our ResourceData objects, we can just undo this rename

2022-03-31 16:39 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/Models/CreateManagementGroupChildInfo.Serialization.cs
> +    public partial class CreateManagementGroupChildInfo
undo this rename

2022-03-31 16:39 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/Models/CreateManagementGroupChildInfo.cs
> +    public partial class CreateManagementGroupChildInfo
undo this rename

2022-03-31 16:39 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/Models/CreateManagementGroupData.Serialization.cs
> +    public partial class CreateManagementGroupData : IUtf8JsonSerializable
undo this rename

2022-03-31 16:39 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/Models/CreateParentGroupInfo.Serialization.cs
> +    public partial class CreateParentGroupInfo : IUtf8JsonSerializable
undo this rename

2022-03-31 16:39 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/Models/CreateParentGroupInfo.cs
> +    public partial class CreateParentGroupInfo
undo this rename

2022-04-01 01:51 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/Models/CreateManagementGroupData.cs
> +    public partial class CreateManagementGroupData
[Entity][Method]Options -> reserved for optional parameter bag

2022-04-01 02:11 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/ManagementGroup/Generated/ManagementGroupCollection.cs
> +        public virtual async Task<ArmOperation<ManagementGroupResource>> CreateOrUpdateAsync(WaitUntil waitUntil, string groupId, CreateManagementGroupData data, string cacheControl = null, Cancellat
CreateManagementGroupOptions
ManagementGroupCreateOrUpdateOptions

CreateManagementGroupInfo

Patchable[Entity]Data
Creatable[Entity]Data

[Entity]CreateOrUpdateInfo
[Entity][Method]Info

2022-04-01 02:11 UTC, m-nash approved these changes
Approve based on undoing the renames and moving that into a separate PR

2022-04-01 06:39 UTC, merged