Route Filter Feature Support from Express Route
Azure/azure-sdk-for-net pull request #2795
Opened 2017-02-07 21:55 UTC by dihan0604

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-02-07 21:56 UTC, dihan0604 commented
Swagger Spec: 
https://github.com/Azure/azure-rest-api-specs/pull/855

2017-02-08 19:27 UTC, cormacpayne commented
@dihan0604 it looks like the following session record was not found: `Network.Tests.Tests.RouteFilterTests\EmptyRouteFilterTest.json`

2017-02-08 20:15 UTC, dihan0604 commented
@cormacpayne , I debugged this with Abhijeet and we realize we can not have tests in SDK. My feature is enabled in brazilUS (Stage ARM), however, for the current SDK tests, we do not provide this environment. I discussed with Abhijeet and he agreed that I can add tests in PS instead of SDK. I have removed the tests from this PR. Once brazilUS environment is available in SDK,  I will add these tests back.

2017-02-09 00:53 UTC, cormacpayne commented
@azuresdkci test this please

2017-02-09 18:38 UTC, cormacpayne requested changes
@dihan0604 a few comments about breaking changes in this pull request. Since this SDK is in preview, it is fine to introduce breaking changes, but you will need to mitigate these changes in PowerShell

Also, you have a large number of commits, so you are going to need to [rebase](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md#rebasing) to clean this up

2017-02-09 18:38 UTC, cormacpayne commented on src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ExpressRouteCircuitPeering.cs
> +        public ExpressRouteCircuitPeering(string id = default(string), string peeringType = default(string), string state = default(string), int? azureASN = default(int?), int? peerASN = default(int?
@dihan0604 changing the order of parameters in the constructor is a breaking change

2017-02-09 18:38 UTC, cormacpayne commented on src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/Access.cs
> +    public static class Access
@dihan0604 changing the name of this class is a breaking change

2017-02-09 18:38 UTC, cormacpayne commented on src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/AzureAsyncOperationResult.cs
> -    public partial class AzureAsyncOperationResult
@dihan0604 removing this class is a breaking change

2017-02-09 19:50 UTC, cormacpayne commented
@dihan0604 it looks like @lamchester just opened a similar PR to this one (https://github.com/Azure/azure-sdk-for-net/pull/2798). Can we try and consolidate both PR changes into one?

2017-02-09 20:06 UTC, dihan0604 commented
@cormacpayne Comments addressed

2017-02-09 20:18 UTC, dihan0604 commented
@cormacpayne , I chatted with Chester and he agrees to wait my PR get merged and he makes his PR on top of mine. This is due to my swagger changes already merged but not the SDK.

2017-02-09 22:30 UTC, closed without merging