Updated tests for changes in PR https://github.com/Azure/azure-rest-api-specs/pull/18609
Azure/azure-sdk-for-net pull request #28063
Opened 2022-04-07 20:41 UTC by D1v38om83r

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-04-07 20:49 UTC, D1v38om83r commented
SDK generated from https://github.com/Azure/azure-rest-api-specs/pull/18609/commits/f830443fc02f57330ea9dc27a37e9f4bc6ca8010

PR https://github.com/Azure/azure-rest-api-specs/pull/18609

2022-04-18 19:33 UTC, grizzlytheodore commented on eng/mgmt/mgmtmetadata/compute_resource-manager.txt
>  Executing AutoRest command
please remove this from the PR

2022-04-18 19:41 UTC, grizzlytheodore requested changes

2022-04-18 19:41 UTC, grizzlytheodore commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/GalleryApplicationVersionPublishingProfile.cs
> +            Settings = settings;
customization needed - for theo

2022-04-18 19:41 UTC, grizzlytheodore commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/SdkInfo_ComputeManagementClient.cs
> +      // BEGIN: Code Generation Metadata Section
please also remove this from the PR

2022-04-18 21:07 UTC, D1v38om83r commented on eng/mgmt/mgmtmetadata/compute_resource-manager.txt
>  Executing AutoRest command
done

2022-04-18 21:10 UTC, D1v38om83r commented on sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/SdkInfo_ComputeManagementClient.cs
> +      // BEGIN: Code Generation Metadata Section
done

2022-05-09 22:39 UTC, merged