Initial SQL .NET SDK
Azure/azure-sdk-for-net pull request #2807
Opened 2017-02-10 02:34 UTC by nathannfan

## Description
Corresponding swagger checkin: https://github.com/Azure/azure-rest-api-specs/pull/622

This covers core SQL functionality, firewall rules, and replicationLinks.  

This is a revival of the pull request here: https://github.com/Azure/azure-sdk-for-net/pull/2493
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-02-10 02:34 UTC, azurecla commented
Hi __@nathannfan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nafan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2017-02-10 22:06 UTC, cormacpayne commented
@nathannfan Hey Nathan, would you mind taking a look at the checklist provided above and filling out the corresponding boxes?

2017-02-10 22:13 UTC, nathannfan commented
@cormacpayne Updated.  I was trying to do that earlier but for some reason I couldn't.  Also, I can't read the contributing guidelines.  Is it possible that it has moved?

2017-02-10 22:35 UTC, cormacpayne commented
@nathannfan ah yes, good catch. We recently moved it from `.\CONTRIBUTING.md` to `.github\CONTRIBUTING.md`, which you can find [here](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md)

2017-02-15 00:01 UTC, akromm-zz requested changes
As a note, don't forget to add the required files to generate the nuget package onces all the APIs are done.

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/Database.cs
> +        /// GB … 500 GB }</param>
This list of max sizes should not be here. We should replace it with a suggestion to call the /capabilities API to get a list of max sizes per edition/slo/pool/dtu that are available.

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/Database.cs
> +        /// 'S3', 'P1', 'P2', 'P3'</param>
remove list of possible values and reference to the /capabilities api

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/Database.cs
> +        /// </summary>
Same thing. Reference the /capabilities API to get available editions

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// Possible values include: 'Basic', 'Standard', 'Premium'</param>
ref /capabilities

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// </summary>
ref /capabilities.  

All places please.

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// Elastic Pool.
Nit: This should probably be "Azure SQL Database Elastic Pool" in all locations

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// Elastic Pool.
find & replace "SQL Azure" -> "Azure SQL"

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/RecommendedIndex.cs
> +        /// </summary>
It would be good to reference RecommendedIndexActions class instead of writing out all the possible values here.

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/RecommendedIndex.cs
> +        /// </summary>
RecommendedIndexStates class.

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ServiceObjectiveName.cs
> +        public const string P3 = "P3";
This list is quite out of date. It would be good to remove it if possible.

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/TargetDatabaseEditions.cs
> +    public static class TargetDatabaseEditions
Can references to this be replaced with DatabaseEditions and delete this class?

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/TargetElasticPoolEditions.cs
> +    public enum TargetElasticPoolEditions
Same comment as for TargetDatabaseEditions

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("0.51.0.0")]
Lets change this to 1.0.0.0

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("Microsoft Azure SQL Server Management Library")]
"Microsoft Azure SQL Management Library"

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Sql.Tests/DatabaseCrudScenarioTests.cs
> +﻿using Microsoft.Azure.Management.Resources;
Please add file header

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Sql.Tests/DatabaseReplicationLinkScenarioTests.cs
> +﻿using Microsoft.Azure.Management.Resources;
Please add file header

2017-02-15 00:01 UTC, akromm commented on src/ResourceManagement/SqlManagement/Sql.Tests/ElasticPoolActivityScenarioTests.cs
> +﻿using Microsoft.Azure.Management.Resources;
Please add file header.  Please check all files in SQL.Tests.

2017-02-15 21:32 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("0.51.0.0")]
What are the consequences of version `1.0.0.0`? Doesn't this mean we are committing to keeping API stable?

2017-02-15 21:57 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/Database.cs
> +        /// GB … 500 GB }</param>
This is generated from the swagger, so I will address this in a separate PR for the specs.

2017-02-15 21:57 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/Database.cs
> +        /// 'S3', 'P1', 'P2', 'P3'</param>
This is generated from the swagger, so I will address this in a separate PR for the specs.

2017-02-15 21:57 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/Database.cs
> +        /// </summary>
This is generated from the swagger, so I will address this in a separate PR for the specs.

2017-02-15 21:57 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// Possible values include: 'Basic', 'Standard', 'Premium'</param>
This is generated from the swagger, so I will address this in a separate PR for the specs.

2017-02-15 21:57 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// </summary>
This is generated from the swagger, so I will address this in a separate PR for the specs.

2017-02-15 22:58 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ServiceObjectiveName.cs
> +        public const string P3 = "P3";
The Azure SDK team had me add this.  I know it's hard to keep up-to-date, but that's why I have it as model-as-string, so values not in this list can also be specified.

2017-02-15 23:00 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// Elastic Pool.
Addressed in Swagger.

2017-02-15 23:01 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ElasticPool.cs
> +        /// </summary>
This is generated from the swagger, so I will address this in a separate PR for adding the capabilities api swagger.

2017-02-15 23:10 UTC, salameer commented
@cormacpayne Captain Cormac Can we kindly review these PR :)

2017-02-15 23:22 UTC, shahabhijeet commented
@salameer once we get a sign off from Adam or jared, we should be good to go.

2017-02-16 00:11 UTC, jaredmoo approved these changes

2017-02-16 00:11 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/Sql.Tests/DatabaseCrudScenarioTests.cs
> +                // Create database only required parameters
I know this is annoying to regenerate the replay data, but can you split each of these cases into separate [Fact]s?

2017-02-16 00:11 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/Sql.Tests/DatabaseCrudScenarioTests.cs
> +                var updateEditionAndSloInput = new Database()
these can all be the same [Fact] since they are upgrading a single database through the test

2017-02-16 00:12 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/ServiceObjectiveName.cs
> +        public const string P3 = "P3";
I would recommend updating it to be current as of today then.

2017-02-16 00:12 UTC, akromm commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("0.51.0.0")]
We can still mark the NuGet package as "-prerelease" until all the swagger conversions are done.

The main motivation behind this is to make a distinction between hyak generated and swagger generated nuget packages.

2017-02-16 00:18 UTC, akromm-zz approved these changes

2017-02-16 00:21 UTC, nathannfan commented
Thanks for the signoffs, guys.

Cormac, please don't merge this yet - I'd like to address all the minor issues and send one more commit before checking in.

2017-02-16 18:44 UTC, jaredmoo commented
When I build, I get these warnings:

7>D:\git\azure-sdk-for-net\src\ResourceManagement\SqlManagement\Sql.Tests\project.json(26,43): warning NU1012: Dependency conflict. Microsoft.Rest.ClientRuntime.Azure.Authentication 2.2.10 expected Microsoft.Rest.ClientRuntime >= 2.3.5 < 3.0 but received 2.3.3
7>D:\git\azure-sdk-for-net\src\ResourceManagement\SqlManagement\Sql.Tests\project.json(26,43): warning NU1012: Dependency conflict. Microsoft.Rest.ClientRuntime.Azure.TestFramework 1.5.2 expected Microsoft.Rest.ClientRuntime >= 2.3.5 < 3.0.0 but received 2.3.3

2017-02-16 23:22 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Microsoft.Azure.Management.Sql/Generated/Models/TargetDatabaseEditions.cs
> +    public static class TargetDatabaseEditions
Wow, this wasn't even referenced.

2017-02-16 23:35 UTC, nathannfan commented on src/ResourceManagement/SqlManagement/Sql.Tests/DatabaseCrudScenarioTests.cs
> +                // Create database only required parameters
Discussed offline - because of the huge runtime and because these tests can be considered more E2E than unit tests, leaving like this for now.

2017-02-17 08:10 UTC, nathannfan commented
@cormacpayne can this be merged in now?

2017-02-17 22:09 UTC, merged