CosmosDB management SDK 2022-02-15-preview
Azure/azure-sdk-for-net pull request #28192
Opened 2022-04-13 19:36 UTC by amar-sagare

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-04-18 05:36 UTC, amar-sagare commented
@archerzz  can you please review this PR?

2022-04-18 17:36 UTC, amar-sagare commented
waiting for firhter changes please do not merge.

2022-04-27 20:46 UTC, amar-sagare commented
@archerzz  can you please review this. Thanks!

2022-04-28 01:06 UTC, archerzz requested changes

2022-04-28 01:17 UTC, archerzz commented on sdk/cosmosdb/Microsoft.Azure.Management.CosmosDB/src/Generated/Models/RestorableDatabaseAccountGetResult.cs
> +        public RestorableDatabaseAccountGetResult(string accountName = default(string), System.DateTime? creationTime = default(System.DateTime?), System.DateTime? oldestRestorableTime = default(Syst
breaking change: new parameters inserted in existing parameters

2022-04-28 01:17 UTC, archerzz commented on sdk/cosmosdb/Microsoft.Azure.Management.CosmosDB/src/Generated/Models/RestorableSqlContainerPropertiesResourceContainer.cs
> +        public RestorableSqlContainerPropertiesResourceContainer(string id, IndexingPolicy indexingPolicy = default(IndexingPolicy), ContainerPartitionKey partitionKey = default(ContainerPartitionKey
same breaking change

2022-04-28 01:18 UTC, archerzz commented on sdk/cosmosdb/Microsoft.Azure.Management.CosmosDB/src/Generated/Models/SqlContainerResource.cs
> +        public SqlContainerResource(string id, IndexingPolicy indexingPolicy = default(IndexingPolicy), ContainerPartitionKey partitionKey = default(ContainerPartitionKey), int? defaultTtl = default(
same breaking change

2022-04-28 01:38 UTC, archerzz approved these changes
approved, given the SDK is still in `preview` stage.

2022-04-28 02:33 UTC, merged

2022-05-02 17:47 UTC, chidozieononiwu commented
Looks like this was merged into the wrong directory. Tis needs to be reverted and added into https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cosmosdb/Microsoft.Azure.Management.CosmosDB

@weshaggard

2022-05-11 07:39 UTC, ArthurMa1978 commented
> Looks like this was merged into the wrong directory. Tis needs to be reverted and added into https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cosmosdb/Microsoft.Azure.Management.CosmosDB
> 
> @weshaggard

should be fixed