Enabled interactive login for test framework for .net45 scenarios
Azure/azure-sdk-for-net pull request #2828
Opened 2017-02-16 00:52 UTC by shahabhijeet

Enabling interactive login for test framework for .NET 45 scenarios.

2017-02-16 22:44 UTC, hovsepm requested changes

2017-02-16 22:44 UTC, hovsepm commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure.Authentication/Properties/AssemblyInfo.cs
> -[assembly: AssemblyFileVersion("2.2.10.0")]
Did you mean 2.2.11? if so please keep AssemlbyVersion as 2.0.0 since Patch update means to be non-breaking

2017-02-18 20:04 UTC, shahabhijeet commented
@azuresdkci retest this

2017-02-21 19:17 UTC, hovsepm approved these changes

2017-02-22 01:43 UTC, merged