Generate mgmt sdk with property bag
Azure/azure-sdk-for-net pull request #28362
Opened 2022-04-25 04:14 UTC by Yao725

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-04-25 04:22 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager.CosmosDB`**

API changes have been detected in `Azure.ResourceManager.CosmosDB`. You can review API changes [here](https://apiview.dev/Assemblies/Review/46a7e9e2beea47c5a3f89c1a897b2a80?diffOnly=True&diffRevisionId=33fa8984b4f448f99e4804844c4b0efd)

**API changes**
```diff
-         public virtual Pageable<RestorableSqlContainer> GetRestorableSqlContainers(string restorableSqlDatabaseRid = null, string startTime = null, string endTime = null, CancellationToken cancellationToken = default);
-         public virtual AsyncPageable<RestorableSqlContainer> GetRestorableSqlContainersAsync(string restorableSqlDatabaseRid = null, string startTime = null, string endTime = null, CancellationToken cancellationToken = default);
+         public virtual Pageable<RestorableSqlContainer> GetRestorableSqlContainers(RestorableSqlContainersGetRestorableSqlContainersOptions options = null, CancellationToken cancellationToken = default);
+         public virtual AsyncPageable<RestorableSqlContainer> GetRestorableSqlContainersAsync(RestorableSqlContainersGetRestorableSqlContainersOptions options = null, CancellationToken cancellationToken = default);
+     }
+     public class RestorableSqlContainersGetRestorableSqlContainersOptions {
+         public RestorableSqlContainersGetRestorableSqlContainersOptions();
+         public string EndTime { get; set; }
+         public string RestorableSqlDatabaseRid { get; set; }
+         public string StartTime { get; set; }
```

2022-04-25 04:22 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager.EdgeOrder`**

API changes have been detected in `Azure.ResourceManager.EdgeOrder`. You can review API changes [here](https://apiview.dev/Assemblies/Review/663458965d9d4fa4804f76f08a397c32?diffOnly=True&diffRevisionId=cfd209c670cd46fcadabbb6b461cf170)

2022-04-25 04:22 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager.Compute`**

API changes have been detected in `Azure.ResourceManager.Compute`. You can review API changes [here](https://apiview.dev/Assemblies/Review/f96e8197942d4056bad85665d7b23560?diffOnly=True&diffRevisionId=1e0d4cea82024dfc8f85da3279abed2a)

2022-04-25 04:23 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager.Cdn`**

API changes have been detected in `Azure.ResourceManager.Cdn`. You can review API changes [here](https://apiview.dev/Assemblies/Review/95249c3394094fef9f6c5659b6e2fffd?diffOnly=True&diffRevisionId=fa693ca10d664fcdba77b62f7eb09732)

2022-04-25 04:23 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager.Sql`**

API changes have been detected in `Azure.ResourceManager.Sql`. You can review API changes [here](https://apiview.dev/Assemblies/Review/8f4296a0d2df4ee9991d59dd8d1daecb?diffOnly=True&diffRevisionId=162d17bf976042dd8101f673956eeacf)

2022-04-25 04:23 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager`**

API changes have been detected in `Azure.ResourceManager`. You can review API changes [here](https://apiview.dev/Assemblies/Review/230fc752108741f4afc9335bdb8d5e1f?diffOnly=True&diffRevisionId=0e8a16770e354961be2e9965a1f4aac3)

2022-04-25 04:24 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager.AppService`**

API changes have been detected in `Azure.ResourceManager.AppService`. You can review API changes [here](https://apiview.dev/Assemblies/Review/5ac0a62f034b4758814068fe27742faa?diffOnly=True&diffRevisionId=202d6ddc728b4e3e8d0030e07ab875dc)

2022-04-25 04:27 UTC, azure-sdk commented
**API change check for `Azure.ResourceManager.Storage`**

API changes have been detected in `Azure.ResourceManager.Storage`. You can review API changes [here](https://apiview.dev/Assemblies/Review/a208a34688c24a89ab6b0d89c677bf4a?diffOnly=True&diffRevisionId=8cbe5f8e0fb14fa28fe1d6f7c01dd1ba)

2022-04-26 17:34 UTC, m-nash requested changes

2022-04-26 17:34 UTC, m-nash commented on sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/ResourceGroupResource.cs
> +        public virtual AsyncPageable<GenericResource> GetGenericResourcesAsync()
These overloads don't follow the pattern [here](https://github.com/Azure/autorest.csharp/issues/1630#issuecomment-1018265506).

2022-05-30 01:58 UTC, Yao725 commented on sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/Models/ManagedInstanceDatabaseSchemaTableColumnSensitivityLabelGetCurrentManagedDatabaseSensitivityLabelsOptions.cs
> +    public partial class ManagedInstanceDatabaseSchemaTableColumnSensitivityLabelGetCurrentManagedDatabaseSensitivityLabelsOptions
This class name is really too long, we might need to shorten it.

2022-06-06 17:42 UTC, m-nash requested changes

2022-08-20 05:04 UTC, closed without merging