Using new API version 2022-03-01 and adding new Reserved Resource types support for getCatalog
Azure/azure-sdk-for-net pull request #28620
Opened 2022-05-10 01:10 UTC by gaoyp830

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-05-11 04:04 UTC, archerzz requested changes
@gaoyp830 Please update the following files according to [release proccess](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process):
- https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/mgmtmetadata/reservations_resource-manager.txt
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/reservations/Microsoft.Azure.Management.Reservations/src/Properties/AssemblyInfo.cs

Thanks

2022-05-11 19:57 UTC, gaoyp830 commented
> * [src/Properties/AssemblyInfo.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/reservations/Microsoft.Azure.Management.Reservations/src/Properties/AssemblyInfo.cs)

Ran generate.ps1 and regenerated some new changes. Updated both reservations_resource-manager.txt and AssemblyInfo.cs

2022-05-12 15:08 UTC, archerzz commented on sdk/reservations/Microsoft.Azure.Management.Reservations/src/Generated/Models/ReservationResponse.cs
> -        public ReservationProperties Properties { get; set; }
breaking change

2022-05-12 15:09 UTC, archerzz requested changes
There are some breaking changes. And it seems that we cannot add work-around for backward compatibility.
Please bump `AssemblyVersion` and `AssemblyFileVersion` to the next major version (e.g. `2.0.0.0`)

2022-05-12 19:07 UTC, gaoyp830 commented
> There are some breaking changes. And it seems that we cannot add work-around for backward compatibility. Please bump `AssemblyVersion` and `AssemblyFileVersion` to the next major version (e.g. `2.0.0.0`)

Updated to new major version 2.0.0

2022-05-16 01:17 UTC, archerzz approved these changes
@gaoyp830 I just realized that the SDK seems still in `preview` release. Can you confirm? If so, you can just bump the minor version (e.g. `1.16.0`).

I pre-approve. Please feel free to change the number to what you think is appropriate. I'll merge then.

2022-05-17 04:13 UTC, archerzz approved these changes

2022-05-17 04:13 UTC, merged