Task 13948140: Update C# SDK repository to consume new api version
Azure/azure-sdk-for-net pull request #28960
Opened 2022-05-24 19:40 UTC by thomasp98296

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-05-26 07:52 UTC, Yao725 requested changes
You also need to update following contents:

- `Version` and `PackageReleaseNotes` in Microsoft.Azure.Management.Monitor.csproj
- `AssemblyVersion` and `AssemblyFileVersion` in AssemblyInfo.cs
- `AzureApiTag` in AzSdk.RP.props

It looks like your SDK is still in preview status, If so, you need to bump the minor version. If not, you need to bump the major version because of breaking changes.

2022-05-26 07:52 UTC, Yao725 commented on src/SDKs/_metadata/monitor_resource-manager.txt
> +2022-05-23 16:47:10 UTC
Where does this file come from? I couldn't understand why we need it.

2022-05-26 07:52 UTC, Yao725 commented on sdk/monitor/Microsoft.Azure.Management.Monitor/src/Generated/ActionGroupsOperations.cs
> +        public async Task<AzureOperationHeaderResponse<ActionGroupsPostTestNotificationsHeaders>> PostTestNotificationsWithHttpMessagesAsync(NotificationRequestBody notificationRequest, Dictionary<st
I don't see any change in test, do these updated APIs have corresponding tests? If not, could you add tests to see if these APIs could work as expected.

2022-05-26 23:10 UTC, thomasp98296 commented
@Yao725 , thanks for your feedback. I have sent another iteration. Please help to take another look. Thank you again.

2022-05-27 04:32 UTC, Yao725 approved these changes
LGTM, and FYI @thomasp98296, I helped you bump the version in the csproj.

2022-05-27 06:02 UTC, merged