Geographic traffic routing method in Azure Traffic Manager
Azure/azure-sdk-for-net pull request #2896
Opened 2017-03-03 18:21 UTC by vladca

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X ] Title of the pull request is clear and informative.
- [X ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-03-03 19:41 UTC, msftgits commented
Closing and reopening to ping CLA bot.

2017-03-03 19:42 UTC, msftclas commented
@__vladca__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-03-03 23:51 UTC, markcowl commented
@vladca traffic manager tests are failing

2017-03-03 23:53 UTC, markcowl commented
@vladca Why are you making changes to the master branch, instead of the AutoRest branch?

2017-03-04 00:02 UTC, markcowl requested changes
Need tests for the new features, and need to re-record existing tests for the new api version
[Vlad]: Done!

2017-03-04 00:02 UTC, markcowl commented on src/ResourceManagement/TrafficManager/TrafficManagerManagement/Generated/EndpointOperations.cs
>              url = url + "/";
Where are the tests for the new features?

2017-03-04 11:48 UTC, vladca commented on src/ResourceManagement/TrafficManager/TrafficManagerManagement/Generated/EndpointOperations.cs
>              url = url + "/";
Added

2017-03-04 11:51 UTC, vladca commented
This is done now, thank you Mark

From: Mark Cowlishaw [mailto:notifications@github.com]
Sent: 04 March 2017 00:02
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Vlad Cananau <Vlad.Cananau@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] Geographic traffic routing method in Azure Traffic Manager (#2896)


@markcowl requested changes on this pull request.

Need tests for the new features, and need to re-record existing tests for the new api version

________________________________

In src/ResourceManagement/TrafficManager/TrafficManagerManagement/Generated/EndpointOperations.cs<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F2896%23discussion_r104266842&data=02%7C01%7CVlad.Cananau%40microsoft.com%7Cb353b6612fa94c30170408d46291becd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636241825491447340&sdata=AryLH4hvwalN92kGmNESByXg8sgFgJkyq2kob8Q27p8%3D&reserved=0>:

> @@ -154,7 +154,7 @@ public TrafficManagerManagementClient Client

             url = url + "/";

Where are the tests for the new features?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F2896%23pullrequestreview-25096143&data=02%7C01%7CVlad.Cananau%40microsoft.com%7Cb353b6612fa94c30170408d46291becd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636241825491447340&sdata=bxf2lDq7dhX6CYm2rRtO9hUlSR0yIwDFoh%2F9NwZNZ6M%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHG6yfT1qwuRlYtqW-CKoXLLmZz8XRwyks5riKoRgaJpZM4MSlSs&data=02%7C01%7CVlad.Cananau%40microsoft.com%7Cb353b6612fa94c30170408d46291becd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636241825491447340&sdata=yWwc1cgN8Rmg%2FWJ%2FWLqOstQlbQKGuYc5E%2FRqk0GVoTw%3D&reserved=0>.

2017-03-07 01:24 UTC, markcowl requested changes

2017-03-07 01:24 UTC, markcowl commented on src/ResourceManagement/TrafficManager/TrafficManagerManagement/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.1.0.0")]
AssemblyVersion shopuld remain at 1.0.0.0 to maintain backward compatibility, AssemblyFileVersion should match the package version (as it does).

2017-03-07 13:36 UTC, ms-alguerra commented on src/ResourceManagement/TrafficManager/TrafficManagerManagement/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.1.0.0")]
This is now fixed

2017-03-09 19:06 UTC, cormacpayne commented
@vladca it looks like you changed the `AssemblyFileVersion` when you only needed to change `AssemblyVersion`. Please change the `AssemblyFileVersion` back to 1.1.0.

2017-03-21 16:17 UTC, markcowl approved these changes

2017-03-21 16:18 UTC, merged