ClientRuntime: Don't serialize protected members.
Azure/azure-sdk-for-net pull request #2915
Opened 2017-03-09 19:54 UTC by olydis

WORK IN PROGRESS

(abusing CI since my machine is no longer capable of opening that project in VS, msbuild also can't find some targets... guess the move to VS2017 messed that up)

2017-03-09 20:19 UTC, olydis commented
Reproed the problem, `RawJsonIsSerialized` failed in http://azuresdkci.cloudapp.net/job/sdk-for-net/4657/console.
Pushing the fix.

2017-03-10 22:57 UTC, markcowl requested changes
Please update the version (should bve a revision update)

2017-03-11 02:42 UTC, markcowl approved these changes

2017-03-11 02:42 UTC, markcowl commented
Waiting for end-to-end test to verify

2017-03-15 16:27 UTC, merged