Search 4x preview
Azure/azure-sdk-for-net pull request #2916
Opened 2017-03-09 20:10 UTC by mhko

First and last commits are generated* code. Please take a closer look at the 2nd and 3rd commits where I customized* CreateOrUpdate and Exists calls and added tests cases.

* PR request for the swagger spec : https://github.com/Azure/azure-rest-api-specs-pr/pull/47

** The customization is done for CreateOrUpdate() and Exists() calls in Synonyms API. The former is analogous to [this](https://github.com/Azure/azure-sdk-for-net/commit/17150524091d560fbb360db415b6cec5d15720ec#diff-502ae5bc6a272c5f5e3d7ae3b59fa3a9) Exists() call is just a wrapper around Get. 

FYI @brjohnstmsft @Yahnoosh @chaosrealm

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-03-09 20:10 UTC, msftclas commented
@mhko,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-03-09 20:10 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-03-09 21:15 UTC, cormacpayne commented
@azuresdkci add to whitelist

2017-03-24 22:42 UTC, bitsforthought requested changes
Please re-generate the code once you've made the requested spec changes.

2017-03-24 22:42 UTC, brjohnstmsft commented on src/Search/Search.Tests/Tests/IndexManagementTests.cs
> +                index.Fields.First(f => f.Name == "hotelName").SynonymMaps = new String[1] { synonymMapName };
`String` is typically not capitalized in C#. You don't need the array size (it is inferred automatically). In fact, you don't even need the type:

`= new[] { synonymMapName };`

2017-03-24 22:42 UTC, brjohnstmsft commented on src/Search/Search.Tests/Tests/SearchTests.cs
> +            string synonymMapName = "names";
nit: `const string SynonymMapName = "names";`

2017-03-24 22:42 UTC, brjohnstmsft commented on src/Search/Search.Tests/Tests/SearchTests.cs
> +                    QueryType = QueryType.Full,
This would work with the simple syntax too, right?

2017-03-24 22:42 UTC, brjohnstmsft commented on src/Search/Search.Tests/Tests/SearchTests.cs
> +                client.Documents.Search<Hotel>(@"luxury", searchParameters);
nit: @ not needed

2017-03-24 22:42 UTC, brjohnstmsft commented on src/Search/Search.Tests/Tests/SynonymMapTests.cs
> +        private void TestAllSynonymMapFormats(Action<SearchServiceClient, SynonymMap> testMethod)
This method doesn't seem useful given that we only support one synonym format right now. Maybe it's best to inline it for now.

2017-03-29 21:46 UTC, mhko commented on src/Search/Search.Tests/Tests/SearchTests.cs
> +            string synonymMapName = "names";
Thanks

2017-03-29 21:47 UTC, mhko commented on src/Search/Search.Tests/Tests/IndexManagementTests.cs
> +                index.Fields.First(f => f.Name == "hotelName").SynonymMaps = new String[1] { synonymMapName };
Thanks

2017-03-29 21:51 UTC, mhko commented on src/Search/Search.Tests/Tests/SearchTests.cs
> +                    QueryType = QueryType.Full,
Yes, it does. We have more extensive coverage in the API layer.

2017-03-29 21:52 UTC, mhko commented on src/Search/Search.Tests/Tests/SearchTests.cs
> +                client.Documents.Search<Hotel>(@"luxury", searchParameters);
Thanks

2017-03-29 21:55 UTC, mhko commented on src/Search/Search.Tests/Tests/SynonymMapTests.cs
> +        private void TestAllSynonymMapFormats(Action<SearchServiceClient, SynonymMap> testMethod)
Sure.

2017-03-30 00:40 UTC, bitsforthought approved these changes

2017-03-30 00:40 UTC, brjohnstmsft commented
@mhko I'll merge once the CI build passes.

2017-03-30 00:58 UTC, merged