Updated RepoTask module with new supported KeyVaule pairs
Azure/azure-sdk-for-net pull request #2919
Opened 2017-03-10 02:51 UTC by shahabhijeet

As TestFramework support custom env. updating the module to create proper connection string for the newly supported key value pairs.

2017-03-10 20:29 UTC, markcowl requested changes
Please leave in the old constraints in the module manifest (minimum powershell version, .nte version, clr version,etc.

Otherwise, this looks good.

2017-03-10 20:29 UTC, markcowl commented on tools/Repo-Tasks.psd1
> +# PowerShellVersion = ''
Don't we still need this?  I think we do.

2017-03-10 20:29 UTC, markcowl commented on tools/Repo-Tasks.psd1
> -# ProcessorArchitecture = 'x86, Amd64'
should be None

2017-03-11 21:52 UTC, shahabhijeet commented on tools/Repo-Tasks.psd1
> -# ProcessorArchitecture = 'x86, Amd64'
@markcowl no matter how much I try, Update-ModuleManifest will not add/update None value. I have now added that manually.

2017-03-11 21:52 UTC, shahabhijeet commented on tools/Repo-Tasks.psd1
> +# PowerShellVersion = ''
I believe Update-ModuleManifest made those changes. I will add it back.

2017-03-17 17:29 UTC, shahabhijeet commented
@azuresdkci test this please

2017-03-26 20:54 UTC, merged