Regen with renaming plural enums
Azure/azure-sdk-for-net pull request #29191
Opened 2022-06-08 14:53 UTC by Yao725

This is the regen PR of https://github.com/Azure/autorest.csharp/pull/2296
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-06-08 15:01 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.EventHubs](https://apiview.dev/Assemblies/Review/755f6458ff4d4f5d9b3ec4234bcb6974)

2022-06-17 01:00 UTC, m-nash requested changes
Left comments in apiview

- https://apiview.dev/Assemblies/Review/c3d2892f4efd4daabce6d2c87cf02534/d92add6fdb864a9892a9e3110597c5ab?diffRevisionId=97cd5b900bad459781aa1bf383cafc56&doc=False&diffOnly=True#496b08db5c9440948fa2cc4016848a23
- https://apiview.dev/Assemblies/Review/ddf513334c6d4e49bb55ccd613894cc3/7eb80e472a9d4a879c216b4035f16fa5?diffRevisionId=42648daba9ee486c9b6781ee968cc8f4&doc=False&diffOnly=True#1467583c5817406eb073c9307e60eb71
- https://apiview.dev/Assemblies/Review/ddf513334c6d4e49bb55ccd613894cc3/7eb80e472a9d4a879c216b4035f16fa5?diffRevisionId=42648daba9ee486c9b6781ee968cc8f4&doc=False&diffOnly=True#372e446b5a4046b6a59db7697948c68b
- https://apiview.dev/Assemblies/Review/96552feabb2b41ed86638ccbd6dbcb01/8aa856ac9412474cb2894fc4ae7dad9c?diffRevisionId=96321cc028d24bb1bfd378aba56452dc&doc=False&diffOnly=True#3cca6a4445cc42cfbd2bf4e550dddadf
- https://apiview.dev/Assemblies/Review/45336f4a0afc44acb941b4eaf2f0c8b6/7f2ae0e40fd0402bb860704f66b0fccd?diffRevisionId=6ea06dcea1be4deda85513fe700bcb6d&doc=False&diffOnly=True#4cc5a6d1ff574ad8831b6572bdf62792
- https://apiview.dev/Assemblies/Review/0acf7b2ef4654f18a88bef9ad59b8580/3a5ed9377f6147109445260f2d412a44?diffRevisionId=accf0a110138442e934a58cc87eaf96c&doc=False&diffOnly=True#cf7ef2abdd7347e394d6552b5f18a9d6
- https://apiview.dev/Assemblies/Review/0acf7b2ef4654f18a88bef9ad59b8580/3a5ed9377f6147109445260f2d412a44?diffRevisionId=accf0a110138442e934a58cc87eaf96c&doc=False&diffOnly=True#f2e0e25c9101475ca540d5176383a221

2022-06-17 07:45 UTC, Yao725 commented on sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/Models/ResourceTypeAliasPathAttributes.cs
> +    [EditorBrowsable(EditorBrowsableState.Never)]
Introduced a new configuration `keep-plural-enum` to keep them.

2022-06-17 07:46 UTC, Yao725 commented on sdk/resources/Azure.ResourceManager.Resources/src/Custom/Models/ScriptCleanupOptions.cs
> +    [EditorBrowsable(EditorBrowsableState.Never)]
Used autorest.md to keep it unchanged.

2022-06-20 21:57 UTC, m-nash commented
> > Left comments in apiview
> > 
> > * https://apiview.dev/Assemblies/Review/c3d2892f4efd4daabce6d2c87cf02534/d92add6fdb864a9892a9e3110597c5ab?diffRevisionId=97cd5b900bad459781aa1bf383cafc56&doc=False&diffOnly=True#496b08db5c9440948fa2cc4016848a23
> > * https://apiview.dev/Assemblies/Review/ddf513334c6d4e49bb55ccd613894cc3/7eb80e472a9d4a879c216b4035f16fa5?diffRevisionId=42648daba9ee486c9b6781ee968cc8f4&doc=False&diffOnly=True#1467583c5817406eb073c9307e60eb71
> > * https://apiview.dev/Assemblies/Review/ddf513334c6d4e49bb55ccd613894cc3/7eb80e472a9d4a879c216b4035f16fa5?diffRevisionId=42648daba9ee486c9b6781ee968cc8f4&doc=False&diffOnly=True#372e446b5a4046b6a59db7697948c68b
> > * https://apiview.dev/Assemblies/Review/96552feabb2b41ed86638ccbd6dbcb01/8aa856ac9412474cb2894fc4ae7dad9c?diffRevisionId=96321cc028d24bb1bfd378aba56452dc&doc=False&diffOnly=True#3cca6a4445cc42cfbd2bf4e550dddadf
> > * https://apiview.dev/Assemblies/Review/45336f4a0afc44acb941b4eaf2f0c8b6/7f2ae0e40fd0402bb860704f66b0fccd?diffRevisionId=6ea06dcea1be4deda85513fe700bcb6d&doc=False&diffOnly=True#4cc5a6d1ff574ad8831b6572bdf62792
> > * https://apiview.dev/Assemblies/Review/0acf7b2ef4654f18a88bef9ad59b8580/3a5ed9377f6147109445260f2d412a44?diffRevisionId=accf0a110138442e934a58cc87eaf96c&doc=False&diffOnly=True#cf7ef2abdd7347e394d6552b5f18a9d6
> > * https://apiview.dev/Assemblies/Review/0acf7b2ef4654f18a88bef9ad59b8580/3a5ed9377f6147109445260f2d412a44?diffRevisionId=accf0a110138442e934a58cc87eaf96c&doc=False&diffOnly=True#f2e0e25c9101475ca540d5176383a221
> 
> This PR will not cover the cases of name conflicts and generic name.

I assume you mean we will fix those as part of the GA task for each of those libraries?  If so can we create issues so track in our project so we don't lose track of them?

2022-06-20 21:58 UTC, m-nash approved these changes
Lets make sure we track the punted items found in apiview so we don't lose track when we GA those libraries.

The apiview for the 2 GA libraries look good.

2022-06-23 05:54 UTC, Yao725 reviewed
In general, it looks good to me. Finding some unexpected changes in compute, will fix them in another separated PR. And also opened a [PR](https://github.com/Azure/autorest.csharp/issues/2347) to improve this feature in the future.

2022-06-23 05:54 UTC, Yao725 commented on sdk/compute/Azure.ResourceManager.Compute/src/Generated/Models/IntervalInMin.cs
> +    public enum IntervalInMin
This is an unexpected change, will revert after this PR.

2022-06-23 05:54 UTC, Yao725 commented on sdk/compute/Azure.ResourceManager.Compute/src/Generated/Models/ExpandTypesForGetCapacityReservationGroup.cs
> +    public readonly partial struct ExpandTypesForGetCapacityReservationGroup : IEquatable<ExpandTypesForGetCapacityReservationGroup>
This can't be covered by the autorest change, will rename it manually.

2022-06-23 05:54 UTC, Yao725 commented on sdk/compute/Azure.ResourceManager.Compute/src/Generated/Models/ExpandTypesForGetVmScaleSet.cs
> +    public readonly partial struct ExpandTypesForGetVmScaleSet : IEquatable<ExpandTypesForGetVmScaleSet>
Same as above.

2022-06-23 06:08 UTC, merged