New version
Azure/azure-sdk-for-net pull request #2921
Opened 2017-03-10 20:10 UTC by NonStatic2014

## Description

Azure Machine Learning Web Services RP is publishing a new version of API. The .Net SDK needs to be regenerated from a new swagger spec. The pull request of swagger spec change is here: https://github.com/Azure/azure-rest-api-specs/pull/1019. Compare with the existing preview version, this is a breaking change according to [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md)

Scenario Tests have been updated and two new test cases were added to cover new scenarios.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-03-10 20:23 UTC, markcowl commented
@NonStatic2014 Please change the PR title to be more descriptive.  You realize that you checked a box saying the PR had a descriptive title, right? :-)

2017-03-10 20:30 UTC, NonStatic2014 commented
Good catch Mark! I reopen the web page but forget to update the title. Now it is updated.

2017-03-17 08:02 UTC, NonStatic2014 commented
I have run the following command locally and exit successfully. Not sure why lab build keep failing. 

`.\CredentialScanner.exe -I D:\code\GitHub\azure-sdk-for-net\src\ResourceManagement\MachineLearning -S Searchers\buildsearchers.xml -O d:\temp\scan1 -t -v > Result.txt`
[Result.txt](https://github.com/Azure/azure-sdk-for-net/files/849946/Result.txt)

2017-03-21 16:47 UTC, cormacpayne requested changes
@NonStatic2014 Hey Klein, some minor comments that need to be resolved before the swagger gets merged and we can review the generated code.

2017-03-21 16:47 UTC, cormacpayne commented on src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/project.json
> +  "version": "1.0.0",
@NonStatic2014 this should be version 1.0.0-preview (or 0.11.0-preview) since you are introducing breaking changes

2017-03-21 16:47 UTC, cormacpayne commented on src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/generate.cmd
> +set webServicesSpecFile="https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-machinelearning/2017-01-01/swagger/webservices.json"
@NonStatic2014 please use the URL containing the commit Id when the spec gets merged instead of the URL containing the branch

2017-03-21 16:47 UTC, cormacpayne commented on src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/generate.cmd
>  set autoRestVersion=0.17.0-Nightly20160824
@NonStatic2014 AutoRest is now at version 1.0.x. Please refer to aka.ms/autorest/install for more information on how to install and use the latest version(s).

2017-03-22 05:47 UTC, NonStatic2014 commented on src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/project.json
> +  "version": "1.0.0",
This version is going to be the GA version, so we expect it is called 1.0.0.

2017-03-22 07:43 UTC, NonStatic2014 commented on src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/generate.cmd
>  set autoRestVersion=0.17.0-Nightly20160824
Then please ignore this cmd file and we are going to follow the new instruction generate code locally.

2017-03-22 22:17 UTC, cormacpayne commented on src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/project.json
> +  "version": "1.0.0",
We still require the package to be in preview when breaking changes are introduced to the SDK, and after enough time to ensure it is stable, you can remove the `-preview` suffix and re-publish a new version

2017-03-22 22:19 UTC, cormacpayne commented on src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/generate.cmd
>  set autoRestVersion=0.17.0-Nightly20160824
We would still prefer if you updated this file with the version of AutoRest used (even if it's from the new instructions); it let's us know that you aren't using an outdated version of AutoRest if we were to just look at this file

2017-03-27 23:03 UTC, shahabhijeet commented
@NonStatic2014 please reopen this PR once the swagger PR is merged.
We are trying to accurately asses our SLA and opening a PR which is not ready to be reviewed. We will not review SDK PR unless swagger PR is merged.

2017-03-27 23:03 UTC, closed without merging