fresh DPG libaries for refence doc
Azure/azure-sdk-for-net pull request #29264
Opened 2022-06-13 09:52 UTC by chunyu3

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

re-gened all the RPs in the entire azure-sdk-for-net repo to refresh the refence doc.

2022-06-13 17:24 UTC, heaths commented
Before marking "ready for review", could you update the description with a summary of the change so we know what we're reviewing? Or, if it'd be easier to link to a PR for the generator that would have more information, that works as well. It'd be great and helpful to know what we're reviewing. In this case, it seems like it's updating the generator to better handle polymorphic models. Is that correct?

2022-06-14 22:29 UTC, annelo-msft commented
> Before marking "ready for review", could you update the description with a summary of the change so we know what we're reviewing?

@heaths, this PR shows the output of a proposed generator change on the azure-sdk-for-net repo.  @chunyu3, could you update the description with this information as well as a link to the generator change and the issue this is addressing to help @heaths and other library owners understand what they're being asked to review?

2022-06-14 22:29 UTC, annelo-msft commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/Generated/ConfidentialLedgerClient.cs
> +        /// https://docs.microsoft.com/rest/api/ConfidentialLedger/ConfidentialLedger/GetConstitution
I get a 404 for this link.

2022-06-14 22:44 UTC, annelo-msft commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/Generated/ConfidentialLedgerClient.cs
> +        /// https://docs.microsoft.com/rest/api/ConfidentialLedger/ConfidentialLedger/GetConstitution
@christothes, would you be able to work with the ConfidentialLedger team to update their swagger file with https://swagger.io/specification/v2/#externalDocumentationObject values that link to REST API docs?

2022-06-15 02:01 UTC, chunyu3 commented
> > Before marking "ready for review", could you update the description with a summary of the change so we know what we're reviewing?
> 
> @heaths, this PR shows the output of a proposed generator change on the azure-sdk-for-net repo. @chunyu3, would you please update the description with this information as well as a link to the generator change and the issue this is addressing to help @heaths and other library owners understand what they're being asked to review?

Updated the description with the feature information and the changes in autorest.csharp which will apply.

2022-06-15 02:05 UTC, chunyu3 commented on sdk/agrifood/Azure.Verticals.AgriFood.Farming/src/Generated/ApplicationDataClient.cs
> +        /// https://docs.microsoft.com/rest/api/FarmBeats/ApplicationData/Get
Hi @annelo-msft we will be able to generate the right rest-api-doc link ourselves. If service team does not provide the link in swagger, we will not display the link in the <Remarks> for GA. And we will support to generate the right link after GA, and I will file an issue to track this. @annelo-msft is it OK for GA?

2022-06-15 23:36 UTC, annelo-msft commented on sdk/agrifood/Azure.Verticals.AgriFood.Farming/src/Generated/ApplicationDataClient.cs
> +        /// https://docs.microsoft.com/rest/api/FarmBeats/ApplicationData/Get
Yes, once the DPG generator supports generating the REST API link in the comments from `externalDocumentationObject`, we will have satisfied the requirement for links to REST API docs sufficient to GA.

2022-06-16 00:23 UTC, heaths requested changes

2022-06-16 00:23 UTC, heaths commented on sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/Generated/ConversationAnalysisClient.cs
> +        public virtual async Task<Operation> SubmitJobAsync(WaitUntil waitUntil, RequestContent content, RequestContext context = null)
The documentation changes look great, but this change (and similar) are breaking. I'm opening another issue to track some work from the archboard per @annelo-msft's request and will include a detailed breakdown of CLU's LROs.

2022-06-23 06:47 UTC, chunyu3 commented
close this PR since autorest.csharp has already be upgraded to 3.0.0-beta.20220622.2 in other PR.

2022-06-23 06:47 UTC, closed without merging