SQL breaking changes to fix Swagger spec validation errors/warnings
Azure/azure-sdk-for-net pull request #2927
Opened 2017-03-11 22:15 UTC by jaredmoo

AutoRest enabled several new validation rules which exposed some naming issues in SQL swagger specs. I also noticed that several classes are no longer supported.
- Removed unsupported types (e.g. Schema, Table, Column)
- Revised import export  operation and class names
- Removed unnecessary import export operation results APIs

Corresponding Swagger change: https://github.com/Azure/azure-rest-api-specs/pull/1005

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-03-11 22:16 UTC, msftclas commented
@jaredmoo,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-03-15 22:28 UTC, cormacpayne commented
This PR should be merged at the same time as https://github.com/Azure/azure-sdk-for-net/pull/2914 and https://github.com/Azure/azure-sdk-for-net/pull/2925

2017-03-17 02:07 UTC, jaredmoo commented
#2914 and #2925 are now combined into this

2017-03-17 17:55 UTC, jaredmoo commented
Swagger changes are all merged now.

2017-03-17 17:58 UTC, jaredmoo commented
btw project.json isn't updated because 1.2.0-preview hasn't been published yet.

2017-03-17 18:01 UTC, cormacpayne commented
@jaredmoo Hey Jared, two quick questions:

1) Just to be sure, does this spec include _all_ of the changes you originally wanted to make in this PR and the two that you closed?

2) There are a lot of unnecessary commits, would you mind [rebasing](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md#rebasing) to get the number of commits down to 1 or 2?

2017-03-17 19:37 UTC, jaredmoo commented
Yes, since all swagger changes are now merged, all generated files in this change are based on rest-api-specs master branch.

I have squashed into a single commit and described all the breaking changes.

2017-03-20 16:14 UTC, jaredmoo commented
@cormacpayne can I get a review?

2017-03-20 18:32 UTC, cormacpayne requested changes
@jaredmoo some comments that need to be resolved

Also, what is the `UpgradeLog.htm` file? I was unable to view it on GitHub or CodeFlow

2017-03-20 18:32 UTC, cormacpayne commented on global.json
> +  "sdk": {
@jaredmoo why was this added?

2017-03-20 18:32 UTC, cormacpayne commented on src/ClientRuntime/global.json
> +    "version": "1.0.0-preview2-003121"
@jaredmoo same comment

2017-03-20 18:32 UTC, cormacpayne commented on src/ResourceManagement/SqlManagement/global.json
> +    "version": "1.0.0-preview2-003121"
@jaredmoo same comment

2017-03-20 18:32 UTC, cormacpayne commented on src/TestFramework/global.json
> +    "version": "1.0.0-preview2-003121"
@jaredmoo same comment

2017-03-20 18:32 UTC, cormacpayne commented on src/ResourceManagement/SqlManagement/Sql.Tests/ImportExportScenarioTests.cs
> -                // List Server import/export operations
@jaredmoo is this removed block being tested somewhere else? Making sure there isn't any test regression with this being removed

2017-03-20 18:32 UTC, cormacpayne commented on src/ResourceManagement/SqlManagement/Sql.Tests/BlobAuditingTest.cs
> +﻿using Microsoft.Azure.Management.Resources;
@jaredmoo this file is missing the license header

2017-03-20 18:32 UTC, cormacpayne commented on src/ResourceManagement/SqlManagement/Sql.Tests/ThreatDetectionTest.cs
> +﻿using Microsoft.Azure.Management.Resources;
@jaredmoo this file is missing license header

2017-03-20 18:35 UTC, jaredmoo commented on global.json
> +  "sdk": {
I have VS2017 installed on my machine, without this the build is totally broken. See https://github.com/Azure/azure-sdk-for-net/issues/2922 .

2017-03-20 18:35 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/Sql.Tests/ImportExportScenarioTests.cs
> -                // List Server import/export operations
This API is removed so no test is needed.

2017-03-20 18:39 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/Sql.Tests/ImportExportScenarioTests.cs
> -                // List Server import/export operations
Fixed in 83501016bb0744278a7d4a388985c2c37fc80258

2017-03-20 18:39 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/Sql.Tests/ThreatDetectionTest.cs
> +﻿using Microsoft.Azure.Management.Resources;
Fixed in 83501016bb0744278a7d4a388985c2c37fc80258

2017-03-20 18:39 UTC, jaredmoo commented on src/ClientRuntime/global.json
> +    "version": "1.0.0-preview2-003121"
#2922

2017-03-20 18:40 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/global.json
> +    "version": "1.0.0-preview2-003121"
#2922

2017-03-20 18:40 UTC, jaredmoo commented on src/TestFramework/global.json
> +    "version": "1.0.0-preview2-003121"
#2922

2017-03-20 18:40 UTC, jaredmoo commented on src/ResourceManagement/SqlManagement/Sql.Tests/BlobAuditingTest.cs
> +﻿using Microsoft.Azure.Management.Resources;
Fixed in 8350101

2017-03-20 18:41 UTC, jaredmoo commented
`UpgradeLog.htm` is visual studio junk. Delete it.

2017-03-21 21:40 UTC, jaredmoo commented
@cormacpayne - I have addressed feedback. Not changing project.json since then it doesn't build for me. I think project.json goes away when #2815 is done.

2017-03-21 22:58 UTC, cormacpayne commented
@jaredmoo it looks like there is a merge conflict from a pull request that was merged earlier today

2017-03-21 23:06 UTC, jaredmoo commented
Ok, I reverted my change to this file in order to resolve the conflict.

2017-03-22 02:45 UTC, jaredmoo commented
@cormacpayne ready to merge again :)

2017-03-23 18:50 UTC, cormacpayne approved these changes

2017-03-23 18:51 UTC, merged