Update AMS SDK to use 2021-11-01 API version
Azure/azure-sdk-for-net pull request #29785
Opened 2022-07-11 20:52 UTC by giakas

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-07-12 06:10 UTC, ArcturusZhang approved these changes

2022-07-12 06:35 UTC, ArcturusZhang requested changes
Need to confirm with @ArthurMa1978 before we merge something related with track 1

2022-07-12 06:38 UTC, ArthurMa1978 commented on sdk/mediaservices/Microsoft.Azure.Management.Media/CHANGELOG.md
> +## Changes in 6.1.0
The track 1 is being deprecated soon, let's talk why we need another new track 1 release now

2022-07-19 05:22 UTC, ArthurMa1978 commented
As we offline talked, customer don't need a .net sdk now, so cancel this release and will release track 2 instead

2022-07-19 05:22 UTC, closed without merging