Azure Communication Services Phone Numbers SDK With Browsing Capabilities
Azure/azure-sdk-for-net pull request #29962
Opened 2022-07-18 21:28 UTC by whisper6284

This is the draft pull request to generate the definitions of the Azure Phone Numbers Browse functionalities.

This includes the ability to
- List supported countries.
- List supported cities/towns/localities within a country.
- List available area codes.
- List available offerings.

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-07-18 21:39 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.Communication.PhoneNumbers](https://apiview.dev/Assemblies/Review/cf78ef5f8213402eaf411eb9f0813134)

2022-10-06 20:38 UTC, whisper6284 commented
/reopen

2022-12-02 01:19 UTC, danielortega-msft reviewed
As currently implemented, none of the methods returning a `Pageable` or `AsyncPageable` allow users to customize the number of elements retrieved per page.

This is done my using the `pageSizeHint` argument, e.g.:
`var countries = client.GetAvailableCountriesAsync().AsPages(pageSizeHint: 15);`

I left comments in all the places I noticed that would require a change to support this. In summary, all of the `FirstPageFunc` definitions need to pass `pageSizeHint` to the respective RestClient method. It is not required for the `NextPageFunc` since that relies on the `nextLink`, which is generated by the server.

However, this is also not implemented by the `GetPurchasedPhoneNumbers` and `GetPurchasedPhoneNumbersAsync` methods, so another option is releasing this new revision as is and then make a x.1 update to include support for `pageSizeHint` across the board.

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = await RestClient.ListAvailableCountriesAsync( skip: null, maxPageSize: null, acceptLanguage: _acceptedLanguage, cancellationToken).ConfigureAwait(false);
```suggestion
                    var response = await RestClient.ListAvailableCountriesAsync( skip: null, maxPageSize: pageSizeHint, acceptLanguage: _acceptedLanguage, cancellationToken).ConfigureAwait(false);
```

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = RestClient.ListAvailableCountries(skip: null, maxPageSize: null, acceptLanguage: _acceptedLanguage, cancellationToken);
```suggestion
                    var response = RestClient.ListAvailableCountries(skip: null, maxPageSize: pageSizeHint, acceptLanguage: _acceptedLanguage, cancellationToken);
```

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = await RestClient.ListAvailableLocalitiesAsync(twoLetterIsoCountryName, skip: null, maxPageSize: null, administrativeDivision, acceptLanguage: _acceptedLanguage, can
```suggestion
                    var response = await RestClient.ListAvailableLocalitiesAsync(twoLetterIsoCountryName, skip: null, maxPageSize: pageSizeHint, administrativeDivision, acceptLanguage: _acceptedLanguage, cancellationToken).ConfigureAwait(false);
```

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = RestClient.ListAvailableLocalities(twoLetterIsoCountryName, skip: null, maxPageSize: null, administrativeDivision, acceptLanguage: _acceptedLanguage, cancellationTo
```suggestion
                    var response = RestClient.ListAvailableLocalities(twoLetterIsoCountryName, skip: null, maxPageSize: pageSizeHint, administrativeDivision, acceptLanguage: _acceptedLanguage, cancellationToken);
```

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = await RestClient.ListOfferingsAsync(twoLetterIsoCountryName, skip: null, maxPageSize: null, phoneNumberType, phoneNumberAssignmentType, acceptLanguage: _acceptedLan
```suggestion
                    var response = await RestClient.ListOfferingsAsync(twoLetterIsoCountryName, skip: null, maxPageSize: pageSizeHint, phoneNumberType, phoneNumberAssignmentType, acceptLanguage: _acceptedLanguage, cancellationToken).ConfigureAwait(false);
```

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = RestClient.ListOfferings(twoLetterIsoCountryName, skip: null, maxPageSize: null, phoneNumberType, phoneNumberAssignmentType, acceptLanguage: _acceptedLanguage, canc
```suggestion
                    var response = RestClient.ListOfferings(twoLetterIsoCountryName, skip: null, maxPageSize: pageSizeHint, phoneNumberType, phoneNumberAssignmentType, acceptLanguage: _acceptedLanguage, cancellationToken);
```

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = await RestClient.ListAreaCodesAsync(twoLetterIsoCountryName, phoneNumberType, skip: null, maxPageSize: null, phoneNumberAssignmentType, locality, administrativeDivi
```suggestion
                    var response = await RestClient.ListAreaCodesAsync(twoLetterIsoCountryName, phoneNumberType, skip: null, maxPageSize: pageSizeHint, phoneNumberAssignmentType, locality, administrativeDivision, acceptLanguage: _acceptedLanguage, cancellationToken).ConfigureAwait(false);
```

2022-12-02 01:19 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/src/PhoneNumbersClient.cs
> +                    var response = RestClient.ListAreaCodes(twoLetterIsoCountryName, phoneNumberType, skip: null, maxPageSize: null, phoneNumberAssignmentType, locality, administrativeDivision, accep
```suggestion
                    var response = RestClient.ListAreaCodes(twoLetterIsoCountryName, phoneNumberType, skip: null, maxPageSize: pageSizeHint, phoneNumberAssignmentType, locality, administrativeDivision, acceptLanguage: _acceptedLanguage, cancellationToken);
```

2022-12-07 20:40 UTC, benbp commented
@whisper6284 sorry I accidentally linked a pipeline. It should be erased if you push a new update.

2023-01-06 20:27 UTC, danielortega-msft requested changes

2023-01-06 20:27 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/tests/samples/Sample_PhoneNumbersClient.cs
> +            await WaitForCompletionAsync(searchOperation);
I believe this should be outside of the snippet region; otherwise, this appears in the generated samples in the readme file.

2023-01-06 20:27 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/tests/samples/Sample_PhoneNumbersClient.cs
> +            Assert.AreEqual(purchaseOperation.GetRawResponse().Status, 200);
Same as my other comment

2023-01-06 20:27 UTC, danielortega-msft commented on sdk/communication/Azure.Communication.PhoneNumbers/tests/samples/Sample_PhoneNumbersClient.cs
> +            await WaitForCompletionAsync(updateCapabilitiesOperation);
Same as my other comment.

2023-01-07 00:30 UTC, danielortega-msft commented
> As currently implemented, none of the methods returning a `Pageable` or `AsyncPageable` allow users to customize the number of elements retrieved per page.
> 
> This is done my using the `pageSizeHint` argument, e.g.: `var countries = client.GetAvailableCountriesAsync().AsPages(pageSizeHint: 15);`
> 
> I left comments in all the places I noticed that would require a change to support this. In summary, all of the `FirstPageFunc` definitions need to pass `pageSizeHint` to the respective RestClient method. It is not required for the `NextPageFunc` since that relies on the `nextLink`, which is generated by the server.
> 
> However, this is also not implemented by the `GetPurchasedPhoneNumbers` and `GetPurchasedPhoneNumbersAsync` methods, so another option is releasing this new revision as is and then make a x.1 update to include support for `pageSizeHint` across the board.

FYI, this will be done in the future alongside the update for `GetPurchasedPhoneNumbers` and `GetPurchasedPhoneNumbersAsync`.

2023-01-07 00:42 UTC, danielortega-msft approved these changes

2023-01-09 18:08 UTC, merged