Relay SDK Draft
Azure/azure-sdk-for-net pull request #2998
Opened 2017-03-28 04:03 UTC by v-Ajnava

## Description

This is a Relay SDK first draft.
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/1061

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [X] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-03-28 04:03 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-03-28 04:03 UTC, msftclas commented
@v-Ajnava,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-03-28 17:57 UTC, cormacpayne commented
@azuresdkci add to whitelist

2017-03-28 23:34 UTC, shahabhijeet requested changes

2017-03-28 23:34 UTC, shahabhijeet commented on src/ResourceManagement/Relay/Relay.Tests/project.json
> +    "Microsoft.Rest.ClientRuntime.Azure.TestFramework": "1.5.0-preview",
@v-Ajnava can you use the latest Test Framework 1.6.0

2017-03-28 23:34 UTC, shahabhijeet commented on src/ResourceManagement/Relay/Relay.Tests/Tests/ScenarioTests.cs
> +                        _relayManagementClient = RelayManagementHelper.GetServiceBusManagementClient(context, new RecordedDelegatingHandler { StatusCodeToReturn = HttpStatusCode.OK });
@v-Ajnava please update the function name, make it GetRelayClient or something that says you are getting the relay client.

2017-03-28 23:36 UTC, shahabhijeet commented
Talked with @v-Ajnava and he mentioned more updated needs to be made to this PR due to swagger changes.

2017-03-29 22:45 UTC, shahabhijeet commented
@v-Ajnava please remove "needs-revision" flag once this is ready to be reviewed.
Please add link to the swagger once the updated swagger is merged

2017-03-30 03:23 UTC, v-Ajnava commented on src/ResourceManagement/Relay/Relay.Tests/project.json
> +    "Microsoft.Rest.ClientRuntime.Azure.TestFramework": "1.5.0-preview",
Updated.

2017-03-30 03:23 UTC, v-Ajnava commented on src/ResourceManagement/Relay/Relay.Tests/Tests/ScenarioTests.cs
> +                        _relayManagementClient = RelayManagementHelper.GetServiceBusManagementClient(context, new RecordedDelegatingHandler { StatusCodeToReturn = HttpStatusCode.OK });
corrected the function name.

2017-03-30 03:27 UTC, v-Ajnava commented
Updated Swagger Link : https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-relay/2016-07-01/swagger/relay.json

2017-04-01 00:09 UTC, merged