[HDInsight][Data Plane] Hdinsight job client supports token credential
Azure/azure-sdk-for-net pull request #30081
Opened 2022-07-22 10:29 UTC by aim-for-better

# Contributing to the Azure SDK

This PR is about updating HDInsight data plane SDK, this PR doesn't use the new swagger to generate new code, just adding some new logic in customization code.

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2022-07-25 03:06 UTC, aim-for-better commented
Hi team, could you please  help review this PR?

2022-07-26 02:10 UTC, aim-for-better commented
Hi @weshaggard @JoshLove-msft @ArcturusZhang ,
Hoping you are everything goes well. Could you please help review this PR?  Thanks.

2022-07-27 06:29 UTC, archerzz requested changes
@aim-for-better 
Make sure you update the following files, according to [the guide](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-generation-from-updated-spec).

- `AzSDK.RP.Props`
- `eng\mgmt\mgmtmetadata\<rpName>.txt`
- `.csproj`
- `AssemblyInfo.cs`

2022-07-27 06:34 UTC, archerzz approved these changes

2022-07-27 06:56 UTC, merged