RecoveryServicess on latest Swagger
Azure/azure-sdk-for-net pull request #3028
Opened 2017-04-04 21:36 UTC by dragonfly91

## Description
Corresponding Swagger Spec PRs (merged): https://github.com/Azure/azure-rest-api-specs/pull/920 and https://github.com/Azure/azure-rest-api-specs/pull/1089

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-05 22:59 UTC, shahabhijeet requested changes

2017-04-05 22:59 UTC, shahabhijeet commented on src/ResourceManagement/RecoveryServices/Microsoft.Azure.Management.RecoveryServices/project.json
> +  "version": "4.2.0-preview",
@dragonfly91 can you update AssemblyInfo.cs files.
Soon we are moving to new csproj based project system and this version will be used, so please update it to reflect the update version from project.json

2017-04-06 16:07 UTC, cormacpayne commented on src/ResourceManagement/RecoveryServices/Microsoft.Azure.Management.RecoveryServices/Customizations/RecoveryServicesClient.cs
> +using System.Linq;
@dragonfly91 this file needs a license header

2017-04-08 00:36 UTC, shahabhijeet approved these changes

2017-04-08 00:36 UTC, merged