Added support for AzureGermanCloud
Azure/azure-sdk-for-net pull request #3030
Opened 2017-04-05 14:44 UTC by horrion

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-05 14:44 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-04-05 14:44 UTC, msftclas commented
@__horrion__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-04-05 14:55 UTC, msftclas commented
__@horrion__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, Microsoft Pull Request Bot_

2017-04-05 17:47 UTC, hovsepm commented
@azuresdkci test this please

2017-04-05 17:54 UTC, hovsepm commented
@horrion Hi Robert. Thank you for the contribution! We would like to better understand your usage scenarios because  Authentication library in this repo is not supported anymore. We moved all the  functionality to azure-powershell repo because it was used primarily there.

2017-04-05 19:19 UTC, markcowl commented
Note that, if you wanted to make a contribution that impacts the current libraries, an update here:  https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure.Authentication/ActiveDirectoryServiceSettings.cs would be accepted

2017-04-10 18:03 UTC, shahabhijeet commented
@horrion add to whitelist

2017-04-10 18:04 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-04-10 21:57 UTC, hovsepm commented
@azuresdkci add to whitelist

2017-04-11 12:22 UTC, horrion commented
@markcowl please be advised that I just updated the content of https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure.Authentication/ActiveDirectoryServiceSettings.cs

2017-04-17 18:32 UTC, markcowl requested changes

2017-04-17 18:32 UTC, markcowl commented on src/Authentication/Common.Authentication/Models/AzureEnvironment.Methods.cs
> +            },
@horrion We have no plans to update this library, so please revert this.

2017-04-17 18:32 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure.Authentication/ActiveDirectoryServiceSettings.cs
> +            AuthenticationEndpoint= new Uri("https://login.microsoftonline.com/"),
login.windows.net is preferred.

2017-04-17 18:35 UTC, markcowl requested changes
Thanks for this PR, I love to see this kinf of proactive support.  We are deprecating the AutoRest branch, but once this is ready, either you or we can move this into the new branch.

Also, need to update the library version so that we cna publish a new nuget package with the changes.

Thanks again for the contribution!

2017-04-17 18:37 UTC, markcowl commented
@horrion Note that the ci failure is due to adding the new environment in common.authentication without updating one of the tests - since this part of the change should be reverted, the tests should pass once this is done.

2017-04-21 14:33 UTC, horrion commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure.Authentication/ActiveDirectoryServiceSettings.cs
> +            AuthenticationEndpoint= new Uri("https://login.microsoftonline.com/"),
@markcowl Could you please explain why the "old" endpoint is preferred? I thought everything that depends on Azure Resource Manager has to go through the new endpoint (login.microsoftonline.com).

2017-04-21 14:35 UTC, horrion commented
@markcowl I'll take care of removing the new environment in common.authentication. 
Would you mind notifying me when the new branch becomes available?

2017-04-26 19:49 UTC, markcowl commented on src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure.Authentication/ActiveDirectoryServiceSettings.cs
> +            AuthenticationEndpoint= new Uri("https://login.microsoftonline.com/"),
@horrion You are absolutely right, I was reading this entirely the wrong way

2017-04-27 23:02 UTC, azuresdkci commented
The AutoRest branch is retired and no longer takes pull requests. vs17Dev is the new autorest based .net sdk branch located here:  <a href="http://github.com/azure/azure-sdk-for-net/tree/vs17Dev">Azure/azure-sdk-for-net</a>.  Please submit pull requests to that branch.

2017-04-27 23:02 UTC, closed without merging

2017-04-28 02:42 UTC, azuresdkci commented
The AutoRest branch is retired and no longer takes pull requests. vs17Dev is the new autorest based .net sdk branch located here:  <a href="http://github.com/azure/azure-sdk-for-net/tree/vs17Dev">Azure/azure-sdk-for-net</a>.  Please submit pull requests to that branch.

2017-05-08 13:47 UTC, horrion commented
@markcowl Thanks for your support, so far! I have just created a new PR for the vs17Dev branch here: https://github.com/Azure/azure-sdk-for-net/pull/3182