Enable backup and restore operations for KeyVault secrets
Azure/azure-sdk-for-net pull request #3035
Opened 2017-04-05 20:27 UTC by dragav

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-05 20:27 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-04-05 20:27 UTC, msftclas commented
@dragav,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-05 20:31 UTC, pomortaz approved these changes

2017-04-06 17:51 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-04-06 21:38 UTC, hovsepm commented
@azuresdkci add to whitelist.

2017-04-06 21:49 UTC, shahabhijeet requested changes

2017-04-06 21:49 UTC, shahabhijeet commented on src/KeyVault/Microsoft.Azure.KeyVault/Generated/KeyVaultClientExtensions.cs
> +        public static async Task<SecretBundle> RestoreSecretAsync( this IKeyVaultClient operations, string vaultBaseUrl, byte[ ] secretBundleBackup, CancellationToken cancellationToken = default( Can
@dragav can you bump up the version of the nugget.

2017-04-06 21:55 UTC, dragav commented on src/KeyVault/Microsoft.Azure.KeyVault/Generated/KeyVaultClientExtensions.cs
> +        public static async Task<SecretBundle> RestoreSecretAsync( this IKeyVaultClient operations, string vaultBaseUrl, byte[ ] secretBundleBackup, CancellationToken cancellationToken = default( Can
@shahabhijeet That was already done by this [PR](https://github.com/Azure/azure-sdk-for-net/pull/3021), and we'd like to stay on this version until ready to GA. A few other small features will be brought into the same SDK ver (2.1.0-preview).

2017-04-06 22:47 UTC, shahabhijeet approved these changes

2017-04-06 22:47 UTC, merged