Expose new enums for VPNGatewaySku for VPN Gateways
Azure/azure-sdk-for-net pull request #3108
Opened 2017-04-20 00:21 UTC by ritwikbasu

Expose new enums for VPNGatewaySku for VPN Gateways

2017-04-20 00:21 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-04-20 00:21 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-04-20 00:21 UTC, msftclas commented
@ritwikbasu,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-20 04:45 UTC, markcowl commented
@ritwikbasu This is out of date with the branch, please pull the latest

2017-04-21 01:51 UTC, markcowl commented
@azuresdkci add to whitelist

2017-04-21 18:08 UTC, shahabhijeet requested changes

2017-04-21 18:08 UTC, shahabhijeet commented on src/SDKs/Network/Management.Network/Generated/Models/VirtualNetworkGatewaySkuTier.cs
> +        public const string VpnGw1 = "VpnGw1";
@ritwikbasu can you link the swagger spec for this change?
Also what is still not clear is, how come the sdk branch as 9.1.0-preview as the latest version of network package, but what is published out on nuget is 10.0.0-preview?

2017-04-21 20:23 UTC, ritwikbasu commented on src/SDKs/Network/Management.Network/Generated/Models/VirtualNetworkGatewaySkuTier.cs
> +        public const string VpnGw1 = "VpnGw1";
This is the swagger PR : https://github.com/Azure/azure-rest-api-specs/pull/1130.

I pulled the latest sdk branch - I am not sure of the versioning. I did not change anything except for the three generated code files in the PR.

2017-04-24 20:26 UTC, shahabhijeet commented on src/SDKs/Network/Management.Network/Generated/Models/VirtualNetworkGatewaySkuTier.cs
> +        public const string VpnGw1 = "VpnGw1";
@ritwikbasu in order to publish this SDK, it has to be a different version that is already not published to nuget.
But also, if currently your SDK that is published on nuget as 10.0, but you end up publishing this particular with 9.1, that will create confusion.
this version should be 10.1.0

2017-04-25 19:01 UTC, shahabhijeet requested changes
@ritwikbasu I don't see any version information.
What version will be this nuget? I see now that from prior iteration, you have completely ignored version number, what will be the version number of your nuget that you plan to publish.

2017-04-25 20:03 UTC, ritwikbasu commented
Strange – I pushed a new commit to update the version information:

[cid:image002.jpg@01D2BDC4.4A200DA0]

From: Abhijeet [mailto:notifications@github.com]
Sent: Tuesday, April 25, 2017 12:02 PM
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Ritwik Basu <ritwikb@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] Expose new enums for VPNGatewaySku for VPN Gateways (#3108)


@shahabhijeet requested changes on this pull request.

@ritwikbasu<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fritwikbasu&data=02%7C01%7Critwikb%40microsoft.com%7Cb90df7e172194eaad4e408d48c0d941d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636287437329089415&sdata=X0%2FO1mm3dzB%2FOFgKL31a4qfjRkS3QbPQRcbedqQByUI%3D&reserved=0> I don't see any version information.
What version will be this nuget? I see now that from prior iteration, you have completely ignored version number, what will be the version number of your nuget that you plan to publish.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F3108%23pullrequestreview-34657290&data=02%7C01%7Critwikb%40microsoft.com%7Cb90df7e172194eaad4e408d48c0d941d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636287437329089415&sdata=Rc%2F45rPXCWGIQqkbKUpjaXjTdu%2F48BaaDJXZrvln3aQ%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL39oksTez_vCLhirrhCoEru9HvKy9JCks5rzkMtgaJpZM4NCZMh&data=02%7C01%7Critwikb%40microsoft.com%7Cb90df7e172194eaad4e408d48c0d941d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636287437329089415&sdata=nbJlC31aObYcCFTugtW70AjnGsf%2B7IZUhxqcrwdJhMw%3D&reserved=0>.

2017-04-25 21:34 UTC, shawns1 commented
@azuresdkci please test

2017-04-26 22:04 UTC, shahabhijeet commented
@azuresdkci test this please

2017-04-27 05:39 UTC, shahabhijeet commented
@azuresdkci test this please

2017-04-27 06:49 UTC, shahabhijeet approved these changes

2017-04-27 06:50 UTC, merged