[Storage] Added support for HttpsTrafficOnly
Azure/azure-sdk-for-net pull request #3110
Opened 2017-04-20 08:30 UTC by JasonYang-MSFT

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-20 10:29 UTC, JasonYang-MSFT commented
Related Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/1120

2017-04-21 01:52 UTC, markcowl commented
@azuresdkci retest this please

2017-04-21 06:47 UTC, shahabhijeet requested changes

2017-04-21 06:47 UTC, shahabhijeet commented on src/SDKs/Storage/Management.Storage/Microsoft.Azure.Management.Storage.csproj
> +    <Version>6.3.0-preview</Version>
Better option remove VersionPrefix and replace it with <Version>
Add it under top property group where all package meta data is declared.

2017-04-21 06:47 UTC, shahabhijeet commented on src/SDKs/Storage/Management.Storage/project.json
> +  "version": "6.3.0-preview",
Delete this file. This file is no longer needed.
Also delete .xproj and global.json (if they are still in the directory)

2017-04-21 07:31 UTC, JasonYang-MSFT commented
@shahabhijeet Comments are addressed.

2017-04-21 16:44 UTC, merged