SB: Update SDK for Swagger changes
Azure/azure-sdk-for-net pull request #3114
Opened 2017-04-20 18:25 UTC by v-Ajnava

## Description
Update SDK for : 
Swagger property fixes
Namespace patch operation added 
Version update

Swagger PR Links : 
 https://github.com/Azure/azure-rest-api-specs/pull/879
https://github.com/Azure/azure-rest-api-specs/pull/1057

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [X] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-20 18:25 UTC, msftclas commented
@v-Ajnava,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-21 06:01 UTC, shahabhijeet commented
@v-Ajnava I had forgotten to delete xproj and project.json.
Please delete those files and restore .csproj file.
In VS2017 .csproj are the project files, we will not be needing project.json, global.json and *.xproj files.

2017-04-21 23:31 UTC, shahabhijeet commented
@v-Ajnava can we get a sign off from sazeesha

2017-04-21 23:42 UTC, shahabhijeet requested changes
Can you generate using the commit ids for the swagger that was checked in for this change.
And after that we need version bump for the newly generated sdk

2017-04-22 03:42 UTC, v-Ajnava commented
Done the requested changes.

2017-04-24 20:35 UTC, shahabhijeet requested changes

2017-04-24 20:35 UTC, shahabhijeet commented on src/SDKs/ServiceBus/Management.ServiceBus/Microsoft.Azure.Management.ServiceBus.csproj
> +    <Version>0.2.0-preview</Version>
@v-Ajnava <versionPrefix> is good enough for the version info. Either use versionPrefix or version but not both.
Also remove all commented code from .csproj files

2017-04-24 22:55 UTC, v-Ajnava commented on src/SDKs/ServiceBus/Management.ServiceBus/Microsoft.Azure.Management.ServiceBus.csproj
> +    <Version>0.2.0-preview</Version>
Used VersionPrefix and removed the commented code.

2017-04-25 21:01 UTC, merged