Update ADLA catalog
Azure/azure-sdk-for-net pull request #3118
Opened 2017-04-21 01:05 UTC by begoldsm

## Description
This change updates the ADLA catalog to do the following:
1. Introduces the new package item type
2. Allows for listing the following items from their parent's parent item (the database):
  * Table
  * view
  * Table valued function
  * Table statistics

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-21 01:57 UTC, markcowl commented
@begoldsm You may want to pull the latest from this PR: #3117 

Also, please fill out the checklist

2017-04-21 17:06 UTC, begoldsm commented
@markcowl shame on me, I know better! :). 
Here is the PR for the swagger update: https://github.com/Azure/azure-rest-api-specs/pull/1119

2017-04-21 19:29 UTC, begoldsm commented
@markcowl @shahabhijeet I have synced to the latest and squahsed my commits down and update the title, description and the checklist. Let me know if you have any questions or need anything else from me!

2017-04-24 20:41 UTC, shahabhijeet requested changes

2017-04-24 20:41 UTC, shahabhijeet commented on src/SDKs/DataLake.Analytics/Management.DataLake.Analytics/Microsoft.Azure.Management.DataLake.Analytics.csproj
> +    <Version>2.2.0-preview</Version>
@begoldsm let's continue using <versionPrefix> as that is being used across, but if you want to use <version> then you don't need <versionPrefix>. Also you do not need any package related properties.
All you need is the PackageId, assemblyName, assembly description and package tags. All the remaining ones not needed.
Also remove all commented code.

2017-04-24 20:41 UTC, shahabhijeet commented on src/SDKs/DataLake.Store/Management.DataLake.Store/generate.cmd
> +set accountSpecFile="https://raw.githubusercontent.com/Azure/azure-rest-api-specs/12a6c2299296b6877fa1e5a03ed42752445877dc/arm-datalake-store/account/2016-11-01/swagger/account.json"
@begoldsm was this missed as part of earlier checkin for the DataLake Store?

2017-04-24 20:48 UTC, begoldsm commented on src/SDKs/DataLake.Store/Management.DataLake.Store/generate.cmd
> +set accountSpecFile="https://raw.githubusercontent.com/Azure/azure-rest-api-specs/12a6c2299296b6877fa1e5a03ed42752445877dc/arm-datalake-store/account/2016-11-01/swagger/account.json"
no I just want to keep all specs at the same commit level.

2017-04-25 21:06 UTC, shahabhijeet commented on src/SDKs/DataLake.Store/Management.DataLake.Store/generate.cmd
> +set accountSpecFile="https://raw.githubusercontent.com/Azure/azure-rest-api-specs/12a6c2299296b6877fa1e5a03ed42752445877dc/arm-datalake-store/account/2016-11-01/swagger/account.json"
@begoldsm URL, licensense agreement, generating assembly version info. All this is getting controlled from common properties. So removing them will be really make all the nuget consistent

2017-04-26 16:48 UTC, begoldsm commented on src/SDKs/DataLake.Store/Management.DataLake.Store/generate.cmd
> +set accountSpecFile="https://raw.githubusercontent.com/Azure/azure-rest-api-specs/12a6c2299296b6877fa1e5a03ed42752445877dc/arm-datalake-store/account/2016-11-01/swagger/account.json"
@shahabhijeet this has been fixed and I removed all other entries. I am also, in the next iteration, moving the package ID to the top for easier identification.

2017-04-26 17:43 UTC, shahabhijeet approved these changes

2017-04-26 17:43 UTC, merged