EH: Update SDK for Swagger changes
Azure/azure-sdk-for-net pull request #3119
Opened 2017-04-21 04:15 UTC by v-Ajnava

## Description
Update SDK for : 
Swagger property changes reverted (SDK was not updated) and fixes
Namespace patch operation added 
Version update

Swagger PR Links : 
https://github.com/Azure/azure-rest-api-specs/pull/1111
https://github.com/Azure/azure-rest-api-specs/pull/1132

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [X] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-21 04:15 UTC, msftclas commented
@v-Ajnava,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-21 09:08 UTC, v-Ajnava commented
will fix the errors and update the PR.

2017-04-21 13:46 UTC, shahabhijeet requested changes

2017-04-21 13:46 UTC, shahabhijeet commented on src/SDKs/EventHub/EventHub.Tests/EventHub.Tests.csproj
> +    <PackageId>EventHub.Tests</PackageId>
@v-Ajnava please let me know if you were having any difficulty in building the project, that prompted you for this change.
Please reach out to me and I can explain if things were either not building or understand what you wanted to do.

2017-04-22 00:29 UTC, shahabhijeet approved these changes

2017-04-24 20:46 UTC, shahabhijeet requested changes

2017-04-24 20:46 UTC, shahabhijeet commented on src/SDKs/EventHub/Management.EventHub/Microsoft.Azure.Management.EventHub.csproj
> +    <Version>1.2.0</Version>
@v-Ajnava no need to have <version> <versionPrefix> at the same time

2017-04-24 22:56 UTC, v-Ajnava commented on src/SDKs/EventHub/Management.EventHub/Microsoft.Azure.Management.EventHub.csproj
> +    <Version>1.2.0</Version>
Used VersionPrefix

2017-04-25 21:01 UTC, shahabhijeet approved these changes

2017-04-25 21:02 UTC, merged