Azure Analysis Services: added support for new SKUs
Azure/azure-sdk-for-net pull request #3128
Opened 2017-04-24 22:11 UTC by igor-uzhviev

## Description
Added new SKUs for Azure Analysis Services: B1, B2, S0.
Pull request for API spec changes: https://github.com/Azure/azure-rest-api-specs/pull/1109

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-04-24 22:11 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-04-24 22:11 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-04-24 22:11 UTC, msftclas commented
@igor-uzhviev,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-26 20:55 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-04-26 20:55 UTC, shahabhijeet commented
@azuresdkci test this please

2017-04-26 20:56 UTC, shahabhijeet requested changes
I don't see any changes to the version.
Please update the version of the nuget inside .csproj as well as version info in AssemblyInfo.cs
If there are any legacy project.json, global.json and *.xproj, delete them for your project.

2017-04-27 05:40 UTC, shahabhijeet commented
@azuresdkci test this please

2017-04-27 05:50 UTC, shahabhijeet requested changes

2017-04-27 05:50 UTC, shahabhijeet commented on src/SDKs/AnalysisServices/Management.Analysis/Generated/Models/SkuName.cs
> +        public const string B2 = "B2";
@igor-uzhviev you will need to bump up the version in .csproj and AssemblyInfo.cs

2017-04-27 22:06 UTC, markcowl commented
@azuresdkci add to whitelist

2017-04-27 22:26 UTC, igor-uzhviev commented on src/SDKs/AnalysisServices/Management.Analysis/Generated/Models/SkuName.cs
> +        public const string B2 = "B2";
done.

2017-04-28 09:09 UTC, shahabhijeet commented
@igor-uzhviev do you already have existing tests for SKU's?

2017-04-28 16:19 UTC, markcowl requested changes

2017-04-28 16:19 UTC, markcowl commented on src/SDKs/AnalysisServices/Management.Analysis/Generated/Models/SkuName.cs
> +        public const string B2 = "B2";
Can we add one of the new skus to an existing test?

2017-04-28 22:20 UTC, igor-uzhviev commented on src/SDKs/AnalysisServices/Management.Analysis/Generated/Models/SkuName.cs
> +        public const string B2 = "B2";
I would really prefer not to do it now. There is just one scenario test which tests multiple actions one by one (provision->update->delete), it does not really test different skus, it just provisions a server with first sku. We have already many sku constants defined and I just added extra more. In the near future we want to switch to dynamic skus loading when they will be loaded from REST call, then we will definitely implement more advanced sku testing.

2017-05-05 18:33 UTC, igor-uzhviev commented
@markcowl a new test was added. Please check.

2017-05-05 18:40 UTC, igor-uzhviev commented
Travis CI build failed. The error is:
`/home/travis/.travis/job_stages: line 53: ./testSdkOnLinux.sh: Permission denied`
Seems to be infrastructure related...

2017-05-05 23:01 UTC, shahabhijeet commented
@igor-uzhviev so ignore travis build, that is still getting worked on.
But Jenkins failed and AnalysisService tests failed.

2017-05-08 19:43 UTC, shahabhijeet requested changes

2017-05-08 19:43 UTC, shahabhijeet commented on src/SDKs/AnalysisServices/AnalysisServices.Tests/AnalysisServices.Tests.csproj
> +    </None>
@igor-uzhviev please remove commented code from all csproj files.

2017-05-08 23:28 UTC, igor-uzhviev commented on src/SDKs/AnalysisServices/AnalysisServices.Tests/AnalysisServices.Tests.csproj
> +    </None>
@shahabhijeet done.

2017-05-09 23:54 UTC, shahabhijeet approved these changes

2017-05-09 23:55 UTC, merged