Add failover group operations
Azure/azure-sdk-for-net pull request #3155
Opened 2017-05-02 22:05 UTC by btasdoven

Adding Failover Groups operations to Microsoft.Sql provider with their tests, and reflecting the API changes in our swagger file.

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-02 22:05 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-02 22:05 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-02 22:05 UTC, msftclas commented
@btasdoven,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-02 23:30 UTC, jaredmoo commented on src/SDKs/SqlManagement/Management.Sql/Generated/DatabasesOperations.cs
> +            if ((int)_statusCode != 200 && (int)_statusCode != 202)
Note to reviewers: Swagger change was https://github.com/Azure/azure-rest-api-specs/pull/1166

2017-05-02 23:33 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +                        FailoverPolicy = "Disabled",
You should be able to write `ReadOnlyEndpointFailoverPolicy.Disabled`. (How do I know? see https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2015-05-01-preview/swagger/failoverGroups.json#L490 )

2017-05-02 23:33 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +                        FailoverPolicy = "Automatic",
Use `ReadWriteEndpointFailoverPolicy.Automatic`

2017-05-02 23:34 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +        public void TestUpdateFailoverGroup()
Seems a bit repetitive, could this be part of the above test case?

2017-05-02 23:34 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +        public void TestUpdateFailoverGroup()
Or could you at least factor out the common setup code?

2017-05-02 23:35 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +
Could you have a test where you call Failover? Seems like an important scenario for FailoverGroups ;)

2017-05-02 23:35 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +
It doesn't have to be a separate test, could be part of this or the other one. As long as it's covered somehow.

2017-05-03 17:34 UTC, btasdoven commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +        public static string DefaultPrimaryLocation
Yup, they are for Stage. Moved them to SqlManagementTestUtilities.

2017-05-03 17:34 UTC, btasdoven commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +        private Server CreateServer(SqlManagementClient sqlClient, ResourceGroup resourceGroup, string serverPrefix, string location)
Done.

2017-05-03 17:35 UTC, btasdoven commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +
That makes sense :) Added failover operation as part of the test case.

2017-05-03 17:35 UTC, btasdoven commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +        public void TestUpdateFailoverGroup()
Combined the test cases into one.

2017-05-03 18:25 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/FailoverGroupCrudScenarioTests.cs
> +                Assert.Equal(FailoverGroupReplicationRole.Primary, failoverGroupOnSecondary.PartnerServers.First().ReplicationRole);
Beautiful. 💯

2017-05-03 18:25 UTC, jaredmoo approved these changes

2017-05-05 09:34 UTC, shahabhijeet requested changes
I don't see any change in version.
Will need changes to csproj and assemblyinfo files related to versions.

2017-05-05 22:55 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-05-09 23:09 UTC, shahabhijeet approved these changes

2017-05-09 23:09 UTC, merged