C# SDK change with Routing Properties
Azure/azure-sdk-for-net pull request #3163
Opened 2017-05-03 21:16 UTC by ssankar1984

Routing Properties changes for C# SDK
Swagger Spec https://github.com/Azure/azure-rest-api-specs/pull/1174

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ Y] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ Y] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ Y] Title of the pull request is clear and informative.
- [ Y] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ Y] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [Y ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [Y ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [Y ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-03 21:16 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-03 21:16 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-03 21:16 UTC, msftclas commented
@ssankar1984,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-03 21:59 UTC, shahabhijeet requested changes
Bump up the version in csproj, AssemblyInfo.cs
Remove all traces of global.json, project.json and *.xproj from your SDK and SDK Test project directories.

2017-05-05 00:28 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-05-05 00:37 UTC, shahabhijeet requested changes

2017-05-05 00:37 UTC, shahabhijeet commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
>      <Description>Provides management capabilities for Microsoft Azure IotHub.</Description>
@ssankar1984 please remove all commented code from csproj files.

2017-05-05 08:18 UTC, shahabhijeet requested changes

2017-05-05 08:18 UTC, shahabhijeet commented on src/SDKs/IotHub/IotHub.Tests/Helpers/IotHubTestUtilities.cs
> +// you may not use this file except in compliance with the License.
@ssankar1984 why change the header and use the apache license?
We have adopted to use MIT license, please retain the previous license header

2017-05-05 08:18 UTC, shahabhijeet commented on src/SDKs/IotHub/IotHub.Tests/ScenarioTests/IotHubLifeCycleTests.cs
> +//   http://www.apache.org/licenses/LICENSE-2.0
@ssankar1984 retain previous license header

2017-05-05 19:46 UTC, shahabhijeet commented
@azuresdkci test this please

2017-05-08 17:03 UTC, ssankar1984 commented
Swagger PR here - https://github.com/Azure/azure-rest-api-specs/pull/1200

2017-05-09 23:44 UTC, merged