Testcases for RSBackup.dll
Azure/azure-sdk-for-net pull request #3168
Opened 2017-05-05 05:30 UTC by VinothJeyaraman

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-05 05:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-05 05:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-05 05:30 UTC, msftclas commented
@__VinothJeyaraman__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-05-05 08:31 UTC, shahabhijeet commented
@VinothJeyaraman add to whitelist

2017-05-05 08:32 UTC, shahabhijeet commented
@VinothJeyaraman please use the link above and get CLA approved.

2017-05-05 10:36 UTC, VinothJeyaraman commented
@shahabhijeet , I am a Microsoft FTE. I have just linked my account to Microsoft. 
Is CLA still required?

2017-05-05 19:47 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-05 19:47 UTC, msftclas commented
@__VinothJeyaraman__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-05-09 12:12 UTC, VinothJeyaraman commented
Hi,

I am a Microsoft FTE and I have given details in CLA form. I am yet to get the mail from DocuSign to sign electronically. 
Can someone tell me what should I do further?

2017-05-10 16:29 UTC, shahabhijeet requested changes
Please update the version number for your SDK package.
Please remove any traces of project.json, global.json and *.xproj, these files are no longer needed for the new project system.
Also add a description for your change.

2017-05-10 16:29 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.Backup/RecoveryServices.Backup.Tests/ScenarioTests/DpmTests.cs
> +        [Fact]
@VinothJeyaraman please record all new tests using latest version of Resource Manager or latest version of dependent ARM sdk packages.
We had a lots of issue migrating majority of tests when we moved to VS2017, so we are asking everyone who are recording tests to record using latest SDK packages

2017-05-10 16:29 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.Backup/RecoveryServices.Backup.Tests/TestHelpers/TestSettings.cs
> +			AzureSqlContainerName = testSettings.AzureSqlContainerName;
nit: fix tabs

2017-05-16 01:02 UTC, shahabhijeet commented
@VinothJeyaraman please let me know if you are not clear as to what needs to be done.
In short, by default your tests are using 1.1.0-preview version of nuget package.
I am asking you to start recording new tests using 1.6.0 version of Resource Manager nuget package.
This will allow you to move away from a basic nuget package that is really very old and we should not be using it anyway to begin with at this stage.
So you will want to add a reference to the new version in your test project and start using the new Resource Manager client Side by Side in your tests. Eventually you would want to re-record all your tests with the latest resource manager client.

2017-05-22 13:00 UTC, VinothJeyaraman commented
@shahabhijeet 
Hi Abhijeet, Could you please tell me how to update nugget package? I tried with update-package in package Manager console. It says 'update not available'.

2017-05-23 21:12 UTC, markcowl commented
@VinothJeyaraman Y&ou can simply update the version in the csproj.  1.6.0-preview is the latest, I believe.

2017-05-24 08:20 UTC, VinothJeyaraman commented
@shahabhijeet , @markcowl 
I don't find the package reference in csproj file. 

However, I found that in AzSdk.test.reference.props. When I changed the version number and tried to build it, I got the following error :  Unable to resolve 'Microsoft.Azure.ResourceManager (>= 1.6.0)' for '.NETCoreApp,Version=v1.1'.	

can you please help me out?

2017-05-26 00:32 UTC, shahabhijeet commented
@VinothJeyaraman add a reference to the nuget package to your test project and then load your project that would add the new reference.
E.g. Add this to your test project and reload your csproj file in VS
<ItemGroup> 
	<PackageReference Include="Microsoft.Azure.Management.ResourceManager" Version="1.6.0-preview" /> 
</ItemGroup> 
You do not need to change it in AzSdk.test.reference.props, that is for backward compatibility.
Once you do this, the new nuget package has new namespace and that would help you start creating new ResourceManagmentClient using the new nuget package.

2017-06-05 07:21 UTC, shahabhijeet commented
@VinothJeyaraman please reopen PR once you are ready to merge

2017-06-05 07:21 UTC, closed without merging