bump Azure.ResourceManager.Avs to 2022-05-01 API
Azure/azure-sdk-for-net pull request #31791
Opened 2022-10-13 18:00 UTC by cataggar

This bumps the Azure.ResourceManager.Avs to use the 2022-05-01 API that was recently merged in https://github.com/Azure/azure-rest-api-specs/pull/20873 .

2022-10-13 20:08 UTC, cataggar reviewed
~I think the apicompat checker may have a bug.~

2022-10-13 20:08 UTC, cataggar commented on sdk/avs/Azure.ResourceManager.Avs/api/Azure.ResourceManager.Avs.netstandard2.0.cs
> +        public static Azure.Response<Azure.ResourceManager.Avs.Models.AvsSubscriptionTrialAvailabilityResult> CheckAvsTrialAvailability(this Azure.ResourceManager.Resources.SubscriptionResource subsc
> ##[error]D:\a\_work\1\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(82,5): Error : MembersMustExist : Member 'public Azure.Response<Azure.ResourceManager.Avs.Models.AvsSubscriptionTrialAvailabilityResult> Azure.ResourceManager.Avs.AvsExtensions.CheckAvsTrialAvailability(Azure.ResourceManager.Resources.SubscriptionResource, Azure.Core.AzureLocation, System.Threading.CancellationToken)' does not exist in the implementation but it does exist in the contract.

Is this a bug with `microsoft.dotnet.apicompat\5.0.0-beta.20467.1` ? It doesn't seem to handle the `AvsSku sku = null` well. It is in this contract and the implementations.

2022-10-13 20:25 UTC, cataggar commented on sdk/avs/Azure.ResourceManager.Avs/api/Azure.ResourceManager.Avs.netstandard2.0.cs
> +        public static Azure.Response<Azure.ResourceManager.Avs.Models.AvsSubscriptionTrialAvailabilityResult> CheckAvsTrialAvailability(this Azure.ResourceManager.Resources.SubscriptionResource subsc
Nevermind. I read https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#api-compatibility-verification and then made ace36b185e5bb3ed284d549b9e7aff784e304e5c to make it compatible with 1.0.0.

2022-10-13 20:57 UTC, cataggar commented
Hi @Yao725, how much more work is it to get the version bumped and published to NuGet?
https://www.nuget.org/packages/Azure.ResourceManager.Avs

2022-10-14 11:01 UTC, Yao725 requested changes
Please also update the changelog so we can let the customer know what happened in this upgrade.

2022-10-18 03:23 UTC, cataggar commented
@Yao725, the requested changes have been made.

2022-10-18 09:35 UTC, Yao725 approved these changes
LGTM

2022-10-18 11:28 UTC, merged

2022-10-18 13:39 UTC, Yao725 commented
Hi @cataggar, as this PR is merged, we are going to release the new version 1.1.0 for avs tomorrow, is it ok with you?

2022-10-18 15:27 UTC, cataggar commented
@Yao725 Yes. Please do release it.