Added support for HTTP2 APNS authentication
Azure/azure-sdk-for-net pull request #3179
Opened 2017-05-06 01:29 UTC by amolr

## Description
1. Added support to create/update the Hub with HTTP2 APNS authentication parameters
2. Added a checkNameAvailability API with new request/response parameters. Will add tests once this is in prod

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-06 01:29 UTC, msftclas commented
@amolr,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-08 18:12 UTC, smithab commented
Please update the Package.json file with the new api version to be "2.3.0-preview" and update the generated.cmd file with the path to the new swagger file that you created. Update the Assemblyinfo.cs file with the new version as well !

2017-05-08 20:14 UTC, shahabhijeet requested changes

2017-05-08 20:14 UTC, shahabhijeet commented on src/SDKs/NotificationHubs/Management.NotificationHubs/Generated/HubsOperations.cs
> +// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
@amolr please add the right license header to all your code files.
Also please link the spec PR.
I suspect you are not using the right header constants in your swagger that is causing AutoRest to skip generating the right licensing header text.

2017-05-08 20:14 UTC, shahabhijeet commented on src/SDKs/NotificationHubs/NotificationHubs.Tests/Tests/ScenarioTests.NotificationHubTests.CRUD.cs
> +                        SecretKey = "w7TBprR-9tJxn9mUOdK4PPHLCAzSYFhp",
@amolr this will get flagged when you try to publish. Any reason this has to be hardcoded?

2017-05-08 20:14 UTC, shahabhijeet commented on src/SDKs/NotificationHubs/NotificationHubs.Tests/Tests/ScenarioTests.NotificationHubTests.CRUD.cs
> +                        Token = "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpVB15km4qskA5Ra5XvdtOwWPvaXIhVVQZdonzINh+hGgCgYIKoZIzj0DAQehRANCAASS3ek04J20BqA6WWDlD6+xd3dJEifhW87wI0nnkfUB8LDb424TiW
@amolr why tokens are being hard-coded.

2017-05-10 04:33 UTC, shahabhijeet commented
@amolr please address all feedback. Let me know if you have any questions.
You need to bump up the version for your nuget to be published.
Also update AssemblyFileVersion in AssemblyInfo.cs

2017-05-11 04:22 UTC, shahabhijeet commented
@amolr test this please

2017-05-11 19:51 UTC, merged