Added support for VirtualNetworkUsages API to Virtual Networks
Azure/azure-sdk-for-net pull request #3193
Opened 2017-05-10 11:55 UTC by number213

## Description
Added support for VirtualNetworkUsages API to Virtual Networks
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/1168

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-10 11:55 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-10 11:55 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-10 11:55 UTC, msftclas commented
@__number213__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-05-10 12:01 UTC, msftclas commented
__@number213__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, Microsoft Pull Request Bot_

2017-05-10 18:13 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-05-10 18:16 UTC, shahabhijeet requested changes

2017-05-10 18:16 UTC, shahabhijeet commented on src/SDKs/Network/Network.Tests/Tests/VirtualNetworkTests.cs
> +        [Fact]
@number213 all new tests should be using latest Resource Manager nuget package.

2017-05-11 06:57 UTC, number213 commented
@shahabhijeet re-recorded new test with the latest Resource Manager

2017-05-13 00:17 UTC, shahabhijeet requested changes

2017-05-13 00:17 UTC, shahabhijeet commented on src/SDKs/Network/Network.Tests/Tests/VirtualNetworkTests.cs
> +                var resourcesClient = ResourcesManagementTestUtilities.GetResourceManagementClientWithHandler(context, handler1);
@number213 I don't see any changes to code that creates the actual Resource Manager client.
Could you point me to that change?

2017-05-15 10:01 UTC, number213 commented
@shahabhijeet sorry for taking so long, finally got what you meant. Updated Virtual Network tests to use latest Resource Manager instead of depreciated one.

2017-05-15 18:55 UTC, shahabhijeet approved these changes

2017-05-15 18:57 UTC, merged