[DO NOT MERGE] Adding projects for RecoveryServices.SiteRecovery service.
Azure/azure-sdk-for-net pull request #3194
Opened 2017-05-10 17:29 UTC by avneeshrai

It's corresponding to new swagger spec which is under PR https://github.com/Azure/azure-rest-api-specs/pull/1209
Intent is to get early feedback here.

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-10 17:30 UTC, msftclas commented
@avneeshrai,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-13 07:39 UTC, avneeshrai commented
Can someone review this PR please. Corresponding swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/1209 is merged.

I have removed do not merge tag.

2017-05-13 22:52 UTC, shahabhijeet requested changes

2017-05-13 22:52 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.SiteRecovery/Management.RecoveryServices.SiteRecovery/Generated/IOperationsOperations.cs
> +// Changes may cause incorrect behavior and will be lost if the code is
@avneeshrai missing license header.
Chances are your swagger does not have the right License Header Constant, please double check, I believe the constant that you need to use in your swagger is "MIT-no-version"

2017-05-13 22:52 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.SiteRecovery/Management.RecoveryServices.SiteRecovery/Generated/IOperationsOperations.cs
> +// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
@avneeshrai please use latest AutoRest (at least 1.0)

2017-05-13 23:05 UTC, avneeshrai commented on src/SDKs/RecoveryServices.SiteRecovery/Management.RecoveryServices.SiteRecovery/Generated/IOperationsOperations.cs
> +// Changes may cause incorrect behavior and will be lost if the code is
@shahabhijeet can you please point to some example spec on what exacty needs to be done here
I tried searching MIT-no-version in azure-rest-api-spec repository but couldnt find any instance of it

2017-05-13 23:06 UTC, avneeshrai commented on src/SDKs/RecoveryServices.SiteRecovery/Management.RecoveryServices.SiteRecovery/Generated/IOperationsOperations.cs
> +// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
even after doing autorest --latest or autorest --reset 
the version that i get is 0.16.0.0.
How to i get 1.0?

2017-05-14 00:54 UTC, avneeshrai commented on src/SDKs/RecoveryServices.SiteRecovery/Management.RecoveryServices.SiteRecovery/Generated/IOperationsOperations.cs
> +// Changes may cause incorrect behavior and will be lost if the code is
Fixed in the latest commit

2017-05-14 00:55 UTC, avneeshrai commented
@shahabhijeet Please review and merge the change in swagger spec as you had suggested in the PR: https://github.com/Azure/azure-rest-api-specs/pull/1227

2017-05-16 07:42 UTC, shahabhijeet approved these changes

2017-05-16 07:42 UTC, merged

2017-05-16 08:32 UTC, avneeshrai commented on src/SDKs/RecoveryServices.SiteRecovery/RecoveryServices.SiteRecovery.Tests/RecoveryServices.SiteRecovery.Tests.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
@shahabhijeet as discussed offline...we dont have dependency on Resource manager in our projects. Have removed all the stale references that we had.