Add test for AzureRmSqlServerActiveDirectoryAdministratorTest
Azure/azure-sdk-for-net pull request #3196
Opened 2017-05-10 18:19 UTC by jaczhan

2017-05-10 18:19 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-10 18:19 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-10 18:19 UTC, msftclas commented
@jaczhan,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-10 21:05 UTC, nathannfan commented on src/SDKs/SqlManagement/Sql.Tests/AzureRmSqlServerActiveDirectoryAdministratorTest.cs
> +
Add a check for list here too?

2017-05-10 21:06 UTC, nathannfan approved these changes
Looks good to me if it passes validation.

2017-05-10 23:30 UTC, shahabhijeet requested changes

2017-05-10 23:30 UTC, shahabhijeet commented on src/SDKs/SqlManagement/Sql.Tests/Sql.Tests.csproj
> +    <PackageReference Update="Microsoft.Rest.ClientRuntime.Azure" Version="3.3.5" />
@jaczhan you don't need to add these references, they get implicitly added.

2017-05-10 23:30 UTC, shahabhijeet commented on src/SDKs/SqlManagement/Sql.Tests/AzureRmSqlServerActiveDirectoryAdministratorTest.cs
> +        [Fact]
@jaczhan please record test using latest nugets (e.g. 1.5.0 version of Resource manager) Currently you are using 1.1.0-preview version of Resource Manager.
All new tests should be using latest version of Resource Manager.

2017-05-11 00:10 UTC, jaczhan commented on src/SDKs/SqlManagement/Sql.Tests/AzureRmSqlServerActiveDirectoryAdministratorTest.cs
> +        [Fact]
how do I switch to the latest nugets?

2017-05-11 00:26 UTC, jaczhan commented on src/SDKs/SqlManagement/Sql.Tests/AzureRmSqlServerActiveDirectoryAdministratorTest.cs
> +        [Fact]
just updated

2017-05-11 18:31 UTC, shahabhijeet requested changes

2017-05-11 18:31 UTC, shahabhijeet commented on src/SDKs/SqlManagement/Management.Sql/Microsoft.Azure.Management.Sql.csproj
> +    <PackageReference Include="Microsoft.Azure.Management.ResourceManager" Version="1.6.0-preview" />
@jaczhan any reason you need this nuget in your SQL package?
The requirement was only for recording new test, so your other change is all you need.
You don't want additional dependency on your SQL SDK package.
Please revert "this" particular change.
Please keep your other change that you made in the test project (that is what I had asked for)

2017-05-11 18:31 UTC, shahabhijeet commented on src/SDKs/SqlManagement/Sql.Tests/Sql.Tests.csproj
> +    <PackageReference Update="Microsoft.Rest.ClientRuntime.Azure.TestFramework" Version="1.6.0" />
@jaczhan you do not need this, this is being added to every project.
Any reason you had to add reference to TestFramework?

2017-05-11 21:05 UTC, jaczhan reviewed
remove Resource Manager 1.6

2017-05-11 21:36 UTC, shahabhijeet commented
@jaczhan add to whitelist

2017-05-11 21:41 UTC, jaczhan commented
Adding test for Swagger AzureRmSqlServerActiveDirectoryAdministrator

https://github.com/Azure/azure-rest-api-specs/pull/1203

2017-05-11 23:35 UTC, jaczhan reviewed
changes made to fix 1.6 tag

2017-05-22 22:43 UTC, jaredmoo commented
We will rerecord the tests separately - https://github.com/Azure/azure-sdk-for-net/issues/3267

2017-05-23 05:09 UTC, shahabhijeet commented
@jaczhan looks good, as soon as CI passes this can be merged.

2017-05-23 17:30 UTC, merged