Redis track 2 .NET SDK 2022-06-01 API version updates
Azure/azure-sdk-for-net pull request #32031
Opened 2022-10-26 16:47 UTC by austintolani

**Summary**
These changes contain the newly generated code for the `Azure.ResourceManager.Redis` package based on the new 2022-06-01 API version. This generation actually includes new code for changes made in both the 2022-06-01 and 2022-05-01 API versions:

- https://github.com/Azure/azure-rest-api-specs/pull/20869
- https://github.com/Azure/azure-rest-api-specs/pull/19506

**Testing**
I have re-recorded the existing tests using the new API version and added some additional testing coverage.

2022-10-31 07:18 UTC, archerzz requested changes
There are two types of breaking changes in the new version:
1. Two methods are changed to long running
2. New parameters inserted into the constructor of model class

- For item2, you could write customization codes to provide backward compatible constructors. 
- For item1, I think you could also write customization codes to provide backward compatible operation methods. Inside the backward compatible methods, you `await` on the new long running methods.

I'll leave the decision for you. You could write customization codes to provide backward compatibility. Or you could bump the major version.

2022-10-31 07:18 UTC, archerzz commented on sdk/redis/Azure.ResourceManager.Redis/CHANGELOG.md
> +- Deleting a linked server is now a long running operation
If there are breaking changes, we need to bump the major version, e.g. `2.0.0-beta.1`. @ArthurMa1978  FYI

2022-10-31 07:18 UTC, archerzz commented on sdk/redis/Azure.ResourceManager.Redis/src/Generated/RedisLinkedServerWithPropertyData.cs
> +        internal RedisLinkedServerWithPropertyData(ResourceIdentifier id, string name, ResourceType resourceType, SystemData systemData, ResourceIdentifier linkedRedisCacheId, AzureLocation? linkedRe
There are breaking changes in the interfaces (e.g. parameters are inserted before existing parameters). Here are 2 options:
  - Add manual codes to provide backward compatibility, see compute for reference: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations
- Or you need to bump the major version

2022-11-03 08:51 UTC, archerzz approved these changes

2022-11-03 08:57 UTC, archerzz commented
> @archerzz I've spoked with my team and we've decided the best approach for us is to bump the major version number. I've updated the version number to 2.0.0 in `CHANGELOG.md`. Is there anything else that I need to do to? Should I be leaving the date as "(Unreleased)" in `CHANGELOG.md`?

- If it's just an update on the codes and you're not going to release the SDK right now, you can leave it with `(Unreleased)`.
- If you're going to release the SDK, you need to update with the release date. 

By the way, the pipeline is broken because the version number in `CHANGELOG.md` is inconsistent with the value in [Azure.ResourceManager.Redis.csproj](https://github.com/Azure/azure-sdk-for-net/blob/71241a89e8e999a62bb14f7b8ac33955533aa0f1/sdk/redis/Azure.ResourceManager.Redis/src/Azure.ResourceManager.Redis.csproj#L3).

2022-11-04 05:28 UTC, austintolani commented
Thanks @archerzz, I've updated the CHANGELOG accordingly. My plan is to release the SDK. Can we merge the PR?

2022-11-07 05:29 UTC, austintolani commented
@archerzz There is one failing test that seems to be a timeout failure. Are these type of failures common? Is there anything I can do to fix it?

2022-11-07 07:46 UTC, archerzz commented
> @archerzz There is one failing test that seems to be a timeout failure. Are these type of failures common? Is there anything I can do to fix it?

No worry. I've restarted the failed job, and it's fine now.

2022-11-07 07:46 UTC, merged

2022-11-07 16:43 UTC, austintolani commented
Awesome, thanks for all your help @archerzz