Change GUID to string for principalid in PAS ( record sessions included)
Azure/azure-sdk-for-net pull request #3223
Opened 2017-05-16 21:03 UTC by shaosong2017

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-16 21:03 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-16 21:03 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-16 21:03 UTC, msftclas commented
@shaosong2017,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-16 21:22 UTC, shahabhijeet requested changes
Can you paste the link to the Hydra spec PR that was submitted for this change?

2017-05-16 21:22 UTC, shahabhijeet commented on src/ResourceManagement/Authorization/Authorization/Generated/AuthorizationManagementClient.cs
> +        public const string APIVersion = "2015-07-01";
@shaosong2017 is this code edited or generated?

2017-05-16 21:22 UTC, shahabhijeet commented on src/ResourceManagement/Authorization/Authorization/Generated/Models/RoleAssignmentProperties.cs
> +        private string _principalId;
@shaosong2017 is this a change in swagger? or hand edited?

2017-05-16 21:22 UTC, shahabhijeet commented on src/ResourceManagement/Authorization/Authorization/Generated/PermissionOperations.cs
> +        public const string APIVersion = "api-version=2015-07-01";
@shaosong2017 is this code generated?

2017-05-16 21:26 UTC, shaosong2017 commented on src/ResourceManagement/Authorization/Authorization/Generated/AuthorizationManagementClient.cs
> +        public const string APIVersion = "2015-07-01";
they are generated.

2017-05-16 21:29 UTC, shaosong2017 commented on src/ResourceManagement/Authorization/Authorization/Generated/AuthorizationManagementClient.cs
> +        public const string APIVersion = "2015-07-01";
It is edited, since lots of place use "2015-07-01", which is hard coded and not good for mainteance.

2017-05-16 21:30 UTC, shaosong2017 commented on src/ResourceManagement/Authorization/Authorization/Generated/Models/RoleAssignmentProperties.cs
> +        private string _principalId;
no, it is not a change in swagger. It is generated by Hydra.

2017-05-16 21:33 UTC, shaosong2017 commented on src/ResourceManagement/Authorization/Authorization/Generated/PermissionOperations.cs
> +        public const string APIVersion = "api-version=2015-07-01";
Same reason, I think it is better for code maintenance.

2017-05-16 21:50 UTC, shaosong2017 commented on src/ResourceManagement/Authorization/Authorization/Generated/AuthorizationManagementClient.cs
> +        public const string APIVersion = "2015-07-01";
Sorry, maybe I misunderstood your commit. The code is generated by Hydra. I changed this for code maintenance, or I can leave as it is. We do not change the Hydra spec.

2017-05-17 18:04 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-05-17 18:40 UTC, shahabhijeet commented
@azuresdkci test this please

2017-05-17 18:44 UTC, shaosong2017 commented
dummy comment.

2017-05-17 19:00 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-17 19:00 UTC, msftclas commented
@shaosong2017,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-17 19:56 UTC, shahabhijeet commented
@azuresdkci test this please

2017-05-18 16:48 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-18 16:48 UTC, msftclas commented
@shaosong2017,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-05-18 16:49 UTC, closed without merging