Update SB samples to target NET6.0
Azure/azure-sdk-for-net pull request #32581
Opened 2022-11-19 21:01 UTC by JoshLove-msft

The repo update to use .NET 6 SDK (along with .NET 5 being EOL) is resulting in build errors for SB CI pipeline.

2022-11-19 21:17 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2022-11-21 14:01 UTC, jsquire requested changes

2022-11-21 19:22 UTC, jsquire approved these changes

2022-11-21 19:22 UTC, jsquire commented on sdk/servicebus/Azure.Messaging.ServiceBus/samples/DeadLetterQueue/DeadLetterQueue.csproj
> +    <PackageReference Update="System.CommandLine" Version="%(VersionOverride)" />
nifty.

2022-11-21 19:23 UTC, JoshLove-msft commented on sdk/servicebus/Azure.Messaging.ServiceBus/samples/DeadLetterQueue/DeadLetterQueue.csproj
> +    <PackageReference Update="System.CommandLine" Version="%(VersionOverride)" />
Yes, the credit goes to @heaths 😄

2022-11-21 19:29 UTC, merged