[Cognitive Services] Add .nuspec file to include readme.txt
Azure/azure-sdk-for-net pull request #3290
Opened 2017-05-27 06:13 UTC by felixwa

Add .nuspec file to include readme.txt

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-05-27 06:18 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-05-27 06:19 UTC, felixwa commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Microsoft.Azure.Management.CognitiveServices.nuspec
> +    <file src="bin\release\netstandard1.4\Microsoft.Azure.Management.CognitiveServices.dll" target="lib\netstandard1.4" />
The "src" path works on my local machine but I'm not very sure if I should specify it in this way for "official" build. Please confirm.

2017-05-27 06:22 UTC, felixwa commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Microsoft.Azure.Management.CognitiveServices.nuspec
> +﻿<?xml version="1.0" encoding="utf-8"?>
This .nuspec file is authored based on the file I extracted from Cognitive Services package in nuget.org

2017-05-27 06:23 UTC, felixwa commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Microsoft.Azure.Management.CognitiveServices.nuspec
> +        <dependency id="Microsoft.NETCore.Platforms" version="[1.1.0, )" />
Not sure if we really need this long dependency list?

2017-05-30 19:02 UTC, shahabhijeet requested changes

2017-05-30 19:02 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Microsoft.Azure.Management.CognitiveServices.nuspec
> +    <file src="bin\release\netstandard1.4\Microsoft.Azure.Management.CognitiveServices.dll" target="lib\netstandard1.4" />
@felixwa were you able to create a nuget and install the new nuget and see the notice get's added to the users Solution in Visual Studio?

2017-05-30 23:28 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-05-30 23:58 UTC, shahabhijeet requested changes

2017-05-30 23:58 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Microsoft.Azure.Management.CognitiveServices.nuspec
> +    <file src="bin\release\netstandard1.4\Microsoft.Azure.Management.CognitiveServices.dll" target="lib\netstandard1.4" />
@felixwa a good way to make this change is good is to create a signed nuget package using the signing job to create a signed package and test out in SDK and PowerShell scenarios.

2017-06-01 08:40 UTC, felixwa commented
@shahabhijeet , I have removed that .nuspec file because I found it is not a must have to include the notice.txt file in the package. You can refer to this build artifacts: http://azuresdkci.cloudapp.net/view/NetCore-SDK/job/NetCore-SDK-Sign/156/

2017-06-05 07:20 UTC, shahabhijeet approved these changes

2017-06-05 07:20 UTC, merged