Updated .NET SDK from latest swagger for RecoveryServices.Backup
Azure/azure-sdk-for-net pull request #3311
Opened 2017-06-01 17:47 UTC by DheerendraRathor

## Description

- Upgraded version to 1.4.0.0-preview
- Removed redundant files
- Added tests and record files for List Operations API

Swagger spec PR: https://github.com/Azure/azure-rest-api-specs/pull/1267 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-07 21:46 UTC, shahabhijeet requested changes

2017-06-07 21:46 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Generated/Models/Page2.cs
> +         [JsonProperty("NextLink")]
@DheerendraRathor why is it not camelCase?

2017-06-07 21:46 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Generated/Models/Page2.cs
> +         [JsonProperty("Value")]
@DheerendraRathor any reason this is not camelCase?

2017-06-07 21:46 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup.csproj
> +    <VersionPrefix>1.4.0-preview</VersionPrefix>
@DheerendraRathor you have a breaking change, that requires major version change and not minor version.

Please also use latest resource manager nuget package for recording your tests that you have in this PR.
You are still using 1.1.0-preview Resource Manager and you need start using >=1.6.0

2017-06-07 21:46 UTC, shahabhijeet commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.4.0.0")]
@DheerendraRathor major version change in FileVersion as well as AssemblyVersion

2017-06-08 05:37 UTC, DheerendraRathor commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Generated/Models/Page2.cs
> +         [JsonProperty("NextLink")]
This is auto generated from swagger spec and which in turn reflects field name directly from service data contracts.

2017-06-08 05:37 UTC, DheerendraRathor commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Generated/Models/Page2.cs
> +         [JsonProperty("Value")]
Same as for "NextLink"

2017-06-08 16:58 UTC, DheerendraRathor commented
@shahabhijeet Currently project is referring `Microsoft.Azure.ResourceManager 1.1.0-preview` which is read from `AzSdk.test.reference.props`. On nuget this package is unavailable and name of package is [`Microsoft.Azure.Management.ResourceManager`](https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager/1.6.0-preview). Should I still refer to new package? I can't remove old 1.1.0 as it will require modification of `AzSdk.test.reference.props` and that will change references in all test projects.

2017-06-08 20:19 UTC, shahabhijeet commented
@DheerendraRathor you add the new package in your test project and not in reference.props file.
Version 1.1.0 and 1.6.0 can co-exists.
The idea is to make sure you are creating and using the latest resource manager package and using it in your tests.

2017-06-13 06:18 UTC, DheerendraRathor commented
@shahabhijeet Can you please look into it? It has been pending for a while now.

2017-06-15 00:27 UTC, shahabhijeet approved these changes

2017-06-15 00:27 UTC, merged