[Azure.AI.TextAnalytics.Authoring] Standalone package for the authoring client
Azure/azure-sdk-for-net pull request #33209
Opened 2022-12-27 18:28 UTC by LouaiZahran

As per our agreement, we decided to publish the TA authoring client as a standalone beta package until we have the chance to consolidate both the authoring and runtime packages into one package.

### Remaining work:
Recording the tests.

2023-01-05 18:18 UTC, heaths requested changes
One main question: all the work you did here could easily have been done in the existing package. We don't have separate authoring packages for the other Language clients, but you can look at their autorest.md for how I do a batch-build to reference separate input files (if needed). Why release a separate package when even less work is required than this to add it to the existing package?

Who was this discussion about releasing a separate package with?

2023-01-05 18:18 UTC, heaths commented on sdk/textanalytics/Azure.AI.TextAnalytics.Authoring/CHANGELOG.md
> +
Should at least have `- Initial release` or something for at least one entry ready when released.

2023-01-05 18:18 UTC, heaths commented on sdk/textanalytics/Azure.AI.TextAnalytics.Authoring/Directory.Build.props
> +  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory).., Directory.Build.props))\Directory.Build.props" />
File not necessary. May as well delete.

2023-01-05 18:18 UTC, heaths commented on sdk/textanalytics/Azure.AI.TextAnalytics.Authoring/README.md
> +This section should give out brief introduction of the client library.
The README needs to be updated at some point. Do you have a separate tracking issue?

2023-01-05 18:18 UTC, heaths commented on sdk/textanalytics/Azure.AI.TextAnalytics.Authoring/samples/README.md
> +<!-- please refer to <https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/Azure.Template/samples/README.md> to write sample readme. -->
This needs to reference every sample herein.

2023-01-06 10:03 UTC, LouaiZahran commented
> One main question: all the work you did here could easily have been done in the existing package. We don't have separate authoring packages for the other Language clients. Why release a separate package when even less work is required than this to add it to the existing package?
> 
> Who was this discussion about releasing a separate package with?

This discussion was done a while ago (almost a month ago) in a long email thread titled "Authoring Client Status". I'm not sure whether you were included but Kareem, Krista, and Johan were there, and they came to the conclusion that currently it is better to have a separate package for the authoring clients for both Python and .NET as they had concerns about the maintainability of the authoring client in the same package as the runtime one.

Unfortunately, my internship has ended and I no longer have access to my work email to forward the thread to you. The SDK is handed over to @AhmedLeithy to continue working on and you can talk to Kareem or Krista to have a better understanding of the situation.

2023-01-08 19:23 UTC, closed without merging

2023-01-09 19:40 UTC, heaths commented
Thanks. I'll take this offline with them.