ADLA: Add Job Relationship functonality
Azure/azure-sdk-for-net pull request #3325
Opened 2017-06-06 19:37 UTC by begoldsm

## Description
- Add Job Relationship properties and APIs. This includes a new property bag on JobInfo called `Related`
- Update package to Stable
- Update changelog to show all the changes that are going in to this stable release from the last one.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-06 19:39 UTC, begoldsm commented
Swagger PR that this is based on: https://github.com/Azure/azure-rest-api-specs/pull/1272
NOTE: There is a breaking change in this stable release vs. the previous stable release (but not the previous preview release). That is documented and the version of the SDK reflects this.

2017-06-07 22:06 UTC, shahabhijeet requested changes

2017-06-07 22:06 UTC, shahabhijeet commented on src/SDKs/DataLake.Analytics/Management.DataLake.Analytics/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("2.2.2.0")]
@begoldsm bump up to 3.0.0, because your last stable was 2.0.0 and this seems to have breaking change compared to 2.0.0

2017-06-08 04:00 UTC, begoldsm commented
@shahabhijeet it is updated to 3.0.0 can you take a quick look and merge if there are no other issues?
Thank you so much!

2017-06-08 22:14 UTC, shahabhijeet approved these changes

2017-06-08 22:15 UTC, merged