Recorded test for CheckConnectivity Api
Azure/azure-sdk-for-net pull request #3328
Opened 2017-06-06 23:51 UTC by irrogozh

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-07 19:43 UTC, irrogozh commented
Link to the corresponding issue: Workitem for chackConnectivity API: https://github.com/Azure/azure-sdk-for-net/pull/3149 #3154

2017-06-07 22:15 UTC, shahabhijeet requested changes

2017-06-07 22:15 UTC, shahabhijeet commented on src/SDKs/Network/Network.Tests/Tests/CheckConnectivityTests.cs
> +using Microsoft.Azure.Management.Resources;
@irrogozh please use the latest Resource manager nuget package >=1.6.0 to record your tests

2017-06-07 23:47 UTC, irrogozh commented on src/SDKs/Network/Network.Tests/Tests/CheckConnectivityTests.cs
> +using Microsoft.Azure.Management.Resources;
Abhijeet, I looked into Nuget gallery. https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager/1.6.0-preview It seems like this version is the latest one...

2017-06-08 17:45 UTC, irrogozh commented on src/SDKs/Network/Network.Tests/Tests/CheckConnectivityTests.cs
> +using Microsoft.Azure.Management.Resources;
And I use this version already. Here is reference from Network.Tests.csproj
    <PackageReference Include="Microsoft.Azure.Management.ResourceManager" Version="1.6.0-preview" />

2017-06-08 17:57 UTC, shahabhijeet requested changes

2017-06-08 17:57 UTC, shahabhijeet commented on src/SDKs/Network/Network.Tests/Tests/CheckConnectivityTests.cs
> +using Microsoft.Azure.Management.Resources;
@irrogozh yes you have the right references, but you need to create a ResourceManagment Client using the new nuget and you are still using the old client and recorded your test using the old client.

2017-06-08 22:15 UTC, shahabhijeet approved these changes

2017-06-08 22:15 UTC, merged