[ACS][CallAutomatoin] Easily Handling EventHandler
Azure/azure-sdk-for-net pull request #33307
Opened 2023-01-05 05:53 UTC by minwoolee-msft

2023-01-05 06:11 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.Communication.CallAutomation](https://apiview.dev/Assemblies/Review/616d083d0b1340f2a713115b478c3ebf)

2023-01-06 23:49 UTC, DominikMe commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/EventAwaiterOngoing.cs
> +        internal Action<object, CallAutomationEventArgs> OnEventRecieved => OnEventsReceived;
typo:
```suggestion
        internal Action<object, CallAutomationEventArgs> OnEventReceived => OnEventsReceived;
```
(and update references)

2023-01-06 23:51 UTC, DominikMe commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/CallAutomationEventHandler.cs
> +            CallAutomationEventBase recievedEvent = events.FirstOrDefault();
typo
```suggestion
            CallAutomationEventBase receivedEvent = events.FirstOrDefault();
```

2023-01-10 14:13 UTC, petrsvihlik requested changes

2023-01-10 14:13 UTC, petrsvihlik commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/EventBacklog.cs
> +        internal bool GetAndRemoveEvent(IEnumerable<Type> eventTypes, string callConnectionId, string operationContext, out KeyValuePair<string, CallAutomationEventBase> matchingEvent)
This is a typical example for Try Pattern. The method should be prefixed with `Try`

2023-01-10 14:13 UTC, petrsvihlik commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/EventBacklog.cs
> +        internal bool AddEvent(string backlogEventId, CallAutomationEventBase eventsToBeSaved)
This is a typical example for Try Pattern. The method should be prefixed with `Try`

2023-01-10 14:13 UTC, petrsvihlik commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/EventBacklog.cs
> +        internal bool RemoveEvent(string internalEventId) => _eventBacklog.TryRemove(internalEventId, out _);
TryRemoveEvent

2023-01-14 00:53 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/CallAutomationEventHandler.cs
> +            CallAutomationEventBase receivedEvent = events.FirstOrDefault();
The reason is that events received will always be (as of now) single event.
I think when I was doing development, I assumed there will be no changes that will register more than 1 (as that is the case right now)
I can update this to work with multiple events passed, for future proof.

2023-01-14 00:55 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/CallAutomationEventArgs.cs
> +        internal CallAutomationEventBase callAutomationEvent { get; set; }
Thanks - Will Update.

2023-01-14 00:56 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/EventAwaiter.cs
> +        }
Thank you - will read and follow the guideline's suggestion.

2023-01-17 07:37 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/CallAutomationEventHandler.cs
> +    public class CallAutomationEventHandler
Updated to EventProcessor

2023-01-17 07:37 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/CallAutomationEventHandler.cs
> +            => await WaitForEvent(new List<Type> { typeof(T1), typeof(T2), typeof(T3), typeof(T4), typeof(T5) }, callConnectionId, operationContext).ConfigureAwait(false);
Added a lot more testing for each cases

2023-01-17 07:43 UTC, petrsvihlik commented on sdk/communication/Azure.Communication.CallAutomation/src/EventHandler/CallAutomationEventHandler.cs
> +            CallAutomationEventBase receivedEvent = events.FirstOrDefault();
thanks for explaining!

>I can update this to work with multiple events passed, for future proof.

either that or at least leave a comment for future generations reading the code :) it's not intuitive at the first glance.

2023-01-19 16:32 UTC, petrsvihlik reviewed
mostly nits

2023-01-19 16:32 UTC, petrsvihlik commented on sdk/communication/Azure.Communication.CallAutomation/src/EventProcessor/EventProcessor.cs
> +        public async Task<CallAutomationEventBase> WaitForEvent(Func<CallAutomationEventBase, bool> predicate, TimeSpan eventTimeout = default)
do we want/need to expose it publicly? are we expecting customers to come up with more complex/granular predicates than those defined by us?

if so, maybe it'd make sense to distinguish the method even further from Attach/Detach methods by naming it `WaitForSingleEvent`. 

and/or provide some overload(s) for common operations... like `WaitForSingleEvent<TEvent>(string connectionId = null, string operationContext = null, Func<CallAutomationEventBase, bool> predicate = null)`

2023-01-19 19:45 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventProcessor/EventResult/StartRecognizingEventResult.cs
> +    /// <summary> StartRecognizingEventResult is returned from WaitForEvent of StartRecognizingResult. </summary>
Thanks - will update all of them.

2023-01-19 20:06 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventProcessor/EventAwaiter.cs
> +                // dispose expiring timer, as we don't want timer activating.
Yep - will go through the items

2023-01-19 21:15 UTC, minwoolee-msft commented on sdk/communication/Azure.Communication.CallAutomation/src/EventProcessor/EventProcessor.cs
> +        public async Task<CallAutomationEventBase> WaitForEvent(Func<CallAutomationEventBase, bool> predicate, TimeSpan eventTimeout = default)
Thank you for the suggestion - I agree that waiting for single event with old way of doing things (with generic event <TEvent>) is very easy to use, and I can see this is 90% of the time how devs would use it. I will have them added as overload.

2023-01-20 12:30 UTC, petrsvihlik approved these changes

2023-01-20 16:21 UTC, merged