Swagger SDK for HDInsight
Azure/azure-sdk-for-net pull request #3374
Opened 2017-06-15 02:27 UTC by shefaliv

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-15 06:24 UTC, shahabhijeet requested changes

2017-06-15 06:24 UTC, shahabhijeet commented on src/SDKs/HDInsight/Management.HDInsight/Management.HDInsight.csproj
> +    <TargetFramework>netcoreapp1.1</TargetFramework>
@shefaliv the only supported target frameworks are net452 and netstandard1.4.
We do not support .NET Core as of now.

2017-06-15 06:25 UTC, shahabhijeet commented on src/SDKs/HDInsight/Management.HDInsight/Management.HDInsight.csproj
> +    <TargetFramework>netcoreapp1.1</TargetFramework>
@shefaliv please add link to the corresponding swagger PR

2017-06-15 17:51 UTC, shefaliv commented on src/SDKs/HDInsight/Management.HDInsight/Management.HDInsight.csproj
> +    <TargetFramework>netcoreapp1.1</TargetFramework>
ah okay. I thought this is what the documentation said to do. Let me fix it!

2017-06-15 17:57 UTC, shefaliv commented
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/1312

2017-06-26 20:44 UTC, shahabhijeet requested changes
Need test coverage before we can accept this PR.
Please use the latest nugets (including latest resource manager) to record all your tests.

2017-06-26 20:45 UTC, shahabhijeet commented
@shefaliv add "needs-review" when you have addressed the PR.

2017-06-30 00:16 UTC, shahabhijeet commented
@shefaliv please either reopen this PR or create a new one, once you are ready to merge your new SDK.

2017-06-30 00:16 UTC, closed without merging