Add server communication links and geo backup policy client, tests, recordings
Azure/azure-sdk-for-net pull request #3375
Opened 2017-06-15 20:45 UTC by nathannfan

Add server communication link and geo backup policy clients, scenario tests in new files for both, and session records.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-15 21:46 UTC, jaredmoo commented
Swagger change is https://github.com/Azure/azure-rest-api-specs/pull/1302

2017-06-15 21:54 UTC, jaredmoo requested changes
Minor comments. Mostly looks great.

2017-06-15 21:54 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/ServerCommunicationLinkScenarioTests.cs
> +                var server1 = sqlClient.Servers.CreateOrUpdate(resourceGroup.Name, server1Name, new Server()
nit: can you use SqlManagementTestUtils.CreateServer instead?

2017-06-15 21:54 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/ServerCommunicationLinkScenarioTests.cs
> +                var server1 = sqlClient.Servers.CreateOrUpdate(resourceGroup.Name, server1Name, new Server()
this will require either re-recording or just manually fix the Names section at the bottom of recording file.

2017-06-15 21:54 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/ServerCommunicationLinkScenarioTests.cs
> +            SqlManagementTestUtilities.RunTestInNewResourceGroup(suiteName, "TestCreateUpdateGetDropServer", testPrefix, (resClient, sqlClient, resourceGroup) =>
can you rename `TestCreateUpdateGetDropServer`

2017-06-16 04:21 UTC, jaredmoo commented
To make priorities clear, https://github.com/Azure/azure-sdk-for-net/pull/3377 is higher priority than this. I could combine these 2 reviews, but I don't want any risk of slowing down #3377.

2017-06-16 23:37 UTC, jaredmoo commented
I bumped the version from 1.5.0-preview to 1.7.0-preview because #3377 will be 1.6.0-preview.

2017-06-20 06:18 UTC, jaredmoo approved these changes

2017-06-22 00:56 UTC, shahabhijeet requested changes
@nathannfan how many nugets will be published?
Are you publishing 1.6.0 and 1.7.0?
Why these changes cannot be co-ordinated?

2017-06-22 01:01 UTC, jaredmoo commented
Changed version to 1.6.0-preview with commit b7cd391

2017-06-22 01:10 UTC, shahabhijeet approved these changes

2017-06-22 01:10 UTC, merged