Regenerated SDK basing on specs updates; Added tests
Azure/azure-sdk-for-net pull request #3378
Opened 2017-06-16 13:06 UTC by EvgenyAgafonchikov

## Description

---
PR: https://github.com/Azure/azure-rest-api-specs/pull/1276

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-16 13:06 UTC, msftclas commented
@EvgenyAgafonchikov,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-21 21:34 UTC, DeepakRajendranMsft approved these changes
looks like we are using a new version of auto rest code gen which is changing almost all files

2017-06-21 21:34 UTC, DeepakRajendranMsft commented
@cormacpayne  please review this. we need these for PS changes

2017-06-22 19:07 UTC, shahabhijeet requested changes
All new tests should be recorded using latest nugets packages (e.g. resource manager, storage etc)
Definitely newer resource manager >=1.6.0

2017-06-23 11:37 UTC, EvgenyAgafonchikov commented
updated packages, re-recorded tests. @shahabhijeet please have another look

2017-06-23 19:16 UTC, shahabhijeet commented
@EvgenyAgafonchikov can you point me out the file that actually uses the new ResourceManagementClient?

2017-06-23 19:55 UTC, shahabhijeet approved these changes

2017-06-23 19:55 UTC, shahabhijeet commented on src/SDKs/Network/Network.Tests/Network.Tests.csproj
> +  <ItemGroup>
@EvgenyAgafonchikov you do not need this, it adds warning as your test project implicitly reference these, else no tests would have run on the first place.
Remove these redundant entries

2017-06-23 19:56 UTC, shahabhijeet requested changes

2017-06-23 19:56 UTC, shahabhijeet commented on src/SDKs/Network/Network.Tests/Network.Tests.csproj
> +  <ItemGroup>
@EvgenyAgafonchikov please remove these redundant entries

2017-06-26 18:47 UTC, shahabhijeet approved these changes

2017-06-26 18:48 UTC, merged