use new endpoint to read SKUs during validation and updates for backu…
Azure/azure-sdk-for-net pull request #3393
Opened 2017-06-21 08:23 UTC by yuchouMS

…p container uri

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above. https://github.com/Azure/azure-rest-api-specs/pull/1334
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-21 08:23 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-06-21 08:23 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-06-21 08:23 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-06-21 08:23 UTC, msftclas commented
@__yuchouMS__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-06-21 08:28 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-06-21 10:05 UTC, yuchouMS commented
PR for backup container uri swagger spec changes: https://github.com/Azure/azure-rest-api-specs/pull/1326

2017-06-21 23:54 UTC, hovsepm commented
@azuresdkci test this please

2017-06-22 00:34 UTC, msftclas commented
__@yuchouMS__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, Microsoft Pull Request Bot_

2017-06-22 22:24 UTC, yuchouMS commented
@hovsepm could you help review the pr? thanks

2017-06-23 19:26 UTC, shahabhijeet commented
@yuchouMS could you sign the CLA. https://cla.microsoft.com.
If you are MS employee, please connect your id with GitHub id at this location
https://opensource.microsoft.com/link

2017-06-23 21:46 UTC, yuchouMS commented
@shahabhijeet I've already connected my id with Github long time ago. but when I click the URL it shows: "opensource.microsoft.com is currently unable to handle this request. HTTP ERROR 500." something wrong with the website?

2017-06-26 21:24 UTC, shahabhijeet requested changes

2017-06-26 21:24 UTC, shahabhijeet commented on src/SDKs/AnalysisServices/Management.Analysis/Generated/Models/SkuEnumerationForNewResourceResult.cs
> +// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
@yuchouMS please use latest autoRest to generate your SDK.

2017-06-26 21:29 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-06-27 01:18 UTC, yuchouMS commented on src/SDKs/AnalysisServices/Management.Analysis/Generated/Models/SkuEnumerationForNewResourceResult.cs
> +// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
@shahabhijeet fixed, please take another look. thanks

2017-06-27 23:34 UTC, yuchouMS commented
@shahabhijeet please help review when you have time, thanks

2017-06-28 21:45 UTC, shahabhijeet commented
@yuchouMS you will need major version bump for your nuget as well as AssemblyFileVersion/AssemblyVersion bump.

2017-06-29 23:14 UTC, yuchouMS commented
@shahabhijeet fixed, please help review. thanks

2017-06-29 23:33 UTC, shahabhijeet approved these changes

2017-06-29 23:33 UTC, merged