StorSimple 8000 series ARM API dotnet client SDK - generated code and testcases.
Azure/azure-sdk-for-net pull request #3404
Opened 2017-06-22 19:54 UTC by manaas-microsoft

… Series ARM APIs.

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-22 19:54 UTC, msftclas commented
@manaas-microsoft,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-22 21:06 UTC, shahabhijeet requested changes
Please record all your tests using latest nugets that includes Resource Manager >=1.6.0

2017-06-22 21:06 UTC, shahabhijeet commented on src/SDKs/StorSimple8000Series/StorSimple8000Series.Tests/StorSimple8000Series.Tests.csproj
> +    <PackageReference Include="xunit" Version="2.2.0" />
@manaas-microsoft can you remove *.Test.Sdk, ClientRuntime.Azure, *.TestFramewok, and all xunit package references.
And add <Import Project="$([MSBuild]::GetPathOfFileAbove('AzSdk.test.reference.props'))" /> as one of the imports on line 2
You can model your test project looking at other test projects in the repo.

2017-06-23 16:25 UTC, manaas-microsoft commented on src/SDKs/StorSimple8000Series/StorSimple8000Series.Tests/StorSimple8000Series.Tests.csproj
> +    <PackageReference Include="xunit" Version="2.2.0" />
@shahabhijeet Hi, I replaced the individual package reference by the line to import "AzSdk.test.reference.props". Also, I added some other fields common across other SDKs test projects .csproj.  Still getting the same build failure. Any suggestions?

Also, for Resource Manager, I see the current version is 1.1.0-perview in above imported file. (similar version in other SDKs also) 
<PackageReference Include="Microsoft.Azure.ResourceManager" Version="[1.1.0-preview]" />
Do I still need to change it?

2017-06-24 00:00 UTC, shahabhijeet approved these changes

2017-06-24 00:00 UTC, merged