New RP version for EventHub
Azure/azure-sdk-for-net pull request #3421
Opened 2017-06-27 16:42 UTC by v-Ajnava

regenerating SDK for the new swagger for RP version 2017-04-01 
New RP version swagger: https://github.com/Azure/azure-rest-api-specs/pull/1305
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [X] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-06-28 05:37 UTC, shahabhijeet approved these changes

2017-06-28 05:37 UTC, shahabhijeet commented on src/SDKs/EventHub/Management.EventHub/Microsoft.Azure.Management.EventHub.csproj
> +    <Version>2.0.0</Version>
@v-Ajnava let's stick with <VersionPrefix> for now.

2017-06-28 05:38 UTC, shahabhijeet requested changes
let's stick with versionPrefix> for now.

2017-06-28 23:35 UTC, shahabhijeet requested changes

2017-06-28 23:35 UTC, shahabhijeet commented on src/SDKs/EventHub/Management.EventHub/Properties/AssemblyInfo.cs
>  [assembly: AssemblyVersion("1.0.0.0")]
@v-Ajnava also AssemblyVersion needs to be bumped

2017-06-29 18:58 UTC, v-Ajnava commented on src/SDKs/EventHub/Management.EventHub/Properties/AssemblyInfo.cs
>  [assembly: AssemblyVersion("1.0.0.0")]
Done

2017-06-29 23:36 UTC, shahabhijeet approved these changes

2017-06-29 23:36 UTC, merged