New RP version for Relay
Azure/azure-sdk-for-net pull request #3455
Opened 2017-07-06 20:01 UTC by v-Ajnava

regenerating SDK for the new swagger for RP version 2017-04-01
New RP version swagger:
https://github.com/Azure/azure-rest-api-specs/pull/1306

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [X] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-07-10 22:28 UTC, shahabhijeet requested changes

2017-07-10 22:28 UTC, shahabhijeet commented on src/SDKs/Relay/Management.Relay/Generated/Models/AccessKeys.cs
> +    public partial class AccessKeys
@v-Ajnava will this change have any impact on PowerShell due to change in type?
Please plan accordingly, you cannot introduce breaking changes in PS

2017-07-10 22:28 UTC, shahabhijeet commented on src/SDKs/Relay/Management.Relay/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.1.0.0")]
@v-Ajnava breaking change will need major version bump

2017-07-12 01:52 UTC, v-Ajnava commented on src/SDKs/Relay/Management.Relay/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.1.0.0")]
version bump up.

2017-07-12 01:52 UTC, v-Ajnava commented on src/SDKs/Relay/Management.Relay/Generated/Models/AccessKeys.cs
> +    public partial class AccessKeys
no, it will not have impact on PowerShell.

2017-07-13 16:52 UTC, shahabhijeet requested changes

2017-07-13 16:52 UTC, shahabhijeet commented on src/SDKs/Relay/Management.Relay/Microsoft.Azure.Management.Relay.csproj
> +    <VersionPrefix>1.0.0</VersionPrefix>
@v-Ajnava why nuget is 1.0, but Assembly version is 2.0?

2017-07-13 18:00 UTC, v-Ajnava commented on src/SDKs/Relay/Management.Relay/Microsoft.Azure.Management.Relay.csproj
> +    <VersionPrefix>1.0.0</VersionPrefix>
My bad, corrected it to 2.0.0

2017-07-17 18:08 UTC, shahabhijeet approved these changes

2017-07-17 18:08 UTC, merged