[Do Not Merge Yet] Update for Multi CA, Accelerated Networking and runCommands.
Azure/azure-sdk-for-net pull request #3461
Opened 2017-07-07 18:32 UTC by hyonholee

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-07-10 22:32 UTC, shahabhijeet commented
@hyonholee please add needs-review once you are ready for merge.

2017-07-13 16:56 UTC, shahabhijeet requested changes

2017-07-13 16:56 UTC, shahabhijeet commented on src/SDKs/Compute/Management.Compute/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("16.0.0.0")]
@hyonholee just curious, why AssemblyVersion and nuget version differed earlier (nuget version being 15, but AssemblyVersion 16)
And now why update from 16.0 to 16.2? why skip 16.1?

2017-07-13 21:53 UTC, hyonholee commented on src/SDKs/Compute/Management.Compute/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("16.0.0.0")]
@shahabhijeet   It should be 16.1.   I updated this PR.  I don't know why the AssemblyVersion was not updated last time.  It looks like a mistake last time.

2017-07-17 19:16 UTC, shahabhijeet approved these changes

2017-07-17 19:17 UTC, merged

2017-08-28 08:24 UTC, saguiitay commented
Any update on when this will be released? I need to be able to read/set the AcceleratedNetwork property..