apimanagement - 2022-08-01 - track1 sdk
Azure/azure-sdk-for-net pull request #34639
Opened 2023-03-01 19:35 UTC by solankisamir

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-03-03 13:50 UTC, ArthurMa1978 requested changes
Please fix the tests

2023-07-22 16:11 UTC, solankisamir commented
/azp run

2023-07-24 18:29 UTC, solankisamir commented
@ArthurMa1978 I am stuck with the failure in the pipeline. Can you help?

2023-07-27 05:50 UTC, ArthurMa1978 approved these changes

2023-07-27 05:50 UTC, merged