Update property should not be read only
Azure/azure-sdk-for-net pull request #3472
Opened 2017-07-11 00:30 UTC by dihan0604

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-07-11 00:43 UTC, shahabhijeet requested changes

2017-07-11 00:43 UTC, shahabhijeet commented on src/SDKs/Network/Management.Network/Generated/Models/PatchRouteFilter.cs
> +        public IList<ExpressRouteCircuitPeering> Peerings { get; set; }
@dihan0604 can you provide me the swagger spec for this change?

2017-07-11 00:46 UTC, shahabhijeet requested changes

2017-07-11 00:46 UTC, shahabhijeet commented on src/SDKs/Network/Management.Network/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("11.1.1.0")]
@dihan0604 AssemblyVersion number should change when you change the major version.
Usually you don't need to update assembly version everytime you change minor, revision number

2017-07-11 00:57 UTC, dihan0604 commented
swagger changes: https://github.com/Azure/azure-rest-api-specs/pull/1406

2017-07-11 20:13 UTC, shahabhijeet requested changes
@dihan0604 this PR needs to be generated using the commit Id that you get when your swagger spec PR is merged.

2017-07-12 18:04 UTC, dihan0604 commented
swagger merged : https://github.com/Azure/azure-rest-api-specs/commit/dc20a2cdf8ae368407fe897552b7f3620972f61a

2017-07-12 21:24 UTC, shahabhijeet requested changes

2017-07-12 21:24 UTC, shahabhijeet commented on src/SDKs/Network/Management.Network/Microsoft.Azure.Management.Network.csproj
> +    <VersionPrefix>11.0.0-preview</VersionPrefix>
@dihan0604 I just now noticed, why version is mentioned twice and that also separate version number?
Also as this is changing the public surface area, your major version should increase.

2017-07-13 17:02 UTC, shahabhijeet commented
@dihan0604 can you also sync with this PR, so that the versions do not conflict
https://github.com/Azure/azure-sdk-for-net/pull/3473

2017-07-18 00:25 UTC, shahabhijeet approved these changes

2017-07-18 00:25 UTC, merged