Do hydra to swagger specs migration for azure-sdk-for-net
Azure/azure-sdk-for-net pull request #3482
Opened 2017-07-12 10:51 UTC by Monicalyy

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-07-12 10:51 UTC, msftclas commented
@Monicalyy,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-07-13 17:06 UTC, shahabhijeet commented
@Monicalyy can you provide swagger spec PR link.

2017-07-14 00:20 UTC, darshanhs90 commented
can you update https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Authorization/Management.Authorization/Properties/AssemblyInfo.cs with the new version of 2.6.0

2017-07-17 08:04 UTC, Monicalyy commented
@shahabhijeet  Because we compared Hydra and swagger files and found out that we don't need to modify the swagger Json. So we don't have any PR about Swagger.
 About generate.cmd, It seems like we don't need to update the specFile, Maybe we need to update the autoRestVersion to the latest version (1.2.0-Nightly20170714) right?

2017-07-17 21:56 UTC, shahabhijeet commented
@Monicalyy what I am clear is:
1) why are generating? as I see you are increasing the version number
2) If you are regenerating, where is the update for the swagger spec?
That is the reason I am asking if you can provide what commit of swagger spec are you generating for?

Also provide a detailed description as to what is the reason for this PR.

2017-07-18 09:14 UTC, Monicalyy commented
@shahabhijeet 
Because we received a task to generating Swagger specs from Hydra specs for authorization. 
Document says the spec might already be generated, just validate it covers all the API and filters. So After compared Hydra and swagger, We found we don't need to modify the swagger spec. But After generated the swagger specs there has some changes for Authorization project. So we did the test for the changes and created this pull request.
Maybe I did an unintelligible description, So if you have more question, could you contact Haridarshan Hosakere Sudhakar <hahosake@microsoft.com> online?

2017-07-18 19:10 UTC, darshanhs90 commented
@shahabhijeet Maybe there was some confusion regarding updating the assembly file version.
we were under the impression that we need to update the version for every change done to the sdk and publish[rather it be from swagger specs or sdk repo alone]
Since this PR doesnt involve changes to the swagger specs,looks like we dont need to update the version.
Hope that clarifies your queries.

2017-07-19 18:09 UTC, shahabhijeet requested changes
@Monicalyy once the minor update is made, this PR is ready to be merged.

2017-07-19 18:09 UTC, shahabhijeet commented on src/SDKs/Authorization/Authorization.Tests/Authorization.Tests.csproj
> +    <None Update="SessionRecords\Authorization.Tests.BasicTests\ProviderOperationsMetadataListGetTests.json">
@Monicalyy please replace all these lines with something like below.
This helps in maintaining project files concise.
< ItemGroup>
    < None Update="SessionRecords \ ** \ *.json">
      < CopyToOutputDirectory>PreserveNewest< /CopyToOutputDirectory>
    < /None>
< /ItemGroup>

2017-07-20 09:55 UTC, Monicalyy commented on src/SDKs/Authorization/Authorization.Tests/Authorization.Tests.csproj
> +    <None Update="SessionRecords\Authorization.Tests.BasicTests\ProviderOperationsMetadataListGetTests.json">
@shahabhijeet  I have finished the change. Please review.

2017-07-20 18:23 UTC, darshanhs90 commented
:shipit:

2017-07-20 20:31 UTC, shahabhijeet commented
@azuresdkci  test this please

2017-07-20 21:44 UTC, darshanhs90 commented on src/SDKs/Authorization/Authorization.Tests/Tests/BasicTests.cs
> +                Assert.NotNull(providerOperationsMetadata.Type);
can you add a negative test for this get method?

2017-07-20 23:33 UTC, shahabhijeet commented
@darshanhs90 can you use the code review tool to request for change. This way it shows red cross next to your name. Once you approve only then I will merge.

2017-07-24 23:07 UTC, darshanhs90 commented
@Monicalyy could you update the tests,so that we can finish this PR

2017-07-27 16:14 UTC, shahabhijeet commented
@azuresdkci test this please

2017-07-27 16:19 UTC, shahabhijeet commented
once the CI passes this is good to merge

2017-07-27 16:33 UTC, shahabhijeet commented
@azuresdkci test this please

2017-07-27 17:06 UTC, shahabhijeet commented
@Monicalyy Authorization tests have failed.
I had disabled all Authorization tests so far, so today I enabled them back and they started failing.

2017-07-27 19:04 UTC, darshanhs90 commented
@shahabhijeet The tests are passing in both record and playback mode on our local system.
It is failing with the following issue,**Subscription Id is not present in the recorded mock**
even though it is part of the recorded mock.

2017-07-27 21:23 UTC, shahabhijeet commented
@azuresdkci test this please

2017-07-27 22:10 UTC, shahabhijeet approved these changes

2017-07-27 22:10 UTC, merged