Storage update
Azure/azure-sdk-for-net pull request #3491
Opened 2017-07-14 20:48 UTC by anuchandy

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-07-14 20:48 UTC, msftclas commented
@anuchandy,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-07-14 21:05 UTC, anuchandy commented
1. Fluent storage was completely handwritten. This PR contains regenerated interfaces and implementation.
2. Adding support for encryption.
3. Adding more test cases.

2017-07-31 17:44 UTC, hovsepm requested changes

2017-07-31 17:44 UTC, hovsepm commented on src/ResourceManagement/Storage/StorageAccountImpl.cs
> +            return GetKeysAsync().ConfigureAwait(false).GetAwaiter().GetResult();
Please change all ".ConfigureAwait(false).GetAwaiter().GetResult();" to Extensions.Synchronize(() => <your ASYNC method call>)

2017-07-31 17:44 UTC, hovsepm commented on src/ResourceManagement/Storage/StorageAccountImpl.cs
> +            return RegenerateKeyAsync(keyName).ConfigureAwait(false).GetAwaiter().GetResult();
here as well use  Extensions.Synchronize(()  instead of GetAwaiter.

2017-07-31 17:49 UTC, anuchandy commented on src/ResourceManagement/Storage/StorageAccountImpl.cs
> +            return GetKeysAsync().ConfigureAwait(false).GetAwaiter().GetResult();
good catch,thanks!

2017-08-01 17:59 UTC, hovsepm approved these changes

2017-08-01 17:59 UTC, merged