[ClientRuntime] Fixed polymorphic deserialization in case of multi-level inheritance (WIP)
Azure/azure-sdk-for-net pull request #3503
Opened 2017-07-21 21:20 UTC by olydis

## Description
Polymorphic deserialization has broken cases. Consider the following scenario:
``` C#
class A {}
class B : A {}
class C : B {}
```

An API method returning an `A` will call `JsonConvert.DeserializeObject<A>(...response body...)`. The `PolymorphicDeserializeJsonConverter` we have will *successfully* deserialize objects of dynamic type `A`, `B` and `C` using the discriminator.
Now, there may be another API method returning `B`. AutoRest will (reasonably) emit `JsonConvert.DeserializeObject<B>(...response body...)`. Note that the service may return an object of dynamic type `B` or `C`. However, `PolymorphicDeserializeJsonConverter` will not be aware that it *still applies* so we will always deserialize into `B`!

In a nutshell:
Current behavior: `PolymorphicDeserializeJsonConverter` only works correctly for `JsonConvert.DeserializeObject<T>` where `T` is the root type (that the `discriminator` was declared on)
Expected behavior: `PolymorphicDeserializeJsonConverter` works correctly for `JsonConvert.DeserializeObject<T>` where `T : <root type>`, i.e. `T` is any type in the inheritance hierarchy.

Note that this problem is only exposed for hierarchies of depth at least 2 since otherwise you are dealing with either the root type (which the converter works fine for) or a leaf type (which works fine natively).

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

2017-07-21 23:05 UTC, fearthecowboy approved these changes

2017-07-27 18:17 UTC, olydis commented
@shahabhijeet any clue why CI no longer terminates? My change is one line, could it be the fact that I'm using reflection?

2017-07-27 20:55 UTC, shahabhijeet commented
@olydis looking at the logs it is not clear at all as to why the test process was terminated.

2017-07-27 21:03 UTC, shahabhijeet requested changes

2017-07-27 21:03 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime.Tests/PolymorphicJsonConverterTests.cs
> +        private static void AssertRoundTrips<T>(T instance) where T : Model
@olydis do we have any negative tests, where it fails to convert if we reverse the order of inheritance hierarchy? If not we should add those.

2017-07-27 21:03 UTC, olydis commented
@shahabhijeet well, it says timeout, but I don't get how my test times out on both Linux and Windows... will try to repro locally, but it definitely ran through on my machine before 😞

2017-07-27 21:04 UTC, olydis commented on src/SdkCommon/ClientRuntime/ClientRuntime.Tests/PolymorphicJsonConverterTests.cs
> +        private static void AssertRoundTrips<T>(T instance) where T : Model
will add

2017-07-28 17:05 UTC, olydis commented
@shahabhijeet investigating the non-termination I exposed an even more fundamental issue... my fix will have to be more sophisticated 😉

2017-07-28 22:51 UTC, olydis commented
@markcowl @shahabhijeet Note that I had to essentially rewrite the deserializer from scratch, it was *very fundamentally* broken, I'll gladly share details.

In short: Calling `ToObject` reevaluates JSON converters. We called that from inside a JSON converter. That quickly leads to infinite recursion and an SO unless you "trick around" a bit to prevent recusrsion.
Trick 1: `CanConvert` only returns true if the type asked for is the root of the hierarchy. After one iteration of the converter, the type will be more narrow. => termination since `CanConvert` now returns false (but this causes issue 1)
Trick 2: If the discriminator actually points to the root type of the hierarchy, the object is deserialized without further application of *any* converters to the entire object tree. => termination since... no more converters (but this causes issue 2)

My current approach explicitly traverses down into the properties before calling out to Newtonsoft.JSON again.

2017-08-09 17:13 UTC, olydis commented
@shahabhijeet Tests pass now! All I did was rebase onto your most recent changes in `psSdkJson6` and it worked out of the box. I haven't committed my version bumps, that may simplify combining our changes for the 2.4.0 release.

2017-08-24 17:03 UTC, shahabhijeet approved these changes

2017-08-24 22:07 UTC, merged