Update code owners for translation
Azure/azure-sdk-for-net pull request #35106
Opened 2023-03-23 18:01 UTC by pallavit

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-03-23 18:28 UTC, jsquire requested changes

2023-03-23 18:28 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/translation/                                                  @mikeymcz, @cpoulain, @joseharriaga
The commas aren't valid here, just space-delimited.

2023-03-27 17:32 UTC, jsquire approved these changes

2023-03-27 17:33 UTC, pallavit commented
/check-enforcer override

2023-03-27 17:36 UTC, joseharriaga approved these changes

2023-03-28 16:33 UTC, merged