first version of C# apim spec on autorest
Azure/azure-sdk-for-net pull request #3544
Opened 2017-08-03 01:41 UTC by solankisamir

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-03 01:41 UTC, msftclas commented
@solankisamir,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-04 01:13 UTC, shahabhijeet requested changes
@solankisamir can you provide link to the Swagger PR that was merged.

2017-08-04 01:13 UTC, shahabhijeet commented on src/SDKs/ApiManagement/ApiManagement.Tests/Helpers/Extensions.cs
> +        public static bool DictionaryEqual<TKey, TValue>(this IDictionary<TKey, TValue> first, IDictionary<TKey, TValue> second)
@solankisamir 
nit: Can you not use Linq extension methods first.Except<String>(second) or better use Linq to do the comparison.
I assume you only want to compare keys and not their values, in that case you can still do that using the above

2017-08-04 01:13 UTC, shahabhijeet commented on src/SDKs/ApiManagement/Management.ApiManagement/Microsoft.Azure.Management.ApiManagement.csproj
> +    <Folder Include="Customization\Models\" />
@solankisamir you don't need to include any folders. Project system will include it. This is not needed

2017-08-06 18:14 UTC, solankisamir commented on src/SDKs/ApiManagement/ApiManagement.Tests/ApiManagement.Tests.csproj
> +    <VersionPrefix>1.0.0-preview</VersionPrefix>
#fixed

2017-08-06 18:17 UTC, solankisamir commented on src/SDKs/ApiManagement/ApiManagement.Tests/ApiManagement.Tests.csproj
> +    <None Update="Resources\SwaggerPetStoreV2.json">
#fixed

2017-08-06 18:19 UTC, solankisamir commented on src/SDKs/ApiManagement/ApiManagement.Tests/ApiManagementTestBase.cs
> +                this.testCertificatePassword = testEnv.ConnectionString.KeyValuePairs.GetValueUsingCaseInsensitiveKey(TestCertificatePasswordKey);
#fixed

2017-08-06 18:33 UTC, solankisamir commented on src/SDKs/ApiManagement/ApiManagement.Tests/ApiManagementTestBase.cs
> +                this.tenantId = testEnv.Tenant;
remove some extra variables. I require some initialization during playback, as some of the tests can only be executed on an active service. Service Activation takes 40 minutes, hence use this as a place to provide active service details, and proceed with additional validation.

2017-08-06 18:38 UTC, solankisamir commented on src/SDKs/ApiManagement/Management.ApiManagement/Microsoft.Azure.Management.ApiManagement.csproj
> +    <Folder Include="Customization\Models\" />
#fixed

2017-08-07 18:34 UTC, shahabhijeet commented
@solankisamir as long as Kedar or someone from your team approves, this is good to merge

2017-08-07 21:21 UTC, solankisamir commented
@shahabhijeet can you take a look?

2017-08-08 13:17 UTC, shahabhijeet commented
@azuresdkci test this please

2017-08-09 18:47 UTC, KedarJoshi commented
#sign-off

2017-08-10 18:16 UTC, merged