Management.Sql - Generated SQL DataSync and added test scenario's
Azure/azure-sdk-for-net pull request #3558
Opened 2017-08-08 04:40 UTC by ScottHolden

## Description
Generated Management.Sql with package-2015-05-preview api spec including datasync, added SyncAgent SyncGroup SyncMember scenario's with session records.

Corresponding rest-api-spec change can be found at:
https://github.com/Azure/azure-rest-api-specs/pull/1510

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [X] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-08 04:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-08-08 04:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-08-08 04:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-08-08 04:40 UTC, msftclas commented
@__ScottHolden__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-08-08 04:43 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-08-08 04:53 UTC, msftclas commented
__@ScottHolden__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, Microsoft Pull Request Bot_

2017-08-08 04:53 UTC, ScottHolden commented
I have signed the cla :)

2017-08-08 13:14 UTC, shahabhijeet commented
@ScottHolden are you part of the Azure org, if not please become a part of the Azure Team by visiting
https://github.com/Azure/

2017-08-08 16:22 UTC, jaredmoo commented
@fhljys ,@ferno-ms , @nathannfan fyi

2017-08-08 16:30 UTC, jaredmoo requested changes
Looks excellent, just some minor changes requested. Thank you!

2017-08-08 16:30 UTC, jaredmoo commented on src/SDKs/SqlManagement/Management.Sql/Microsoft.Azure.Management.Sql.csproj
> +    <VersionPrefix>1.8.0-preview</VersionPrefix>
the latest published version is 1.6.0 (see https://www.nuget.org/packages/Microsoft.Azure.Management.Sql ) so please undo this

2017-08-08 16:30 UTC, jaredmoo commented on src/SDKs/SqlManagement/Management.Sql/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.8.0.0")]
please undo

2017-08-08 16:30 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/SyncMemberScenarioTests.cs
> +                Assert.NotEqual(syncMemberDirection, updateSyncMemberDirection);
can you also test empty update, e.g.

```
// Empty update of sync member
SyncMember updateSyncMember2 = sqlClient.SyncMembers.Update(resourceGroup.Name, server.Name, testDatabaseName, syncGroupName, syncMemberName, new SyncMember());
```

2017-08-08 16:30 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/SyncMemberScenarioTests.cs
> +                Assert.Equal(syncMemberName, listSyncMembers.FirstOrDefault()?.Name);
nit: already checked that there is one, so this can be `listSyncMembers.Single().Name`

2017-08-08 16:30 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/SyncGroupScenarioTests.cs
> +                Assert.Equal(interval2, updateSyncGroup.Interval);
Can you please test empty update, i..e.

```
SyncGroup updateSyncGroup = sqlClient.SyncGroups.Update(resourceGroup.Name, server.Name, testDatabaseName, syncGroupName, new SyncGroup());
```

2017-08-08 23:29 UTC, ScottHolden commented on src/SDKs/SqlManagement/Management.Sql/Microsoft.Azure.Management.Sql.csproj
> +    <VersionPrefix>1.8.0-preview</VersionPrefix>
Done :)

2017-08-08 23:29 UTC, ScottHolden commented on src/SDKs/SqlManagement/Management.Sql/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.8.0.0")]
Done :)

2017-08-08 23:29 UTC, ScottHolden commented on src/SDKs/SqlManagement/Sql.Tests/SyncMemberScenarioTests.cs
> +                Assert.Equal(syncMemberName, listSyncMembers.FirstOrDefault()?.Name);
Done :)

2017-08-08 23:29 UTC, ScottHolden commented on src/SDKs/SqlManagement/Sql.Tests/SyncMemberScenarioTests.cs
> +                Assert.NotEqual(syncMemberDirection, updateSyncMemberDirection);
Done :)

2017-08-08 23:29 UTC, ScottHolden commented on src/SDKs/SqlManagement/Sql.Tests/SyncGroupScenarioTests.cs
> +                Assert.Equal(interval2, updateSyncGroup.Interval);
Done :)

2017-08-08 23:33 UTC, ScottHolden commented
@shahabhijeet I'm not currently part of the Azure GitHub organisation, who do I need to reach out to to be added, as I couldn't see a link on https://github.com/Azure/

2017-08-09 00:17 UTC, jaredmoo commented
@ScottHolden I think that this is only applicable to Microsoft employees working in the Azure organization. So my understanding is that this is not applicable to you.

2017-08-09 01:36 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/SyncGroupScenarioTests.cs
> +                Assert.Equal(interval2, updateSyncGroup.Interval);
oops, these empty updates ideally should not fail. Not your fault though, it has to be fixed server-side. Thanks for testing!

2017-08-09 01:36 UTC, jaredmoo approved these changes

2017-08-10 02:10 UTC, shahabhijeet commented
@azuresdkci test this please

2017-08-10 02:11 UTC, shahabhijeet commented
@ScottHolden add to whitelist

2017-08-10 02:12 UTC, shahabhijeet commented
@ScottHolden sql tests are failing on travis.
Were you able to successfully run SQL tests locally?
Click on Details and check the failures.

2017-08-10 02:12 UTC, shahabhijeet commented
@azuresdkci add to whitelist

2017-08-10 03:28 UTC, ScottHolden commented
All tests were working fine locally @shahabhijeet. I was able to run in record mode and playback mode, and committed the SessionRecord with the test changes.
I'll have a look into what is happening and try and replicate locally :)

2017-08-14 00:45 UTC, ScottHolden commented
Running locally gives me no errors at all, I can't seem to replicate :(

![image](https://user-images.githubusercontent.com/20675893/29254781-abf977aa-80dd-11e7-9e49-0926708757ca.png)

2017-08-14 04:05 UTC, jaredmoo commented
It looks like the lab build merges with the target branch (azure/psSdkJson6) before running tests, and we made some incompatible test changes recently that you haven't pulled in. It should be fixed by merging from azure/psSdkJson6 and re-recording the tests. You will need to add a few new properties to your test environment connection string, e.g. `DefaultLocationId=japaneast;DefaultLocation=Japan East`.

2017-08-14 12:31 UTC, ScottHolden commented
Thanks @jaredmoo ! That did the trick :)
Should be fine to merge now :)

2017-08-14 17:59 UTC, shahabhijeet approved these changes
@jaredmoo I assume you will be updating the AssemblyInfo to reflect the next release version.

2017-08-14 17:59 UTC, merged

2017-08-14 20:12 UTC, jaredmoo commented
Awesome! Yes AssemblyInfo is handled. Thx