Update SDK for new Azure Analysis Services API spec
Azure/azure-sdk-for-net pull request #3563
Opened 2017-08-08 18:01 UTC by michael-falk

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-08 18:01 UTC, msftclas commented
@michael-falk,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-08 18:57 UTC, michael-falk commented
PR for swagger spec change

https://github.com/Azure/azure-rest-api-specs/pull/1515

2017-08-10 01:51 UTC, shahabhijeet commented
@michael-falk please add description about the PR.
As to what this PR is all about
What has been added or changed.
Any idea as to what kind of functionality been added/updated helps in reviewing the PR.

2017-08-12 00:22 UTC, michael-falk commented
@shahabhijeet I've updated the description as per above request. However, I cannot remove the 'needs-revision' label. Would you please have a look?

2017-08-14 17:52 UTC, shahabhijeet requested changes
Please use latest AutoRest by using Generate.cmd to regenerate.

2017-08-14 17:52 UTC, shahabhijeet commented on src/SDKs/AnalysisServices/AnalysisServices.Tests/AnalysisServices.Tests.csproj
> +    <None Update="SessionRecords\AnalysisServices.Tests.ScenarioTests.ServerOperationsTests\ScaleOutTest.json">
@michael-falk please replace the individual .json files with something like below 
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Compute.Tests/Compute.Tests.csproj#L21

2017-08-14 17:52 UTC, shahabhijeet commented on src/SDKs/AnalysisServices/Management.Analysis/Generated/AnalysisServicesManagementClient.cs
> +        public AnalysisServicesManagementClient(System.Uri baseUri, Microsoft.Rest.ServiceClientCredentials credentials, System.Net.Http.HttpClientHandler rootHandler, params System.Net.Http.Delegati
@michael-falk seems you are using an older version of autoRest.
Can you use the existing generate.cmd and if you need any info, use generate.cmd /? and you will get more information.

2017-08-17 18:00 UTC, michael-falk commented
@shahabhijeet I've rerun generate using the newest autorest

2017-08-17 22:09 UTC, michael-falk commented
Closing to allow integration with other Analysis Services SDK changes (w/ Taiwu)

2017-08-17 22:09 UTC, closed without merging