Add Fluent implementation for Search service
Azure/azure-sdk-for-net pull request #3575
Opened 2017-08-11 18:22 UTC by milismsft

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-11 18:22 UTC, msftclas commented
@milismsft,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-11 20:15 UTC, hovsepm commented
@milismsft please pull from upstream and resolve conflicts.

2017-08-11 20:19 UTC, hovsepm commented on src/ResourceManagement/Scheduler/Generated/JobsOperationsExtensions.cs
> +            }
please remove all Sync methods from the generated code. There is a regex expression that should help you.

2017-08-11 20:21 UTC, hovsepm commented on src/ResourceManagement/Search/SearchServiceImpl.cs
> +            }
? something missing in the if statement?

2017-08-11 20:21 UTC, hovsepm commented on src/ResourceManagement/Search/SearchServiceImpl.cs
> +            }
here as well. What is this check for?

2017-08-11 20:24 UTC, hovsepm commented
Please add your new projects to https://github.com/Azure/azure-sdk-for-net/blob/Fluent/test_on_linux.sh#L34 file

2017-08-11 20:24 UTC, hovsepm commented
Schedulers does not seems to have AssemblyInfo.cs file. Please add.

2017-08-11 20:27 UTC, hovsepm requested changes
please address review comments.

2017-08-11 21:18 UTC, brjohnstmsft commented on src/ResourceManagement/Search/AdminKeysImpl.cs
> +namespace Microsoft.Azure.Management.Search.Fluent
What is the relationship between this code and the generated code for our non-fluent .NET management SDK that lives in the `vs17dev` & `psSdkJson6` branches? If this is meant to be completely separate, why not have it in a separate repo?

2017-08-11 22:02 UTC, milismsft commented on src/ResourceManagement/Search/AdminKeysImpl.cs
> +namespace Microsoft.Azure.Management.Search.Fluent
@martinsawicki
This class is the required implementation for the AdminKeys interface which is a wrapper for the *Inner respective class; in Fluent we do not want to expose the *Inner directly to the user.

2017-08-11 22:57 UTC, hovsepm approved these changes

2017-08-11 23:01 UTC, hovsepm commented
sing-job: http://azuresdkci.cloudapp.net/view/NetCore-SDK/job/Fluent-NetCore-SDK-Sign/10/

2017-08-11 23:21 UTC, merged

2017-08-11 23:55 UTC, brjohnstmsft commented on src/ResourceManagement/Search/AdminKeysImpl.cs
> +namespace Microsoft.Azure.Management.Search.Fluent
@milismsft Sorry for the confusion; My question wasn't about this class in particular, it was about all these changes. I maintain the Search SDKs in the main branches (vs17dev & psSdkJson6) but I've been ignoring all things Fluent up until now. Is this code ever going to be merged back into the mainline branches, or is it permanently separate?

2017-08-12 00:23 UTC, milismsft commented on src/ResourceManagement/Search/AdminKeysImpl.cs
> +namespace Microsoft.Azure.Management.Search.Fluent
@martinsawicki might be able to talk more about the future of Fluent branch but as of now the code stays in a separate branch out of the Azure/azure-sdk-for-net repo.