Container instances/groups management client
Azure/azure-sdk-for-net pull request #3580
Opened 2017-08-14 12:41 UTC by ScottHolden

Generated the ContinerInstances client along with a base set of scenario tests.

This rest api spec was already merged, so generated it straight off there :)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [X] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-14 12:41 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-08-14 12:41 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-08-14 12:41 UTC, msftclas commented
@ScottHolden,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-08-14 18:08 UTC, shahabhijeet commented
@sauryadas @rgardler Can one of you review this PR for Container instance.

2017-08-14 22:05 UTC, ScottHolden commented
Hi @shahabhijeet ,
This was merged into the rest spec back in https://github.com/Azure/azure-rest-api-specs/pull/1480

The .NET SDK did not have this client, thus it was created from scratch.

Let me know if you need any more info :)

2017-08-16 22:25 UTC, shahabhijeet commented
@sauryadas can you approve this PR?

2017-08-23 23:21 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/Utilities/TestContext.cs
> +		public const string DefaultLocationId = "japaneast";
>public const string DefaultLocationId = "japaneast"; [](start = 2, length = 52)

@scott@nullops.io No need. Just use location.

2017-08-23 23:22 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/Utilities/TestContext.cs
> +		public const string DefaultLocation = "Japan East";
>"Japan East"; [](start = 40, length = 13)

Is it possible to use "westus" instead?

2017-08-23 23:23 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/Utilities/TestContext.cs
> +		}
Can you just use `TestUtilities.GenerateName`

2017-08-23 23:24 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerGroupScenarioTests.cs
> +				string containerGroupName = context.GenerateName("containergroup");
>context.GenerateName [](start = 32, length = 20)

Just use `TestUtilities.GenerateName`

2017-08-23 23:25 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerGroupScenarioTests.cs
> +				string containerName = "test1";
>"test1" [](start = 27, length = 7)

Can you also use `TestUtilities.GenerateName` to generate a random name?

2017-08-23 23:26 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerGroupScenarioTests.cs
> +				string containerOsType = "Linux";
>"Linux" [](start = 29, length = 7)

Use `OperatingSystemTypes.Linux`

2017-08-23 23:27 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerGroupScenarioTests.cs
> +				Assert.Equal(1, createdContainerGroup.Containers.Count);
Also verify the there is public IP address assigned.

2017-08-23 23:30 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerGroupScenarioTests.cs
> +				Assert.Equal(containerMemoryInGB, getContainer.Resources.Requests.MemoryInGB);
Wrap all the assertion into a helper method.

2017-08-23 23:31 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerGroupScenarioTests.cs
> +				Assert.True(listRgContainerGroup.Any(x => containerGroupID.Equals(x?.Id)));
Create a test case in which you create 2 container group. When listing all, you should get both. When listing by resource group, you should only get one.

2017-08-23 23:32 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerGroupScenarioTests.cs
> +				ContainerGroupUtilities.WaitTillProvisioningStateSucceeded(containerClient, resourceGroup.Name, containerGroupName);
Not really necessary. You can call get or list before reach succeeded provisioning state.

2017-08-23 23:34 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/Utilities/ContainerInstanceTestUtilities.cs
> +    class ContainerInstanceTestUtilities
>ContainerInstanceTestUtilities [](start = 10, length = 30)

Seems not used anywhere? Remove this class?

2017-08-23 23:36 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerInstance.Tests.csproj
> +  </ItemGroup>
Remove. All not needed.

2017-08-23 23:37 UTC, yolo3301 commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerLogScenarioTests.cs
> +				string containerName = "test1";
Similar to the other scenario tests. Use built in function to generate name.

2017-08-23 23:52 UTC, yolocs requested changes
Hi Scott, thanks for contributing. Left several comments.

2017-08-23 23:59 UTC, shahabhijeet requested changes
@ScottHolden thank you for your valuable contribution. This is helpful.
Please make changes suggested in the PR

2017-08-23 23:59 UTC, shahabhijeet commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerInstance.Tests.csproj
> +    <Compile Remove="Utilities\ContainerInstanceTestUtilities.cs" />
@ScottHolden this is not needed. I know VS might have added it, can you remove it. VS will include code files by default in all sub directories.

2017-08-23 23:59 UTC, shahabhijeet commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerInstance.Tests.csproj
> +    <Folder Include="SessionRecords\" />
@ScottHolden can you clean up these itemgroup, you do not need a separate directory itemgroup for SessionRecords

2017-08-28 19:00 UTC, shahabhijeet commented
@ScottHolden this PR has not addressed the feedback and the below PR is ready to be merged
https://github.com/Azure/azure-sdk-for-net/pull/3615
Closing this PR

2017-08-28 19:00 UTC, closed without merging