Vbs elastic pool changes and regenerating sdk for sql
Azure/azure-sdk-for-net pull request #35921
Opened 2023-05-01 18:50 UTC by vidit-msft

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-05-01 19:03 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.Sql](https://apiview.dev/Assemblies/Review/3aeb15c55cfc45aea81f08f3fc387afc)

2023-05-25 01:27 UTC, vidit-msft commented
@live1206 Can you please review this PR once. It is currently failing on spell-check for Euap( Prod canary region) I added for recording tests.

![image](https://github.com/Azure/azure-sdk-for-net/assets/78883096/f89aaaa1-dfa8-41ba-b4da-387cea0b5f91)

2023-06-02 07:02 UTC, live1206 commented on sdk/core/Azure.Core/src/AzureLocation.cs
> +		/// <summary>
Why change in `Azure.Core`?

2023-06-02 07:59 UTC, live1206 commented on sdk/core/Azure.Core/src/AzureLocation.cs
> +		/// <summary>
As discussed offline, if you wan to release a public version of .NET SDK, your service should be available publicly.
No need to add Canary region for test here.

Re-generate the code to latest:
```
Generated code is not up to date.
    You may need to rebase on the latest main, 
    run 'eng\scripts\Update-Snippets.ps1' if you modified sample snippets or other *.md files (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#updating-sample-snippets), 
    run 'eng\scripts\Export-API.ps1' if you changed public APIs (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#public-api-additions). 
    run 'dotnet build /t:GenerateCode' to update the generated code.
    run 'dotnet build /t:GenerateTests' to update the generated test code.
    
To reproduce this error locally, run 'eng\scripts\CodeChecks.ps1 -ServiceDirectory sqlmanagement'.
```

Compile errors:
```
##[error]sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/ArmSqlModelFactory.cs(2456,24): Error CS7036: There is no argument given that corresponds to the required parameter 'highAvailabilityReplicaCount' of 'ElasticPoolData.ElasticPoolData(ResourceIdentifier, string, ResourceType, SystemData, IDictionary<string, string>, AzureLocation, SqlSku, string, ElasticPoolState?, DateTimeOffset?, long?, double?, ElasticPoolPerDatabaseSettings, bool?, ElasticPoolLicenseType?, ResourceIdentifier, int?, SqlAlwaysEncryptedEnclaveType?, SqlAvailabilityZoneType?)'

/mnt/vss/_work/1/s/sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/ArmSqlModelFactory.cs(2456,24): error CS7036: There is no argument given that corresponds to the required parameter 'highAvailabilityReplicaCount' of 'ElasticPoolData.ElasticPoolData(ResourceIdentifier, string, ResourceType, SystemData, IDictionary<string, string>, AzureLocation, SqlSku, string, ElasticPoolState?, DateTimeOffset?, long?, double?, ElasticPoolPerDatabaseSettings, bool?, ElasticPoolLicenseType?, ResourceIdentifier, int?, SqlAlwaysEncryptedEnclaveType?, SqlAvailabilityZoneType?)' [/mnt/vss/_work/1/s/sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Azure.ResourceManager.Sql.csproj]
```

2023-06-27 05:31 UTC, live1206 requested changes
Please resolve the comments for further review.

2023-06-29 21:02 UTC, closed without merging