Cognitive Services Ver.1.1.0
Azure/azure-sdk-for-net pull request #3597
Opened 2017-08-17 08:02 UTC by felixwa

1. Everything is re-generated with the latest AutoRest (by
generate.cmd).
2. With the latest swagger file change, now Location is a parameter of
the method, not a property of client class, this is a breaking change.
3. Change the UT accordingly.
4. Bump the version to 1.1.0.

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-21 05:32 UTC, shahabhijeet requested changes

2017-08-21 05:32 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.1.0.0")]
@felixwa this is not needed. We usually bump up assemblyverion on major version update.

2017-08-21 05:56 UTC, felixwa commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.1.0.0")]
@shahabhijeet , you mean both AssemblyVersion and AssemblyFileVersion need not to be changed or only AssemblyVersion need not to be changed? 
Note this PR introduced a breaking change (Location from property to method parameter) so we definitely need re-versioning.

2017-08-22 18:55 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.1.0.0")]
@felixwa what is the usual practice is, you only update AssemblyVersion when you update the major version.
If you have introduced a breaking change, then simply update
AssemblyFileVersion to 2.0.0.0
AssemblyVersion to 2.0.0.0

2017-08-22 18:55 UTC, shahabhijeet commented
@azuresdkci test this please

2017-08-23 06:22 UTC, felixwa commented on src/SDKs/CognitiveServices/Management.CognitiveServices/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.1.0.0")]
@shahabhijeet , okay then I have reversioned everything to 2.0.0.0

2017-08-28 17:07 UTC, shahabhijeet approved these changes

2017-08-28 17:08 UTC, merged