Adding Cognitive Services Data Plane Vision SDK.
Azure/azure-sdk-for-net pull request #3604
Opened 2017-08-20 05:06 UTC by DavidLiCIG

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x ] Title of the pull request is clear and informative.
- [x ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-20 05:06 UTC, msftclas commented
@DavidLiCIG,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-21 05:45 UTC, shahabhijeet commented
@DavidLiCIG seems tests are failing on CI

2017-08-21 05:47 UTC, shahabhijeet requested changes

2017-08-21 05:47 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/Microsoft.CognitiveServices.Vision.Tests/Microsoft.CognitiveServices.Vision.Tests.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
@DavidLiCIG can you model your test project by looking at other tests.

2017-08-31 01:12 UTC, arv100kri approved these changes

2017-08-31 01:12 UTC, arv100kri commented on src/SDKs/CognitiveServices/data-plane/Language/Microsoft.CognitiveServices.Language.Tests/BaseTests.cs
> +namespace Microsoft.CognitiveServices.Language.Tests
Shouldn't the namespace be Microsoft.CognitiveServices.Language.TextAnalytics.Tests? To better match the namespace of the actual API?

2017-08-31 01:12 UTC, arv100kri commented on src/SDKs/CognitiveServices/data-plane/Language/Microsoft.CognitiveServices.Language.Tests/DetectLanguageTests.cs
> +                Assert.Equal("en", result.Documents[0].DetectedLanguages[0].Iso6391Name);
Also worth adding an assert for the score

2017-09-03 23:26 UTC, shahabhijeet requested changes
@DavidLiCIG travis changes have been pushed.
Please address the feedback and this PR is good to be merged

2017-09-03 23:26 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/Language/Microsoft.CognitiveServices.Language.Tests/BaseTests.cs
> +﻿using Microsoft.CognitiveServices.Language.TextAnalytics;
@DavidLiCIG we have certain directory structure that is being used throughout the repo.
1) One being, if you have management and data plane the directories should be structured as
SDKs\CognitiveServices\management
SDKs\CognitiveServices\dataPlane
we rely on particular names to build and run tests during CI build.

Please change the directory structure accordingly.

2017-09-03 23:26 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj
> +    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
@DavidLiCIG please remove GeneratePackageOnBuild, we have specific targets to build pacakges.
The target that we use is /t:CreateNugetPackage to create nuget packages, having it part of build system hampers the CI perf.

2017-09-03 23:26 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj
> +    <PackageReleaseNotes>For detailed release notes, see: </PackageReleaseNotes>
< packagereleasenotes > should be included on the top PropertyGroup where you have PackageId and version defined.
move it under right propertygroup.

2017-09-03 23:26 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj
> +  <PropertyGroup Condition=" '$(TargetFramework)'=='net452' ">
@DavidLiCIG remove line 20 to 32.
All these are already included for your projects.
Also we no longer use PORTABLE compiler constant in the entire repo. We have few traces of those constants being used in couple of RPs which are on track to be removed.

2017-09-03 23:26 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/Vision/Microsoft.CognitiveServices.Vision.Tests/Microsoft.CognitiveServices.Vision.Tests.csproj
> +    <None Update="TestImages\detection1.jpg">
@DavidLiCIG combine items in Itemgroup starting line 27 to be part of ItemGroup starting line 17
Please organize items in limited item groups especially if they logically belong to same category

2017-09-03 23:26 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/Vision/Microsoft.CognitiveServices.Vision/Microsoft.CognitiveServices.Vision.csproj
> +  <PropertyGroup Condition=" '$(TargetFramework)'=='net452' ">
@DavidLiCIG please format project file according to the feedback given to the language project

2017-09-03 23:26 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/data-plane/dirs.proj
> +<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
@DavidLiCIG this file is not needed.

2017-09-08 23:00 UTC, DavidLiCIG commented
@shahabhijeet Thanks. All feedbacks are addressed

2017-09-11 23:10 UTC, shahabhijeet requested changes
Forgot to mention earlier.
add < PackageReleaseNotes > and add Release notes.
I would recommend to use < ![CDATA and then format your Release notes

2017-09-12 16:30 UTC, shahabhijeet requested changes
Did not see AssemblyInfo for individual SDKs which has AssemblyVersion and AssemblyFileVersion.
If you are missing you need those files.

2017-09-12 16:30 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/dataPlane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj
> +    <VersionPrefix>1.0.0</VersionPrefix>
@DavidliCIG if this is a preview release, I still see your SDK nuget is not marked as preview
the version should 1.0.0-preview

2017-09-12 16:30 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/dataPlane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj
> +  <ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">
@DavidLigCIG please remove this redundant ItemGroup, this is not needed

2017-09-12 16:30 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/dataPlane/Vision/Microsoft.CognitiveServices.Vision/Microsoft.CognitiveServices.Vision.csproj
> +    <VersionPrefix>1.0.0</VersionPrefix>
@DavidLiCIG please mark this version as preview if this is a preview release. Release notes say this is preview but the version is not marked accordingly.
Developers who will be downloading from nuget will be confused what is the case, is it preview or not.

2017-09-12 16:30 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/dataPlane/Vision/Microsoft.CognitiveServices.Vision/Microsoft.CognitiveServices.Vision.csproj
> +  <ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">
Remove the Itemgroup as it's not needed.

2017-09-12 16:30 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/dataPlane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj
> +    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
@DavidLiCIG generating documentation property is already applicable for the SDKs, this is again redundant, please remove

2017-09-12 16:30 UTC, shahabhijeet commented on src/SDKs/CognitiveServices/dataPlane/Vision/Microsoft.CognitiveServices.Vision/Microsoft.CognitiveServices.Vision.csproj
> +    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
@DavidLiCIG please remove redundant property

2017-09-12 19:21 UTC, shahabhijeet approved these changes

2017-09-12 19:21 UTC, merged