Add Azure container instance net SDK
Azure/azure-sdk-for-net pull request #3615
Opened 2017-08-22 23:13 UTC by yolo3301

## Description

- [Container Instance REST API spec](https://github.com/Azure/azure-rest-api-specs/tree/current/specification/containerinstance/resource-manager)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-08-22 23:13 UTC, msftclas commented
@yolo3301,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-23 03:43 UTC, shahabhijeet requested changes

2017-08-23 03:43 UTC, shahabhijeet commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerInstance.Tests.csproj
> +    <!-- When xunit cannot detect tests, uncomment the following dependencies -->
@yolo3301 remove commented code

2017-08-23 03:43 UTC, shahabhijeet commented on src/SDKs/ContainerInstance/Management.ContainerInstance/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.2.0.0")]
@yolo3301 have consistent versions between nuget version as well as AssemblyFile Version.

2017-08-23 03:43 UTC, shahabhijeet commented on src/SDKs/dirs.proj
> +		<ProjectToBuild Include="$(MSBuildThisFileDirectory)ContainerInstance\Management.ContainerInstance\Microsoft.Azure.Management.ContainerInstance.csproj" />
@yolo3301 dirs.proj is no longer used, you can revert this change.

2017-08-23 03:45 UTC, shahabhijeet requested changes
@yolo3301 please provide detailed description about this PR.
If this is your first version, please specify it else describe the changes going in this version.

2017-08-23 04:06 UTC, brendandburns commented
awesome, thank you!

2017-08-23 18:14 UTC, yolo3301 commented
@shahabhijeet Thanks for reviewing. All comments have been addressed.

2017-08-28 18:12 UTC, shahabhijeet requested changes
@yolo3301 this is your first time, are you sure you want to go 1.0.0 or you rather go 1.0.0-preview
If so, please mark as that version in csproj file and not AssemblyInfo.cs

2017-08-28 18:12 UTC, shahabhijeet commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerInstance.Tests.csproj
> +    <StartupObject></StartupObject>
@yolo3301 please remove this

2017-08-28 18:12 UTC, shahabhijeet commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/Properties/AssemblyInfo.cs
> +[assembly: ComVisible(false)]
nit:
@yolo3301 you made this assembly COM visible false, but then providing typelib GUID
Please consider removing this.

2017-08-28 18:12 UTC, shahabhijeet commented on src/SDKs/ContainerInstance/Management.ContainerInstance/Microsoft.Azure.Management.ContainerInstance.csproj
> +    <PackageIconUrl>http://go.microsoft.com/fwlink/?LinkID=288890</PackageIconUrl>
@yolo3301 please remove this tag, as it's centrally controlled.

2017-08-28 18:40 UTC, yolo3301 commented
@shahabhijeet I do want to go with 1.0.0-preview. So I removed the versions in AssemblyInfo.cs.

2017-08-28 18:58 UTC, shahabhijeet approved these changes
as soon as CI passes, this is good to go

2017-08-29 05:44 UTC, yolo3301 commented
@shahabhijeet The other check failed. However, I don't have permission to check what's wrong there. Could you help?

2017-08-29 21:11 UTC, merged