Mocking hacks
Azure/azure-sdk-for-net pull request #36171
Opened 2023-05-10 07:25 UTC by ArcturusZhang

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-05-10 13:43 UTC, jsquire requested changes

2023-05-10 13:43 UTC, jsquire commented on eng/Packages.Data.props
> +    <PackageReference Update="Moq" Version="4.18.2" />
Moq already appears under the Test project section (L258).   We do not want to add it here, as it should not be referenced by our non-test projects.

2023-05-10 13:43 UTC, jsquire commented on sdk/resources/Azure.ResourceManager.Resources/src/Generated/Extensions/MockingExtensions.cs
> +        internal static void SetupAzureExtensionMethod<T>(this Mock<T> mock, Expression<Action<T>> expression) where T : ArmResource
What if a customer is using a different mocking library?   For example, `NSubstitute`, `FakeItEasy`, `RhinoMocks`, `JustMock`

We do not want to offer built-in support for a specific mocking library and remove customer choice or provide a degraded experience for those who prefer other libraries.

2023-05-10 13:43 UTC, jsquire commented on eng/Directory.Build.Common.targets
> +    <PackageReference Include="Moq" />
We should not be including `Moq` in a non-test project.

2023-05-10 13:44 UTC, jsquire commented
I don't know if this is just experimentation or the intention was to actually move forward with this as part of the Azure SDK.   Please add a meaningful description to all pull requests that you open.  Anyone should be able to understand your intent and the scope of your work by reading the PR.

2023-05-10 14:42 UTC, ArcturusZhang commented
> I don't know if this is just experimentation or the intention was to actually move forward with this as part of the Azure SDK. Please add a meaningful description to all pull requests that you open. Anyone should be able to understand your intent and the scope of your work by reading the PR.

Yes this is only an experiment - when it is ready to review I will add more descriptions

2023-05-10 14:48 UTC, jsquire commented
> Yes this is only an experiment - when it is ready to review I will add more descriptions

Please add a meaningful description for every PR you open, when you open it.   The intent should be clear upfront.  Let's not wait until things come out of draft status.   Anyone looking at PRs in our repository should be able to open any pull request - draft or not - and understand why it exists and what it is attempting to do.

2023-05-11 09:40 UTC, ArcturusZhang commented on sdk/resources/Azure.ResourceManager.Resources/tests/MockingTests.cs
> +        public async Task TestUsingAzureMock()
This is the instance way.
Customer needs to use `AzureMock<T>` instead when mocking azure APIs.
This AzureMock not only works for extension methods, it also works just like Mock for normal instance method.

2023-05-23 06:40 UTC, ArcturusZhang commented
The things we need to override to redirect: 
- `public ISetup<T> Setup(Expression<Action<T>> expression)` in Mock<T>
- `public ISetup<T, TResult> Setup<TResult>(Expression<Func<T, TResult>> expression)` in Mock<T>
The adaptors we need:
- `ISetup<TMock, TResult>` (60 methods)
- `IReturnsResult<T>` (40 methods)

2023-08-14 09:08 UTC, closed without merging