Onboard Management.Network to version 09-01-2017
Azure/azure-sdk-for-net pull request #3681
Opened 2017-09-12 02:04 UTC by murilogr

# Description

This change was autogenerated from the Swagger changes for the new version of the Network API:

[https://github.com/Azure/azure-rest-api-specs/pull/1661/commits](https://github.com/Azure/azure-rest-api-specs/pull/1661/commits)

These changes have been approved by ARM and REST teams and are merged into "current" branch.

The changes include:
- Application Security Group
- Secure VNETs
- ILB HA
- Small API fixes

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-09-12 02:04 UTC, msftclas commented
@murilogr,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-12 02:27 UTC, murilogr commented
Please provide guidelines for updating the version.

2017-09-13 05:09 UTC, shahabhijeet reviewed
Update version so that you can publish the nuget.
Add < PackageReleaseNotes > in .csproj
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj#L11

2017-09-13 05:10 UTC, shahabhijeet requested changes
Update version so that you can publish the nuget.
Add < PackageReleaseNotes > in .csproj
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Language/Microsoft.CognitiveServices.Language/Microsoft.CognitiveServices.Language.csproj#L11

2017-09-13 07:31 UTC, murilogr commented
@shahabhijeet I updated the PR with the requested changes.

2017-09-13 15:18 UTC, shahabhijeet requested changes

2017-09-13 15:18 UTC, shahabhijeet commented on src/SDKs/Network/Management.Network/Microsoft.Azure.Management.Network.csproj
> +    <PackageReleaseNotes>This is a preview release of the Network SDKs. It includes the support for application security groups (ASGs), secure VNETs, ILB HA,
Network SDK is one of the top 5 RPs. Providing details that helps to understand what the new version has is very helpful for developers who are trying to develop using Netwok SDK.
What does ILB HA mean?

2017-09-19 23:48 UTC, shahabhijeet commented
@murilogr Please address the feedback or this PR will be closed by eow

2017-09-22 00:54 UTC, murilogr commented
@shahabhijeet These changes were done in the private repo. I'm deactivating this PR, unless I see there's any diff later.

2017-09-22 00:54 UTC, closed without merging