NRP 2023-02-01 Release
Azure/azure-sdk-for-net pull request #37088
Opened 2023-06-19 02:18 UTC by htippanaboya

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-06-19 03:26 UTC, archerzz requested changes, later dismissed
The name is too generic. Consider appending RP prefix or renaming it.
- use `prepend-rp-prefix` to automatically append PR name. See example [here](https://github.com/Azure/azure-sdk-for-net/blob/176fd476588e8e61ebce747d66714cb39947cae5/sdk/azurestackhci/Azure.ResourceManager.Hci/src/autorest.md?plain=1#L52-L57).
- use `rename-mapping` to rename a model. See example [here](https://github.com/Azure/azure-sdk-for-net/blob/176fd476588e8e61ebce747d66714cb39947cae5/sdk/azurestackhci/Azure.ResourceManager.Hci/src/autorest.md?plain=1#L58-L76)

2023-06-19 11:22 UTC, htippanaboya commented
@archerzz - Receiving the below error for dotnet build /t:GenerateTest

![image](https://github.com/Azure/azure-sdk-for-net/assets/102244326/7f800123-6296-4f46-abef-241753e908f7)

2023-06-20 00:36 UTC, htippanaboya commented
@archerzz  - Updated the samples

2023-06-29 03:12 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.Network](https://apiview.dev/Assemblies/Review/fc45abaca6f94b3d8995603b4aaf2f2a)

2023-06-29 04:04 UTC, ArthurMa1978 approved these changes

2023-06-30 06:54 UTC, merged