Microsoft.GraphServices add new SDK version for stable swagger spec
Azure/azure-sdk-for-net pull request #37105
Opened 2023-06-20 02:21 UTC by amatukmolina

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-06-20 02:22 UTC, amatukmolina commented
The only change between the previous swagger spec and this one is we changed the operation ids, no functional change was made. For that reason the same tests apply to this spec.

2023-06-20 02:30 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-06-30 01:49 UTC, amatukmolina commented
@ArthurMa1978 Thanks for the guidance, all tests passed after the changes you suggested. Is there something else we need to do or can we continue with the merge?

2023-07-05 07:21 UTC, amatukmolina commented
@archerzz @ArcturusZhang Could you please help us merge this PR if it looks good? I think Arthur is the assignee but I see he's OOF until next week. Arthur told us that for a GA version we need to do some extra polishing steps after this gets merged so we want to get started on that as soon as possible. Thanks!

2023-07-06 00:54 UTC, carlosov-ms commented
@archerzz @ArcturusZhang @ArthurMa1978 Are there any action items we still have to perform on our side? If not, could you help us by approving and merging this PR? Our GA release date is end of this month and this is a prerequisite, we want to meet the deadline.

Appreciate all the help you can provide.

Thank you

cc @amatukmolina

2023-07-07 03:08 UTC, ArcturusZhang approved these changes

2023-07-10 01:01 UTC, archerzz commented
@carlosov-ms could you fix the conflicts? Thanks.

2023-07-10 15:12 UTC, carlosov-ms commented
> @carlosov-ms could you fix the conflicts? Thanks.

@amatukmolina was working on them, Alexis could you provide an update to @archerzz please?

Thanks

2023-07-10 21:43 UTC, amatukmolina commented
@archerzz Sorry for the delay, I merged the changes and pushed again. I made a new recording of the tests but the pipelines are saying they need to be uploaded to a different repo via the test-proxy command and I don't have access to push to that one. What should I do to fix those errors? Thanks!

2023-07-13 02:48 UTC, live1206 reviewed
- Update the changelog with new features added in new version 
- Update the version to statble in `Azure.ResourceManager.GraphServices.csproj`
- Remove `--prerelease` from `dotnet add package Azure.ResourceManager.GraphServices --prerelease` in `sdk\graphservices\Azure.ResourceManager.GraphServices\README.md` L25

2023-07-13 02:48 UTC, live1206 commented on sdk/graphservices/Azure.ResourceManager.GraphServices/src/autorest.md
> +# tag: package-2023-04-13
remove the tag since it is the default on in readme.md

2023-07-13 07:02 UTC, live1206 requested changes, later dismissed
Need to polish the naming before first GA

2023-07-14 04:40 UTC, ArthurMa1978 approved these changes

2023-07-14 05:24 UTC, merged