Update .net SDK based on latest official swagger spec for sql 2017-03-01-preview
Azure/azure-sdk-for-net pull request #3722
Opened 2017-09-20 18:10 UTC by jiawang003

## Description

1) Update .net SDK based on latest official swagger spec for Sql 2017-03-01-preview, here's the link for that committed PR:
https://github.com/Azure/azure-rest-api-specs/commit/b3f4823378bab4812792ad0b90da6e8a8385a2f1

2) include newly added testcase TestCancelDatabaseOperation for list and cancel database operation API, and new test passed

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-09-20 18:10 UTC, msftclas commented
@jiawang003,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-20 18:58 UTC, shahabhijeet requested changes
If you are planning ot publish, you will need to bump up the version for your nuget package.

2017-09-20 19:02 UTC, shahabhijeet commented
You can use this instead of checking for record mode
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/TestFramework/ClientRuntime.Azure.TestFramework/Utilities/TestUtilities.cs#L84

2017-09-20 20:41 UTC, jiawang003 commented
updated to use TestUtilities.Wait instead of checking for record mode

2017-09-20 21:18 UTC, jiawang003 commented
resolved all review comments so far

2017-09-20 21:29 UTC, jaredmoo commented
@shahabhijeet the last published version was 1.6 ( https://www.nuget.org/packages/Microsoft.Azure.Management.Sql ) so 1.7 in assemblyversion is already correct.

2017-09-20 21:47 UTC, jaredmoo approved these changes

2017-09-20 21:47 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/OperationsScenarioTests.cs
>                  OperationListResult result = sqlClient.Operations.List();
change OperationListResult to IPage<Operation> and uncomment

2017-09-21 19:23 UTC, shahabhijeet approved these changes

2017-09-21 19:23 UTC, merged