[Do not merge] Add code for Microsoft.Azure.Services.AppAuthentication library
Azure/azure-sdk-for-net pull request #3738
Opened 2017-09-23 00:16 UTC by varunsh-msft

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

Based on discussion with @shahabhijeet, creating a PR to test CI. Will wait for @shahabhijeet to review this in first week of October.

2017-09-23 00:16 UTC, msftclas commented
@varunsh-msft,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-25 17:44 UTC, AArnott commented on src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.IntegrationTests/Microsoft.Azure.Services.AppAuthentication.IntegrationTests.csproj
> +
nit: why so many empty lines?

2017-10-01 23:43 UTC, shahabhijeet requested changes

2017-10-01 23:43 UTC, shahabhijeet commented on src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.IntegrationTests/Microsoft.Azure.Services.AppAuthentication.IntegrationTests.csproj
> +		<SignAssembly>True</SignAssembly>
@varunsh-msft you  do not need this property, it's already been added as part of common properties references for the entire repo

2017-10-01 23:43 UTC, shahabhijeet commented on src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.IntegrationTests/Microsoft.Azure.Services.AppAuthentication.IntegrationTests.csproj
> +		<DelaySign>True</DelaySign>
redundant property, please remove

2017-10-01 23:43 UTC, shahabhijeet commented on src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.IntegrationTests/Microsoft.Azure.Services.AppAuthentication.IntegrationTests.csproj
> +	<PropertyGroup Condition=" '$(TargetFramework)'=='net452' ">
the compiler constant as well as property group is part of common targets/props. Please remove

2017-10-01 23:43 UTC, shahabhijeet commented on src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.TestCommon/Microsoft.Azure.Services.AppAuthentication.TestCommon.csproj
> +		<SignAssembly>True</SignAssembly>
@varunsh-msft if you model your project file after one of the existing project file, that will help eliminating redundant properties.

2017-10-01 23:43 UTC, shahabhijeet commented on src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication.Unit.Tests/Microsoft.Azure.Services.AppAuthentication.Unit.Tests.csproj
> +		<PackageReference Include="xunit" Version="2.2.0" />
@varunsh-msft please model your test project from one of the eixsitng test project and remove redundant properties

2017-10-13 17:10 UTC, shahabhijeet commented
@varunsh-msft as we talked earlier this week. We will revisit merging this code next month. Until then please address conflicts in this PR and reopen the PR.
Closing it for now.

2017-10-13 17:10 UTC, closed without merging