Make AzureBlobXmlRepository to be public
Azure/azure-sdk-for-net pull request #37526
Opened 2023-07-11 14:28 UTC by SerhiiVodotyka

We need to have the opportunity to instantiate AzureBlobXmlRepository when copying keys from one repository to another one (FileSystemXmlRepository -> AzureBlobXmlRepository).  FileSystemXmlRepository is public, but AzureBlobXmlRepository is internal. I suggest making AzureBlobXmlRepository to be public too.

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-07-13 14:23 UTC, jsquire requested changes
Hi @SerhiiVodotyka.  Thank you for your contribution.  The Azure SDK is very deliberate about public API changes, and we do not take them lightly.   I'd like to understand your end-to-end scenario better before we make a decision on this pull request.  Can you provide some additional context?

2023-07-14 08:16 UTC, SerhiiVodotyka commented
> jsquire

Hi @jsquire!
Thank you for your attention to this PR!
In our case, we need to move the protection keys from File System to Azure Blob Storage, to use these keys by another service too. 
Of course, we could manually prepare a key file with all keys from File System, but it would be great to do it programmatically by doing something like this:
```
// Calling this before setting DataProtection up in the startup.cs
    var fileSystemRepository = new FileSystemXmlRepository(keysDirectoryInfo, NullLoggerFactory.Instance);
    var azureBlobRepository = new AzureBlobXmlRepository(client);
    fileSystemRepository.CopyKeysIfNotExistTo(azureBlobRepository);
```
where CopyKeysIfNotExistTo is an extension method like this one:
```
using System.Linq;
using System.Xml.Linq;
using Microsoft.AspNetCore.DataProtection.Repositories;

public static class XmlRepositoryExtensions
{
    public static void CopyKeysIfNotExistTo(this IXmlRepository fromRepository, IXmlRepository toRepository)
    {
        var keys = fromRepository.GetAllElements();
        foreach (var key in keys)
        {
            if (!toRepository.Contains(key))
            {
                toRepository.StoreElement(key, null);
            }
        }
    }

    private static bool Contains(this IXmlRepository repository, XElement element)
    {
        var elements = repository.GetAllElements();
        return elements.Any(el => element.Value == el.Value);
    }
}
```

I agree that it's better to don't expose public members without extra needs, but I think in this case we could do it. Of course, I could miss something, but IXmlRepository is a public interface and some of its implementations are also public (FileSystemXmlRepository, RegistryXmlRepository), but AzureBlobXmlRepository - is an internal class.

We could do different workarounds in our case, but it would be great to make IXmlRepository-implementations' scopes identical through the code base (either public or internal), IMO.

2023-07-25 16:19 UTC, jsquire commented
Related: ##32020

2023-07-25 16:26 UTC, jsquire commented
Hi @SerhiiVodotyka.  Thanks for your patience while we had some internal discussions.   This is a change that we're open to, though it may require a change to the type name as part of architect review.   To get to that step, we'll need to get CI to pass.

To do so, we'll need to regenerate the public API, as described [here](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#public-api-additions).  We'll also need to suppress the analyzer yelling about an unapproved namespace, which will likely be in the form of adding a global suppressions file.   Your next push will kick off a build that will let us see the actual error in logs, which we can use to craft that.

I'm happy to offer what support I'm able, so please yell if you run into difficulties.

2023-10-06 08:31 UTC, closed without merging