Adding ManagedNetworkFabric - GA SDK
Azure/azure-sdk-for-net pull request #37726
Opened 2023-07-19 16:45 UTC by Mohana-Krishna-Nali

## ManagedNetworkFabric SDK for GA
Our service [**ManagedNetworkFabric**] recently supported stable - 2023-06-15 version.

This PR creates the dotnet-sdk using the [latest - readme.md](https://github.com/Azure/azure-rest-api-specs/blob/e680f9bf4f154ec427ba7feac432ed8efd9665d0/specification/managednetworkfabric/resource-manager/readme.md).

2023-07-19 16:54 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.ManagedNetworkFabric](https://apiview.dev/Assemblies/Review/f27cf27c8dae4c758155993f965ac402)

2023-07-21 03:18 UTC, live1206 commented
- Update the changelog 
  - Add new features
  - Add expecting release date
  - Update the version to 1.0.0
- Update the version in `Azure.ResourceManager.ManagedNetworkFabric.csproj`
- Remove `--prerelease` in [Install the pacakge](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/managednetworkfabric/Azure.ResourceManager.ManagedNetworkFabric/README.md#install-the-package)

2023-07-21 10:04 UTC, Mohana-Krishna-Nali commented
> * Update the changelog
>   
>   * new features
>   * expecting release date
>   * Update the version to 1.0.0
> * Update the version in `Azure.ResourceManager.ManagedNetworkFabric.csproj`
> * Remove `--prerelease` in [Install the pacakge](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/managednetworkfabric/Azure.ResourceManager.ManagedNetworkFabric/README.md#install-the-package)

Hi @live1206, updated as suggested. Could you please take a look?

2023-07-28 11:11 UTC, ArthurMa1978 requested changes
Need more tweaks.

2023-07-29 08:15 UTC, ArthurMa1978 approved these changes

2023-07-29 08:15 UTC, merged