Add sdk change for nrp version 2023-04-01
Azure/azure-sdk-for-net pull request #37784
Opened 2023-07-21 20:58 UTC by Joanna-Yang-Art

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-07-21 21:01 UTC, Joanna-Yang-Art commented
@ArthurMa1978 . @archerzz and @ArcturusZhang Could you help us review and approve this PR?

2023-07-24 02:00 UTC, archerzz reviewed
@Joanna-Yang-Art Could you please fix the errors in the pipeline first? From the error logs, looks like there are 3 issues:
- spell check
- test error
- some implementation change is not align with API interface, need to update the interface. Run `eng\scripts\Export-API.ps1 {your_sdk}` to update it.

2023-07-25 17:06 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.Network](https://apiview.dev/Assemblies/Review/3191489d11fc40ac89d61ce1d7ad913e)

2023-07-26 03:55 UTC, ArthurMa1978 commented
@Joanna-Yang-Art the definition of property `httpListeners` here https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-04-01/applicationGateway.json#L1657 is wrong, which is array of `ApplicationGatewayHttpListener` instead of a `SubResource`.

2023-07-26 07:03 UTC, ArthurMa1978 commented on sdk/network/Azure.ResourceManager.Network/src/autorest.md
> +  # Fix the httpListeners which is array of `ApplicationGatewayHttpListener` instead of a `SubResource`
This is a workaround for the swagger spec issue

2023-07-26 07:03 UTC, ArthurMa1978 approved these changes

2023-07-26 07:42 UTC, archerzz approved these changes

2023-07-26 17:05 UTC, Joanna-Yang-Art commented
Hi @ArthurMa1978 thanks for your help, we already realized the ApplicationGatewayHttpListener issue in swagger and pushed app gateway team to fix it. Our entire release plan got delayed by this. Could you help us hold this PR for now, once they checked in the fix to swagger repo, I will reach out to confirm with you see if the fix match with current sdk change or if there is anything need to be updated on sdk part

2023-07-27 09:16 UTC, ArthurMa1978 requested changes
Waiting for the swagger spec fixing

2023-07-31 04:21 UTC, ArthurMa1978 approved these changes

2023-07-31 06:11 UTC, merged