[KeyVault] Adding ECC key support
Azure/azure-sdk-for-net pull request #3782
Opened 2017-10-13 17:21 UTC by schaabs

## Description
These changes introduce ECC key support to the Key Vault SDK.  They correspond to the swagger update https://github.com/Azure/azure-rest-api-specs/pull/1724.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-10-13 20:04 UTC, shahabhijeet requested changes
I don't see any AssemblyInfo changes for this PR?

2017-10-13 20:04 UTC, shahabhijeet commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.WebKey/Microsoft.Azure.KeyVault.WebKey.csproj
> +    <VersionPrefix>2.0.8-alpha2</VersionPrefix>
any reason you want to tag as alpha. Usually in nuget we tag such releases are preview?

2017-10-18 22:53 UTC, shahabhijeet requested changes

2017-10-18 22:53 UTC, shahabhijeet commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault/Properties/AssemblyInfo.cs
@schaabs any reason you do not use AssemblyFileVersion?

2017-10-18 22:53 UTC, shahabhijeet commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Core/Properties/AssemblyInfo.cs
@schaabs any reason AssemblyFileVersion is missing.

2017-10-18 22:53 UTC, shahabhijeet commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Cryptography/Properties/AssemblyInfo.cs
@schaabs any reason AssemblyFileVersion is missing

2017-10-25 00:00 UTC, schaabs commented
closing since this will be merged into the KvDev branch instead. https://github.com/Azure/azure-sdk-for-net/pull/3815

2017-10-25 00:00 UTC, closed without merging