Azure SDK for PowerBI Dedicated
Azure/azure-sdk-for-net pull request #3788
Opened 2017-10-16 12:11 UTC by selasagi

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [V] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [V] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [V] Title of the pull request is clear and informative.
- [V] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [V] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [V] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [V] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [V] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-10-16 18:49 UTC, shahabhijeet requested changes
Missing description. This PR cannot be reviewed if there is no information that describes what this PR is about.
Add detail description about the change
Link to spec PR
make sure CI is passing.

2017-10-16 20:19 UTC, selasagi commented
**Description:**
First generation of SDK for Power BI Dedicated resource. New Azure resource which simplify the way ISVs and developers use Power BI capabilities.
**Link to spec PR:** 
https://github.com/Azure/azure-rest-api-specs/tree/current/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/2017-10-01/powerbidedicated.json

Thanks!

2017-10-27 14:12 UTC, shahabhijeet requested changes

2017-10-27 14:12 UTC, shahabhijeet commented on src/SDKs/PowerBIDedicated/Management.PowerBIDedicated/Microsoft.Azure.Management.PowerBIDedicated.csproj
> +  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.4' ">
@selasagi you don't need any of these references. Please model your sdk project file by looking at other project files in the repo, e.g. https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/BatchAI/Management.BatchAI/Microsoft.Azure.Management.BatchAI.csproj

2017-10-27 14:12 UTC, shahabhijeet commented on src/SDKs/PowerBIDedicated/Management.PowerBIDedicated/Microsoft.Azure.Management.PowerBIDedicated.csproj
> +    <PackageTags>Microsoft Azure resource management;asazure;REST HTTP client;azureofficial;windowsazureofficial;netcore451511</PackageTags>
@selasagi also add PackageReleaseNotes for your nuget package.
As this is your first version for this brand new service, start with 0.9.0-preview
Any questions reach out to me.

2017-10-30 11:35 UTC, closed without merging