Workload Identity Support for AzureComponentFactory
Azure/azure-sdk-for-net pull request #37944
Opened 2023-07-31 22:40 UTC by wsugarman

- Allow `AzureCredentialFactory` to create instances of `WorkloadIdentityCredential` based on the new `"workloadidentity"` `credential` value
  - Workload Identity credentials must have a Tenant Id, Client Id, and a Token File Path specified
  - Add new `tokenFilePath` field to the configuration expected by `ClientFactory.CreateCredential`
- Update `Azure.Identity` version to `1.9.0` across the repository to support `WorkloadIdentityCredential`

2023-07-31 22:51 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-08-01 13:28 UTC, jsquire requested changes
Hi @wsugarman.  Thank you for your contribution and interest in improving the Azure developer experience.  As mentioned in #37943, I'd like to seek some perspectives from our Identity team before we make a decision on whether to move forward with these enhancements.

I'm going to mark as requesting changes in the meantime, to prevent any accidental approvals/merges.

2023-08-01 19:38 UTC, jsquire commented
Hi @wsugarman.   Thanks for your patience.  I was able to find the right folks for perspective, and we're in agreement that this serves a core scenario and is an enhancement that we'd like to include.  If you're willing, would you please add an entry in the [changelog](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Extensions.Azure/CHANGELOG.md) that describes the new value?   Beyond that, it looks like we're good to merge.

2023-08-01 22:30 UTC, wsugarman commented
@jsquire Awesome! I've added to the changelog (as well as added a comment in the code). Please let me know if you'd like to see any other changes.

2023-08-03 14:15 UTC, jsquire approved these changes

2023-08-03 14:15 UTC, jsquire commented on sdk/extensions/Microsoft.Extensions.Azure/CHANGELOG.md
> +- Updated dependency `Azure.Identity` to version `1.9.0`
```suggestion
- Updated dependency `Azure.Identity` to version `1.9.0`.
```

2023-08-03 14:16 UTC, jsquire commented
Thanks, @wsugarman.   Looks good.  I'll get this merged in and we'll look to release the new version as part of our August cycle next week.

2023-08-03 15:05 UTC, merged