Adding Web Search C# cognitive SDK
Azure/azure-sdk-for-net pull request #3818
Opened 2017-10-27 21:20 UTC by sudhansu88

This also updates Entity Search SDK and related namespaces

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-10-30 19:12 UTC, sudhansu88 commented
Ping ! Can somebody please start looking into this ?

2017-10-30 19:58 UTC, markcowl commented
@azuresdkci add to whitelist

2017-10-30 20:57 UTC, sudhansu88 commented on src/SDKs/CognitiveServices/dataPlane/Search/Search/Customizations/ApiKeyServiceClientCredentials.cs
> +        private const string SDKIdentifier = "Search.CSharp.1.0";
Removed

2017-10-31 21:24 UTC, markcowl requested changes

2017-10-31 21:24 UTC, markcowl commented on src/SDKs/CognitiveServices/dataPlane/Search/Search/Microsoft.Azure.CognitiveServices.Search.csproj
>      <VersionPrefix>1.0.0-preview</VersionPrefix>
If you want to release this, you should update the package version

2017-10-31 22:13 UTC, shahabhijeet requested changes
Please update version changes in AssemblyInfo.cs as well.

2017-10-31 22:54 UTC, sudhansu88 commented
Updated Package versions based on feedback. Please let me know further

2017-11-01 19:36 UTC, shahabhijeet requested changes
Why is this 2.0.0? Upgrading a major version usually means you either have breaking changes or have lot of new functionality. As you are still in preview, what difference does it make if you are 1.1.0-preview. Be conservative with your version numbers for preview.
If you still want to do it have the release notes reflect what are the changes that are going in that makes a compelling reason for it to have 2.0.0 version.

2017-11-01 19:45 UTC, sudhansu88 commented
Current Change adds Web Search functionality to already existing SDK  [with Entity Search] So I think this would be a major change. But as we are still in preview [ Considering we have not published any SDK versions until now ] we can be conservative here to go with  1.1.0-preview. Will update to  1.1.0-preview.
Thanks !

2017-11-02 19:50 UTC, merged