Ran generate code
Azure/azure-sdk-for-net pull request #39025
Opened 2023-09-28 18:50 UTC by alec-baird

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-09-29 13:32 UTC, jsquire requested changes, later dismissed
@alec-baird:   Your account is being flagged as a community contributor.  Please review the Azure SDK onboarding documentation and ensure that your GitHub organization membership and permissions are correct.  

- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

2023-09-29 19:35 UTC, alec-baird commented
Requested access to sdk-write team, will update here when access is given.

2023-09-29 20:08 UTC, jsquire commented
Thanks, @alec-baird.   I've reset my request and will hand-off to @ArthurMa1978 and team for review.

2023-09-29 20:37 UTC, alec-baird commented
I have receieved access to the following sdk team: https://github.com/orgs/Azure/teams/azure-sdk-write-avd/ , so the PR should be able to move forward

2023-10-18 06:32 UTC, ArcturusZhang reviewed
Please always run the following command after you change the generated code to generate the api files as well. The api file is the main focus of reviewing a SDK update.
```
.\eng\scripts\Export-API.ps1 desktopvirtualization
```
Please run this command at the root directory of azure-sdk-for-net repo, and push everything to the branch.
I notice your PR is introducing SDK breaking changes. We need to introduce customization code to mitigate them, but for starter, let us include the changes in the api files so that we could know how exactly the breaking change looks like

2023-10-19 14:21 UTC, ArcturusZhang reviewed
Please check the comments for renaming some too generic names.
Here are some guides on how to do that: https://github.com/Azure/autorest.csharp/blob/feature/v3/docs/mgmt/polishing.md#rename-a-type
Please check this section to enable the debug options to show the original names of properties to make this easier: https://github.com/Azure/autorest.csharp/blob/feature/v3/docs/mgmt/polishing.md#how-to-get-original-name

2023-10-19 14:21 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/api/Azure.ResourceManager.DesktopVirtualization.netstandard2.0.cs
> +    public readonly partial struct HostpoolPublicNetworkAccess : System.IEquatable<Azure.ResourceManager.DesktopVirtualization.Models.HostpoolPublicNetworkAccess>
This must be a typo, it should be Host**P**oolPublicNetworkAccess

Please introduce a renaming for this.

2023-10-19 14:21 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/api/Azure.ResourceManager.DesktopVirtualization.netstandard2.0.cs
> +    public partial class DesktopVirtualizationPrivateLinkResource : Azure.ResourceManager.Models.ResourceData
Could we rename this to `DesktopVirtualizationPrivateLinkResourceData`?

2023-10-19 14:21 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/api/Azure.ResourceManager.DesktopVirtualization.netstandard2.0.cs
> +    public partial class PrivateEndpointConnectionWithSystemDataData : Azure.ResourceManager.Models.ResourceData
This is quite not a good name, could we rename this to something like `DesktopVirtualizationPrivateEndpointConnectionData`?

2023-10-19 14:21 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/api/Azure.ResourceManager.DesktopVirtualization.netstandard2.0.cs
> +    public readonly partial struct PublicNetworkAccess : System.IEquatable<Azure.ResourceManager.DesktopVirtualization.Models.PublicNetworkAccess>
This name is quite generic, could we rename this to `DesktopVirtualizationPublicNetworkAccess`?

2023-10-20 02:46 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/autorest.md
> +  DesktopVirtualizationPrivateLinkResource: DesktopVirtualizationPrivateLinkResourceData
the key here should be `PrivateLinkResource` to take effect

2023-10-20 02:47 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/autorest.md
> +  PrivateEndpointConnectionWithSystemDataData: DesktopVirtualizationPrivateEndpointConnectionData
the key here should be `PrivateEndpointConnectionWithSystemData` to take effect

2023-10-20 02:53 UTC, ArcturusZhang commented
There are also some breaking changes reported by the API compat tool: https://github.com/Azure/azure-sdk-for-net/pull/39025/checks?check_run_id=17882734745
To resolve them, let me take one of them as example:
```
Error : MembersMustExist : Member 'public Azure.ResourceManager.DesktopVirtualization.HostPoolData Azure.ResourceManager.DesktopVirtualization.Models.ArmDesktopVirtualizationModelFactory.HostPoolData(...)
```
This is saying there is a method `HostPoolData` with specified parameters in class `Azure.ResourceManager.DesktopVirtualization.Models.ArmDesktopVirtualizationModelFactory` is not found in your new code but it existed in the previous code.
You need to:
Introduce a partial class `ArmDesktopVirtualizationModelFactory` and put the file in `Custom` directory under the `Azure.ResourceManager.DesktopVirtualization` (parallel with the directory `Generated`), and the class should look like this:
```csharp
public static partial class ArmDesktopVirtualizationModelFactory
{
// copy all the xml docs from the method HostPoolData on PREVIOUS code (you could find this in git)
public static HostPoolData HostPoolData() // copy the signature of this method from PREVIOUS code here
    => HostPoolData(); redirect this method from old code to the method in new code, if there is any parameter missing, using `default` or `null`.
}
```
Please also do the same for other methods reported in the log

2023-10-20 07:20 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Custom/ArmDesktopVirtualizationModelFactory.cs
> +    public static HostPoolData HostPoolData(ResourceIdentifier id, string name, ResourceType resourceType, SystemData systemData, IDictionary<string, string> tags, AzureLocation location, string obje
this is a method instead of a constructor, we should not have a `: base()` here

2023-10-24 20:04 UTC, alec-baird commented
It looks like the issue is when we overload the function, it can't find where the overloaded function definition is in Generated.. so we get compiler errors that we can't find the overloaded function. Do you have any insight here?

2023-10-25 06:04 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Customize/ArmDesktopVirtualizationModelFactory.cs
> +namespace Azure.ResourceManager.DesktopVirtualization.Customize
this namespace should be same as the generated `ArmDesktopVirtualizationModelFactory` class
```suggestion
namespace Azure.ResourceManager.DesktopVirtualization.Models
```

2023-10-25 06:31 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Customize/ArmDesktopVirtualizationModelFactory.cs
> +        public static HostPoolData HostPoolData(ResourceIdentifier id, string name, ResourceType resourceType, SystemData systemData, IDictionary<string, string> tags, AzureLocation location, string
Please add a `[EditorBrowsable(EditorBrowsableState.Never)]` attribute to every method inside this customized partial class

2023-10-26 03:08 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Customize/ArmDesktopVirtualizationModelFactory.cs
> +        public static HostPoolData HostPoolData(ResourceIdentifier id, string name, ResourceType resourceType, SystemData systemData, IDictionary<string, string> tags, AzureLocation location, string
there is a parameter `IReadOnlyList<string> applicationGroupReferences`, we need to change its type to `IEnumerable<string>`

2023-10-26 03:09 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/src/Customize/ArmDesktopVirtualizationModelFactory.cs
> +        public static VirtualWorkspaceData VirtualWorkspaceData(ResourceIdentifier id, string name, ResourceType resourceType, SystemData systemData, IDictionary<string, string> tags, AzureLocation l
there is a parameter `IList<string> applicationGroupReferences`
we need to change its type to `IEnumerable<string>`

2023-10-26 03:13 UTC, ArcturusZhang reviewed
Left two comments in the customized model factory, which should resolve the apicompat issue.
We have a "duplicate file" issue. This usually happens when we introduce a rename which only change the casing of one file on Windows because windows system filenames are case-insensitive.
You could find more details about this issue in the `checks` which tells you the name of that file.
I usually solve this using the following steps:
1. `git rm -rf ./src/Generated`: this removes the whole directory of Generated. Since this directory only contains generated files and we could easily get it back by just regenerating the library, it is OK
2. `git commit -m "temp"`: commits the removal to ensure windows does not do some funny things
3. `dotnet build /t:GenerateCode`: regenerate everything
4. commit everything and push to the branch
But feel free to take any step that could solve this issue. If we know the filename, a `git mv` command should do the trick

2023-10-27 05:45 UTC, ArcturusZhang commented on sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/CHANGELOG.md
>  ### Bugs Fixed
I believe if we remove this subsection, the CI could pass. It is complaining that changelog should not have empty sections.

2023-10-27 05:58 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.DesktopVirtualization](https://apiview.dev/Assemblies/Review/a65270707c6f494cb10564a0ba952787)

2023-10-27 06:39 UTC, ArcturusZhang approved these changes

2023-10-27 06:40 UTC, merged