Azure Redis .Net SDK update for new api v2023-08-01
Azure/azure-sdk-for-net pull request #39230
Opened 2023-10-12 19:33 UTC by koderjoker

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redis/resource-manager/Microsoft.Cache/stable/2023-08-01/redis.json

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2023-10-12 21:27 UTC, pallavit commented
@koderjoker this PR is getting tagged as a community contribution. Please review the Azure SDK onboarding documentation and ensure that your GitHub organization membership and permissions are correct.

[Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) (Microsoft internal)
[Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) (Microsoft internal)

/cc: @ArthurMa1978. Also please ensure you have the correct aliases are added to the code owners file - https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS

2023-10-13 06:39 UTC, koderjoker commented
@pallavit no new names to add to Code Owners from our side

2023-10-13 10:59 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.Redis](https://apiview.dev/Assemblies/Review/ee79ff326fae4824bd8f01607d850abf)

2023-11-21 15:38 UTC, koderjoker commented
Test recording in progress, will push session records once complete

2023-11-29 19:37 UTC, koderjoker commented
Recordings updated as part of https://github.com/Azure/azure-sdk-assets/releases/tag/net%2Fredis%2FAzure.ResourceManager.Redis_50c384bcc2

2023-11-29 20:30 UTC, jsquire requested changes, later dismissed
@koderjoker:  You are still coming up as having none of the public organizations required nor write permissions in the repository.   Please review the Azure SDK onboarding guide. 
  This will need to be corrected before this PR can move forward.

2023-11-30 07:51 UTC, koderjoker commented
@jsquire I'm already a part of Azure GitHub and Azure SDK partners. Applied for write permissions for Azure cache for Redis SDKs.

2023-11-30 07:53 UTC, koderjoker commented
/azp run

2023-12-02 04:09 UTC, koderjoker commented
/azp run

2023-12-02 05:29 UTC, koderjoker commented
Hi @archerzz @jsquire @tg-msft @KrzysztofCwalina @ArcturusZhang @pallavit @ArthurMa1978 @live1206! Who would be the assigned reviewer for this PR?

Despite the PR having the latest code generated and recordings for 2023-08-01 https://github.com/Azure/azure-sdk-assets/releases/tag/net%2Fredis%2FAzure.ResourceManager.Redis_50c384bcc2, the pipeline is showing errors regarding both

2023-12-04 06:02 UTC, archerzz requested changes

2023-12-04 10:04 UTC, koderjoker commented
> > Hi @archerzz @jsquire @tg-msft @KrzysztofCwalina @ArcturusZhang @pallavit @ArthurMa1978 @live1206! Who would be the assigned reviewer for this PR?
> > Despite the PR having the latest code generated and recordings for 2023-08-01 [Azure/azure-sdk-assets@`net%2Fredis%2FAzure.ResourceManager.Redis_50c384bcc2` (release)](https://github.com/Azure/azure-sdk-assets/releases/tag/net%2Fredis%2FAzure.ResourceManager.Redis_50c384bcc2), the pipeline is showing errors regarding both
> 
> @koderjoker I think the error message is quite clear:
> 
> ```
> Generated code is not up to date.
>     You may need to rebase on the latest main, 
>     run 'eng\scripts\Update-Snippets.ps1' if you modified sample snippets or other *.md files (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#updating-sample-snippets), 
>     run 'eng\scripts\Export-API.ps1' if you changed public APIs (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#public-api-additions). 
>     run 'dotnet build /t:GenerateCode' to update the generated code and samples.
>     
> To reproduce this error locally, run 'eng\scripts\CodeChecks.ps1 -ServiceDirectory redis'.
> ```
@archerzz running `eng\scripts\CodeChecks.ps1 -ServiceDirectory redis` as mentioned in the error, on our local gives us 0 errors. 

No new code is generated when `eng\scripts\Export-API.ps1` or `dotnet build /t:GenerateCode` are run, and no snippets on running `eng\scripts\Update-Snippets.ps11

2023-12-05 04:18 UTC, koderjoker commented
@jsquire corrected

2023-12-05 15:23 UTC, jsquire commented
> [koderjoker](/koderjoker)

Thanks.  Confirmed that we're looking good.   Removing my block.   Please work with Arthur and team on the code review.

2023-12-09 08:00 UTC, koderjoker commented on sdk/redis/Azure.ResourceManager.Redis/src/Generated/RedisCacheAccessPolicyAssignmentData.cs
> +        public string ObjectId { get; set; }
Updated as GUID

2023-12-09 08:01 UTC, koderjoker commented on sdk/redis/Azure.ResourceManager.Redis/src/Generated/Models/RedisCommonConfiguration.cs
> +        public string AadEnabled { get; set; }
Renamed as IsAadEnabled

2023-12-13 10:01 UTC, koderjoker commented
Updated session records: https://github.com/Azure/azure-sdk-assets/tree/net/redis/Azure.ResourceManager.Redis_73d38d0d17/net/sdk/redis/Azure.ResourceManager.Redis/tests/SessionRecords

2023-12-14 02:37 UTC, archerzz approved these changes
@koderjoker LGTM.

By the way, if you are going to release a new version, don't forget to update `CHANGELOG.md`. See [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=signing-and-publishing-nuget-packges) for details.

2023-12-15 08:11 UTC, archerzz approved these changes

2023-12-15 08:11 UTC, merged