Add Microsoft.NetworkAnalytics RP SDK package
Azure/azure-sdk-for-net pull request #39240
Opened 2023-10-13 02:45 UTC by gaagarwalMS

## Adding SDK package and the generated code for the Microsoft.NetworkAnalytics RP

Test Results:
![image](https://github.com/Azure/azure-sdk-for-net/assets/120563366/2120ac1b-264d-47a5-b637-f12440d31539)

2023-10-13 13:15 UTC, jsquire commented
@gaagarwalMS:  Our automation is recognizing you as a community member.  Please review the Azure SDK onboarding documentation and ensure that your GitHub organization membership and permissions are correct before moving this out of draft. 

- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

2023-10-16 04:00 UTC, ArthurMa1978 commented on sdk/hdinsight/ci.mgmt.yml
> -    - sdk/hdinsight/Azure.ResourceManager.HDInsight/
revert this change

2023-10-16 04:00 UTC, ArthurMa1978 requested changes, later dismissed
This is the first release for your service, did you get the namespace review for it? If yes can you provide the like of the [request](https://github.com/Azure/azure-sdk-pr/issues/new?assignees=kyle-patterson%2C+ronniegeraghty&labels=architecture%2C+board-review%2C+mgmt-namespace-review&projects=&template=adp_mgmt_namespace_review.md&title=Board+Review%3A+Management+Plane+Namespace+Review+%3Cclient+library+name%3E)? If no, please file the request for review.

2023-10-16 04:01 UTC, ArthurMa1978 commented on sdk/networkanalytics/Azure.ResourceManager.NetworkAnalytics/src/Properties/AssemblyInfo.cs
> +[assembly: Azure.Core.AzureResourceProviderNamespace("NetworkAnalytics")]
Microsoft.NetworkAnalytics

2023-10-16 04:02 UTC, ArthurMa1978 commented on sdk/networkanalytics/Azure.ResourceManager.NetworkAnalytics/README.md
> +**[Describe the service briefly first.]**
Describe your service here

2023-10-16 05:26 UTC, gaagarwalMS commented
> This is the first release for your service, did you get the namespace review for it? If yes can you provide the like of the [request](https://github.com/Azure/azure-sdk-pr/issues/new?assignees=kyle-patterson%2C+ronniegeraghty&labels=architecture%2C+board-review%2C+mgmt-namespace-review&projects=&template=adp_mgmt_namespace_review.md&title=Board+Review%3A+Management+Plane+Namespace+Review+%3Cclient+library+name%3E)? If no, please file the request for review.

Yes, we have got the namespace approval for our service. Please find the link here:
[Mgmt Namespace Approval for Azure Operator Insights · Issue #867 · Azure/azure-sdk-pr (github.com)](https://github.com/Azure/azure-sdk-pr/issues/867)

2023-10-16 05:33 UTC, ArthurMa1978 commented on sdk/networkanalytics/Azure.ResourceManager.NetworkAnalytics/CHANGELOG.md
> +## 1.0.0-beta.1 (Unreleased)
Please specify the release date you expected by replacing the `Unreleased` , format is `yyyy-mm-dd`.

2023-10-23 03:35 UTC, ArthurMa1978 approved these changes

2023-10-23 03:35 UTC, merged