Regenerate SDKs with a missing parameter in AddFaceFromStream operation in FaceList
Azure/azure-sdk-for-net pull request #3941
Opened 2017-12-12 16:14 UTC by DavidLiCIG

Regenerate SDKs adding a missing parameter.

2017-12-12 19:29 UTC, shahabhijeet requested changes
Can you use the latest autorest 2.0.4221 or greater to generate the SDK.

2017-12-13 03:00 UTC, DavidLiCIG commented on src/SDKs/CognitiveServices/dataPlane/Vision/Vision.Tests/.vscode/launch.json
> +{
Removed

2017-12-13 03:00 UTC, DavidLiCIG commented on src/SDKs/CognitiveServices/dataPlane/Vision/Vision.Tests/.vscode/tasks.json
> +{
Removed

2017-12-13 03:01 UTC, DavidLiCIG commented
@shahabhijeet the latest version of Autorest as shown here is 4215?
https://www.npmjs.com/package/autorest

2017-12-13 08:47 UTC, DavidLiCIG commented
Not sure what the error from CI is all about though.

2017-12-14 06:28 UTC, shahabhijeet approved these changes

2017-12-14 06:29 UTC, merged