[CognitiveServices] LUIS Runtime SDK - Updates based on latest Spec
Azure/azure-sdk-for-net pull request #3946
Opened 2017-12-13 16:42 UTC by JuanAr

Updates based on latest Spec changes (Azure/azure-rest-api-specs#2083)
* Documentation updates
* New Operation IDs
* Unit tests for all operations

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-12-13 16:42 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-12-13 16:42 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-12-13 16:42 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-12-13 16:44 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-12-14 06:39 UTC, shahabhijeet requested changes
@JuanAr please fix your commit history, either squash or create a new PR
Can you also do the following in the below order:
1)	Pull latest from upstream (if you have already done this good)
2)	Execute msbuild.exe build.proj from the repo root
a.	This will update the build tools in the current repo
3)	Generate your SDK
4)	Build you sdk at least one from command line of IDE
a.	Msbuild.exe build.proj /t:build /p:Scope=SDKs\CognitiveService\management
5)	Update the PR

2017-12-14 17:59 UTC, JuanAr commented
Hi @shahabhijeet, 
The PR changelist was squashed and the build process tested as you requested. 
Regards,

2017-12-15 19:43 UTC, shahabhijeet commented
@DavidLiCIG can you approve this PR. Also JuanAr has to be part of Azure org on github

2017-12-19 19:49 UTC, chrimc62 approved these changes
Aside from the minor nit of XML comments needing periods at the end of sentences, this looks pretty good.  I like the extensive tests and the model is consistent with the API.  (Eventually I would prefer URLs not based on GUIDs so everything isn't two round trips.)

2017-12-19 19:49 UTC, chrimc62 commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS-Programmatic/Customizations/ApiKeyServiceClientCredentials.cs
> +        /// Creates a new instance of the ApiKeyServiceClientCredentails class
Documentation standards require punctuation and sentences here and throughout the file.

2017-12-19 19:49 UTC, chrimc62 commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS-Programmatic/Customizations/Models/ErrorResponse.cs
> +        public string Code
Missing documentation.

2017-12-21 23:14 UTC, shahabhijeet requested changes
Please talk to David li as I have suggested the directory structure for Language data plane SDK.
If you have any questions, please let me know.

Also please onboard using aka.ms/azuregithub
This seems you are not authorized to kick off CI jobs.
Once you get onboarded the CI job will be kicked off and once the CI passes this PR will be ready to be reviewed.

2017-12-22 09:27 UTC, DavidLiCIG commented
Hi @shahabhijeet, this directory structure looks fine and I agree with you on the other email with regards to modular Nuget packages. Let's get this in if it looks good.

2018-01-04 23:02 UTC, pcostantini commented
Hi @shahabhijeet  & @DavidLiCIG ,

The directory structure was updated as discussed and latest changes from the Spec added to the Programmatic SDK.

![image](https://user-images.githubusercontent.com/57197/34588115-1dcf1ef8-f18a-11e7-87ba-346342ece4c4.png)

2018-01-09 21:05 UTC, shahabhijeet commented
@JuanAr closing at request of Pablo

2018-01-09 21:05 UTC, closed without merging