Add optional deleteAll parameter
Azure/azure-sdk-for-net pull request #3959
Opened 2017-12-18 18:35 UTC by shutchings

## Description
When deleting an operationalization cluster we leave behind the ACR, Application Insights, and Storage Accounts so the user has them for history. However some users do not want to delete these manually if they are not needed. The optional 'deleteAll' parameter adds the ability to delete all resources associated with the cluster as well.

[REST spec PR](https://github.com/Azure/azure-rest-api-specs/pull/2078)
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2017-12-21 23:27 UTC, shahabhijeet requested changes
1. Please get latest from upstream
2. Execute from root msbuild build.proj (this will update the build tools)
3. Then build your project from IDE or command line
msbuild build.proj /t:Build /p:Scope=SDKs\MachineLEarningCompute
4. Update PR

2017-12-21 23:49 UTC, shutchings commented
Done. It looks like this created a new AzSdk.RP.props file. Are there any other expected changes?

2018-01-02 17:11 UTC, shutchings commented
@shahabhijeet Could I get another look at this? My powershell cmdlet release deadline is coming up. Thanks!

2018-01-03 07:01 UTC, shahabhijeet requested changes

2018-01-03 07:01 UTC, shahabhijeet commented on src/SDKs/MachineLearningCompute/Management.MachineLearningCompute/Microsoft.Azure.Management.MachineLearningCompute.csproj
> +        <PackageTags>Microsoft Azure Machine Learning Compute management;REST HTTP client;azureofficial;windowsazureofficial;netcore451511</PackageTags>
@shutchings please remove all the extra tags that were removed earlier. Those tags does not make any sense.
All these tags are not required for searching your nuget package. Please remove them. We are cleaning these tags across all SDKs.

2018-01-03 18:00 UTC, shutchings commented
@shahabhijeet I removed the tags. Anything else?

2018-01-04 05:59 UTC, shahabhijeet approved these changes

2018-01-04 05:59 UTC, merged