Added two new operations for Management Consumption
Azure/azure-sdk-for-net pull request #3972
Opened 2018-01-03 21:36 UTC by kc786

1. Reservation Summaries
2. Reservation Details

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-01-04 06:07 UTC, shahabhijeet requested changes
1) Get latest updates from upstream (if you have not done so in last 3 weeks)
2) Then execute msbuild build.proj to update your build tools
3) Then regenerate your SDK using generate.cmd (this will regenerate couple of additional files)
4) build you project (ether IDE or command line)
5) Then update your PR
With the latest changes, every regeneration will generate couple of additional meta data files that are needed in each PR.

2018-01-04 06:07 UTC, shahabhijeet commented on src/SDKs/Consumption/Management.Consumption/Microsoft.Azure.Management.Consumption.csproj
> +        <PackageReleaseNotes />
@kc786 please add package release notes

2018-01-04 19:18 UTC, kc786 commented
Done With Changes

2018-01-05 00:17 UTC, shahabhijeet approved these changes

2018-01-05 00:18 UTC, merged