Adding interfaces and base classes for exceptions
Azure/azure-sdk-for-net pull request #3975
Opened 2018-01-03 23:04 UTC by dsgouda

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-01-10 02:36 UTC, shahabhijeet requested changes

2018-01-10 02:36 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/IRestException.cs
> +    public interface IRestException
@dsgouda something to consider this for this feature.
Your intend is to provide a constraint for your generated exceptions and not create exceptions and return for clients to use it.
Move properties out of the Interface and into the base class

2018-01-10 02:36 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestException.cs
> +    public class RestException : Exception, IRestException
@dsgouda do not change existing RestException.
This change can be made during breaking change cycle.

2018-01-10 02:36 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestExceptionGeneric.cs
> +        public V Body { get; private set; }
Change Body to ErrorModel or ResponseErrorModel. Bascially idea is to use the same name that we use during swagger review.
Remove private setter (basically nothing that you gain out of making it private) if made public also aligns with CloudException body property

2018-01-10 02:36 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestExceptionGeneric.cs
> +        public virtual void SetErrorModel(V model)
@dsgouda once Body/ErrorModel has public setter, this function is no longer needed.

2018-01-10 02:36 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestExceptionGeneric.cs
> +        public int ResponseStatusCode { get; set; }
@dsgouda we no longer need this as discussed during PR review.

2018-01-26 19:32 UTC, dsgouda commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestExceptionGeneric.cs
> +        public RestException()
Call the base from constructor

2018-01-26 19:33 UTC, dsgouda commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestExceptionGeneric.cs
> +        public RestException(string message, HttpRequestMessageWrapper requestMessage, HttpResponseMessageWrapper responseMessage) : base(message)
Remove this

2018-02-01 17:23 UTC, shahabhijeet requested changes

2018-02-01 17:23 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/IRestErrorModel.cs
> +
missing xml comment avoids compiler warnings (we are already have more than 1000 warnings in our repo)
Please describe the interface and the purpose of the interface.

2018-02-01 17:23 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestExceptionGeneric.cs
> +using System;
xml comments and description for the class.
All public APIs get xml comments

2018-02-01 17:23 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime/ClientRuntime/RestExceptionGeneric.cs
> +
missing RequestId as we discussed earlier

2018-02-03 02:01 UTC, closed without merging