Shihying sdk0801
Azure/azure-sdk-for-net pull request #4014
Opened 2018-01-24 10:08 UTC by shihying

## Description

Onboard API version 0801, regenerate ASAzure SDK based on a 0801 version swagger spec.
https://github.com/Azure/azure-rest-api-specs/commit/cb9c18b988dd67894653a34dc55b7978403b120a
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-01-25 07:00 UTC, shahabhijeet requested changes
do the following in below order
1) Generate SDK using generate.cmd (this add required meta data file)
2) Once SDK generated, build your project as below
msbuild build.proj /t:build /p:Scope=SDKs\AnalysisServices
this will add second meta data file that is required.
Update the PR

2018-01-25 07:00 UTC, shahabhijeet commented on src/SDKs/AnalysisServices/Management.Analysis/Microsoft.Azure.Management.Analysis.csproj
> +		<PackageId>Microsoft.Azure.Management.Analysis</PackageId>
Add package release notes

2018-01-25 08:36 UTC, shihying commented on src/SDKs/AnalysisServices/Management.Analysis/Microsoft.Azure.Management.Analysis.csproj
> +		<PackageId>Microsoft.Azure.Management.Analysis</PackageId>
thanks!

2018-01-25 08:37 UTC, shihying commented
@shahabhijeet

Thanks for reminder, have used generate.cmd and rebuild to generate metadata file
Also updated release note.

2018-02-02 01:16 UTC, shahabhijeet approved these changes

2018-02-02 01:16 UTC, merged