Added support for Autotuning API
Azure/azure-sdk-for-net pull request #4015
Opened 2018-01-24 11:08 UTC by kosta-bizetic

## Description

---

I generated C# libraries using Autorest for these two APIs:

[https://docs.microsoft.com/en-us/rest/api/sql/serverautomatictuning](url)
[https://docs.microsoft.com/en-us/rest/api/sql/databaseautomatictuning](url)

and added a test for each API

Swagger specs were already in azure-rest-api-specs. I added them to the corresponding readme.md.

Link to the azure-rest-api-specs PR [https://github.com/Azure/azure-rest-api-specs/pull/2325]()

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-01-24 11:09 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-01-24 11:09 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-01-24 11:09 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-01-24 11:09 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-sdk-for-net?pullRequest=4015) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-sdk-for-net?pullRequest=4015) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-sdk-for-net?pullRequest=4015) it.</sub>

2018-01-24 11:13 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-01-25 07:05 UTC, shahabhijeet requested changes
Use generate.cmd to generate you SDK
Second build your project as below
msbuild build.proj /t:build /p:Scope=SDKs\SqlManagement
this will create a meta data file that is required (if there are any changes in the API version)

2018-01-25 07:05 UTC, shahabhijeet commented
@kosta-bizetic get onboarded to github by visting aka.ms/azuregithub
This will allow you to get required permisison to kick off CI process.
Also make sure you create an account in travis by visiting travis-ci.org

2018-01-25 11:44 UTC, kosta-bizetic commented
I have created an account on travis-ci.org so I should have the permissions now.

I have built the SDK prior to this PR and even when I build it now using your command I still don't see any meta data file. Where should it appear?

2018-01-25 11:46 UTC, kosta-bizetic commented
Here is the link to the new PR for azure-rest-api-specs [https://github.com/Azure/azure-rest-api-specs/pull/2332](https://github.com/Azure/azure-rest-api-specs/pull/2332)

2018-01-25 20:05 UTC, jaredmoo approved these changes

2018-01-25 20:05 UTC, jaredmoo commented on src/SDKs/SqlManagement/Sql.Tests/AutomaticTuningOperationsTests.cs
> +                        {"createIndex", new AutomaticTuningServerOptions() {DesiredState=AutomaticTuningOptionModeDesired.On} },
is there an enum for these options?

2018-01-25 21:01 UTC, kosta-bizetic commented on src/SDKs/SqlManagement/Sql.Tests/AutomaticTuningOperationsTests.cs
> +                        {"createIndex", new AutomaticTuningServerOptions() {DesiredState=AutomaticTuningOptionModeDesired.On} },
There isn't

2018-01-26 17:02 UTC, kosta-bizetic commented
@shahabhijeet can you tell me more about the meta data file?

2018-01-31 00:36 UTC, shahabhijeet commented
@azuresdkci retest this please

2018-01-31 00:36 UTC, shahabhijeet commented
@azuresdkci test this please

2018-01-31 00:37 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-01-31 00:37 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-01-31 00:37 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-01-31 11:26 UTC, kosta-bizetic commented
@shahabhijeet 
I merged changes from psSdkJson6 into my branch, regenerated and rebuilt the code, and run the tests again. Is the sql_resource-manager.txt from the latest commit the meta data file that should appear?

2018-01-31 20:43 UTC, shahabhijeet commented
@kosta-bizetic I do not see Jenkins job completed for your PR.
Unless Jenkins job is a success, this PR cannot be merged.
Have you onboarded using aka.ms/azuregithub?

2018-02-01 10:06 UTC, kosta-bizetic commented
@shahabhijeet All checks have passed. Can the PR be merged now?

2018-02-01 10:10 UTC, kosta-bizetic commented
@shahabhijeet All checks have passed. Can the PR be merged now?

2018-02-02 21:30 UTC, shahabhijeet approved these changes

2018-02-02 21:31 UTC, merged