Make Reason required for attribute CallerShouldAuditAttribute
Azure/azure-sdk-for-net pull request #40682
Opened 2023-12-11 05:22 UTC by RodgeFu

Make Reason required for attribute CallerShouldAuditAttribute as discussed in https://github.com/Azure/azure-sdk-for-net/pull/40548

2023-12-11 05:32 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-12-11 06:35 UTC, RodgeFu commented
@tg-msft, could you help to suggest how these compat issues could be handled? thanks.

2023-12-12 04:37 UTC, RodgeFu commented
double check the error and found the Attribute had already been released in some sdk which means removing the parameterless ctor will introduce compatibility issue for these SDKs, so I am going to close this PR considering we are holding a high bar for compatibility for .Net as I understand. 

@heaths , please let me know if you still think we should make the change with the compat issue handled in some way. thanks.

2023-12-14 18:56 UTC, heaths commented
> double check the error and found the Attribute had already been released in some sdk which means removing the parameterless ctor will introduce compatibility issue for these SDKs, so I am going to close this PR considering we are holding a high bar for compatibility for .Net as I understand.
> 
> @heaths , please let me know if you still think we should make the change with the compat issue handled in some way. thanks.

It's shared source - the source file is included and compiled into the binary, so there's no way to break it. Changing it and shipping a new copy in other SDKs - and eventually a newer version of the older SDK - won't be breaking. We should still consider making this required if our goal is indeed to require it. /cc @tg-msft

2023-12-18 09:07 UTC, RodgeFu commented
@tg-msft, since the compatibility errors are reported from Data Plain code of storage and table, could you help to review and confirm the change looks good and how we can ignore these errors so that they won't block the merge? thanks.

copied one compatibility error here for your convenience:
```
/mnt/vss/_work/1/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.20467.1/build/Microsoft.DotNet.ApiCompat.targets(82,5): Error : CannotRemoveAttribute : Attribute 'Azure.Core.CallerShouldAuditAttribute' exists on 'Azure.Data.Tables.TableClient.GenerateSasUri(Azure.Data.Tables.Sas.TableSasBuilder)' in the contract but not the implementation.
```

2024-01-03 21:18 UTC, heaths requested changes

2024-01-03 21:18 UTC, heaths commented on sdk/keyvault/Azure.Security.KeyVault.Administration/src/KeyVaultAccessControlClient.cs
> +        [CallerShouldAudit(reason: KeyVaultAdministrationClientOptions.CallerShouldAuditReason)]
Nit: this works (obviously it compiles) but is atypical. Can we just remove the `reason: ` named parameter in all instances?

2024-01-09 06:37 UTC, RodgeFu commented
@heaths , @tg-msft , please help to review and confirm you are fine with the change in Data Plane and how I can ignore these compatible errors so that they won't block the merge. thanks.

2024-01-10 00:33 UTC, heaths approved these changes

2024-01-10 07:24 UTC, RodgeFu commented
@heaths , do you know how we can skip these compatible errors from the pipeline check? Or any expertise I can ask for suggestions? thanks.

2024-01-10 08:07 UTC, heaths commented
@JoshLove-msft or @tg-msft any ideas about these validation errors? Seems we're including these internal attributes in the contract, but since they are internal, they don't appear in the actual public API so there's a discrepancy.

2024-01-10 15:37 UTC, JoshLove-msft commented
> @JoshLove-msft or @tg-msft any ideas about these validation errors? Seems we're including these internal attributes in the contract, but since they are internal, they don't appear in the actual public API so there's a discrepancy.

Were the attribute updates shipped already in GA versions of the KV libraries?

2024-01-10 15:40 UTC, heaths commented
An older version was, but we changed to require a reason parameter; however, this attribute is `internal` and shouldn't be considered part of the contract.

2024-01-10 15:46 UTC, JoshLove-msft commented
> An older version was, but we changed to require a reason parameter; however, this attribute is `internal` and shouldn't be considered part of the contract.

That's strange that ApiCompat would complain about it then. The only way I'm aware of to bypass this would be to modify the csproj to comment out the ApiCompatVersion, ship the new version, and finally uncomment (if it wasn't re-added automatically by the azure-sdk bot).

2024-01-10 17:36 UTC, heaths commented
You might also try https://learn.microsoft.com/dotnet/fundamentals/apicompat/diagnostic-ids#how-to-suppress

2024-01-10 17:38 UTC, JoshLove-msft commented
> You might also try https://learn.microsoft.com/dotnet/fundamentals/apicompat/diagnostic-ids#how-to-suppress

I would not do this as we have no way of ensuring it gets removed. I think with the ApiCompatVersion approach, after the release the Azure SDK bot will add it back (but not 100% sure). /cc @weshaggard

2024-01-10 22:03 UTC, weshaggard commented
You can create a baseline file for these errors. See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/src/ApiCompatBaseline.txt as an example. You will need to create a file with that exact name living next to the project file you want it to apply to and then copy the error from the output into that text file one line at a time.

2024-01-12 00:54 UTC, heaths approved these changes

2024-01-12 01:19 UTC, merged