Generated SDK
Azure/azure-sdk-for-net pull request #40984
Opened 2024-01-03 20:30 UTC by 8Gitbrix

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-01-11 21:27 UTC, jsquire requested changes, later dismissed
@8Gitbrix :

You're missing "write" permissions to the repository.  Please review the Azure SDK onboarding documentation and request the correct set of permissions.

- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2024-01-12 14:54 UTC, ArthurMa1978 commented
/azp run prepare-pipelines

2024-01-12 16:12 UTC, ArthurMa1978 commented
/azp run prepare-pipelines

2024-01-12 18:53 UTC, 8Gitbrix commented
@jsquire Thanks for letting me know. Sorry which Azure-sdk-write org am I supposed to join?

2024-01-16 13:51 UTC, jsquire commented
> @jsquire Thanks for letting me know. Sorry which Azure-sdk-write org am I supposed to join? EDIT: NVM, I see there's an azure-sdk-write, just submitted a request to join

Please follow the linked onboarding guide, which walks you through requesting permissions.   Please use the linked Teams channel for assistance.

2024-01-18 18:54 UTC, 8Gitbrix commented
/azp run prepare-pipelines

2024-01-23 01:10 UTC, 8Gitbrix commented
Does anything else need to be done on my end to merge this?

2024-01-23 14:59 UTC, jsquire commented
> Does anything else need to be done on my end to merge this?

You'll need to work with @ArthurMa1978 and team to have this reviewed.

2024-01-23 15:05 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/azurelargeinstance                                             @8Gitbrix
```suggestion
# PRLabel: %Large Instance
/sdk/azurelargeinstance                                             @8Gitbrix

# ServiceLabel: %Large Instance %Service Attention
#/<NotInRepo>/                                                     @8Gitbrix
```

2024-01-25 07:02 UTC, ArthurMa1978 approved these changes

2024-01-25 09:19 UTC, merged