update roledefinition filters
Azure/azure-sdk-for-net pull request #4102
Opened 2018-03-02 23:22 UTC by darshanhs90

Linked to https://github.com/Azure/azure-rest-api-specs/pull/2586
waiting for https://github.com/Azure/azure-sdk-for-net/pull/4079 to be merged

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-03-05 23:11 UTC, dsgouda requested changes
Please pull down the latest changes and run:
-  `msbuild build.proj /t:build /p:Scope=SDKs\Monitor
-  generate.cmd` to generate the code
These steps should generate the `.props` and `.txt` files, you need to commit these files

2018-03-05 23:11 UTC, dsgouda commented on src/SDKs/Authorization/Authorization.Tests/Tests/BasicTests.cs
> +		public void RoleDefinitionsFilterTests()
nit: FIx indentation

2018-03-05 23:12 UTC, dsgouda commented
There are some build failures, please address them

2018-03-10 00:40 UTC, darshanhs90 commented
.props file isnt changed,since this isnt introducing a new api version

2018-03-10 00:41 UTC, darshanhs90 commented
@dsgouda Fixed the build issues

2018-03-10 01:19 UTC, dsgouda approved these changes
LGTM subject to successful CI builds, @shahabhijeet PTAL and merge

2018-03-10 02:27 UTC, shahabhijeet approved these changes

2018-03-10 02:28 UTC, merged