Generating control plane sdks for playwrighttesting
Azure/azure-sdk-for-net pull request #41123
Opened 2024-01-10 06:29 UTC by ShreyaAnand

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-01-10 14:48 UTC, jsquire requested changes, later dismissed
@ShreyaAnand :

Your account does not have the necessary  permissions to the repository, which are required for this PR to move forward.  Please review the Azure SDK onboarding documentation and ensure that your GitHub organization membership and permissions are correct.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2024-01-12 15:24 UTC, ArthurMa1978 commented
/azp run prepare-pipelines

2024-01-12 16:17 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.PlaywrightTesting](https://apiview.dev/Assemblies/Review/3336a4ab60d44be6a5540c888bceddf4?revisionId=3cefd31fe4e843da9ff52307b7ceb03d)

2024-01-18 02:56 UTC, ArthurMa1978 approved these changes

2024-01-18 14:30 UTC, jsquire approved these changes

2024-01-18 14:30 UTC, jsquire commented on .github/CODEOWNERS
> +# ServiceLabel: %Playwright Testing %Service Attention
```suggestion
# PRLabel: %Playwright
/sdk/playwrighttesting/                                            @shreyaanand @mjmadhu

# ServiceLabel: %Playwright %Service Attention
#/<NotInRepo>/                                                       @shreyaanand @mjmadhu
```

2024-01-18 14:30 UTC, jsquire commented on .github/CODEOWNERS
> +# ServiceLabel: %Playwright Testing %Service Attention
There is no existing label for this service, I created "Playwright", which we'll use.

The CODEOWNERS structure is invalid as written.   You cannot add both a PR Label and Service Label directive to the same path in this form; only the PR Label would have been applied.   I've corrected and ensured that we can tag "Service Attention" and alert the right contacts.

2024-01-18 14:31 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/playwrighttesting/                                            @shreyaanand @mjmadhu
```suggestion
```

2024-01-18 14:33 UTC, jsquire approved these changes

2024-01-18 14:33 UTC, jsquire commented on .github/CODEOWNERS
> +#/<NotInRepo>/                                                       @shreyaanand @mjmadhu
```suggestion
#/<NotInRepo>/                                                     @shreyaanand @mjmadhu
```

2024-01-19 04:57 UTC, merged