Fix Schema.
Azure/azure-sdk-for-net pull request #41166
Opened 2024-01-11 04:52 UTC by wangbwn

2024-01-11 04:52 UTC, wangbwn commented
[External Code]	
>	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.Models.AvroDataset.Azure.Core.IUtf8JsonSerializable.Write(System.Text.Json.Utf8JsonWriter writer) Line 33	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(System.Text.Json.Utf8JsonWriter writer, object value) Line 79	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DataFactoryDatasetData.Azure.Core.IUtf8JsonSerializable.Write(System.Text.Json.Utf8JsonWriter writer) Line 22	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(System.Text.Json.Utf8JsonWriter writer, object value) Line 79	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DatasetsRestOperations.CreateCreateOrUpdateRequest(string subscriptionId, string resourceGroupName, string factoryName, string datasetName, Azure.ResourceManager.DataFactory.DataFactoryDatasetData data, string ifMatch) Line 143	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DatasetsRestOperations.CreateOrUpdate(string subscriptionId, string resourceGroupName, string factoryName, string datasetName, Azure.ResourceManager.DataFactory.DataFactoryDatasetData data, string ifMatch, System.Threading.CancellationToken cancellationToken) Line 201	C#
 	Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DataFactoryDatasetCollection.CreateOrUpdate(Azure.WaitUntil waitUntil, string datasetName, Azure.ResourceManager.DataFactory.DataFactoryDatasetData data, string ifMatch, System.Threading.CancellationToken cancellationToken) Line 136	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore.__Await|0() Line 93	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Func<System.Threading.Tasks.ValueTask<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>> innerTask) Line 105	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Type genericType, Azure.Core.TestFramework.AsyncCallInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>> wrap) Line 126	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResult(Castle.DynamicProxy.IInvocation invocation, object target, System.Reflection.MethodInfo interceptorMethod) Line 73	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.InstrumentResultInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 77	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore.__Await|0() Line 93	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScopeInterceptor.AnonymousMethod__0() Line 174	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(System.Func<System.Threading.Tasks.ValueTask<(Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource> Result, bool SkipChecks)>> action, System.Reflection.MethodInfo methodInfo, string source) Line 208	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScopeInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Func<System.Threading.Tasks.ValueTask<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>> innerTask) Line 174	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Type genericType, Azure.Core.TestFramework.AsyncCallInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>> wrap) Line 126	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResult(Castle.DynamicProxy.IInvocation invocation, object target, System.Reflection.MethodInfo interceptorMethod) Line 73	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 45	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.GetOriginalInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 28	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.ManagementInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 27	C#
 	[External Code]	
 	Azure.ResourceManager.DataFactory.Tests.dll!Azure.ResourceManager.DataFactory.Tests.Scenario.DataFactoryDatasetResourceTests.Dataset_Avro_Create() Line 2255	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.RecordedTestAttribute.RecordedTestAttributeCommand.Execute(NUnit.Framework.Internal.TestExecutionContext context) Line 49	C#
 	[External Code]

2024-01-11 05:02 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.DataFactory](https://apiview.dev/Assemblies/Review/0dd9c8d2e38f4cd6981a3618a4a2dd86?revisionId=79a0fd14a4654395a32c8150fe2c3bb8)

2024-01-12 01:46 UTC, archerzz requested changes
Please double check the override of `Schema` property.

Also fix the pipeline error.

2024-01-12 01:46 UTC, archerzz commented on sdk/datafactory/Azure.ResourceManager.DataFactory/src/Customized/AvroDataset.cs
> +namespace Azure.ResourceManager.DataFactory.Models
Better to split this file into `AvroDataset.cs` and `AvroDataset.Serliaization.cs`.

2024-01-12 01:46 UTC, archerzz commented on sdk/datafactory/Azure.ResourceManager.DataFactory/src/Customized/AvroDataset.cs
> +        public new DataFactoryElement<BinaryData> Schema { get; set; }
You didn't override the parent `Schema` property. Are you sure this is what you want? https://github.com/Azure/azure-sdk-for-net/blob/9ac52a165101b727ff606dd50dd82f771ec7c710/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/Models/DataFactoryDatasetProperties.cs#L65

2024-01-12 01:46 UTC, archerzz commented on sdk/datafactory/Azure.ResourceManager.DataFactory/src/Customized/AvroDataset.cs
> +                    linkedServiceName = JsonSerializer.Deserialize<Core.Expressions.DataFactory.DataFactoryLinkedServiceReference>(property.Value.GetRawText());
```suggestion
                    linkedServiceName = JsonSerializer.Deserialize<DataFactoryLinkedServiceReference>(property.Value.GetRawText());
```

2024-01-12 16:42 UTC, ruowan commented
```
 	[External Code]	
>	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.Models.AvroDataset.Azure.Core.IUtf8JsonSerializable.Write(System.Text.Json.Utf8JsonWriter writer) Line 33	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(System.Text.Json.Utf8JsonWriter writer, object value) Line 79	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DataFactoryDatasetData.Azure.Core.IUtf8JsonSerializable.Write(System.Text.Json.Utf8JsonWriter writer) Line 22	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(System.Text.Json.Utf8JsonWriter writer, object value) Line 79	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DatasetsRestOperations.CreateCreateOrUpdateRequest(string subscriptionId, string resourceGroupName, string factoryName, string datasetName, Azure.ResourceManager.DataFactory.DataFactoryDatasetData data, string ifMatch) Line 143	C#
 	[Exception] Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DatasetsRestOperations.CreateOrUpdate(string subscriptionId, string resourceGroupName, string factoryName, string datasetName, Azure.ResourceManager.DataFactory.DataFactoryDatasetData data, string ifMatch, System.Threading.CancellationToken cancellationToken) Line 201	C#
 	Azure.ResourceManager.DataFactory.dll!Azure.ResourceManager.DataFactory.DataFactoryDatasetCollection.CreateOrUpdate(Azure.WaitUntil waitUntil, string datasetName, Azure.ResourceManager.DataFactory.DataFactoryDatasetData data, string ifMatch, System.Threading.CancellationToken cancellationToken) Line 136	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore.__Await|0() Line 93	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Func<System.Threading.Tasks.ValueTask<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>> innerTask) Line 105	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Type genericType, Azure.Core.TestFramework.AsyncCallInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>> wrap) Line 126	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResult(Castle.DynamicProxy.IInvocation invocation, object target, System.Reflection.MethodInfo interceptorMethod) Line 73	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.InstrumentResultInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 77	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore.__Await|0() Line 93	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScopeInterceptor.AnonymousMethod__0() Line 174	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(System.Func<System.Threading.Tasks.ValueTask<(Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource> Result, bool SkipChecks)>> action, System.Reflection.MethodInfo methodInfo, string source) Line 208	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScopeInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Func<System.Threading.Tasks.ValueTask<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>> innerTask) Line 174	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResultCore<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>>(Castle.DynamicProxy.IInvocation invocation, System.Type genericType, Azure.Core.TestFramework.AsyncCallInterceptor<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.DataFactory.DataFactoryDatasetResource>> wrap) Line 126	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.WrapAsyncResult(Castle.DynamicProxy.IInvocation invocation, object target, System.Reflection.MethodInfo interceptorMethod) Line 73	C#
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 45	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.GetOriginalInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 28	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.ManagementInterceptor.Intercept(Castle.DynamicProxy.IInvocation invocation) Line 27	C#
 	[External Code]	
 	Azure.ResourceManager.DataFactory.Tests.dll!Azure.ResourceManager.DataFactory.Tests.Scenario.DataFactoryDatasetResourceTests.Dataset_Avro_Create() Line 2255	C#
 	[External Code]	
 	Azure.Core.TestFramework.dll!Azure.Core.TestFramework.RecordedTestAttribute.RecordedTestAttributeCommand.Execute(NUnit.Framework.Internal.TestExecutionContext context) Line 49	C#
 	[External Code]	
```

2024-03-11 04:05 UTC, closed without merging