restore point create and delete API
Azure/azure-sdk-for-net pull request #4119
Opened 2018-03-09 18:06 UTC by sarvesh-s

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-03-09 18:20 UTC, sarvesh-s commented
Rest spec links
https://github.com/Azure/azure-rest-api-specs-pr/pull/374
https://github.com/Azure/azure-rest-api-specs-pr/pull/392
https://github.com/Azure/azure-rest-api-specs/pull/2593

2018-03-09 20:15 UTC, jaredmoo requested changes
Need test for delete, otherwise looks good :)

2018-03-10 02:42 UTC, shahabhijeet requested changes

2018-03-10 02:42 UTC, shahabhijeet commented on src/SDKs/_metadata/sql_resource-manager.txt
> +GitHub user: Azure
@sarvesh-s please pull from upstream and regenerate using generate.cmd
It has the fix to get you the commit id for your generation

2018-03-12 22:08 UTC, dsgouda requested changes
Looks like there are some breaking changes introduced here. Please bump the package version to `1.13.0-preview` in the csproj file.
Please pull down the latest changes from upstream and run
`msbuild build.proj /t:build /p:Scope=SDKs\SqlManagement`
This should update the `.props` file. Please commit these changes.

2018-03-15 23:51 UTC, shahabhijeet commented
@sarvesh-s we will do a final review as soon as @jaredmoo approves this PR

2018-03-19 19:16 UTC, shahabhijeet commented
@sarvesh-s this PR needs your attention. If you are not able to move forward, I request you to close this PR and open it when it's ready to be reviewed and signed off in due to time by your team.
This PR will be closed by EOW

2018-03-22 02:39 UTC, jaredmoo approved these changes

2018-03-22 02:42 UTC, sarvesh-s commented
I updated the PR, now I only have a test change. Rest of the code was already merged as part of different PR, @shahabhijeet

2018-03-23 01:08 UTC, shahabhijeet requested changes
Any idea why
src/SDKs/_metadata/sql_resource-manager.txt 
is a binary file in your PR?

2018-03-23 01:21 UTC, sarvesh-s commented
@jaredmoo Any idea why its binary file shown here as I don't see it locally, its plain text for me

2018-03-23 04:29 UTC, jaredmoo commented
```
git fetch --all
git reset --hard jaredmoo/sarvesh-fix
```

Then force push

2018-03-28 02:02 UTC, closed without merging