regenerate the sdk since the swagger is updated
Azure/azure-sdk-for-net pull request #4136
Opened 2018-03-15 20:09 UTC by jeffrey-ACE

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-03-15 23:55 UTC, shahabhijeet requested changes
Please add a link to your swagger spec PR.
Also please pull latest from upstream and use generate.cmd to generate your SDK.
Finally build after generation using
msbuild build.proj /t;build /p:Scope=SDKs\ManagementPartner

this will ensure all the meta data is generated required for the SDK to be merged.

2018-03-16 00:15 UTC, jeffrey-ACE commented
@shahabhijeet 
Swagger spec PR: https://github.com/Azure/azure-rest-api-specs/pull/2665 
Pulled from upstream.
For the other two steps, run generate.cmd and build, I did these too, no new change

2018-03-16 20:11 UTC, shahabhijeet approved these changes

2018-03-16 20:12 UTC, shahabhijeet commented
@jeffrey-ACE in order to publish, you will have to bump up the version as well as add ReleaseNotes.

2018-03-16 22:15 UTC, jeffrey-ACE commented
@shahabhijeet thank you, made the fix.

2018-03-19 19:20 UTC, shahabhijeet commented
@jeffrey-ACE you have to generate SDK using generate.cmd or generate.ps1
We cannot accept this PR without it.

2018-03-19 20:57 UTC, dsgouda commented
@jeffrey-ACE  Please create a `generate.ps1` script next to your `generate.cmd` and run it, this should generate the same code but with a diff in the .txt file. Please commit these changes

2018-03-19 21:15 UTC, dsgouda commented
@jeffrey-ACE  that was expected, we are moving towards replacing the .cmd file with a .ps1 script without affecting the code generation.
Your changes look good.

2018-03-19 22:23 UTC, jeffrey-ACE commented
@dsgouda cool, thanks, can you please also approve and merge this PR

2018-03-19 23:06 UTC, dsgouda commented on src/SDKs/ManagementPartner/Management.ManagementPartner/generate.ps1
> +powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -File "$(split-path $SCRIPT:MyInvocation.MyCommand.Path -parent)\..\..\..\..\tools\generateTool.ps1" -ResourceProvider "manag
@jeffrey-ACE Please remove the `-SdkDirectory` argument here and generate again.
Apologize for the confusion, will fix the example soon.

2018-03-19 23:28 UTC, dsgouda reviewed
Thanks @jeffrey-ACE LGTM subject to CI builds, will merge on passing.

2018-03-20 02:13 UTC, jeffrey-ACE commented
@dsgouda , all checks have passed, can you please merge

2018-03-20 16:49 UTC, merged