updating service fabric managed clusters sdk with 2023-12-01-preview api
Azure/azure-sdk-for-net pull request #41396
Opened 2024-01-18 19:14 UTC by mwesigwaguma

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-01-18 19:31 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.ServiceFabricManagedClusters](https://apiview.dev/Assemblies/Review/b95412e8fd364260ac8e7c648759a0f7?revisionId=80976ec2ce3b402d801b2e2cba643293)

2024-01-26 13:43 UTC, ArthurMa1978 requested changes
Please sync up the code with main branch and re-record the test by following the https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/TestGuide.md.

2024-01-31 03:08 UTC, mwesigwaguma commented
Hey @ArthurMa1978, the pipeline errors seem to be false positives. Can you please approve PR

2024-02-01 15:50 UTC, ArthurMa1978 approved these changes

2024-02-01 15:50 UTC, merged