[Container Instance] update api version 2018-04-01
Azure/azure-sdk-for-net pull request #4207
Opened 2018-04-10 21:30 UTC by yolo3301

## Description

https://github.com/Azure/azure-rest-api-specs/pull/2778

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-04-10 22:37 UTC, dsgouda requested changes
Please create a `generate.ps1` file like [here](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) and regenerate the code

2018-04-10 22:37 UTC, dsgouda commented on src/SDKs/ContainerInstance/ContainerInstance.Tests/ContainerInstance.Tests.csproj
> -    <VersionPrefix>1.0.2-preview</VersionPrefix>
It is not necessary to modify the version number here. Simply set this to `1.0.0` since these won't be published

2018-04-10 22:37 UTC, dsgouda commented on src/SDKs/ContainerInstance/Management.ContainerInstance/Microsoft.Azure.Management.ContainerInstance.csproj
> +		<Version>1.0.3</Version>
Please update the `PackageReleaseNotes` here

2018-04-10 22:37 UTC, dsgouda commented on src/SDKs/ContainerInstance/Management.ContainerInstance/Generated/Models/OperationDisplay.cs
> +        public string Operation { get; private set; }
This could potentially be a breaking change for customers. Please bump the package version number to `1.1.0`

2018-04-11 18:43 UTC, yolo3301 commented
All comments addressed. Please take a look. Thanks

2018-04-11 18:45 UTC, dsgouda approved these changes
LGTM subject to builds passing

2018-04-11 22:39 UTC, merged