Regenerated IotHub Sdk for Basic SKU
Azure/azure-sdk-for-net pull request #4208
Opened 2018-04-10 23:34 UTC by anusapan

## Description
PR for new swagger spec [here](https://github.com/Azure/azure-rest-api-specs/pull/2695)

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-04-10 23:34 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-04-10 23:34 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-04-10 23:34 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-04-11 00:47 UTC, anusapan commented
Can anyone check, why the build is failing? Is it related to the current PR?

2018-04-11 18:01 UTC, dsgouda requested changes
Please create a generate.ps1 similar to this and regenerate the code, [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) should generate a .txt file, please commit this file too.

2018-04-11 18:01 UTC, dsgouda commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
> +	  <Compile Remove="Generated\CertificatesOperations.cs" />
What is the intention here?

2018-04-11 18:01 UTC, dsgouda commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
> +		<Version>1.1.4</Version>
Looks like you might be introducing some breaking changes here, @shahabhijeet can you please verify,
This might need a major version change.

2018-04-11 22:03 UTC, dsgouda commented
@anusapan still doesn't like code is generated by generate.cmd or generate.ps1
Please do so for the PR to be accepted

2018-04-12 01:03 UTC, anusapan commented
Generated the code by autorest cmd directly, because when I am executing generate.cmd it is picking 2018-01 swagger instead of 2018-04, Or what will be the best way to get the code for 2018-04 swagger?

2018-04-12 22:26 UTC, dsgouda commented
@anusapan please regenerate the code now, rest spec repo PR has been merged.

2018-04-12 22:49 UTC, anusapan commented
@dsgouda generated by generate.cmd

2018-04-13 00:08 UTC, dsgouda requested changes
Please pull down latest changes from upstream and run
`msbuild build.proj`
Regenerate code using generate.cmd
This should create/modify a .txt file, please commit this file

2018-04-14 01:36 UTC, anusapan commented
@dsgouda updated the PR as requested

2018-04-16 16:34 UTC, dsgouda requested changes
Looks good, but needs a couple of comments to be addressed

2018-04-16 16:34 UTC, dsgouda commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
>  		<PackageReleaseNotes>
Please update the `PackageReleaseNotes`

2018-04-16 16:34 UTC, dsgouda commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
> -	<Import Condition=" Exists('$([MSBuild]::GetPathOfFileAbove(AzSdk.RP.props))') " Project="$([MSBuild]::GetPathOfFileAbove('AzSdk.RP.props'))" />
Please do not delete these lines.

2018-04-16 16:51 UTC, anusapan commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
> -	<Import Condition=" Exists('$([MSBuild]::GetPathOfFileAbove(AzSdk.RP.props))') " Project="$([MSBuild]::GetPathOfFileAbove('AzSdk.RP.props'))" />
Added deleted line

2018-04-16 16:52 UTC, anusapan commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
>  		<PackageReleaseNotes>
done

2018-04-16 17:14 UTC, anusapan commented on src/SDKs/IotHub/Management.IotHub/Microsoft.Azure.Management.IotHub.csproj
>  		<PackageReleaseNotes>
changed

2018-04-16 17:29 UTC, dsgouda approved these changes
LGTM will merge when CI builds pass

2018-04-16 21:30 UTC, merged