GA sdk release.
Azure/azure-sdk-for-net pull request #42278
Opened 2024-02-29 05:58 UTC by wangbwn

2024-02-29 06:23 UTC, ruowan approved these changes

2024-02-29 15:03 UTC, jsquire requested changes, later dismissed
@wangbwn :

Your account lacks write permissions to the repository, which is required before this PR can move forward. Please review the Azure SDK onboarding documentation and use the associated teams channel for assistance.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2024-03-04 01:51 UTC, ruowan commented
updated code owner file. https://github.com/Azure/azure-sdk-for-net/pull/42345/files

2024-03-04 01:54 UTC, ruowan commented on sdk/datafactory/Azure.ResourceManager.DataFactory/CHANGELOG.md
>  ### Breaking Changes
Please remove breaking changes. And other changes seem it cause validation failure.

2024-03-04 02:57 UTC, ruowan commented
@JoshLove-msft We are releasing the .NET GA version SDK. The CI failure report that
`eng\Directory.Build.Common.targets(316,5): Error : When the project has a release version it shouldn't reference any pre-release libraries. Found the following pre-release references: Azure.Core.Expressions.DataFactory`   Seems we need to release a Azure.Core.Expression.DataFactory first and then release the ADF GA version .net SDK.  Could you please help to take a look?

2024-03-06 08:13 UTC, ArthurMa1978 requested changes
Pending on Josh release Azure.Core.Expressions.DataFactory first stable

2024-03-06 08:56 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-03-06 15:45 UTC, jsquire requested changes, later dismissed
`wangbwn` still requires write permissions to the repository for this PR to move forward.

2024-03-12 09:58 UTC, wangbwn commented
Hi, @JoshLove-msft.
"I locally modified the version of Azure.Core.Expressions.DataFactory to '1.0.0', then regenerated the code. However, I found that the 'dotnet build /t:GenerateCode' command did not rename DataFactorySecretBaseDefinition to DataFactorySecret as expected."
![image](https://github.com/Azure/azure-sdk-for-net/assets/69622111/2d4fa589-d4bc-4507-b7e1-b11858612a2f)

2024-03-13 05:57 UTC, ruowan commented on sdk/openai/Azure.AI.OpenAI.Assistants/api/Azure.AI.OpenAI.Assistants.netstandard2.0.cs
> +    public readonly partial struct InternalAssistantDeletionStatusObject : System.IEquatable<Azure.AI.OpenAI.Assistants.InternalAssistantDeletionStatusObject>
Pls don't update this file openai.

2024-03-13 15:47 UTC, ArthurMa1978 approved these changes

2024-03-13 23:49 UTC, ArthurMa1978 commented on sdk/datafactory/Azure.ResourceManager.DataFactory/src/autorest.md
>  csharp: true
Need confirm why `generate-model-factory: false` which disable generate model factory

2024-03-14 09:15 UTC, merged