Content Moderator- Set language as a non-required field for Screen Text API
Azure/azure-sdk-for-net pull request #4240
Opened 2018-04-17 20:22 UTC by v-sodsou

## Description

https://github.com/Azure/azure-rest-api-specs/pull/2884
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-04-17 20:58 UTC, dsgouda requested changes
Please create a generate.ps1 file similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Language/Language/Language/generate.ps1) and regenerate the code.

2018-04-17 20:58 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Vision/ContentModerator/ContentModerator.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("0.12.0.0")]
Please do not update the AssemblyVersion here

2018-04-17 21:55 UTC, v-sodsou commented
Regarding "Please create a generate.ps1 file similar to this and regenerate the code." I have already regenerated the code and committed the files changed along with metadata file(.txt file) while got generated when I ran generate.cmd command.

2018-04-17 21:57 UTC, dsgouda commented
I understand, we are slowly migrating towards using a generate.ps1 script instead of a cmd. You can do it later if you wish but we are eventually going to get there

2018-04-17 22:48 UTC, v-sodsou commented
@dsgouda 
 When I ran generateTool.ps1 , I see log file generated in metadata folder but not ps1 file in my sdk folder.
Could you provide the instructions on powershell script to be run.

2018-04-17 22:51 UTC, dsgouda commented
You need to create a `generate.ps1` file similar to the one linked and put the proper relative paths and other args as in the example

2018-04-17 23:00 UTC, v-sodsou commented
@dsgouda 

Hi , I have added the generate.ps1 file. could you please review it.

Thanks
Sonali Dsouza

2018-04-17 23:27 UTC, dsgouda commented
@v-sodsou looks like the changes to package versions are no longer in the PR, please take a look

2018-04-18 00:04 UTC, v-sodsou commented
@dsgouda 
I have added the version changes.Could you please review it.
Thanks
Sonali Dsouza

2018-04-18 00:08 UTC, dsgouda approved these changes
LGTM subject to builds passing

2018-04-18 16:38 UTC, merged