added issue api and tests
Azure/azure-sdk-for-net pull request #4250
Opened 2018-04-19 17:25 UTC by solankisamir

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-04-20 01:30 UTC, solankisamir commented
@dsgouda @shahabhijeet @promoisha can you take a look?

2018-04-20 16:17 UTC, dsgouda requested changes
Looks good for the most part

2018-05-01 07:58 UTC, solankisamir commented on src/SDKs/ApiManagement/Management.ApiManagement/Generated/SdkInfo_ApiManagementClient.cs
> +                new Tuple<string, string, string>("ApiManagement", "ApiIssue", "2018-01-01"),
built again. there is no change in api version and no change in `.props` file

2018-05-01 07:59 UTC, solankisamir commented on src/SDKs/ApiManagement/Management.ApiManagement/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("4.0.1.0")]
reverted

2018-05-01 16:45 UTC, dsgouda approved these changes
LGTM

2018-05-01 16:46 UTC, merged