[NOT AZURE] Updated Azure Stack Infrastructure Insights Admin SDK
Azure/azure-sdk-for-net pull request #4252
Opened 2018-04-20 22:21 UTC by deathly809

## Description

Recreated the FRP specifications and regenerated the SDK.  

https://github.com/Azure/azure-rest-api-specs/pull/2812

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [X] Please add REST spec PR link to the SDK PR
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [X] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-04-20 23:14 UTC, dsgouda requested changes
Looks good, just needs a version bump

2018-04-20 23:14 UTC, dsgouda commented on src/AzureStack/InfrastructureInsightsAdmin/InfrastructureInsights.Admin/Microsoft.AzureStack.Management.InfrastructureInsights.Admin.csproj
> +        <PackageId>Microsoft.AzureStack.Management.InfrastructureInsights.Admin</PackageId>
Looks like this package is already published and there are some additive changes being introduced. Please update the package version number

2018-04-21 00:15 UTC, deathly809 commented
@dsgouda Done!  Also, do we publish the Nugets?  We might have to update the package release notes.

2018-04-23 16:28 UTC, dsgouda commented
@deathly809 I believe so, please check [https://www.nuget.org/packages/Microsoft.AzureStack.Management.InfrastructureInsights.Admin/0.1.0-preview]

2018-04-23 16:35 UTC, deathly809 commented
@dsgouda I already updated the version.  So I have to kick off the build process correct?  Just to be 100% clear.

2018-04-23 16:38 UTC, dsgouda commented
By build if you mean publish the package, then yes. The "build" itself was done successfully here by the CI machines.
What you may have to consider is updating the PackageReleaseNotes, let me know if you plan to do so

2018-04-23 16:45 UTC, deathly809 commented
@dsgouda I have been trying to get feedback on that.  We might just have a single PR to update all the admin PackageReleaseNotes and then kick of a publish job.

2018-04-23 16:47 UTC, dsgouda commented
That would be a good idea. Will merge this for now, feel free to open a new PR for the release notes.

2018-04-23 16:48 UTC, dsgouda approved these changes
LGTM

2018-04-23 16:48 UTC, merged