[Communication][PhoneNumbers] Fix areacodes pageable bug
Azure/azure-sdk-for-net pull request #42629
Opened 2024-03-12 15:18 UTC by sorrego-msft

Fixing an issue with pageables when getting areacodes.

2024-03-12 15:22 UTC, sofiar-msft approved these changes

2024-03-12 15:33 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-03-12 17:29 UTC, jsquire requested changes, later dismissed
@sorrego-msft:

Your account is missing the required public organization memberships required for Azure SDK contributors.  Please review the Azure SDK onboarding documentation and make use of the onboarding Teams channel for assistance.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2024-03-12 17:30 UTC, jsquire commented
Please close #42513 if this supersedes it.

2024-03-13 16:34 UTC, sorrego-msft commented
Followed the onboarding doc and set my organisations to public.
Please review @jsquire

2024-03-13 17:12 UTC, sofiar-msft approved these changes

2024-03-13 17:13 UTC, merged