Updating Language/Language SDK with new /entities endpoint
Azure/azure-sdk-for-net pull request #4286
Opened 2018-05-03 22:28 UTC by assafi

## Description

- Update of existing TA SDK with new /entities endpoint and additional Azure regions. 
- The SDK will be deprecated and succeeded by `Microsoft.Azure.CognitiveServices.Language.TextAnalytics` NuGet. See [new SDK PR](https://github.com/Azure/azure-sdk-for-net/pull/4285).

[Swagger spec PR](https://github.com/Azure/azure-rest-api-specs/pull/2985)

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-05-03 22:28 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-05-03 22:28 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-05-03 22:28 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-05-03 22:33 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-05-04 20:36 UTC, dsgouda commented
@assafi  The `PackageReleaseNotes` here must be updated once the new packages are published

2018-05-04 23:01 UTC, assafi commented
@dsgouda The `PackageReleaseNotes` have been updated. What additional info would you like to see?

2018-05-04 23:11 UTC, dsgouda commented
@assafi Once you publish Language.TextAnalytics package, note the link to that package and add it to the release notes here,

2018-05-07 21:52 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/Language/Language/Microsoft.Azure.CognitiveServices.Language.csproj
> -    <VersionPrefix>1.0.1-preview</VersionPrefix>
Replace `VersionPrefix` with `Version`

2018-05-07 22:31 UTC, dsgouda requested changes
Are you able to generate the code using generate.cmd? please do if you can and commit all changes

2018-05-07 22:31 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/Language/Language.Tests/Microsoft.Azure.CognitiveServices.Language.Tests.csproj
>      <AssemblyName>Microsoft.Azure.CognitiveServices.Language.Tests</AssemblyName>
no changes required to this file

2018-05-07 22:45 UTC, assafi commented
For this SDK update I am not able to use the generate.ps1 since the namespace has changed. However, I've used the generated code from the new SDK and copied it over since it's exactly the same except for the project path. I just copied these changes over.

2018-05-07 23:00 UTC, dsgouda approved these changes
LGTM

2018-05-07 23:01 UTC, dsgouda commented
Will pass on CIs passing

2018-05-07 23:25 UTC, dsgouda approved these changes
LGTM will merge on CIs passing

2018-05-07 23:25 UTC, merged