Introduce Azure Maps
Azure/azure-sdk-for-net pull request #4298
Opened 2018-05-08 23:26 UTC by jp94

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-05-08 23:30 UTC, jp94 commented on src/SDKs/Maps/Management.Maps/Microsoft.Azure.Management.Maps.csproj
> +    <PackageReleaseNotes>This package replaces Microsoft.Azure.Management.LocationBasedServices. Azure Location Based Services is now Azure Maps.</PackageReleaseNotes>
"Open a PR for the Microsoft.Azure.Management.Maps csproj, indicate that this is a replacement for the Microsoft.Azure.Management.LocationBasedServices in the PackageReleaseNotes and release the package"

2018-05-09 16:40 UTC, dsgouda requested changes
Looks good for the most part, please address the comment and run
`msbuild build.proj /t:build /p:Scope=SDKs\Maps` and commit any changes

2018-05-09 16:40 UTC, dsgouda commented on src/SDKs/Maps/Management.Maps/Microsoft.Azure.Management.Maps.csproj
> +  <Import Project="$([MSBuild]::GetPathOfFileAbove('AzSdk.reference.props'))" />
Copy lines 2-4 at the top and lines 22-24 at the bottom from [here](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/Microsoft.Azure.Management.Compute.csproj)

2018-05-09 22:16 UTC, dsgouda approved these changes
LGTM

2018-05-09 22:17 UTC, merged