Update autorest.md
Azure/azure-sdk-for-net pull request #43058
Opened 2024-03-28 03:06 UTC by LGDoor

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-03-28 03:20 UTC, Juliehzl commented on sdk/containerapps/Azure.ResourceManager.AppContainers/src/autorest.md
> +# tag: package-preview-2024-02
uncomment tag

2024-03-28 08:07 UTC, Juliehzl commented on sdk/containerapps/Azure.ResourceManager.AppContainers/src/Generated/ContainerAppManagedEnvironmentStorageData.cs
> -        public ContainerAppAzureFileProperties ManagedEnvironmentStorageAzureFile
remove it will be breaking change.

2024-03-28 12:55 UTC, jsquire requested changes
@LGDoor :

Your account is missing the public organization memberships and write permissions required for a Microsoft contributor.  Please review the Azure SDK onboarding documentation and use the associated Teams channel for any questions.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2024-03-29 07:13 UTC, LGDoor commented on sdk/containerapps/Azure.ResourceManager.AppContainers/src/Generated/ContainerAppManagedEnvironmentStorageData.cs
> -        public ContainerAppAzureFileProperties ManagedEnvironmentStorageAzureFile
Add in a custom class.

2024-06-21 08:33 UTC, closed without merging