SDK changes for traffic analytics parameters added to existing networkwatcher flowlog parameters
Azure/azure-sdk-for-net pull request #4320
Opened 2018-05-15 09:21 UTC by sayghosh

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-05-15 22:56 UTC, dsgouda commented
@MikhailTryakhov is the official may release for network sdk repo? Please confirm

2018-05-15 23:08 UTC, MikhailTryakhov commented
@dsgouda no it's not. The deadline of swagger is May, 17
@sayghosh you have to use minot version change 19.0.0.0->19.0.0.1 or something like that.
The official one would be able later.

2018-05-16 04:29 UTC, sayghosh commented
@MikhailTryakhov pushed it down to 19.0.1.0.

2018-05-16 04:47 UTC, MikhailTryakhov commented
Thanks, LGTM
@dsgouda if you're still not sure we can sync up with Samer - this is my first experience with minor versions publishing :) 
Let's help Sayantan with publishing this version soon - he worked really hard to do everything in time ;)

2018-05-16 05:33 UTC, sayghosh commented
Build failure cause:
![image](https://user-images.githubusercontent.com/37360255/40097813-ebcf30a4-58f5-11e8-8b6c-fa1dba5b9546.png)
 Is this an intermittent issue? If so, can we re trigger the build? Here is a successful build on the same fork with latest changes: https://azuresdkci.westus2.cloudapp.azure.com/job/NetCore-SDK-Sign/327/

2018-05-16 17:43 UTC, dsgouda requested changes
Couple of minor changes apart looks good

2018-05-16 17:43 UTC, dsgouda commented on src/SDKs/Network/Management.Network/Microsoft.Azure.Management.Network.csproj
>  		<![CDATA[
1. Since there are breaking changes, the minor version must be updated, i.e., `19.1.0-preview`
2. `PackageReleaseNotes` must be updated

2018-05-16 17:44 UTC, dsgouda commented
@sayghosh looks like the signing build was successful

2018-05-16 18:00 UTC, sayghosh commented
@dsgouda Yes it succeeded in second attempt. First time it failed due to some intermittent issue. And addressed the changes requested.

2018-05-16 18:02 UTC, dsgouda approved these changes
LGTM subject to CIs passing

2018-05-16 20:31 UTC, dsgouda commented on src/SDKs/_metadata/network_resource-manager.txt
> +Branch:      Network-2018-05-01
@sayghosh We cannot accept this PR. The SDK MUST be generated from `master` branch of REST specs repo.
Please coordinate with @MikhailTryakhov to create a PR for the May branch and integrate your changes there. `

2018-05-16 20:31 UTC, closed without merging

2018-05-16 20:35 UTC, MikhailTryakhov commented
Hi @sayghosh 
the major version would be ready for review tomorrow including all your updates. Can you please wait for it?

2018-05-17 04:50 UTC, sayghosh commented
@MikhailTryakhov  Sure :)

2018-05-17 04:59 UTC, sayghosh commented
@dsgouda Please add this requirement as part of the "SDK Generation Guidelines" above so that no duplicate effort goes in raising a wrong PR from any other branch :)

2018-05-17 16:37 UTC, dsgouda commented
Thanks @sayghosh we will update the documentation