Generating sdk new namespace
Azure/azure-sdk-for-net pull request #4321
Opened 2018-05-15 11:58 UTC by mohabghanem

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-05-18 18:19 UTC, dsgouda commented
@mohabghanem Please fix the failing tests

2018-05-24 18:52 UTC, dsgouda requested changes
A few questions:
- Is this nuget package already published?
- If not, versioning must start with `1.0.0` in the csproj. 
- Is this a preview or a stable version? Please update package version accordingly. If this is a preview package the versioning must start from `0.9.0-preview`

2018-05-24 18:52 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Programmatic.sln
> -# Visual Studio 15
I see `Programmatic.sln` is being replaced by `Authoring.sln` but the csproj names are still the same, please keep consistency, same goes for the package name
On a related note, is your intention to merely rename the directories or the name of the package too

2018-05-25 19:02 UTC, dsgouda commented
@mohabghanem gentle reminder, PR shall be closed if comments are not addressed by end of next week

2018-05-30 14:04 UTC, mohabghanem commented
@dsgouda this is a preview of a new nuget, I updated the versions accordingly and rebased the branch

2018-06-03 09:53 UTC, mohabghanem commented
@dsgouda Are there any other required changes?

2018-06-04 16:38 UTC, dsgouda reviewed
It looks like some of the projects modified here do not have an `AssemblyInfo.cs` file. Please add one and set the assembly versions appropriately.
[Here](https://github.com/mohabghanem/azure-sdk-for-net/tree/c8e902b1307f6a6c73fa0a524078fd60986d746d/src/SDKs/CognitiveServices/dataPlane/Language/Language/Language/Properties) is an example.

2018-06-04 16:38 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime.Tests/Microsoft.Azure.CognitiveServices.LUIS.Tests.csproj
> +    <Version>0.9.0-preview</Version>
Test projects are never published. Please set the version to `1.0.0`

2018-06-04 16:38 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Microsoft.Azure.CognitiveServices.LUIS.csproj
> +    <Version>0.9.0-preview</Version>
If the package is not to be renamed, the preview version must be set to 2.0.1-preview, we cannot go back in versions

2018-06-04 16:38 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Authoring.Tests/Microsoft.Azure.CognitiveServices.LUIS.Authoring.Tests.csproj
> +    <Version>0.9.0-preview</Version>
These tests are never published, simply set the version to `1.0.0` and never update them

2018-06-04 23:08 UTC, dsgouda commented
@ronak25 and @sudhansu88 can you guys take a look at this too. Please confirm whether you are okay with the preview nuget packages being introduced here.

2018-06-04 23:11 UTC, dsgouda requested changes
@mohabghanem Please clean up the git commit history to just 1 commit and update the PR

2018-06-04 23:11 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Microsoft.Azure.CognitiveServices.LUIS.csproj
>      <PackageReleaseNotes>This is a preview release of the Cognitive Services LUIS Runtime SDK. Included with this release is support for LUIS Prediction API.</PackageReleaseNotes>
Please update the `PackageReleaseNotes`

2018-06-07 16:41 UTC, dsgouda commented
Please squash your commits and update the PR.
@ronak25 Please approve these changes before we proceed.

2018-06-07 17:44 UTC, sudhansu88 requested changes
Taking a look.

2018-06-07 20:13 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime/Microsoft.Azure.CognitiveServices.LUIS.csproj
>      <PackageReleaseNotes>This is a preview release of the Cognitive Services LUIS Runtime SDK. Included with this release is support for LUIS Prediction API.</PackageReleaseNotes>
Is this `LUIS Prediction API`?

2018-06-08 16:09 UTC, sudhansu88 reviewed
These all are related to LUIS and does not impact Bing API SDKs

2018-06-10 08:31 UTC, mohabghanem commented
@dsgouda commits squashed

2018-06-11 19:19 UTC, shahabhijeet commented
@mohabghanem can you complete the CLA process by visiting and signing in.
https://github.com/azurecla

2018-06-11 19:29 UTC, mohabghanem commented
@shahabhijeet nothing happens when I click sign in on the page

2018-06-11 19:49 UTC, shahabhijeet commented
@mohabghanem link updated
https://cla.opensource.microsoft.com/

2018-06-11 21:46 UTC, mohabghanem commented
@shahabhijeet still, nothing happens when I click sign in, I tried different browsers

2018-06-13 09:41 UTC, mohabghanem commented
@shahabhijeet any updates on the link?

2018-06-13 16:45 UTC, dsgouda commented
@mohabghanem Please start an email thread regarding this.

2018-06-14 00:50 UTC, mohabghanem commented
@dsgouda to whom should I send the email thread?

2018-06-14 18:11 UTC, shahabhijeet approved these changes

2018-06-14 18:22 UTC, dsgouda approved these changes

2018-06-14 18:22 UTC, merged