Adding vulnerability Assessemtn clinet code
Azure/azure-sdk-for-net pull request #4327
Opened 2018-05-16 16:38 UTC by yaakoviyun

Adding vulnerability Assessemtn clinet code

2018-05-16 16:45 UTC, yaakoviyun commented
@jaredmoo - please review too...

2018-05-16 17:06 UTC, jaredmoo requested changes
Overall looking pretty good :)

2018-05-17 23:58 UTC, dsgouda requested changes
These look like additive changes. Please bump the minor version in csproj file along with PackageReleaseNotes

2018-05-20 17:30 UTC, yaakoviyun commented on src/SDKs/SqlManagement/Sql.Tests/DatabaseVulnerabilityAssessmentScenarioTests.cs
> +                // Get basleine
Thanks, fixed.

2018-05-20 17:30 UTC, yaakoviyun commented on src/SDKs/SqlManagement/Sql.Tests/DatabaseVulnerabilityAssessmentScenarioTests.cs
> +                // Veroify get scan and list scans
Thanks, fixed.

2018-05-20 17:31 UTC, yaakoviyun commented on src/SDKs/SqlManagement/Sql.Tests/DatabaseVulnerabilityAssessmentScenarioTests.cs
> +                string scanId = string.Format("scantest1_{0}", DateTime.UtcNow.Ticks);
Thanks, fixed.

2018-05-20 17:36 UTC, yaakoviyun commented on src/SDKs/SqlManagement/Sql.Tests/DatabaseVulnerabilityAssessmentScenarioTests.cs
> +                sqlClient.DatabaseVulnerabilityAssessmentScans.Execute(resourceGroup.Name, server.Name, dbName, scanId);
yep, it was.
will change the client code and update the swagger in azure-rest-api-specs repo

2018-05-21 05:17 UTC, yaakoviyun commented on src/SDKs/SqlManagement/Management.Sql/Generated/Models/DatabaseVulnerabilityAssessment.cs
> +        public string StorageContainerSasKey { get; set; }
Yep, will fix

2018-05-22 16:11 UTC, jaredmoo commented
@dsgouda - Jenkins build failure below seems like not our fault

```
00:35:56   c:\workspace\NetCore-SdkCI\tools\SdkBuildTools\targets\common.targets(215,5): error MSB3073: The command "dotnet test -f netcoreapp1.1 c:\workspace\NetCore-SdkCI\src\SdkCommon\TestFramework\HttpRecorder.Tests\HttpRecorder.Tests.csproj -l trx;LogFileName=c:\workspace\NetCore-SdkCI\TestResults\netCore11\HttpRecorder.Tests.trx " exited with code 1. [c:\workspace\NetCore-SdkCI\build.proj]
```

2018-05-22 16:12 UTC, jaredmoo approved these changes

2018-05-22 16:42 UTC, yaakoviyun commented
@dsgouda , can you merge?

2018-05-22 19:34 UTC, jaredmoo commented
This PR was merged into #4351 and can be closed,

2018-05-24 18:43 UTC, merged