Consumption: Add Top parameter to pricesheet operation
Azure/azure-sdk-for-net pull request #4339
Opened 2018-05-18 01:49 UTC by bgsky

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [X ] Please add REST spec PR link to the SDK PR
- [X ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-05-18 20:02 UTC, dsgouda commented
@bgsky still failing

2018-05-18 20:54 UTC, dsgouda commented
Please link the REST spec PR

2018-05-18 20:54 UTC, dsgouda requested changes
There are some changes introduced in the code here. Please bump the version to `18.0.1`

2018-05-18 20:54 UTC, dsgouda commented on src/SDKs/_metadata/consumption_resource-manager.txt
> +Commit:      cf93d01f4fe7c177b24056ff2599a164bd136d68
Please create a generate.ps1 similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) and regenerate the code.

2018-05-21 16:16 UTC, dsgouda commented
@bgsky we do have a script [here](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/tools/HelperUtilities/psScripts/Copy-SessionRecords.ps1) that can help you copy the session records.
Do let us know if you have any suggestions for improvements.

2018-05-21 16:42 UTC, dsgouda commented
@bgsky  Please create a generate.ps1 as suggested and re-generate the code

2018-05-21 16:47 UTC, bgsky commented
@dsgouda Would you let me know if there is any difference if the code is re-generated, or generate.ps1 just introduces a new protocol

2018-05-21 16:51 UTC, dsgouda commented
Yes, as a protocol we plan to move RPs towards using the ps1 script code instead of the cmd.
As such the code generated should not show any differences

2018-05-21 18:38 UTC, dsgouda approved these changes
LGTM will merge on CIs passing

2018-05-21 18:43 UTC, bgsky commented
@dsgouda The latest iteration adds generate.ps1 file and updates metadata file on consumption. 

I have played with generate.ps1 and Copy-SessionRecords.ps1 files, while not adding all generated files into the pull request as the latest version of Consumption swagger file includes many other operations. We plan to keep the current pull request small with previous version, and update it with the latest version later. 

Copy-SessionRecords.ps1 works great. Thanks for adding this tool. It does require source and destination root directories manually added.

2018-05-21 18:51 UTC, dsgouda commented
@bgsky The best way to select exactly which operations you would like to generate the sdk for is to filter out the files using tags in the configuration file (and set the default tag to whichever is the one you want to generate sdk for). With more improvements coming in we will allow specifying the tags in the generate.ps1 script itself
Due to some implementation limitations we have decided to keep `Copy-SessionRecords.ps1` simple for the first iteration, would certainly appreciate your feedback

2018-05-21 18:54 UTC, dsgouda commented
Please disregard Travis failures here, working on getting it fixed now

2018-05-21 21:03 UTC, merged

2018-05-21 23:10 UTC, bgsky commented
@dsgouda Just a smalll follow-up, would you have a link of tutorial for our side to publish a new version of nuget package of consumption SDK

2018-05-21 23:12 UTC, dsgouda commented
Most of the documentation to generate and publish an sdk is available [here](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/Documentation/code-generation-instructions.md)

2018-05-21 23:15 UTC, bgsky commented
Thanks, guess it has information needed.