Generate Compute client library version 19.0.0 and update the tests.
Azure/azure-sdk-for-net pull request #4346
Opened 2018-05-21 22:42 UTC by hyonholee

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-05-21 23:08 UTC, dsgouda requested changes
Looks good for the most part

2018-05-21 23:08 UTC, dsgouda commented on src/SDKs/_metadata/compute_resource-manager.txt
> +Bootstrapper version:    C:\Users\hylee\AppData\Roaming\npm `-- autorest@2.0.4262
Please regenerate the code using `generate.ps1` script [here](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1)

2018-05-22 21:20 UTC, hyonholee commented
@dsgouda   I generated the code using the powershell script and updated the PR.

2018-05-22 21:25 UTC, dsgouda approved these changes
LGTM subject to CI builds passing

2018-05-22 21:36 UTC, dsgouda requested changes
Please fix failing tests

2018-05-23 07:49 UTC, hyonholee commented
@dsgouda  Fixed tests and all checks passed.

2018-05-23 16:36 UTC, merged