Add SQL ShortTermRetention
Azure/azure-sdk-for-net pull request #4351
Opened 2018-05-22 18:06 UTC by jaredmoo

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-05-22 18:10 UTC, jaredmoo commented
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/2860

I merged from SqlMgmt-CloudLifter branch, updated tests, then regenerated Swagger from commit f943cdccabceca5467712cf1788cbeb52cbfb25b which is the newest commit that does not contain VA (see #4327) or jobs (see #4340)

2018-05-22 19:38 UTC, jaredmoo commented
Blocking issues:
- @dealaus - need *Backup*ShortTermRetentionPolicy name change merged into Swagger
- @yaakoviyun - need Execute -> InitiateScan name change and required params merged into Swagger. (Please make a PR separate from your MI change so it can be merged into Swagger immediately)

2018-05-22 21:44 UTC, dsgouda requested changes
Looks great apart from the minor comment

2018-05-22 21:44 UTC, dsgouda commented on src/SDKs/_metadata/sql_resource-manager.txt
> -Latest installed version:
Please generate the code using [this](https://github.com/jaredmoo/azure-sdk-for-net/blob/8dd820d23bf7b9f5bd35e2a576681b7559af35f8/src/SDKs/SqlManagement/Management.Sql/generate.ps1) script instead

2018-05-23 17:34 UTC, jaredmoo commented
Now I am just waiting for https://github.com/Azure/azure-rest-api-specs/pull/3125 to be merged so I can do the final regen.

2018-05-23 21:37 UTC, jaredmoo commented
Ready to merge

2018-05-24 18:42 UTC, dsgouda approved these changes
LGTM, thanks for addressing all the feedback

2018-05-24 18:42 UTC, dsgouda commented on src/SDKs/SqlManagement/Sql.Tests/Sql.Tests.csproj
> -    <!--<PackageReference Include="Microsoft.Azure.Management.Sql" Version="1.15.0-preview" />-->
You don't really need this line

2018-05-24 18:43 UTC, merged