[Monitor] SDK Version 0.20.0-preview - Add Metric Alerts SDK
Azure/azure-sdk-for-net pull request #4417
Opened 2018-06-06 05:52 UTC by sanjaypavan

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-06-06 05:52 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-06-06 05:53 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-06-06 17:00 UTC, dsgouda commented
@sanjaypavan Please link the related REST spec.

2018-06-06 17:04 UTC, dsgouda requested changes
- Please create a generate.ps1 file similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) and regenerate the code.
- Please run msbuild build.proj /t:build /p:Scope=SDKs\Monitor
- Please commit any files that may be modified.
- Please rebase all commits into a single commit and update the PR

2018-06-07 11:01 UTC, sanjaypavan commented
Could not squash my commits as they are in not consecutive. So closing this pull request now. And opening an new one #4424 from a new branch with all the requested changes.

2018-06-07 11:01 UTC, closed without merging