update require url format  on eng\templates\Azure.ResourceManager.Template\src\autorest.md
Azure/azure-sdk-for-net pull request #44494
Opened 2024-06-11 05:43 UTC by welovej

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-06-11 13:32 UTC, jsquire requested changes, later dismissed
@welovej :  Please provide context in the description that explains why you are making this change including what problem you're trying to solve and the end-to-end scenario.

2024-06-11 13:33 UTC, jsquire commented
//cc: @ArthurMa1978, for awareness

2024-06-12 01:07 UTC, welovej commented
@jsquire  description added.

2024-06-12 05:03 UTC, ArthurMa1978 approved these changes

2024-06-12 05:04 UTC, merged