Adding Microsoft.DevSpaces SDK for 2018-06-01-preview version
Azure/azure-sdk-for-net pull request #4451
Opened 2018-06-14 23:54 UTC by sanar-microsoft

## Description

Link to the rest api spec pull request: https://github.com/Azure/azure-rest-api-specs/pull/3186 

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-06-15 18:33 UTC, dsgouda requested changes
@sanar-microsoft Please create a test project and add tests related to the sdk, we do not allow sdks without tests

After generating the code, please run `msbuild build.proj /p:Scope=SDKs\DevSpaces` and commit all the changes generated.

2018-06-15 18:33 UTC, dsgouda commented on src/SDKs/DevSpaces/Management.DevSpaces/generate.cmd
> +call %~dp0..\..\..\..\tools\generate.cmd devspaces/resource-manager %*
Please replace this with a generate.ps1 similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Monitor/Management.Monitor/generate.ps1) and regenerate the code.
Please commit any .txt files that get generated.

2018-06-15 18:33 UTC, dsgouda commented on src/SDKs/DevSpaces/Management.DevSpaces/Microsoft.Azure.Management.DevSpaces.csproj
> +		<Version>1.0.0</Version>
If this is a preview release, please start versioning from `0.9.0-preview`

2018-06-21 18:07 UTC, shahabhijeet requested changes

2018-06-21 18:07 UTC, shahabhijeet commented on src/SDKs/DevSpaces/AzSdk.RP.props
> +    <AzureApiTag />
@sanar-microsoft missing meta data.
Can you build the generated SDK as
msbuild build.proj /t:Build /p:Scope=SDKs\DevSpaces

2018-06-21 18:07 UTC, shahabhijeet commented on src/SDKs/DevSpaces/Management.DevSpaces/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
please start your first release versioning scheme at 0.9.0.0 for your first preview release

2018-06-21 21:54 UTC, shahabhijeet approved these changes

2018-06-21 21:57 UTC, merged