Upgrade ComputerVision client SDK to v2.0.0
Azure/azure-sdk-for-net pull request #4452
Opened 2018-06-15 20:52 UTC by cthrash

* Breaking change from 1.x for RecognizeText
* Fix return type for AnalyzeImage with details=Landmark

REST Spec [PR](https://github.com/Azure/azure-rest-api-specs/pull/3236)

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-06-15 22:39 UTC, dsgouda requested changes
Please replace the `generate.cmd` with `generate.ps1`  similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) and regenerate the code
Please run `msbuild build.proj /p:Scope=SDKs/CognitiveServices/dataPlane/Vision/ComputerVision/ComputerVision/` and commit all the changes generated

2018-06-15 22:39 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Vision/ComputerVision/ComputerVision/Microsoft.Azure.CognitiveServices.Vision.ComputerVision.csproj
>      <PackageReleaseNotes>The Cognitive Services Computer Vision Client SDK lets users analyze images via Azure-hosted image classifiers. Classify images, generate image captions, recognize text, crea
Update the `PackageReleaseNotes`

2018-06-18 23:17 UTC, cthrash commented
How exactly is generate.ps1 invoked?  I nuked the 'generated' directory and swagger codegen does not occur, using the steps provided.

2018-06-19 17:21 UTC, closed without merging

2018-06-19 17:23 UTC, cthrash commented
Nevermind - I misread your feedback and got it in to my head that msbuild build.proj would trigger generate.ps1.   Ran it on it's own, and refreshed the PR.