Creating new SDK for ADF new API veriosn
Azure/azure-sdk-for-net pull request #4487
Opened 2018-06-22 04:57 UTC by hvermis

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-06-22 04:58 UTC, hvermis commented
Will add the release notes and updates to proj file in a separate commit.

2018-06-22 17:19 UTC, dsgouda commented
@hvermis Please link the related REST spec

2018-06-22 19:47 UTC, hvermis commented
PR for swagger changes - https://github.com/Azure/azure-rest-api-specs/pull/3270

2018-06-25 17:01 UTC, dsgouda commented
@azuresdkci Test this please

2018-06-25 18:47 UTC, dsgouda commented
@hvermis Please fix the failing tests

2018-06-25 20:19 UTC, dsgouda requested changes

2018-06-25 20:19 UTC, dsgouda commented on src/SDKs/DataFactory/Management.DataFactory/Microsoft.Azure.Management.DataFactory.csproj
>  		<PackageReleaseNotes>
Please update the `PackageReleaseNotes` here

2018-06-25 20:19 UTC, dsgouda commented on src/SDKs/DataFactory/Management.DataFactory/Microsoft.Azure.Management.DataFactory.csproj
> +		<Version>1.0.0</Version>
Please update the `AssemblyInfo.cs` too

2018-06-26 19:24 UTC, dsgouda approved these changes
LGTM
Please merge the commits into a single commit and this is good to merge

2018-06-26 19:26 UTC, merged