Azure Network Swagger June changes merged to .NET SDK 19.0.3
Azure/azure-sdk-for-net pull request #4491
Opened 2018-06-22 21:24 UTC by MikhailTryakhov

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-06-22 21:25 UTC, MikhailTryakhov commented
+@dsgouda to review SDK PR

2018-06-22 23:04 UTC, MikhailTryakhov commented
+@lmazuel can you please take a look?

2018-06-25 17:08 UTC, dsgouda requested changes

2018-06-25 17:08 UTC, dsgouda commented on src/SDKs/Network/Management.Network/Generated/IVirtualNetworkGatewayConnectionsOperations.cs
> +        Task<AzureOperationResponse<VirtualNetworkGatewayConnection>> UpdateTagsWithHttpMessagesAsync(string resourceGroupName, string virtualNetworkGatewayConnectionName, TagsObject parameters, Dict
This is a breaking change in the sdk. Please bump the package version to `19.1.0`

2018-06-25 17:08 UTC, dsgouda commented on src/SDKs/Network/Management.Network/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("19.0.3.0")]
`AssemblyFileVersion` must be updated, `AssemblyVersion` remains the same.

2018-06-25 17:08 UTC, dsgouda commented on src/SDKs/Network/Management.Network/Microsoft.Azure.Management.Network.csproj
>  		<![CDATA[
Please update the `PackageReleaseNotes` here

2018-06-25 19:59 UTC, MikhailTryakhov commented
@dsgouda  please take a look for changes please

2018-06-25 20:10 UTC, dsgouda requested changes
A couple of comments apart looks good

2018-06-25 20:10 UTC, dsgouda commented on src/SDKs/Network/Management.Network/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("19.1.0.0")]
`AssemblyVersion` remains the same for minor version updates, only the `AssemblyFileVersion` changes

2018-06-25 20:10 UTC, dsgouda commented on src/SDKs/Network/Management.Network/Microsoft.Azure.Management.Network.csproj
>  		<![CDATA[
Please update the `PackageReleaseNotes` here

2018-06-25 22:26 UTC, dsgouda approved these changes
LGTM

2018-06-25 22:26 UTC, merged