Batch AI .Net SDKs related to swagger typo fix
Azure/azure-sdk-for-net pull request #4513
Opened 2018-06-29 20:44 UTC by lliimsft

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-06-29 20:45 UTC, lliimsft commented
Swagger Spec PR: https://github.com/Azure/azure-rest-api-specs/pull/3328

2018-06-29 22:29 UTC, dsgouda commented
This is a breaking change, we need to investigate

2018-07-02 18:22 UTC, dsgouda requested changes
Talked to @sarangan12 and confirmed that the breaking changes were notified in REST spec PR

2018-07-02 18:22 UTC, dsgouda commented on src/SDKs/BatchAI/Management.BatchAI/Microsoft.Azure.Management.BatchAI.csproj
> +		<Version>2.0.1</Version>
Since the enum values are being renamed here, it is a breaking change. Please update the major version number here

2018-07-06 17:44 UTC, shahabhijeet commented
@lliimsft please let us know if you still would like to merge this changes. We will close this PR next week if we do not see any activity.

2018-07-06 19:46 UTC, dsgouda commented
Talked to @lliimsft offline, this needs to be discussed and a new PR will be opened when a decision is made by the RP

2018-07-06 19:46 UTC, closed without merging