enable master crc
Azure/azure-sdk-for-net pull request #45602
Opened 2024-08-20 16:26 UTC by jaschrep-msft

- Reenable partitioned download master crc validation.
- Renamed `Size` in `ContentRange` as name was misleading.
- Change partitioned downloader to rely on calculating downloaded length based on Content-Range, as Content-Length is no longer reliable for blob data.

2024-08-20 17:01 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-08-20 20:28 UTC, jalauzon-msft approved these changes

2024-08-20 20:28 UTC, jalauzon-msft commented on sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTransferValidationTests.cs
> +using System.Buffers;
nit: Unused import?

2024-08-20 20:28 UTC, jalauzon-msft commented on sdk/storage/Azure.Storage.Common/src/Shared/ContentRange.cs
> +            long? resourceSize = default;
nit: `resourceLength` to be consistent?

2024-08-21 01:05 UTC, seanmcc-msft commented
@jaschrep-msft, please don't merge this.  We should continue using the https://github.com/jaschrep-msft/azure-sdk-for-net/tree/structured-message-cherrypick-stg96 for all Content Validation work, so there is a single commit to feature/storage/stg96base2.  This way, there will be a clean cherry-pick if we have to move this to 97.

2024-08-21 01:05 UTC, seanmcc-msft requested changes
(Previous comment)

2024-08-21 14:43 UTC, seanmcc-msft approved these changes

2024-08-21 16:33 UTC, closed without merging

2024-08-21 16:57 UTC, jaschrep-msft commented
> We should continue using the https://github.com/jaschrep-msft/azure-sdk-for-net/tree/structured-message-cherrypick-stg96 for all Content Validation work, so there is a single commit to feature/storage/stg96base2. This way, there will be a clean cherry-pick if we have to move this to 97.
> 
> We also need to cherry-pick the following commits from feature/storage/stg96base2 to https://github.com/jaschrep-msft/azure-sdk-for-net/tree/structured-message-cherrypick-stg96 to get CI passing:
> 
> * [034b645](https://github.com/Azure/azure-sdk-for-net/commit/034b6451dcf406bf44f49d77e5747df7ad0c6dc4)
> * [3f9a404](https://github.com/Azure/azure-sdk-for-net/commit/3f9a40479fb1dd4bebe5662c7b5f81b7eea306a7)

the mentioned commit and ones from this PR have been cherry-picked over to https://github.com/jaschrep-msft/azure-sdk-for-net/tree/structured-message-cherrypick-stg96