Set up some code owners for the Remote Rendering service
Azure/azure-sdk-for-net pull request #45690
Opened 2024-08-27 15:54 UTC by FlorianBorn71

The Remote Rendering service did not have proper code owners assigned so it always fell back to @jsquire

2024-08-27 16:03 UTC, ChristopherManthei approved these changes

2024-08-29 01:44 UTC, jsquire requested changes

2024-08-29 01:44 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/remoterendering/                                              @FlorianBorn71 @MichaelZp0 @ChristopherManthei
```suggestion
# PRLabel: %Remote Rendering
/sdk/remoterendering/                                              @FlorianBorn71 @MichaelZp0 @ChristopherManthei

#ServiceLabel: %Remote Rendering
#ServiceOwners:                                                    @FlorianBorn71 @MichaelZp0 @ChristopherManthei
```

The original form would register reviewers for PRs only.   We'll also need to set up the block registering for support issues.

2024-08-30 22:18 UTC, jsquire approved these changes

2024-08-30 22:19 UTC, merged