Update Text Analytics C# SDK auto-generated code.
Azure/azure-sdk-for-net pull request #4589
Opened 2018-07-26 19:39 UTC by yangyuan

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/3491
Doc PR: https://github.com/MicrosoftDocs/azure-docs/pull/12442

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-07-26 19:45 UTC, assafi approved these changes

2018-07-27 20:14 UTC, dsgouda requested changes
Looks great apart from the minor comment

2018-07-27 20:14 UTC, dsgouda commented on src/SDKs/CognitiveServices/dataPlane/Language/TextAnalytics/TextAnalytics/Microsoft.Azure.CognitiveServices.Language.TextAnalytics.csproj
>      <PackageReleaseNotes>
Please update the `PackageReleaseNotes` here

2018-07-27 20:49 UTC, dsgouda approved these changes
LGTM

2018-07-27 20:49 UTC, dsgouda commented
Will merge on CIs passing

2018-07-27 21:14 UTC, yangyuan commented
@dsgouda weird it failed because some package issue. I so rebased to newest psSdkJson6 to see if it works.

2018-07-27 21:35 UTC, yangyuan commented
@dsgouda, it seems to be an issue in Batch:
c:\workspace\VSUpgradeForTest\src\SDKs\Batch\DataPlane\Azure.Batch.Unit.Tests\Azure.Batch.Unit.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NET.Test.Sdk from 15.0.0 to 15.0.0-preview-20170222-09. Reference the package directly from the project to select a different version.

2018-07-27 21:46 UTC, dsgouda commented
@yangyuan kicked off another build. Will investigate if this fails

2018-07-27 22:07 UTC, yangyuan commented
@dsgouda still falls, same error.
Seems that it was cause by the references to different Microsoft.NET.Test.Sdk versions.
Not related to Text Analytics because Text Analytics refer shared AzSdk.test.reference.props

2018-07-27 22:19 UTC, dsgouda commented
@yangyuan We are fixing it now

2018-07-27 23:13 UTC, merged