[Do Not Merge] RecoveryServices.Backup update for latest release
Azure/azure-sdk-for-net pull request #4613
Opened 2018-07-31 14:19 UTC by sumitmal

## Description
https://github.com/Azure/azure-rest-api-specs/pull/3395
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-07-31 16:34 UTC, dsgouda requested changes
Please regenerate the code using the generate.ps1 script [here](https://github.com/sumitmal/azure-sdk-for-net/blob/2c8e0d356109141ad109f6688824abfaf538753f/src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/generate.ps1)
 and commit all changes.

2018-07-31 16:34 UTC, dsgouda commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Generated/Models/MabJob.cs
> -        public string MabServerType { get; set; }
These are breaking changes, please bump the assembly version to `3.1.0-preview`

2018-07-31 16:34 UTC, dsgouda commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("3.0.0.1")]
`AssemblyVersion` remains the same, `AssemblyFileVersion` must be updated

2018-07-31 16:34 UTC, dsgouda commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup.csproj
>  		<PackageReleaseNotes/>
Please add meaningful information in the PackageReleaseNotes similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/SqlManagement/Management.Sql/Microsoft.Azure.Management.Sql.csproj#L13)

2018-07-31 17:55 UTC, dsgouda commented
@sumitmal Please join the Azure org on github [here](https://aka.ms/azuregithub) to trigger the CI builds

2018-08-08 20:38 UTC, dsgouda commented
@sumitmal Please join the Azure org as suggested. Will close the PR by next week if there is no activity

2018-08-09 06:42 UTC, sumitmal commented
Resolved following comments @dsgouda 
1. Bumped the minor version
2. Generated.ps1 used to generate
3. Update package release notes.
4. Joined Azure.

2018-08-09 16:40 UTC, dsgouda requested changes
Looks great apart from the one comment

2018-08-09 16:40 UTC, dsgouda commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("3.1.0.0")]
Please keep the `AssemblyVersion` unchanged here

2018-08-09 16:45 UTC, sumitmal commented
@dsgouda  done

2018-08-09 16:47 UTC, dsgouda approved these changes
LGTM

2018-08-09 16:47 UTC, dsgouda commented
Will merge on CIs passing

2018-08-20 18:18 UTC, shahabhijeet approved these changes
Ignore the fact that this was a preview package.
Looks good.

2018-08-20 18:19 UTC, merged