[Storage] Make SignedResource not required in listSericeSAS
Azure/azure-sdk-for-net pull request #4615
Opened 2018-08-01 03:57 UTC by blueww

## Description

SignedResource not required in listSericeSAS from server, so set is as not required in swagger/SDK.
Also add description to operation since fixing swagger validate failure. (this issue not report before, might cause autorest upgrade)

Swagger pass review and merged in https://github.com/Azure/azure-rest-api-specs/pull/3463 
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-08-02 16:43 UTC, dsgouda requested changes
Please bump the version number to `8.1.1`

2018-08-02 16:43 UTC, dsgouda commented on src/SDKs/_metadata/storage_resource-manager.txt
> -Bootstrapper version:    C:\Users\weiwei\AppData\Roaming\npm `-- autorest@2.0.4280
Please pull down the latest changes from psSdkJson6, run `msbuild build.proj` and regenerate the code

2018-08-02 21:19 UTC, dsgouda requested changes
Since this is a non breaking change, please bump the version to `8.1.1-preview`

2018-08-03 12:09 UTC, blueww commented
@dsgouda 

I have update he PR by rebase from psSdkJson6, run msbuild build.proj and regenerate the code.
O also upgrade to 8.1.1, but we won't release SRP SDK for this. will release  with next new feature.

2018-08-03 16:21 UTC, dsgouda commented
@blueww in case you are not planning to release this version please revert the version back to `8.1.0-preview`

2018-08-06 04:11 UTC, blueww commented
@dsgouda 

I have reverted the version to 8.1.0

2018-08-06 16:10 UTC, dsgouda approved these changes
LGTM

2018-08-06 16:10 UTC, merged