Generating SDK with the latest TypeSpec commit
Azure/azure-sdk-for-net pull request #46604
Opened 2024-10-14 20:32 UTC by hamshavathimunibyraiah

Generating SDK with the latest TypeSpec commit

2024-10-14 20:40 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-10-18 16:08 UTC, vikaspalaskar approved these changes

2024-10-18 16:43 UTC, jsquire requested changes, later dismissed

2024-10-18 16:43 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/translation/                                                  @mikeymcz @cpoulain @joseharriaga @vikaspalaskar
The account `cpoulain` lacks the required public membership to the Microsoft GitHub organization and `write` permission required of CODEOWNER.  

Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

You can verify the state of your account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

2024-10-18 16:51 UTC, vikaspalaskar approved these changes

2024-10-18 18:50 UTC, MikeyMCZ approved these changes

2024-10-18 22:36 UTC, jsquire approved these changes

2024-10-21 17:06 UTC, hamshavathimunibyraiah commented
@microsoft-github-policy-service rerun

2024-10-21 17:06 UTC, merged