Update Batch supporting assemblies
Azure/azure-sdk-for-net pull request #4706
Opened 2018-08-27 20:58 UTC by matthchr

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-08-27 20:59 UTC, matthchr commented
@darylmsft, @xingwu1 - Please take a look

@itowlson - Review if you like

2018-08-27 21:02 UTC, matthchr commented
This fixes #4374 and #4414

2018-08-27 21:38 UTC, darylmsft approved these changes

2018-08-28 17:05 UTC, dsgouda requested changes

2018-08-28 17:05 UTC, dsgouda commented on src/SDKs/Batch/Support/FileStaging/Batch.FileStaging/Batch.FileStaging.csproj
> -    <VersionPrefix>8.0.1</VersionPrefix>
We recommend using `Version` instead of `VersionPrefix`, please fix wherever appropriate

2018-08-28 17:05 UTC, dsgouda commented on src/SDKs/Batch/Support/FileConventions/Src/AzureBatchFileConventions/AzureBatchFileConventions.csproj
> +    <VersionPrefix>4.0.0</VersionPrefix>
Is there a reason you would like to bump the major version here, are there changes outside of this PR going in? Can't see any breaking changes for which there should be a breaking change here.

2018-08-28 17:05 UTC, dsgouda commented on src/SDKs/Batch/Support/FileStaging/Batch.FileStaging/Batch.FileStaging.csproj
> -    <VersionPrefix>8.0.1</VersionPrefix>
Same query regarding major version bump

2018-08-28 17:05 UTC, dsgouda commented on src/SDKs/Batch/Support/FileConventions/Src/AzureBatchFileConventions/AzureBatchFileConventions.csproj
> +    <VersionPrefix>4.0.0</VersionPrefix>
This will also require version bumps in the `AssemblyInfo.cs`

2018-08-30 16:58 UTC, dsgouda approved these changes
LGTM

2018-08-30 16:59 UTC, dsgouda commented
Will merge on CIs passing. Please close the issues once this is merged. Thanks!

2018-08-30 20:55 UTC, merged