Initial release of DurableTask Scheduler management SDK
Azure/azure-sdk-for-net pull request #47179
Opened 2024-11-15 07:35 UTC by berndverst

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-11-15 07:36 UTC, berndverst commented
FYI: I'm working on adding a few simple unit tests / recorded tests to this PR over the next 2-3 business days.

2024-11-15 23:58 UTC, jsquire requested changes, later dismissed
@berndverst:

Your account lacks the required public membership to the "Azure" GitHub organization s required of an internal contributor.  Your membership is marked as private.  Please update the visibility.  You can verify the state of your account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2024-11-20 20:42 UTC, jsquire commented on .github/CODEOWNERS
> +# PRLabel: %Durable Task Scheduler
This is not a change that you can make arbitrarily.   You'll need to work with @ronniegeraghty for an Azure SDK label name.

2025-02-04 18:08 UTC, berndverst commented
Will update this soon.

2025-02-23 20:14 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.DurableTask](https://apiview.dev/Assemblies/Review/676804b68e83400cb1470b65e56306c9?revisionId=87f517a1243e4b3f93e070a261004638)

2025-03-11 07:44 UTC, berndverst commented
FYI I cannot reproduce the failure by running `eng\scripts\CodeChecks.ps1 -ServiceDirectory durabletask` -- that test succeeds. So not sure what the `Build Analyze` is complaining about.

2025-03-18 04:06 UTC, berndverst commented
@ArthurMa1978 FYI - waiting for the Swagger/Typespec update to be merged so that I can regenerate the clients.
https://github.com/Azure/azure-rest-api-specs/pull/33268

Hopefully this will be done by the time you need to release the SDK -- otherwise we should just release anyway.

2025-04-08 17:18 UTC, berndverst commented
Ping @ArthurMa1978

2025-04-24 07:26 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.ResourceManager.DurableTask](https://apiview.dev/Assemblies/Review/676804b68e83400cb1470b65e56306c9?revisionId=87f517a1243e4b3f93e070a261004638)

2025-04-24 10:14 UTC, live1206 approved these changes

2025-04-24 16:42 UTC, jsquire approved these changes
CODEOWNERS changes look good.

2025-04-25 03:23 UTC, ArthurMa1978 approved these changes

2025-04-25 03:23 UTC, merged