Generating confidentialledger SDK for API spec version 2024-01-26-pre…
Azure/azure-sdk-for-net pull request #47340
Opened 2024-11-26 19:25 UTC by taicchoumsft

…view

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-11-26 19:32 UTC, jsquire requested changes, later dismissed
@taicchoumsft:

Your account lacks the required public GitHub organizations and permissions required of an internal contributor.  Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.

- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

You can verify the state of your account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2024-11-26 19:35 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Azure.Security.ConfidentialLedger](https://apiview.dev/Assemblies/Review/7bd936d0b4e64822884106598d9675ea?revisionId=c87ef398574c418c9438d817e1ed8bf8)

2025-01-10 11:42 UTC, vimauro commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerCertificateClientOptions.cs
> +                ServiceVersion.V2024_01_26_Preview => "V2024_01_26_Preview",
How should I interpret this, does this mean all SDK calls will point to the api version V2024_01_26_Preview ?

2025-01-10 11:43 UTC, vimauro commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerCertificateClientOptions.cs
> +                ServiceVersion.V2024_01_26_Preview => "V2024_01_26_Preview",
Shuoldn't this be `2024-01-26-preview` ?

2025-01-10 11:45 UTC, vimauro commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerCertificateClient.cs
> +            _endpoint = certificateEndpoint;
nit: wouldn't be clearer to keep both  `_certificateEndpoint `and `_ledgerEndpoint `?

2025-01-10 16:55 UTC, taicchoumsft commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerCertificateClientOptions.cs
> +                ServiceVersion.V2024_01_26_Preview => "V2024_01_26_Preview",
Yes you're right, fixed this.  It appears this file is used for the identity endpoint (there's another identical file for the ledger endpoints), we don't even really need this file right?

2025-01-10 16:55 UTC, taicchoumsft commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerCertificateClientOptions.cs
> +                ServiceVersion.V2024_01_26_Preview => "V2024_01_26_Preview",
Yes, if the user doesn't set the `ClientCertificateOptions`, the SDK will use the latest version, which is now set to `2024_01_26_preview`.

2025-01-10 17:00 UTC, taicchoumsft commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerCertificateClient.cs
> +            _endpoint = certificateEndpoint;
This is due to API spec change I believe.  The other part of this class is generated from the spec. 

The stable version used `ledgerEndpoint`: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/confidentialledger/data-plane/Microsoft.ConfidentialLedger/stable/2022-05-13/confidentialledger.json

The preview versions, I believed we had to change the name from `ledgerEndpoint` to `endpoint`: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/confidentialledger/data-plane/Microsoft.ConfidentialLedger/preview/2024-01-26-preview/confidentialledger.json

2025-01-10 17:15 UTC, vimauro commented on sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerCertificateClientOptions.cs
> +                ServiceVersion.V2024_01_26_Preview => "V2024_01_26_Preview",
Yeah I agree it may not be needed since it's not dependent on the API version, but we could keep it for now just to reduce the number of changes in this PR :)

2025-01-10 18:12 UTC, amruthashree18 approved these changes
Looks good, approving

2025-01-10 18:34 UTC, merged