Adding support for Api 2018-01-01 with ALIAS record.
Azure/azure-sdk-for-net pull request #4753
Opened 2018-09-08 00:11 UTC by shahabhijeet

- Adding support for Api 2018-01-01 with ALIAS record.
- Fixing test projects. 
- Generating with the right generation script. 
- Removing legacy generate.cmd

- Spec changes Azure/azure-rest-api-specs#3777

2018-09-08 01:00 UTC, karravi-msft approved these changes

2018-09-10 17:05 UTC, dsgouda requested changes
Looks great other than a minor comment
@shahabhijeet will merge if you are happy with the PR

2018-09-10 17:05 UTC, dsgouda commented on src/SDKs/Dns/Dns.Tests/Dns.Tests.csproj
> +	<PackageReference Update="Microsoft.Rest.ClientRuntime.Azure.TestFramework" Version="1.7.3" />
nit: please fix indentation

2018-09-10 18:00 UTC, dsgouda approved these changes
LGTM

2018-09-10 18:00 UTC, merged