fix(playwrighttesting): handled limitation of character in parameters.
Azure/azure-sdk-for-net pull request #47608
Opened 2024-12-18 11:16 UTC by kashish2508

# Contributing to the Azure SDK
 handled limitation of character in parameters.
Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-12-18 11:25 UTC, puagarwa approved these changes

2024-12-18 11:26 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-12-19 06:35 UTC, Sid200026 requested changes
Add tests as well to check truncation is working as expected.

2024-12-19 06:35 UTC, Sid200026 commented on sdk/playwrighttesting/Azure.Developer.MicrosoftPlaywrightTesting.TestLogger/src/Processor/DataProcessor.cs
> +                    Branch = _cIInfo.Branch?.Length > 500? _cIInfo.Branch?.Substring(0,500): _cIInfo.Branch,
Create an util function to truncate any string as per a given length and use it

2024-12-19 07:59 UTC, kashish2508 commented on sdk/playwrighttesting/Azure.Developer.MicrosoftPlaywrightTesting.TestLogger/src/Constants.cs
> +    internal static readonly string s_playwright_service_runId_Length_exceeded_Error = "The runId cannot be more than 200 characters long";
using s_playwright_service_runId_length_exceeded_error_message

2024-12-19 09:39 UTC, Sid200026 approved these changes

2024-12-19 09:39 UTC, Sid200026 commented on sdk/playwrighttesting/Azure.Developer.MicrosoftPlaywrightTesting.TestLogger/src/Constants.cs
> +    internal static readonly string s_playwright_service_runName_truncated_warning = "WARNING: The runName cannot exceed 200 characters. Therefore, it will be truncated to 200 characters.";
You can remove the text WARNING

2024-12-19 09:39 UTC, Sid200026 commented on sdk/playwrighttesting/Azure.Developer.MicrosoftPlaywrightTesting.TestLogger/src/PlaywrightReporter.cs
> +            runNameString = runNameString.Substring(0, 200);
Use truncate util function

2024-12-19 09:39 UTC, Sid200026 commented on sdk/playwrighttesting/Azure.Developer.MicrosoftPlaywrightTesting.TestLogger/src/Processor/DataProcessor.cs
> +            testCaseResultData.TestTitle = testResultSource.TestCase.DisplayName.Length > 500? testResultSource.TestCase.DisplayName.Substring(0, 500): testResultSource.TestCase.DisplayName;
why not use the truncate function directly?

2024-12-19 11:57 UTC, merged