Publishing Azure SDK for ActionGroups version 2024-10-01-preview (enabling incident action and managed identity support)
Azure/azure-sdk-for-net pull request #47634
Opened 2024-12-20 23:49 UTC by thomasp98296

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

2024-12-21 18:58 UTC, jsquire requested changes
@thomasp98296:

Your account lacks the public membership to the Microsoft and Azure GitHub organizations required of an internal contributor.  Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.

- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

You can verify the state of your account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

2025-01-16 18:08 UTC, jsquire requested changes

2025-01-16 18:08 UTC, jsquire commented on .github/CODEOWNERS
> +# PRLabel: %Monitor - Monitor
This should use simply `Monitor` as a service tag.

2025-01-16 18:08 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/monitor/Azure.ResourceManager.Monitor/                        @thomasp98296 @ritwik8119
Please move this down into the management block that starts around L915 and follow the patterns for management libraries there.   Please be sure to preserve alphabetical order by tag in that section.

2025-01-17 23:18 UTC, jsquire commented on .github/CODEOWNERS
> +# PRLabel: %Monitor
management block starts on L958.  To preserve alphabetical order, this would land on 1012.   We're also missing a support section.   It should look like the other management entries:

```
# PRLabel: %Monitor
/sdk/monitor/Azure.ResourceManager.*/       @thomasp98296 @ritwik8119

# ServiceLabel: %Monitor %Mgmt
# ServiceOwners:                            @thomasp98296 @ritwik8119
```

2025-01-21 19:56 UTC, thomasp98296 commented on .github/CODEOWNERS
> +# PRLabel: %Monitor
Thank you very much.

I am not sure what the "support section"? Is that in the same file? I searched for "support" but couldn't locate what it refers to.

Thank you!

2025-01-21 19:59 UTC, jsquire commented on .github/CODEOWNERS
> +# PRLabel: %Monitor
The following controls contacts for issue support, based on labels applied:

```text
# ServiceLabel: %Monitor %Mgmt
# ServiceOwners:                            @thomasp98296 @ritwik8119
```

2025-01-24 07:53 UTC, ArthurMa1978 commented
@thomasp98296 , could you fix the codeowner errors?
![image](https://github.com/user-attachments/assets/902a8091-d3b5-470c-ba44-1fb175193f65)

2025-01-24 20:48 UTC, jsquire submitted a review, later dismissed

2025-01-24 20:48 UTC, jsquire commented on .github/CODEOWNERS
> +# ServiceLabel: %Monitor - Monitor
This needs to move and directly follow your PR block (L1009).   The tag needs to be fixed here as well.

2025-01-24 20:48 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/monitor/Azure.ResourceManager.Monitor/                        @thomasp98296 @ritwik8119
Both of these accounts still lack **public** membership to the Azure and Microsoft orgs.

2025-01-24 23:23 UTC, thomasp98296 commented on .github/CODEOWNERS
> +/sdk/monitor/Azure.ResourceManager.Monitor/                        @thomasp98296 @ritwik8119
I fixed mine last night. Ritwik just fixed his now. Should take some time to reflect I guess, but thank you for pointing it out.

2025-01-29 07:49 UTC, thomasp98296 commented
> @thomasp98296 , could you fix the codeowner errors? ![image](https://private-user-images.githubusercontent.com/20514459/406352205-902a8091-d3b5-470c-ba44-1fb175193f65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxMzcyMzYsIm5iZiI6MTczODEzNjkzNiwicGF0aCI6Ii8yMDUxNDQ1OS80MDYzNTIyMDUtOTAyYTgwOTEtZDNiNS00NzBjLWJhNDQtMWZiMTc1MTkzZjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI5VDA3NDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNzAwNTBkMmE0YmFjZjM1OWZiYjQ5Zjc4MDA0YmI5MWM0OTMyYmU0NjFhZGRkYmJjZDI0ZjRiOTg3NTM2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ah-t5tqoWZIMHhRsUbux0vVxpo3Wil3VPUmsFOHM0Ls)

Resolved. Could you please help review? Thank you!

2025-01-29 16:45 UTC, jsquire commented on .github/CODEOWNERS
> +/sdk/monitor/Azure.ResourceManager.Monitor/                        @thomasp98296 @ritwik8119
@thomasp98296:  `ritwik8119` still does not have a `Microsoft` organization membership.

2025-01-31 18:59 UTC, thomasp98296 commented
@ArthurMa1978 , @jsquire , really appreciate if you can help review the PR. Thanks!

2025-01-31 19:35 UTC, jsquire commented
@thomasp98296:  You'll need Arthur's team to review the library implementation; they own the management libraries.

2025-02-07 08:28 UTC, ArcturusZhang commented on sdk/monitor/Azure.ResourceManager.Monitor/src/autorest.md
> +tag: package-preview-2024-10
we need to fix this first - we should not change the tag, here we are using a tag defined in this file (at the end of this file), could you update the commit id and api-version in this file for your swagger jsons and then regenerate?
Your change leads removals of all other classes generated from other swaggers, this is incorrect.

2025-02-12 06:29 UTC, ArcturusZhang commented on sdk/monitor/Azure.ResourceManager.Monitor/src/autorest.md
>  - https://github.com/Azure/azure-rest-api-specs/blob/cf406046c304ec528a84ae1a151f3d1a647058a2/specification/monitor/resource-manager/Microsoft.Monitor/preview/2023-10-01-preview/azuremonitor.json
this commit id should also align with others.

2025-02-12 06:44 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2025-02-12 07:00 UTC, thomasp98296 commented on sdk/monitor/Azure.ResourceManager.Monitor/src/autorest.md
> +- https://github.com/Azure/azure-rest-api-specs/blob/a9b9241e0d2909e29aa22efb33f55491cbd160de/specification/monitor/resource-manager/Microsoft.Insights/preview/2024-10-01-preview/actionGroups_API.jso
@ArcturusZhang , this is the only swagger file that we want to changes, only actionGroups_API.json.
The version is 2024-10-01-preview.

The swagger PR that has this changes is:

Swagger PR for enabling managed identity and incident actions for action groups
https://github.com/Azure/azure-rest-api-specs/pull/30868

2025-02-14 07:04 UTC, ArcturusZhang commented
Could you also change the changelog to include your changes in this PR?

2025-02-14 10:16 UTC, ArthurMa1978 approved these changes

2025-02-14 15:18 UTC, merged