Fixed customization for Hive/Oozie metastores
Azure/azure-sdk-for-net pull request #4765
Opened 2018-09-14 05:28 UTC by wawon-msft

## Description

There was a bug that would occur if a user specified an Hive/Oozie metastore when they had configurations like hive-site. This change will fix this scenario so the configurations are merged, but still raise an exception when there are duplicate configurations. There is no regeneration necessary for this change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-09-17 18:54 UTC, dsgouda requested changes
Looks OK apart  from the comment.

2018-09-17 18:54 UTC, dsgouda commented on src/SDKs/HDInsight/Management.HDInsight/Management.HDInsight.csproj
>  			<![CDATA[
Please update `PackageReleaseNotes` here

2018-09-17 22:30 UTC, wawon-msft commented on src/SDKs/HDInsight/Management.HDInsight/Management.HDInsight.csproj
>  			<![CDATA[
Good catch.

2018-09-17 22:31 UTC, wawon-msft commented
Thanks for the review. I've resolved the comment.

2018-09-17 22:46 UTC, dsgouda approved these changes
LGTM subject to CIs passing

2018-09-18 16:19 UTC, dsgouda requested changes
@wawon-msft  is planning to introduce more changes

2018-09-18 22:50 UTC, wawon-msft commented
**@dsgouda**: We've decided to delay the other changes until later. You can merge these current changes.

2018-09-18 22:54 UTC, dsgouda approved these changes

2018-09-18 22:54 UTC, merged