Remove commented out code
Azure/azure-sdk-for-net pull request #4823
Opened 2018-10-02 21:40 UTC by ajesusflores

## Description

Improve readability by removing commented out code.

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-10-02 21:51 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-03 16:32 UTC, dsgouda approved these changes
LGTM

2018-10-03 16:33 UTC, dsgouda requested changes
@shahabhijeet please take a look, looks innocuous

2018-10-03 18:21 UTC, shahabhijeet requested changes

2018-10-03 18:21 UTC, shahabhijeet commented on src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure/AzureClientExtensions.cs
> -            //return await LegacyLro<TBody, THeader>(client, response, customHeaders, cancellationToken);
@ajesusflores we recently updated our async operation handling code.
The reason the commented code was not removed is to have the legacy code ready to be used as a fallback during debugging.
Yes this is a bad practice and I realized it, but trust me this code is long overdue on cleaning up commented code.
We will clean up this code soon.
Thank you for your diligence.
I am closing this PR by end of this week.

2018-10-10 17:04 UTC, dsgouda commented
Per @shahabhijeet 's  comment we will dedicate some time in the future to clean up code in our ClientRuntime projects.
Thanks @ajesusflores for the feedback.
Closing this PR

2018-10-10 17:04 UTC, closed without merging