added 2.1 preview SDK for text analytics
Azure/azure-sdk-for-net pull request #4872
Opened 2018-10-15 20:38 UTC by laramume

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-10-15 21:56 UTC, dsgouda requested changes
@laramume Could you tell us why you have created a new directory named `-2.1-preview`

2018-10-15 22:04 UTC, laramume commented
@dsgouda We have two versions right now(stable and preview) which you can take a look at [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/data-plane/TextAnalytics). We needed two separate SDK's for it that's why I created a separate directory and generated new code in a new project.

2018-10-15 22:12 UTC, dsgouda commented
We do not allow multiple versions of SDK in the repo. We need to understand your requirements offline here

2018-10-18 17:29 UTC, laramume commented
@dsgouda based on the discussion I have made it to one sdk instead of two.

2018-10-23 16:32 UTC, dsgouda requested changes
Please link the related REST spec PR

2018-10-23 16:32 UTC, dsgouda commented on src/SDKs/_metadata/cognitiveservices_data-plane_TextAnalytics.txt
> +cmd.exe /c autorest.cmd https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/TextAnalytics/readme.md --csharp --version=latest --reflect-api-versions -
This log looks incorrect. please regenerate the code. The `csharp.output-folder` should not be `TextAnalytics-2.1-preview`

2018-10-23 17:15 UTC, laramume commented
@dsgouda Added the rest api PR and also updated the log files by regenerating the code

2018-10-23 18:28 UTC, dsgouda commented
@laramume please update the `Version` and `PackageReleaseNotes` as we discussed offline

2018-10-25 17:07 UTC, dsgouda approved these changes
LGTM

2018-10-25 17:07 UTC, merged