Enabling mono test runs on travis
Azure/azure-sdk-for-net pull request #4930
Opened 2018-10-25 21:41 UTC by dsgouda

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-10-29 21:23 UTC, shahabhijeet requested changes

2018-10-29 21:37 UTC, dsgouda commented on src/SdkCommon/ClientRuntime/Tests/ClientRuntime.NetCore.Tests/ServiceClientTests.cs
> +        [Fact(Skip="Skipping since mono implementations do not add equal number of default headers")]
When we populate UserAgentInfo on a non windows machine we skip adding empty values while we do add these values on a windows machine (hence the header count is different based on what OS its running on)
We can probably remove lines 271 and 276 or simply delete the test here

2018-10-29 21:39 UTC, dsgouda commented on src/SdkCommon/CR.test.reference.props
> +		<PackageReference Include="xunit.runner.console" Version="2.3.1" />
Unless I'm mistaken I couldn't find any reference to `xunit.runner.console` in any of the common test.props (https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/AzSdk.test.reference.props and https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/CR.test.reference.props), also running on windows does not need this package

2018-10-30 17:11 UTC, dsgouda commented on src/SdkCommon/ClientRuntime/Tests/ClientRuntime.NetCore.Tests/ServiceClientTests.cs
> +        [Fact(Skip="Skipping since mono implementations do not add equal number of default headers")]
Fixed.

2018-10-31 21:15 UTC, shahabhijeet approved these changes

2018-10-31 21:15 UTC, merged