[Newtonsoft] Publish new version of Batch dataplane for preview branch
Azure/azure-sdk-for-net pull request #4978
Opened 2018-10-30 23:10 UTC by maddieclayton

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-10-30 23:47 UTC, maddieclayton commented
https://azuresdkci.westus2.cloudapp.azure.com/view/TEST-NetSdkJobs/job/MaddiePS-Sign/81/

2018-11-01 20:00 UTC, shahabhijeet approved these changes

2018-11-01 20:03 UTC, maddieclayton commented
@matthchr This is a rerelease for Batch dataplane for the PowerShell Batch preview module (with Newtonsoft Json 10).  Can you take a look and let me know if you want me to make any changes?

2018-11-01 20:53 UTC, matthchr requested changes

2018-11-01 20:53 UTC, matthchr commented on src/SDKs/Batch/DataPlane/Azure.Batch/Azure.Batch.csproj
> +    <PackageReleaseNotes>For detailed release notes, see: https://aka.ms/batch-net-dataplane-changelog. Taking dependency on 10.0.3 version of Newtonsoft nuget package.</PackageReleaseNotes>
Please don't update this here -- update it in the actual changelog at src\SDKs\Batch\DataPlane\changelog.md

2018-11-02 00:08 UTC, matthchr commented on src/SDKs/Batch/DataPlane/changelog.md
> +Taking dependency on 10.0.3 version of Newtonsoft nuget package.
Should be: "- Updating Newtonsoft.Json to 1.0.3" or something like that.

2018-11-02 00:08 UTC, matthchr commented on src/SDKs/Batch/DataPlane/changelog.md
> +Taking dependency on 10.0.3 version of Newtonsoft nuget package.
Note the dash prefix (formatted as list)

2018-11-02 18:38 UTC, matthchr requested changes

2018-11-02 18:38 UTC, matthchr commented on src/SDKs/Batch/DataPlane/Azure.Batch/Azure.Batch.csproj
> +    <PackageReleaseNotes>For detailed release notes, see: https://aka.ms/batch-net-dataplane-changelog.</PackageReleaseNotes>
minor: Remove the dot? (it'd be easy to copy that into the URL since nuget doesn't do links currently)

2018-11-02 20:33 UTC, matthchr approved these changes

2018-11-02 20:33 UTC, matthchr commented
@maddieclayton - This looks good to me. Are you going to publish a new version or did you want me to do it?

2018-11-02 22:01 UTC, maddieclayton commented
@matthchr I can take care of publishing as soon as the PR is merged.  Thanks for the review!

2018-11-02 22:14 UTC, merged