Generated SDK files for Microsoft.DataMigration version 0.6.0-preview.
Azure/azure-sdk-for-net pull request #4993
Opened 2018-11-01 21:34 UTC by binuj

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-11-01 21:37 UTC, haitsongmsft commented
:)

2018-11-02 16:26 UTC, dsgouda requested changes
Please regenerate the code using [this](https://github.com/Azure/azure-sdk-for-net/blob/756570aef26a0db93588cb4cf75d8949961babba/src/SDKs/DataMigration/Management.DataMigration/generate.ps1) script
Also commit all files modified (including .txt files)

2018-11-02 20:46 UTC, binuj commented on src/SDKs/DataMigration/Management.DataMigration/Generated/SdkInfo_DataMigrationManagementClient.cs
> -// <auto-generated>
I was calling autorest directly instead of using generate.ps1. I've fixed that. Please let me know.

2018-11-07 17:13 UTC, haitsongmsft commented on src/SDKs/DataMigration/Management.DataMigration/Generated/SdkInfo_DataMigrationManagementClient.cs
> -// <auto-generated>
Anything else we should make the change?

2018-11-07 17:18 UTC, dsgouda requested changes
Looks good apart from the comment below

2018-11-07 17:18 UTC, dsgouda commented on src/SDKs/DataMigration/Management.DataMigration/Microsoft.Azure.Management.DataMigration.csproj
>  		<Description>Provides developers with libraries for the Database Migration Service (DMS) under Azure Resource manager to deploy an instance of DMS. Create, Delete, Create project, Start Migration,
Please update the `PackageReleaseNotes`

2018-11-13 16:48 UTC, dsgouda approved these changes
LGTM

2018-11-13 16:48 UTC, merged