Add ServerVulnerabilityAssessment and ManagedInstanceVulnerabilityAssessment operations
Azure/azure-sdk-for-net pull request #5005
Opened 2018-11-08 14:06 UTC by yaakoviyun

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-11-08 14:07 UTC, yaakoviyun commented
REST API PR -https://github.com/Azure/azure-rest-api-specs/pull/4416

2018-11-08 14:08 UTC, yaakoviyun commented
@jaredmoo   @yoavfr  @talhers

2018-11-08 16:41 UTC, jaredmoo commented
There are test failures, please look at Travis CI build and scroll all the way to the bottom.

I noticed that `ManagedInstanceTestFixture` is reusing the same test recording file for all tests that use it (notice `.ctor.json`). This seems like a problem, the tests that call into `ManagedInstanceTestFixture` should pass in the suite object and method name so that when `ManagedInstanceTestFixture` creates `SqlManagementTestContext` this `suiteObject` and `testName` should be the test method's class and method name. I am not sure however if this is specifically what is causing the test failure.

2018-11-08 16:42 UTC, jaredmoo commented
Other than this test issue the change looks good though :)

2018-11-08 19:00 UTC, dsgouda requested changes
Looks good for the most part, please regenerate the code once REST spec PR is merged

2018-11-14 17:01 UTC, dsgouda requested changes
Looks good for the most part, some unused code needs to be cleaned up

2018-11-14 17:02 UTC, dsgouda commented
@yaakoviyun CI tests still failing, please take a look

2018-11-19 09:41 UTC, yaakoviyun commented
@dsgouda , @jaredmoo  - tests are passing

2018-11-19 10:12 UTC, yaakoviyun commented
@talhers

2018-11-21 06:56 UTC, yaakoviyun commented
Ping...

2018-11-21 06:57 UTC, yaakoviyun commented on src/SDKs/SqlManagement/Sql.Tests/ManagedDatabaseVulnerabilityAssessmentTestFixture.cs
> +namespace Sql.Tests
Is it used in the tests

2018-11-21 06:57 UTC, yaakoviyun commented on src/SDKs/SqlManagement/Sql.Tests/ManagedInstanceVulnerabilityAssessmentTestFixture.cs
> +{
Is it used in the tests

2018-11-21 17:12 UTC, dsgouda commented
@yaakoviyun @jaredmoo What Nuget package version do you wish to release this as, `1.24.-0-preview` or `1.25.0-preview`

2018-11-21 17:22 UTC, jaredmoo approved these changes
We should try to release this and the MI collation change together in 1.24. Please make sure you and Nemanja are in sync with each other.

2018-11-21 17:35 UTC, dsgouda approved these changes
LGTM

2018-11-21 17:36 UTC, dsgouda commented
@yaakoviyun please squash commits into a single commit and we are good to merge

2018-11-21 17:59 UTC, yaakoviyun commented
How can I do it? What is the method you guys use for squashing?

Sent from Outlook
________________________________
מאת: Deepak Shankargouda <notifications@github.com>
‏‏נשלח: יום רביעי 21 נובמבר 2018 19:36:54
‏‏אל: Azure/azure-sdk-for-net
עותק: Yaakov Iyun; Mention
‏‏נושא: Re: [Azure/azure-sdk-for-net] Add ServerVulnerabilityAssessment and ManagedInstanceVulnerabilityAssessment operations (#5005)


@yaakoviyun<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyaakoviyun&data=02%7C01%7Cyaiyun%40microsoft.com%7Cd084f053e1a346a5986808d64fd7eda1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784186157830291&sdata=2t%2BaEZV0PSQwvSalix7LgjrORkY07nsfugkc%2F3RP3Nw%3D&reserved=0> please squash commits into a single commit and we are good to merge

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F5005%23issuecomment-440751045&data=02%7C01%7Cyaiyun%40microsoft.com%7Cd084f053e1a346a5986808d64fd7eda1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784186157840225&sdata=LS9J5nbbW6zGREv7P2%2FXzBhXw2Qg8wOLQj7yeWx9ZX8%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALNguRrwWD5vyU-lqtiMdYc2fgdg1-MBks5uxY82gaJpZM4YUvTO&data=02%7C01%7Cyaiyun%40microsoft.com%7Cd084f053e1a346a5986808d64fd7eda1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784186157840225&sdata=XUts5ZtX7VbnRBGz%2FSfVPo2LU5na37vh23cMAKwOmDM%3D&reserved=0>.

2018-11-21 18:00 UTC, dsgouda commented
@yaakoviyun The easiest way is to copy your changes to a temp directory, recreate a branch from latest psSdkJson6 and copy over the changes to this branch.

2018-11-21 18:01 UTC, jaredmoo commented
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2018-11-21 18:07 UTC, jaredmoo commented
So, `git rebase -i psSdkJson6` and then change all "pick" to "squash" except the first one. This will redo your change history on top of `psSdkJson6` branch and squash them down into one commit.

Or, 
```
git reset --hard psSdkJson6
git merge --squash ee511584aa30b93a7032b9afa896a17b40cc11ec
```
This will reset your branch to the same state as `psSdkJson6`, then squash merge all changes up until `ee511584aa30b93a7032b9afa896a17b40cc11ec` into this branch. (This is the commit id of the latest commit in your branch - https://github.com/Azure/azure-sdk-for-net/pull/5005/commits/ee511584aa30b93a7032b9afa896a17b40cc11ec )

These two methods are equivalent, just different UX.

2018-11-21 18:09 UTC, jaredmoo commented
@dsgouda Is it possible for you to squash merge in github UI?

2018-11-21 18:10 UTC, jaredmoo commented
Oh btw @yaakoviyun after you do this squash you will need to `git push --force` since it rewrites commit history so it is destructive to the remote branch that you are pushing to

2018-11-21 18:16 UTC, dsgouda commented
When you do a pull from upstream, the best way to squash commits is as I mentioned above

2018-11-21 18:20 UTC, yaakoviyun commented
Will it require a new PR?

I must say that is operation seems very messy and doesn’t feel like a best practice move.

Sent from Outlook
________________________________
מאת: Deepak Shankargouda <notifications@github.com>
‏‏נשלח: יום רביעי 21 נובמבר 2018 20:17:07
‏‏אל: Azure/azure-sdk-for-net
עותק: Yaakov Iyun; Mention
‏‏נושא: Re: [Azure/azure-sdk-for-net] Add ServerVulnerabilityAssessment and ManagedInstanceVulnerabilityAssessment operations (#5005)


When you do a pull from upstream, the best way to squash commits is as I mentioned above

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F5005%23issuecomment-440763240&data=02%7C01%7Cyaiyun%40microsoft.com%7C767790be585f4024a78c08d64fdd8bfb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784210279517808&sdata=W%2B2a%2Fb53rbBiiHErDsYjc3UI2DOIr5gjRGsEAOw9hd4%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALNgucXLh4CvW3Ftk5vT3gUa3ztUiZXpks5uxZijgaJpZM4YUvTO&data=02%7C01%7Cyaiyun%40microsoft.com%7C767790be585f4024a78c08d64fdd8bfb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784210279527813&sdata=Us2d7vJ8Ql9TslCh0fHix81ZFLnCkgA5q%2FgQqlzXWyA%3D&reserved=0>.

2018-11-21 18:44 UTC, yaakoviyun commented
It seems not the right thing to do.
Creating a new PR will hide all the original PR’s comments.
It seems that for every change, a developer will need two PRs and additional manual steps which raises the chance for mistakes.

Is this the way all PRs are managed?

Sent from Outlook
________________________________
מאת: Deepak Shankargouda <notifications@github.com>
‏‏נשלח: יום רביעי 21 נובמבר 2018 20:26:52
‏‏אל: Azure/azure-sdk-for-net
עותק: Yaakov Iyun; Mention
‏‏נושא: Re: [Azure/azure-sdk-for-net] Add ServerVulnerabilityAssessment and ManagedInstanceVulnerabilityAssessment operations (#5005)


@jaredmoo<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjaredmoo&data=02%7C01%7Cyaiyun%40microsoft.com%7C56fd8f0699824f69e42308d64fdee8a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784216137842483&sdata=ZcmpTCoXKhyGHQelZHxFpq74ahYbJXXeq8jMZM0T5%2B8%3D&reserved=0> problem is if the "merge" is a part of the commit history, the whole commit history gets messed up too.
As for the concerns about merging, the idea is to make sure the branch is ready to be merged to psSdkJson6 and then recreate a new branch with the ready to merge changes.
If it still feels like an issue, simply create another branch and another PR with it referencing this one so we skip the review.
Hope this helps

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F5005%23issuecomment-440766058&data=02%7C01%7Cyaiyun%40microsoft.com%7C56fd8f0699824f69e42308d64fdee8a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784216137852487&sdata=rGxhLCH1uBuihyo7Zf6mzhZ4Zy%2BbCn441p4h6yClwYI%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALNguXev1AJUsFUluoBCupXUHpKZyCmgks5uxZrsgaJpZM4YUvTO&data=02%7C01%7Cyaiyun%40microsoft.com%7C56fd8f0699824f69e42308d64fdee8a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784216137862490&sdata=m2dKHdvW4Tph%2Fc4ccRQO4fiC%2FevKPZ2Qp8T69%2FYfquE%3D&reserved=0>.

2018-11-21 19:10 UTC, dsgouda commented
The additional steps are needed only if the branch was updated with remote master and some conflicts had to be resolved, else a simple git rebase should work.
If you are able to do a git rebase successfully, we can proceed with this PR
Apologize for the confusion

2018-11-21 23:15 UTC, merged