[KeyVault] updating package versions to republish and resign.
Azure/azure-sdk-for-net pull request #5013
Opened 2018-11-13 18:23 UTC by schaabs

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-11-13 18:57 UTC, dsgouda requested changes
Left a few comments

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Core/Microsoft.Azure.KeyVault.Core.csproj
> -    <VersionPrefix>3.0.0</VersionPrefix>
Please replace `VersionPrefix` with `Version`

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Cryptography.Tests/Microsoft.Azure.KeyVault.Cryptography.Tests.csproj
> +    <VersionPrefix>3.0.1</VersionPrefix>
Please replace `VersionPrefix` with `Version`
Test projects are never publish, please set the version to `1.0.0` and leave it unchanged

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Cryptography.Tests/Microsoft.Azure.KeyVault.Cryptography.Tests.csproj
>      <TargetFrameworks>netcoreapp1.1</TargetFrameworks>
Remove commented lines

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Cryptography/Microsoft.Azure.KeyVault.Cryptography.csproj
> +    <VersionPrefix>3.0.1</VersionPrefix>
`VersionPrefix`

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Extensions.Tests/Microsoft.Azure.KeyVault.Extensions.Tests.csproj
>    <!--<PropertyGroup>
Commented lines

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Extensions.Tests/Microsoft.Azure.KeyVault.Extensions.Tests.csproj
> +    <VersionPrefix>3.0.1</VersionPrefix>
Test projects versioning must be `1.0.0`

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Extensions/Microsoft.Azure.KeyVault.Extensions.csproj
> +    <VersionPrefix>3.0.1</VersionPrefix>
`VersionPrefix`

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.TestFramework/Microsoft.Azure.KeyVault.TestFramework.csproj
>      <!-- <TargetFrameworks>netcoreapp1.1</TargetFrameworks> -->
Same comments as above for test projects

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.Tests/Microsoft.Azure.KeyVault.Tests.csproj
> +    <VersionPrefix>3.0.2</VersionPrefix>
Same comments as above for test projects

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault.WebKey.Tests/Microsoft.Azure.KeyVault.WebKey.Tests.csproj
> +    <VersionPrefix>3.0.2</VersionPrefix>
`VersionPrefix`

2018-11-13 18:57 UTC, dsgouda commented on src/SDKs/KeyVault/dataPlane/Microsoft.Azure.KeyVault/Microsoft.Azure.KeyVault.csproj
> +    <VersionPrefix>3.0.2</VersionPrefix>
`VersionPrefix`

2018-11-14 02:35 UTC, schaabs commented
@dsgouda I believe I addressed all your comments.  The one not marked outdated is because the comment was on the removed line.  PTAL

2018-11-14 16:57 UTC, dsgouda approved these changes
LGTM
@schaabs Thanks for the cleanup

2018-11-14 16:58 UTC, merged