[Storage] Support Failover, and blob Service
Azure/azure-sdk-for-net pull request #5016
Opened 2018-11-14 06:53 UTC by blueww

## Description

Swagger PR:

- BlobService (already merged): https://github.com/Azure/azure-rest-api-specs/pull/4316
- Failover PR (in review): https://github.com/Azure/azure-rest-api-specs/pull/4457
- Get LastSyncTime PR (in review): https://github.com/Azure/azure-rest-api-specs/pull/4455

The SDK is currently generated from a temp repo with contains all the above swagger PR change.
Will regenerate it against public swagger when all the swagger PR merged.

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-11-14 17:27 UTC, dsgouda requested changes
Looks good for the most part, please regenerate the code when spec is merged

2018-11-16 01:58 UTC, blueww commented on src/SDKs/Storage/Management.Storage/Generated/SdkInfo_StorageManagementClient.cs
> +                new Tuple<string, string, string>("Storage", "BlobServices", "2018-07-01"),
@dsgouda 
I have updated the PR per the public swagger, and run msbuild build.proj (Anyway, don't see any change by run msbuild).
Would you please help to review and merge the PR asap?
Thanks!

2018-11-16 16:38 UTC, dsgouda commented on src/SDKs/Storage/Management.Storage/Generated/SdkInfo_StorageManagementClient.cs
> +                new Tuple<string, string, string>("Storage", "BlobServices", "2018-07-01"),
@blueww Can't merge the PR until spec PR is merged.
This PR looks okay, please regenerate the code when all spec PRs are merged

2018-11-16 16:40 UTC, dsgouda approved these changes
LGTM

2018-11-16 16:40 UTC, dsgouda commented on src/SDKs/Storage/Management.Storage/Microsoft.Azure.Management.Storage.csproj
> +		<Version>9.1.0-preview</Version>
@blueww When are you planning to release a stable version? Ideally you should have started preview versioning from `8.8.0-preview` and landed on `9.0.0` stable version. Do let us know when you are planning to move to version 10 so we can provide a better idea.
Not blocking on this

2018-11-16 16:41 UTC, merged