Add kusto 4
Azure/azure-sdk-for-net pull request #5023
Opened 2018-11-15 16:11 UTC by oflipman

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2018-11-18 08:20 UTC, oflipman commented
@dsgouda @shahabhijeet 
Can some one please take a look at this PR.
I Closed the PR before.

2018-11-19 17:15 UTC, dsgouda requested changes

2018-11-19 17:15 UTC, dsgouda commented on src/SDKs/Kusto/Kusto.Tests/Kusto.Tests.csproj
> +  <!--<PropertyGroup>
Please remove commented lines

2018-11-19 17:15 UTC, dsgouda commented on src/SDKs/Kusto/Kusto.Tests/Kusto.Tests.csproj
> +    <OutputType>Library</OutputType>
Remove lines 8-10

2018-11-19 17:15 UTC, dsgouda commented on src/SDKs/Kusto/Kusto.Tests/Kusto.Tests.csproj
> +    <VersionPrefix>1.0.0-preview</VersionPrefix>
Test projects are never published, please replace this line with
```
<Version>1.0.0</Version>
```

2018-11-19 17:15 UTC, dsgouda commented on src/SDKs/Kusto/Management.Kusto/Microsoft.Azure.Management.Kusto.csproj
> +    <AssemblyVersion>1.0.0.0</AssemblyVersion>
Please remove 20, 21, `AssemblyVersion` and `AssemblyFileVersion` must be specified in the `AssemblyInfo.cs` file

2018-11-19 17:15 UTC, dsgouda commented on src/SDKs/Kusto/Management.Kusto/Generated/SdkInfo_KustoManagementClient.cs
> +                new Tuple<string, string, string>("Kusto", "Clusters", "2018-09-07-preview"),
If the REST API version is preview, the Nuget packages published must also be preview. Please start the nuget package versioning from `0.9.0-preview`

2018-11-19 17:15 UTC, dsgouda commented on src/SDKs/Kusto/Kusto.Tests/Kusto.Tests.csproj
> +    <AssemblyName>Kusto.Tests</AssemblyName>
Please add the line
```
 <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
``` 
and fix errors if any

2018-11-21 17:46 UTC, dsgouda requested changes
Left a few comments

2018-11-21 17:46 UTC, dsgouda commented on src/SDKs/Kusto/Kusto.Tests/Kusto.Tests.csproj
> +    <VersionPrefix>1.0.0</VersionPrefix>
Replace `VersionPrefix` with `Version`

2018-11-21 17:46 UTC, dsgouda commented on src/SDKs/Kusto/Kusto.Tests/Kusto.Tests.csproj
> +	<PackageReference Include="Microsoft.Azure.Graph.RBAC" Version="2.2.2-preview" />
nit: fix indentation

2018-11-21 17:46 UTC, dsgouda commented on src/SDKs/Kusto/Management.Kusto/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
`AssemblyVersion` and `AssemblyFileVersion` must be `0.9.0.0`

2018-11-26 14:53 UTC, dsgouda approved these changes
LGTM

2018-11-26 14:53 UTC, merged