Add Postgres/MySql/ManagedInstance online migration scenarios
Azure/azure-sdk-for-net pull request #5120
Opened 2019-01-08 00:33 UTC by ash1625

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2019-01-08 18:45 UTC, ash1625 commented
REST spec PR link to the SDK PR : 
https://github.com/Azure/azure-rest-api-specs/pull/4627

2019-01-08 18:48 UTC, hitenjava approved these changes

2019-01-09 00:13 UTC, dsgouda requested changes
Looks good for the most part, needs a minor change,

2019-01-09 00:13 UTC, dsgouda commented on src/SDKs/DataMigration/Management.DataMigration/Microsoft.Azure.Management.DataMigration.csproj
>  		<PackageReleaseNotes>Preview release of the Database Migration Service (DMS) SDK to Create, Delete, Read Projects, Files and Database Migration Tasks.</PackageReleaseNotes>
Please update `PackageReleaseNotes`

2019-01-09 01:00 UTC, hitenjava commented on src/SDKs/DataMigration/Management.DataMigration/Microsoft.Azure.Management.DataMigration.csproj
> +		<PackageReleaseNotes>Preview release of the Database Migration Service (DMS) SDK to Create, Delete, Read Projects, Files and Database Migration Tasks. The SDK now supports multiple online scenarios
"PostgreSQL"
"MySQL"

2019-01-09 18:58 UTC, dsgouda approved these changes
LGTM

2019-01-09 18:58 UTC, merged