[Azure Data Factory] Generate new SDK
Azure/azure-sdk-for-net pull request #5142
Opened 2019-01-15 03:14 UTC by meiyan-Li

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

2019-01-15 03:17 UTC, meiyan-Li commented
Related spec PRs:
https://github.com/Azure/azure-rest-api-specs/pull/4424
https://github.com/Azure/azure-rest-api-specs/pull/3957
https://github.com/Azure/azure-rest-api-specs/pull/4747
https://github.com/Azure/azure-rest-api-specs/pull/4780
https://github.com/Azure/azure-rest-api-specs/pull/4724
https://github.com/Azure/azure-rest-api-specs/pull/4939
https://github.com/Azure/azure-rest-api-specs/pull/5007
https://github.com/Azure/azure-rest-api-specs/pull/5031

2019-01-16 01:08 UTC, dsgouda requested changes

2019-01-16 09:45 UTC, meiyan-Li commented on src/SDKs/DataFactory/Management.DataFactory/Generated/Models/StoredProcedureParameter.cs
> -        /// <summary>
Thanks! How to do major version bump? Any documents I can refer?

2019-01-16 17:39 UTC, dsgouda commented on src/SDKs/DataFactory/Management.DataFactory/Generated/Models/StoredProcedureParameter.cs
> -        /// <summary>
[These](https://semver.org/) are the versioning guidelines we follow.
Essentially the Nuget version must be set to `3.0.0`. Please make sure to update the `AssemblyInfo.cs` file too

2019-01-16 17:40 UTC, dsgouda requested changes
Looks good apart from versioning

2019-01-17 02:31 UTC, meiyan-Li commented on src/SDKs/DataFactory/Management.DataFactory/Generated/Models/StoredProcedureParameter.cs
> -        /// <summary>
Thanks Deepak. Updated to 3.0.0

2019-01-17 17:21 UTC, dsgouda approved these changes
LGTM

2019-01-17 19:30 UTC, hvermis approved these changes

2019-01-17 19:31 UTC, hvermis commented
@dsgouda Can you please merge this PR? I will update the release notes once you merge this so I can start our release.

2019-01-17 19:32 UTC, hvermis commented on src/SDKs/DataFactory/Management.DataFactory/changelog.md
> +###  Feature Additions
@meiyan-Li I will fix these once @dsgouda merges this PR.

2019-01-17 19:32 UTC, merged