Minor bug fix to recovery services backup
Azure/azure-sdk-for-net pull request #5202
Opened 2019-02-01 17:23 UTC by AdityaTulasi

Undoing unintended removal of a field in two classes

2019-02-01 17:33 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-02-01 17:34 UTC, dsgouda requested changes
How was this code generated. Even if it is changes to minor fields, they must be fixed in the swagger spec first and the code has to be regenerated. Please link the swagger spec changes' PR

2019-02-01 17:34 UTC, dsgouda commented on src/SDKs/RecoveryServices.Backup/Management.RecoveryServices.Backup/Generated/Models/PreValidateEnableBackupRequest.cs
> +        /// <summary>
Please bump the Nuget minor version (in .csproj and AssemblyInfo.cs) and update PackageReleaseNotes

2019-02-01 17:50 UTC, AdityaTulasi commented
>           How was this code generated. Even if it is changes to minor fields, they must be fixed in the swagger spec first and the code has to be regenerated. Please link the swagger spec changes' PR

Link to spec PR - https://github.com/Azure/azure-rest-api-specs/pull/5133

2019-02-01 17:59 UTC, dsgouda approved these changes
LGTM

2019-02-01 17:59 UTC, dsgouda commented
WIll merge once CIs pass

2019-02-01 21:55 UTC, dsgouda commented
@AdityaTulasi please join the azure org [here](aka.ms/azuregithub) to kick off the build

2019-02-04 17:15 UTC, dsgouda requested changes
Please regenerate the code using generate.ps1 script. This should generate changes to SdkInfo_*.cs and .txt files. Please commit these changes too.

2019-02-04 18:17 UTC, dsgouda approved these changes
LGTM, will merge when CIs pass

2019-02-04 19:37 UTC, dsgouda commented
@AdityaTulasi could you pull latest changes from master and update this PR

2019-02-04 21:40 UTC, merged