[Datafactory]SDK Change for SapOpenHub and Rest
Azure/azure-sdk-for-net pull request #5260
Opened 2019-02-19 22:37 UTC by wenbof

2019-02-19 22:59 UTC, hvermis commented on src/SDKs/DataFactory/Management.DataFactory/changelog.md
> +    - Add support for RestService Source
Please fix the indentations

2019-02-19 22:59 UTC, hvermis approved these changes

2019-02-19 23:07 UTC, wenbof commented on src/SDKs/DataFactory/Management.DataFactory/changelog.md
> +    - Add support for RestService Source
thanks.

2019-02-21 17:52 UTC, dsgouda requested changes
How was this code generated? (using generate.ps1?) Please commit all changes generated including those to .txt files

2019-02-21 17:52 UTC, dsgouda commented
@wenbof please link the Rest spec PR too

2019-02-21 18:34 UTC, hvermis commented
@dsgouda This is the spec PR for this change:
https://github.com/Azure/azure-rest-api-specs/pull/5195

2019-02-21 18:46 UTC, shahabhijeet commented
@wenbof can you answer the question raised by @dsgouda? you are missing meta data in this PR.

2019-02-21 19:25 UTC, dsgouda commented
@wenbof please regenerate the code using generate.ps1 and commit changes to the .txt and SdkInfo*_.cs files

2019-02-21 20:46 UTC, dsgouda approved these changes
LGTM based on offline conversation with @hvermis

2019-02-21 20:47 UTC, merged