Update Batch dataplane SDK dependencies
Azure/azure-sdk-for-net pull request #5265
Opened 2019-02-21 00:02 UTC by matthchr

2019-02-21 21:21 UTC, shahabhijeet requested changes
Looks good.
But the sooner you use the common imports, you can get rid of individual targetFx conditions you have added.
I think this is long due, now that all the TragetFx that your RP needs is now available out of the box in our repo.
I will let Alex sign off, but looks good to me.

2019-02-21 22:03 UTC, matthchr commented
Yeah, the TargetFx stuff is the bit I mailed you about, where I can't use the targets defined in the root targets file because we depend on our management plane SDK from nuget which doesn't target those targets yet.

2019-02-23 01:36 UTC, matthchr commented
@AlexGhiondea - Ping, can we merge this?

2019-02-23 17:19 UTC, AlexGhiondea approved these changes

2019-02-24 21:42 UTC, merged

2019-02-24 21:44 UTC, shahabhijeet approved these changes