Azure Search: Regenerate management SDK to add service identity
Azure/azure-sdk-for-net pull request #5332
Opened 2019-03-08 00:47 UTC by natinimni

Regenerating management SDK to get latest MSI related changed from the spec

2019-03-13 23:04 UTC, brjohnstmsft commented
@natinimni Can you please provide a link to the Swagger spec PR on which this change is based?

2019-03-14 01:47 UTC, natinimni commented
Related swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/5319

2019-03-14 18:53 UTC, bitsforthought requested changes
The changes to the Resource and SearchService constructors, while not breaking at compile-time, are breaking changes in terms of binary compatibility, so please bump the major version number of the SDK.

2019-03-14 18:53 UTC, brjohnstmsft commented on src/SDKs/Search/Management/Management.Search/generate.ps1
> +Start-AutoRestCodeGeneration -ResourceProvider "search/resource-manager" -AutoRestVersion "latest" -SpecsRepoFork $SpecsRepoFork -SpecsRepoBranch $SpecsRepoBranch
Thanks for taking care of this!

2019-03-14 18:53 UTC, brjohnstmsft commented on src/SDKs/Search/Management/Search.Management.Tests/Tests/SearchServiceTests.cs
> +        public void CantCreateOrUpdateFreeServiceWithIdentity()
nit: Maybe name the test Cannot instead of Cant (it looked like Can when I first read it)

2019-03-14 19:43 UTC, smaine commented on src/SDKs/Search/Management/Management.Search/generate.ps1
> +Start-AutoRestCodeGeneration -ResourceProvider "search/resource-manager" -AutoRestVersion "latest" -SpecsRepoFork $SpecsRepoFork -SpecsRepoBranch $SpecsRepoBranch
When running Start-AutoRestCodegeneration against a private fork, I had to point -SdkRepoRootPath at the src directory ($PSscriptRoot\..\..\). Can you add this? It's not obvious what to pass here.

2019-03-14 21:30 UTC, bitsforthought approved these changes

2019-03-14 23:38 UTC, dsgouda approved these changes
LGTM

2019-03-14 23:39 UTC, dsgouda commented
@brjohnstmsft is this ready to merge?

2019-03-15 00:15 UTC, brjohnstmsft commented
@dsgouda Yes, please merge it.

2019-03-15 16:32 UTC, merged