Update FrontDoor WAF API to 2019-03-01-preview
Azure/azure-sdk-for-net pull request #5556
Opened 2019-03-22 20:29 UTC by eschwabe

* Generated new SDK from swagger
* Updated unit tests to use new swagger definition
* Incremented Microsoft.Azure.Management.FrontDoor package version

This PR supersedes the automated PR [5527](https://github.com/Azure/azure-sdk-for-net/pull/5527).

2019-03-22 20:42 UTC, dsgouda requested changes
Please use [generate.ps1](https://github.com/Azure/azure-sdk-for-net/blob/f716788ea577ccb37c3ef58ba1f756b4197bbc20/src/SDKs/FrontDoor/Management.FrontDoor/generate.ps1) to generate the code and commit all changes

2019-03-22 20:42 UTC, dsgouda commented on src/SDKs/FrontDoor/Management.FrontDoor/Microsoft.Azure.Management.FrontDoor.csproj
>  			Fixed a regression in enable/disable https for custom domain.
Please update packagereleasenotes

2019-03-22 23:54 UTC, eschwabe commented on src/SDKs/FrontDoor/Management.FrontDoor/Microsoft.Azure.Management.FrontDoor.csproj
>  			Fixed a regression in enable/disable https for custom domain.
Updated release notes.

2019-03-25 16:32 UTC, dsgouda approved these changes
LGTM

2019-03-25 16:33 UTC, merged