PBI 3632670 2019 .Net SDK Release 1
Azure/azure-sdk-for-net pull request #5648
Opened 2019-04-01 17:34 UTC by BrianBlum

We explicitly ran ~\src\SDKs\Media\Management.Media\generate.ps1 to get --opt-in-extensible-enums.
The 'new' files in this PR are enum related files that were incorrectly deleted by https://github.com/Azure/azure-sdk-for-net/pull/5490.

2019-04-01 19:10 UTC, dsgouda commented
@azuresdkci Retest this please

2019-04-01 19:10 UTC, dsgouda commented
@azuresdkci Test this please

2019-04-01 19:17 UTC, BrianBlum commented
This was supposed to be submitted to psSDKJson6. Closing this PR.

2019-04-01 19:19 UTC, dsgouda commented
@BrianBlum reopening the PR. Our default branch has been switched to master now,

2019-04-02 14:42 UTC, BrianBlum commented
@dsgouda, I didn't use the OpenAPI path to submit this code. Who should the reviewers be?

2019-04-02 16:45 UTC, dsgouda commented
> 
> 
> @dsgouda, I didn't use the OpenAPI path to submit this code. Who should the reviewers be?

I will review this one. Will revert soon.

2019-04-02 17:15 UTC, dsgouda requested changes
Looks good for the most part.
Acknowledging that apparent breaking changes are actually enums being reverted to extensible enums

2019-04-02 17:33 UTC, BrianBlum commented on src/SDKs/Media/Management.Media/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("2.0.2.0")]
Thanks. Pushed new version of AssemblyInfo.cs.

2019-04-02 17:43 UTC, dsgouda approved these changes
LGTM will merge once CIs pass

2019-04-02 23:05 UTC, merged

2019-04-02 23:06 UTC, dsgouda commented
Confirmed tests are fixed [here](https://azuresdkci.westus2.cloudapp.azure.com/view/NetCore-SDK/job/NetCore-SDK-Sign/502/)