[Azure Search] adding filter property for Autocomplete in SDK
Azure/azure-sdk-for-net pull request #5822
Opened 2019-04-16 07:07 UTC by ishansrivastava90

- includes generated code from swagger spec from azure-rest-api-specs:master
- added custom code to AutocompleteParameters for POST flavor of the API
- added tests for the property

2019-04-16 07:12 UTC, ishansrivastava90 commented
@brjohnstmsft FYI.

2019-04-16 20:29 UTC, bitsforthought requested changes

2019-04-16 20:29 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Search.Tests/Tests/AutocompleteTests.cs
> +                Filter = "baseRate gt 200 or baseRate lt 100",
@ishansrivastava90 There is no top-level `baseRate` property anymore after my Complex Types changes (I'm assuming this is using the test `Hotel` type). Please pick a different property on which to filter. Sorry for the inconvenience.

2019-04-16 20:29 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Search.Tests/Tests/AutocompleteTests.cs
> +
nit: extra line

2019-04-16 20:29 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Search.Tests/Tests/AutocompleteTests.cs
> +                Filter = "hotelId ne '6' and (baseRate gt 200 or tags/any(t : t eq 'budget'))"
`baseRate` is going away

2019-04-16 20:30 UTC, brjohnstmsft commented
@ishansrivastava90 The build failure appears to be a bug in another Azure service's SDK. I'll merge from master again to resolve it. Sorry for the inconvenience.

2019-04-18 22:36 UTC, bitsforthought approved these changes

2019-04-18 22:36 UTC, brjohnstmsft commented
Will merge once builds are passing

2019-04-18 23:28 UTC, ishansrivastava90 commented
@brjohnstmsft @dsgouda The CI/Travis-CI check is failing consistently with the message, 
_"E: Failed to fetch https://packages.microsoft.com/ubuntu/14.04/prod/dists/trusty/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update" failed and exited with 100 during." _

Any ideas as to get this to pass?

2019-04-19 00:34 UTC, dsgouda commented
@ishansrivastava90 We're taking a look

2019-04-19 17:50 UTC, ishansrivastava90 commented
@dsgouda Both @brjohnstmsft  and I are going to be OOF for the 1st part of the next week. If the issue is determined and fixed before we are back, feel free to merge the PR.

2019-04-22 19:01 UTC, dsgouda commented
@ishansrivastava90 Please pull lkatest changes from master and update this PR, that should fix the CI issues

2019-04-23 20:12 UTC, merged