Expose Azure Search Skill.Name in SDK
Azure/azure-sdk-for-net pull request #6299
Opened 2019-05-16 17:38 UTC by jadrefke

2019-05-16 17:49 UTC, bitsforthought requested changes
I forgot that `Skill` is a base class, and didn't realize that this change would change the constructors of so many model classes. That's much more of a breaking change than I thought it would be.

Let's ask what this requires in terms of a version bump. It definitely seems like a minor bump (like for the deadlock hotfix) isn't sufficient. I propose we don't block the hotfix on your PR, and have a separate train for this when we've figured out versioning.

2019-05-16 17:49 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Microsoft.Azure.Search/Microsoft.Azure.Search.csproj
> +    <PackageReleaseNotes>Latest release fixes deadlocking issue and exposes optional Skill.Name field</PackageReleaseNotes>
Please don't delete the other notes -- those are still applicable. Just add this to the end:

> This release includes a fix for the deadlock issue (`https://github.com/Azure/azure-sdk-for-net/issues/6254`) and exposes the new optional Skill.Name property.

2019-05-16 17:50 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Microsoft.Azure.Search/Microsoft.Azure.Search.csproj
> +    <PackageReleaseNotes>Latest release fixes deadlocking issue and exposes optional Skill.Name field</PackageReleaseNotes>
Actually, you can drop the part about the deadlock fix. I'll make that change in my own PR, so we can decouple them.

2019-05-16 17:54 UTC, brjohnstmsft commented
@weshaggard @AlexGhiondea This change adds new optional constructor parameters to model classes. This should be non-breaking at compile-time most (but not all) of the time, but it's definitely a breaking change from a binary compatibility point of view. Does this warrant a major version bump (i.e. AssemblyVersion goes from 9.0.0.0 to 10.0.0.0)?

2019-05-16 19:59 UTC, weshaggard commented
>This change adds new optional constructor parameters to model classes. This should be non-breaking at compile-time most (but not all) of the time, but it's definitely a breaking change from a binary compatibility point of view. 

Generally in cases like this we simple add an overload to keep it binary compatible as well. That is the simplest way to keep things both source and binary compatible.

2019-05-16 21:02 UTC, brjohnstmsft commented
@weshaggard That would solve the problem, although it's unfortunate that it adds to the burden of custom code that we need to maintain, at least for one major version cycle.

@jadrefke How about this -- You can either wait until we publish a new preview SDK for api-version 2019-05-06-Preview and make this change then, or you can add constructors (using partial classes, in the Customizations folder) as Wes suggests. Then we can get away with just bumping the build number (9.0.1 -> 9.0.2). Either way, I'd like to get 9.0.1 out today, so this change will have to catch a future train.

2019-05-16 22:01 UTC, bitsforthought requested changes

2019-05-16 22:01 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Microsoft.Azure.Search.Service/Customizations/Skillsets/SkillConstructors/EntityRecognitionSkill_BackCompatCtror.cs
> +﻿// Copyright (c) Microsoft Corporation. All rights reserved.
Please use the same file naming convention that we use elsewhere (suffix with `.Customization.cs`)

2019-05-16 22:01 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Microsoft.Azure.Search.Service/Customizations/Skillsets/SkillConstructors/EntityRecognitionSkill_BackCompatCtror.cs
> +    public partial class EntityRecognitionSkill
Please include a comment for future maintainers explaining why this is here, and when it will be safe to remove it.

2019-05-16 22:01 UTC, brjohnstmsft commented on src/SDKs/Search/DataPlane/Microsoft.Azure.Search.Service/Customizations/Skillsets/SkillConstructors/EntityRecognitionSkill_BackCompatCtror.cs
> +    public partial class EntityRecognitionSkill
Same for all the other files

2019-05-16 22:02 UTC, brjohnstmsft commented
@jadrefke Please bump the version # to 9.0.2.

2019-05-18 20:36 UTC, bitsforthought approved these changes

2019-05-21 22:56 UTC, brjohnstmsft commented
@weshaggard @AlexGhiondea @dsgouda We've solved the backcompat issues and bumped the build version number. Please merge.

2019-05-22 00:03 UTC, merged