Add functionality to unregister message handler to servicebus sdk
Azure/azure-sdk-for-net pull request #6360
Opened 2019-05-21 16:00 UTC by rangp

The `MessageReceiver` class and thus the topic and queue clients have the method `RegisterMessageHandler` that allow registration of a message handler that will be used to process incoming messages without the need to manually receive or complete those messages. 

However there is no method to unregister the message handler and the only way to stop automatic message processing seems to be calling `CloseAsync` which will stop message reception but will also immediately close the service bus connection, making it impossible to complete messages that are currently processed, if the processing is long running (And PeekLock is used). Cancelling the processing upon `CloseAsync` is not an option in my use-case since the processing is kind of a transaction scope and has to be completed fully or not at all. 

Hence I feel the need for functionality that allows one to cancel automatic message reception while still keeping the service bus connection open.  This pull request introduces the method `UnregisterMessageHandler` implemented in a way that will solve my problem and I think it would be a consistent thing to add to the API, that could also be used to change message handlers without closing the service bus connection.

Kind regards
Peter

2019-05-21 16:00 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-sdk-for-net?pullRequest=6360) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-sdk-for-net?pullRequest=6360) before we can accept your contribution.<br/><br/>:x: rangp [sign now](https://cla.opensource.microsoft.com/Azure/azure-sdk-for-net?pullRequest=6360)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-sdk-for-net?pullRequest=6360) it.</sub>

2019-05-21 16:02 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-07-12 01:22 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +                    Assert.True(count < messageCount);
>messageCount [](start = 40, length = 12)

Should this be `count < maxConcurrentCalls`?

2019-07-12 01:49 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +                            HandlerRegistration(false);
>HandlerRegistration(false); [](start = 28, length = 27)

Am I missing something? How is this even working? For maxConcurrentCall of say 5, there are 5 different instances of this handler code which are trying to call `RegisterMessageHandler`. And there is always a race condition where two of them try to register without unregistering in between. And that would throw.

2019-07-12 01:50 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +                    new MessageHandlerOptions(ExceptionReceivedHandler) { MaxConcurrentCalls = maxConcurrentCalls, AutoComplete = autoComplete });
>ExceptionReceivedHandler [](start = 46, length = 24)

I am thinking for these tests we need to make sure there are no exceptions. We need to have another variable and Assert that there are no exceptions received during this time.

2019-07-12 01:50 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +                            Thread.Sleep(1000);
>Thread.Sleep(1000); [](start = 28, length = 19)

`await Task.Delay()`

2019-07-12 01:51 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +                    while (stopwatch.Elapsed.TotalSeconds <= 30)
>30 [](start = 61, length = 2)

4 different permutations of this test, which essentially means 2 mins added run time. Not a blocker, but maybe consider optimizing this to a smaller number.

2019-07-12 01:53 UTC, nemakam requested changes
:clock1:

2019-07-12 01:54 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/QueueClient.cs
> +        /// Cancels the continuuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
>continuuous [](start = 24, length = 11)

typo

2019-07-12 01:56 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/QueueClient.cs
> +        /// <remarks>Register a message handler first, using <see cref="RegisterMessageHandler(Func{Message, CancellationToken, Task}, Func{ExceptionReceivedEventArgs, Task})"/>
>remarks [](start = 13, length = 7)

Also add a remark mentioning the behavior when this is called multiple times

2019-07-12 01:57 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/QueueClient.cs
> +        /// <remarks>Register a message handler first, using <see cref="RegisterMessageHandler(Func{Message, CancellationToken, Task}, Func{ExceptionReceivedEventArgs, Task})"/>
The same in other clients

---
In reply to: [302802451](https://github.com/Azure/azure-sdk-for-net/pull/6360#discussion_r302802451) [](ancestors = 302802451)

2019-07-12 01:57 UTC, nemakam commented
>     sealed class MessageReceivePump

This needs to be done for `SessionReceivePump` as well to keep it consistent. 

---
Refers to: sdk/servicebus/Microsoft.Azure.ServiceBus/src/MessageReceivePump.cs:13 in 8637512. [](commit_id = 8637512267ba01c5c128a615626226a2227ed9f5, deletion_comment = False)

2019-07-12 01:59 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +            while (stopwatch.Elapsed.TotalSeconds <= 60)
>60 [](start = 53, length = 2)

Again, could you reduce this further (and enable prefetch on the receiver so that messages are received faster)

2019-07-12 01:59 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +            Assert.True(count == messageCount);
>True [](start = 19, length = 4)

Assert.Equal

2019-07-12 02:00 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +            var count = 0;
nit: could you please take care of indentation?

2019-07-12 02:00 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/SenderReceiverClientTestBase.cs
> +                                                    // Completion should still work, even after message handler is stopped
>// Completion should still work, even after message handler is stopped [](start = 52, length = 70)

nit: indentation

2019-07-12 02:03 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/tests/MessageReceiverTests.cs
> +    public sealed class MessageReceiverTests : SenderReceiverClientTestBase
>MessageReceiverTests [](start = 24, length = 20)

We don't have a test which ensures that once `Unregister` is called, there are no more messages that are received, i.e, ensure no handlers are called after that

2019-07-12 02:05 UTC, nemakam commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/QueueClient.cs
> +        /// <remarks>Register a message handler first, using <see cref="RegisterMessageHandler(Func{Message, CancellationToken, Task}, Func{ExceptionReceivedEventArgs, Task})"/>
Also, looks like there is a difference in the xml doc between different files. Could you make sure all xmldocs of this method have the same comment

---
In reply to: [302802465](https://github.com/Azure/azure-sdk-for-net/pull/6360#discussion_r302802465) [](ancestors = 302802465,302802451)

2019-07-12 02:06 UTC, nemakam commented
@rangp, thanks for the PR. The overall design looks good. There are couple of small changes that I have requested.

2019-08-07 22:24 UTC, SeanFeldman commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/SubscriptionClient.cs
> +        /// Cancels the continuuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
typo

```suggestion
        /// Cancels the continuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
```

2019-08-07 22:24 UTC, SeanFeldman commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/Core/IReceiverClient.cs
> +        /// Cancels the continuuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
typo 

```suggestion
        /// Cancels the continuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
```

2019-08-07 22:24 UTC, SeanFeldman commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/Core/MessageReceiver.cs
> +        /// Cancels the continuuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
typo

```suggestion
        /// Cancels the continuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
```

2019-08-07 22:24 UTC, SeanFeldman commented on sdk/servicebus/Microsoft.Azure.ServiceBus/src/QueueClient.cs
> +        /// Cancels the continuuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
typo

```suggestion
        /// Cancels the continuous reception of messages without closing the underlying service bus connection and unregisters the message handler.
```

2019-08-07 22:42 UTC, SeanFeldman commented
@nemakam given that `IReceiverClient` is changing, this will be a **breaking change**.
Should this be indicated somehow?

2019-08-08 21:19 UTC, nemakam commented
@SeanFeldman , yeah. Maybe we could initially put this into the MessageReceiver class and not the interface and have a separate PR for changes in interface which can be checked in whenever the next major version is to be released.

@rangp , could you please separate out the PR with changes in the IMessageReceiver in a separate PR so that this change need not wait for the next major release.

2019-11-04 23:47 UTC, pakrym commented
This PR is stale and will be closed, please reopen if there are new updates.

2019-11-04 23:47 UTC, closed without merging

2021-02-24 20:32 UTC, DorothySun216 commented
We published this functionality in 5.0.0: Enable a way to Unregister Message Handler and Session Handler [PR 14021](https://github.com/Azure/azure-sdk-for-net/pull/14021)