Generated code for 2019-05-01/resources.
Azure/azure-sdk-for-net pull request #6456
Opened 2019-06-01 00:31 UTC by Tiano2017

2019-06-01 00:35 UTC, shahabhijeet requested changes
Missing release notes
Also update nuget version, assembly, assembly file version

2019-06-10 19:47 UTC, TianoMS commented
> Installing AutoRest version: latest

@Abhijeet, do I need to keep this file?

---
Refers to: src/SDKs/_metadata/resources_resource-manager.txt:1 in 14dc580. [](commit_id = 14dc580c5a3149c86b6aca95f640429806c6b310, deletion_comment = False)

2019-06-10 19:48 UTC, TianoMS commented on src/SDKs/Resource/AzSdk.RP.props
> +    <AzureApiTag>Features_2015-12-01;ManagementLinkClient_2016-09-01;Resources_2016-09-01;Authorization_2016-09-01;Authorization_2018-05-01;Management_2018-05-01;PolicyClient_2018-05-01;Management_20
>ManagementLinkClient_2016 [](start = 37, length = 25)

@Abhijeet, these changes are auto-generated. Do I need to keep them?

2019-06-11 00:53 UTC, shahabhijeet approved these changes

2019-06-11 00:53 UTC, shahabhijeet approved these changes

2019-06-11 00:53 UTC, merged