Update .net SDK for swagger PR 5661
Azure/azure-sdk-for-net pull request #6610
Opened 2019-06-18 03:54 UTC by juniwang

It's for Swagger PR 5661: https://github.com/Azure/azure-rest-api-specs/pull/5661. The original auto-PR wasn't completed due to structural change of the repo.

Codes are auto-generated by `tools\generated.cmd signalr/resource-manager` which is almost the same as the auto PR(https://github.com/Azure/azure-sdk-for-net/pull/5823).

2019-06-19 06:55 UTC, shahabhijeet commented
@erich-wang  will be reviewing your PR.
our SLA is 2 business days.

2019-06-19 08:08 UTC, erich-wang commented
@shahabhijeet , this PR looks fine to me, I'm going to approve the PR tomorrow if you don't have any other comments.

2019-06-21 06:20 UTC, erich-wang requested changes
@juniwang , it seems you need to upgrade nuget package version as well because of new APIs, how about include the changes in this PR as well?

2019-06-21 07:15 UTC, erich-wang approved these changes

2019-06-21 07:15 UTC, merged