Update generated code for spec changes
Azure/azure-sdk-for-net pull request #6685
Opened 2019-06-24 22:17 UTC by mahakjain314

Remove x-ms-azure-resource extension for ManagedResource definition.

2019-06-25 22:53 UTC, shahabhijeet commented
@erich-wang this PR looks good to me.
Check out a breaking change introduced due to change in public surface area, but as this is in preview this is ok to do in sdk.
Take a look and merge this PR.

2019-06-26 04:56 UTC, erich-wang requested changes
@mahakjain314, do you need update AssemblyFileVersion in AssemblyInfo.cs?

2019-06-26 07:32 UTC, mahakjain314 commented
> @mahakjain314, do you need update AssemblyFileVersion in AssemblyInfo.cs?

Updated.

2019-06-26 13:38 UTC, erich-wang approved these changes

2019-06-26 13:38 UTC, merged