Rajivnan/msp dotnet ga
Azure/azure-sdk-for-net pull request #6715
Opened 2019-06-26 18:33 UTC by rajivnandivada

Updating the sdk for the new version 2019-06-01.
Corresponding REST API spec PR https://github.com/Azure/azure-rest-api-specs/pull/6406

2019-06-27 10:30 UTC, erich-wang requested changes

2019-06-27 10:30 UTC, erich-wang commented on package-lock.json
> +{
is this file added accidentally?

2019-06-27 10:30 UTC, erich-wang commented on sdk/managedservices/Microsoft.Azure.Management.ManagedServices/AzSdk.RP.props
> +    <AzureApiTag>ManagedServices_2019-06-01;</AzureApiTag>
Please update the value of **Version** in Microsoft.Azure.Management.ManagedServices.csproj

2019-06-27 16:55 UTC, rajivnandivada commented on package-lock.json
> +{
yes, sorry.  I will remove it.

2019-06-27 17:42 UTC, rajivnandivada commented
@erich-wang I have addressed your feedback. Please review.

2019-06-28 02:42 UTC, erich-wang approved these changes

2019-06-28 02:42 UTC, merged