Update IoTHub SDK
Azure/azure-sdk-for-net pull request #6847
Opened 2019-07-08 23:43 UTC by anusapan

Add test for manual-failover.
fixed broken test

2019-07-09 05:35 UTC, erich-wang requested changes
1. Please provide swagger spec PR link related to this PR
1. Please follow **step 8** in [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation). It will really help us a lot to review your PR if it contains sdk\_metadata\<rpName>.txt which is generated by generate.ps1

1. Please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#creating-pr)
> If **ExcludeFromTest** and **ExcludeFromBuild** are present in your test csproj, make sure their value are false, otherwise you tests won't be run from CI

2019-07-09 05:35 UTC, erich-wang commented on sdk/iothub/Microsoft.Azure.Management.IotHub/src/generate.ps1
> +Start-AutoRestCodeGeneration -ResourceProvider "iothub/Microsoft.Azure.Management.IotHub" -AutoRestVersion "latest"
Any particular reason to change it?

2019-07-09 18:53 UTC, anusapan commented on sdk/iothub/Microsoft.Azure.Management.IotHub/src/generate.ps1
> +Start-AutoRestCodeGeneration -ResourceProvider "iothub/Microsoft.Azure.Management.IotHub" -AutoRestVersion "latest"
change reverted

2019-07-11 23:59 UTC, anusapan commented
@erich-wang Is this PR still in the review process?

2019-07-12 02:43 UTC, erich-wang commented
@anusapan , next time please provide swagger spec PR link in this PR description which looks like https://github.com/Azure/azure-rest-api-specs/pull/xxxx, otherwise I don't know what is changed in the swagger spec and whether it is approved.
> 1. Please provide swagger spec PR link related to this PR

2019-07-12 02:43 UTC, erich-wang approved these changes

2019-07-12 02:44 UTC, merged

2019-07-15 17:36 UTC, anusapan commented
@erich-wang Could you tell me, How can I signed/release the NuGet package of iothub?

2019-07-16 04:48 UTC, erich-wang commented
@anusapan , the process is available at https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#signing-and-publishing-nuget-packges