Failover database and elastic pools Net SDK
Azure/azure-sdk-for-net pull request #6934
Opened 2019-07-15 20:52 UTC by emgu-ms

REST API commit change - https://github.com/Azure/azure-rest-api-specs/commit/597f7dd325c864dd4db48d9374451c16e0337158#diff-cf76f9fb3a55909fa9cd42d1e4612784

Added database and elastic pool failover to Net SDK.  Also included tests.

2019-07-15 21:15 UTC, jaredmoo requested changes

2019-07-15 21:15 UTC, jaredmoo commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Microsoft.Azure.Management.Sql.csproj
>  - Added support for serverless databases.
Line 15 is release notes for 1.31.0-preview, this was already published (see https://www.nuget.org/packages/Microsoft.Azure.Management.Sql). So you should update version to 1.32 (here and in AssemblyInfo.cs) and wipe out the old release notes.

2019-07-15 21:15 UTC, jaredmoo commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/FailoverTests.cs
> +                AzureOperationResponse failoverResponse = await sqlClient.Databases.BeginFailoverWithHttpMessagesAsync(
just call `Failover` instead, that way you are verifying the entire e2e operation succeeds.

2019-07-15 21:15 UTC, jaredmoo commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/FailoverTests.cs
> +                AzureOperationResponse failoverResponse = await sqlClient.ElasticPools.BeginFailoverWithHttpMessagesAsync(
also use `Failover` here.

2019-07-16 03:06 UTC, erich-wang commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Microsoft.Azure.Management.Sql.csproj
>  	</PropertyGroup>
@emgu-ms, you need to update Version if you want to publish new nuget pcakge

2019-07-16 03:08 UTC, erich-wang commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Microsoft.Azure.Management.Sql.csproj
>  	</PropertyGroup>
You may also need update the value of AssemblyFileVersion.

2019-07-16 03:08 UTC, erich-wang commented
Please resolve conflicts as well.

2019-07-16 03:10 UTC, erich-wang requested changes
Please resolve conflicts.

2019-07-16 20:18 UTC, jaredmoo commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Microsoft.Azure.Management.Sql.csproj
> +- Added support for failover databases and elastic pools.
Sorry, looks like 1.32 was just published. Can you wipe out the 1.32 release notes and bump to 1.33?

2019-07-16 20:18 UTC, jaredmoo approved these changes

2019-07-16 20:19 UTC, jaredmoo commented on eng/mgmt/mgmtmetadata/sql_resource-manager.txt
> +GitHub fork: emgu-ms
Aren't your changes checked into master? Published SDK must be based on azure/master.

2019-07-17 03:45 UTC, jaredmoo reviewed
.

2019-07-17 22:06 UTC, jaredmoo approved these changes

2019-07-18 01:25 UTC, erich-wang approved these changes

2019-07-18 01:25 UTC, merged