Add resource group based LTR APIs + tests to azure sdk
Azure/azure-sdk-for-net pull request #6957
Opened 2019-07-17 17:24 UTC by pixia

2019-07-17 22:01 UTC, jaredmoo commented
Let's aim to publish this and https://github.com/Azure/azure-sdk-for-net/pull/6934 together

2019-07-18 00:06 UTC, jaredmoo requested changes

2019-07-18 00:39 UTC, pixia commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/DatabaseRestoreScenarioTests.cs
> +                Assert.True(backups.Count() == 0);
removed the checks

2019-07-18 00:39 UTC, pixia commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/DatabaseRestoreScenarioTests.cs
> +            string locationName = "brazilsouth";
discussed offline, added comments and keep the change so test could pass in playback mode

2019-07-18 02:18 UTC, erich-wang requested changes
Please resolve merge conflicts

2019-07-18 07:19 UTC, pixia commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/DatabaseRestoreScenarioTests.cs
> +            string locationName = "brazilsouth";
discussed offline will keep the change

2019-07-18 07:32 UTC, pixia commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/DatabaseRestoreScenarioTests.cs
> +                Assert.Equal(System.Net.HttpStatusCode.OK, policyResult.Response.StatusCode);
Removed

2019-07-18 07:33 UTC, pixia commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/DatabaseRestoreScenarioTests.cs
> +                Assert.Equal(System.Net.HttpStatusCode.OK, policyResult.Response.StatusCode);
Removed

2019-07-18 07:33 UTC, pixia commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/DatabaseRestoreScenarioTests.cs
> +                Assert.True(backups.Count() == 0);
Removed the check

2019-07-18 07:34 UTC, pixia commented on sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/tests/DatabaseRestoreScenarioTests.cs
> +                Assert.Equal(System.Net.HttpStatusCode.OK, deleteResult.Response.StatusCode);
Yes, did that

2019-07-18 07:37 UTC, pixia commented
Done

2019-07-18 07:57 UTC, erich-wang approved these changes

2019-07-18 20:52 UTC, jaredmoo approved these changes

2019-07-19 02:07 UTC, merged