Regenerate Batch Management SDK
Azure/azure-sdk-for-net pull request #7168
Opened 2019-08-06 22:27 UTC by matthchr

- Regenerate Batch Management SDK based on the 2019-08-01
    version of the Swagger specification.

2019-08-07 05:29 UTC, erich-wang requested changes
@matthchr , could you 
1. Provide swagger spec PR related to this change, so that I can tell whether swagger PR is merged?
1. Follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) for generating this PR? I did not see ``rp-resource-manager.txt` and update for AssemblyFileVersion

2019-08-07 16:29 UTC, matthchr commented
Swagger specification is here: https://github.com/Azure/azure-rest-api-specs/pull/6723

I pushed an update where I used `generate.ps1` rather than `generate.cmd` -- is there a reason there are two ways to generate SDKs...?

2019-08-08 05:37 UTC, erich-wang approved these changes

2019-08-08 05:42 UTC, erich-wang commented
> Swagger specification is here: [Azure/azure-rest-api-specs#6723](https://github.com/Azure/azure-rest-api-specs/pull/6723)
> 
> I pushed an update where I used `generate.ps1` rather than `generate.cmd` -- is there a reason there are two ways to generate SDKs...?

You should use generate.ps1, delete generate.cmd if have.

2019-08-08 05:42 UTC, merged