Added ISE reference to workflow
Azure/azure-sdk-for-net pull request #7334
Opened 2019-08-19 18:29 UTC by visharm

2019-08-20 05:09 UTC, isra-fel requested changes
Hi @visharm , please follow these [instructions](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec), and make sure that:
- The `eng\mgmt\mgmtmetadata\<rpName>.txt` file is included in this PR
- Versions have been updated, if necessary
- Package tags, release notes, have been updated

And please put a link to the corresponding swagger review PR in comments. Thanks

2019-10-15 21:03 UTC, visharm commented
https://github.com/Azure/azure-rest-api-specs/pull/6601

2019-10-16 05:52 UTC, isra-fel requested changes

2019-10-16 05:52 UTC, isra-fel commented on sdk/logic/Microsoft.Azure.Management.Logic/src/Microsoft.Azure.Management.Logic.csproj
> +	  - Added Integration Service Environment reference in Workflow
I think you'd better remove the notes from last release

2019-10-16 05:52 UTC, isra-fel commented on sdk/logic/Microsoft.Azure.Management.Logic/src/Microsoft.Azure.Management.Logic.csproj
> +	  - Added Integration Service Environment reference in Workflow
And please also update `<Version>` in this file

2019-10-16 05:52 UTC, isra-fel commented on sdk/logic/Microsoft.Azure.Management.Logic/src/Properties/AssemblyInfo.cs
>  [assembly: AssemblyFileVersion("4.0.0.0")]
`AssemblyFileVersion` should be updated

2019-10-23 21:45 UTC, visharm commented on sdk/logic/Microsoft.Azure.Management.Logic/src/Properties/AssemblyInfo.cs
>  [assembly: AssemblyFileVersion("4.0.0.0")]
Could you please take a look at the CR?

2019-10-24 07:29 UTC, isra-fel commented
@visharm , you are making a big change and updating API versions, so please
1. Update major version
1. Update the api tag in `AzSdk.RP.props`

Please also fix test errors -- they are mainly caused by the change of the API

2019-11-11 02:06 UTC, isra-fel commented
Hello @visharm any update?

2019-11-15 15:52 UTC, isra-fel commented
Closing this for now @visharm, feel free to reopen to continue, thanks

2019-11-15 15:52 UTC, closed without merging