Ryogok/cvapi 2.1
Azure/azure-sdk-for-net pull request #7367
Opened 2019-08-22 06:43 UTC by ryogok

**Change Summary**
- Updated C# SDK for Computer Vision API based on this swagger change (PR: https://github.com/Azure/azure-rest-api-specs/pull/6976)
- Stopped skipping some test cases
- Added some assertion checks for "Gore" support

**Notes**
- Unit tests all passed except for skipped ones

2019-08-27 03:22 UTC, AlexGhiondea requested changes

2019-08-27 03:37 UTC, ryogok commented on sdk/cognitiveservices/Vision.ComputerVision/src/Generated/ComputerVisionClient.cs
> +        public async Task<HttpOperationResponse<ImageAnalysis>> AnalyzeImageWithHttpMessagesAsync(string url, IList<VisualFeatureTypes> visualFeatures = default(IList<VisualFeatureTypes>), IList<Deta
Yes, we did. We added v2.1.

2019-08-27 03:38 UTC, ryogok commented on sdk/cognitiveservices/Vision.ComputerVision/src/Generated/ComputerVisionClient.cs
> +        public async Task<HttpOperationResponse<ImageAnalysis>> AnalyzeImageWithHttpMessagesAsync(string url, IList<VisualFeatureTypes> visualFeatures = default(IList<VisualFeatureTypes>), IList<Deta
Yes, it was. We added v2.1.

2019-09-03 07:37 UTC, ryogok commented on sdk/cognitiveservices/Vision.ComputerVision/src/Generated/ComputerVisionClient.cs
> +        public async Task<HttpOperationResponse<ImageAnalysis>> AnalyzeImageWithHttpMessagesAsync(string url, IList<VisualFeatureTypes> visualFeatures = default(IList<VisualFeatureTypes>), IList<Deta
Ok. Bumped up the package version. Since it was a breaking change on the service side, I bumped up the major version (i.e. 5.0.0 -> 6.0.0).

2019-09-03 17:37 UTC, AlexGhiondea approved these changes

2019-09-04 01:57 UTC, merged