[Data Factory] Add Switch activity
Azure/azure-sdk-for-net pull request #8016
Opened 2019-10-09 23:15 UTC by mablumen

2019-10-10 01:20 UTC, isra-fel requested changes
Hi @mablumen , please generate SDK code by running `generate.ps1` and track the metadata file. [(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#generating-net-sdk)
Besides, please put a link to your spec review PR in the comments.
THanks

2019-10-10 06:15 UTC, mablumen commented
@isra-fel Should I make a new PR. Or can I execute generate.ps1 on top of these changes?

2019-10-11 02:27 UTC, isra-fel commented
> @isra-fel Should I make a new PR. Or can I execute generate.ps1 on top of these changes?

It calls autorest under the hood, so just run it on top of your changes.
Thanks

2019-10-11 17:51 UTC, mablumen commented
Hi @isra-fel @erich-wang 
I tried running generate.ps1 and get following error:
```Start-AutoRestCodeGeneration : The term 'Start-AutoRestCodeGeneration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.```

So I tried running msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules and get following error:
```C:\Git\azure-sdk-for-net\eng\mgmt\Directory.Build.Mgmt.props(10,3): error MSB4019: The imported project "C:\Git\azure-sdk-for-net\eng\mgmt\CI.Bootstrap.targets" was not found. Confirm that the path in t
he <Import> declaration is correct, and that the file exists on disk. [C:\Git\azure-sdk-for-net\eng\mgmt.proj]```

2019-10-11 20:23 UTC, mablumen commented
Hi @isra-fel @erich-wang
I've resolve the above issue and am now able to run `generate.ps1`

However I'm getting this new error when I run the script:
`npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mablumen\AppData\Roaming\npm\node_modules\autorest'
-> 'C:\Users\mablumen\AppData\Roaming\npm\node_modules\.autorest.DELETE'
npm ERR!  { [Error: EPERM: operation not permitted, rename
'C:\Users\mablumen\AppData\Roaming\npm\node_modules\autorest' ->
'C:\Users\mablumen\AppData\Roaming\npm\node_modules\.autorest.DELETE']`

Any thoughts?

2019-10-11 23:01 UTC, LijuanZ commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/changelog.md
> +- Add Switch activity
Also add "- Added new AzureMLExecutePipeline activity and AzureMLService linked service type

2019-10-11 23:04 UTC, LijuanZ commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/tests/JsonSamples/PipelineJsonSamples.cs
> +";
Add sample for azureMLExecutePipeline activity, I'll will send you sample

2019-10-11 23:04 UTC, mablumen commented
Hi @isra-fel @erich-wang the above issues were all fixed. Can you please review now?

2019-10-11 23:36 UTC, LijuanZ commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/tests/JsonSamples/LinkedServiceJsonSamples.cs
> +            },
Sorry..my back, please remove these lines

2019-10-12 00:38 UTC, hvermis commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/Microsoft.Azure.Management.DataFactory.csproj
> +- Add Switch activity
Added

2019-10-12 00:40 UTC, hvermis commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/changelog.md
>  ###  Feature Additions
Change the version here too to 4.3.0. Make sure to leave the Current Version at the top of the file

2019-10-12 00:51 UTC, hvermis commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/changelog.md
> +- Added Switch activity
feature additions

2019-10-12 01:04 UTC, hvermis approved these changes
Ready for the release.

2019-10-12 01:24 UTC, isra-fel approved these changes

2019-10-12 01:42 UTC, merged