New Kusto version (2019-09-07)
Azure/azure-sdk-for-net pull request #8028
Opened 2019-10-10 18:29 UTC by liatbezalel

Generated and added tests by the new Kusto 2019-09-07 version

2019-10-11 02:13 UTC, isra-fel requested changes
@liatbezalel please link your swagger spec review PR(s) here & update release notes, thanks

2019-10-11 02:13 UTC, isra-fel commented on sdk/kusto/Microsoft.Azure.Management.Kusto/src/Microsoft.Azure.Management.Kusto.csproj
>      <PackageReleaseNotes>
PackageReleaseNotes needs to be updated

2019-10-15 02:26 UTC, isra-fel commented
@liatbezalel ping on this

2019-10-15 16:01 UTC, liatbezalel commented
> @liatbezalel please link your swagger spec review PR(s) here & update release notes, thanks

I updated the release notes and added the links to the relevant PRs in the description.
Thanks

2019-10-15 16:52 UTC, isra-fel approved these changes

2019-10-15 16:52 UTC, merged