[Databox] SDK refresh to support new API version (2019-09-01)
Azure/azure-sdk-for-net pull request #8219
Opened 2019-10-18 10:30 UTC by sashanm

Azure Spec PR : https://github.com/Azure/azure-rest-api-specs/pull/7317

2019-10-18 10:35 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-10-18 10:43 UTC, sashanm commented
@isra-fel  : I closed PR https://github.com/Azure/azure-sdk-for-net/pull/8176 since it was showing others commit as well somehow. so,  I have created a new PR and addressed your code review comments in it. Please take a look and let me know If you have any concerns

Thanks

2019-10-21 05:33 UTC, isra-fel requested changes

2019-10-21 05:33 UTC, isra-fel commented on sdk/databox/Microsoft.Azure.Management.DataBox/src/Microsoft.Azure.Management.DataBox.csproj
> +		<Version>1.2.0</Version>
As we discussed, please use 1.1.0

2019-10-21 05:33 UTC, isra-fel commented on sdk/databox/Microsoft.Azure.Management.DataBox/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.2.0")]
Here too

2019-10-22 12:32 UTC, isra-fel requested changes

2019-10-22 12:32 UTC, isra-fel commented on sdk/databox/Microsoft.Azure.Management.DataBox/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.1.0")]
AssemblyVersion should not be updated unless it's a major version change

2019-10-23 01:20 UTC, isra-fel approved these changes

2019-10-23 01:20 UTC, merged