Webactivity changes for IR
Azure/azure-sdk-for-net pull request #8373
Opened 2019-10-24 14:23 UTC by mfrintu

Adding optional "connectVia" property to the Web activity type properties.

2019-10-24 22:54 UTC, jackmagic313 commented
Eventually you need to use generate.ps1 to generate the C# code as well as datafactory_resource-manager.txt file once swagger change is checked-in

2019-10-25 09:13 UTC, isra-fel requested changes
jackmagic313 is right. Please notify me when it's done

2019-10-30 20:17 UTC, mfrintu commented
Addressed the PR comments

2019-10-31 06:11 UTC, isra-fel requested changes
Hi @mfrintu , could you please
- Add a link to the swagger spec review PR in the description
- Update versions, if you are going to release
Thanks

2019-10-31 06:11 UTC, isra-fel commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/tests/UnitTests/ActivityTests.cs
> +        public void ExecuteWebActivityOnIR_SDKSample()
Need to record the test don't you?

2019-11-01 01:59 UTC, isra-fel requested changes
@mfrintu please see my inline comments and resolve merge conflicts. Thanks

2019-11-01 01:59 UTC, isra-fel commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("4.3.1.0")]
`AssemblyVersion` shouldn't be change unless it's a major version update

2019-11-01 01:59 UTC, isra-fel commented on sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/changelog.md
> +##
Remove this extra line please

2019-11-04 07:26 UTC, isra-fel commented
I got it that version was already changed to 4.4.0 for this release. Please resolve the conflicts then.
You may also close this and open a new PR based on latest master, which I think would be easier.

2019-11-04 18:31 UTC, closed without merging

2019-11-04 18:32 UTC, mfrintu commented
Changes were already merged in a different PR.