Enforce prefix for snippets
Azure/azure-sdk-for-net pull request #8406
Opened 2019-10-24 22:33 UTC by pakrym

2019-10-24 22:43 UTC, heaths requested changes
We have some more changes coming in for Key Vault once the PRs are reviewed and merged. Besides the other scoping issues and possibly bad merges, is this something that should maybe wait until after GA - or at least not a couple of days before publishing the next preview's packages?

2019-10-24 22:43 UTC, heaths commented on eng/SnippetGenerator/DirectoryProcessor.cs
> +        private readonly string _snippetPrefix = "Snippet:";
Make static or even const.

2019-10-24 22:43 UTC, heaths commented on eng/SnippetGenerator/DirectoryProcessor.cs
> +            foreach (var mdFile in Directory.GetFiles(_directory, "*.md", SearchOption.AllDirectories))
Tip: `Directory.EnumerateFiles` is faster and uses less memory.

2019-10-24 22:43 UTC, heaths commented on sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md
> +```C# Snippet:CreateClient
Based on what you told me, these would need to be "scoped" to include "Certificate", "Key", etc., since they have to be unique across the repo.

2019-10-24 22:43 UTC, heaths commented on sdk/keyvault/Azure.Security.KeyVault.Keys/README.md
> -await foreach (KeyProperties keyProperties in allKeys)
This looks like a bad merge.

2019-10-24 22:48 UTC, pakrym commented
> We have some more changes coming in for Key Vault once the PRs are reviewed and merged. Besides the other scoping issues and possibly bad merges, is this something that should maybe wait until after GA - or at least not a couple of days before publishing the next preview's packages?

This is kind of required to have samples in the new format we talked about, so I wouldn't want to wait until post GA.

2019-10-24 23:16 UTC, AlexGhiondea approved these changes

2019-10-25 00:22 UTC, heaths approved these changes
Just one more thing I'd change, then otherwise LGTM.

2019-10-25 00:22 UTC, heaths commented on sdk/keyvault/Azure.Security.KeyVault.Keys/README.md
> +```C# Snippet:NotFound
Perhaps KeyNotFound?

2019-10-25 15:53 UTC, merged