Azure Security Center - Updated IoT Security Solution
Azure/azure-sdk-for-net pull request #8721
Opened 2019-11-11 09:51 UTC by liranc

Relevant spec update: https://github.com/Azure/azure-rest-api-specs/pull/7283

2019-11-12 02:23 UTC, isra-fel requested changes
Hi @liranc , could you
- Write tests for the new APIs
- Update versions if you are going to release

Thanks

2019-11-13 05:48 UTC, isra-fel commented
@liranc if you re adding new feature please update minor version, and if it involves breaking change please update the major version.

Also the version in `.csproj` needs to be updated.
Thanks

2019-11-13 07:05 UTC, liranc commented
> @liranc if you re adding new feature please update minor version, and if it involves breaking change please update the major version.
> 
> Also the version in `.csproj` needs to be updated.
> Thanks

This update is backward compatibility and only adds functionality.
I've reverted my previous version change and now I've just updated the minor version, so we're at `1.1.0`.

Thanks

2019-11-13 09:27 UTC, isra-fel approved these changes

2019-11-13 09:27 UTC, merged