[Azure Search] Regenerate SDK for access condition methods
Azure/azure-sdk-for-net pull request #8762
Opened 2019-11-13 20:26 UTC by arv100kri

1. Regenerate from https://github.com/Azure/azure-rest-api-specs/pull/7777 to pull in access condition methods for skillsets.

2. Add `MySQL` data source type which is in preview.

2019-11-13 20:28 UTC, arv100kri commented
(I hit create pull request instead of create draft pull request by mistake.
Won't check this in until I check in the swagger PR and regenerate from master)

2019-11-14 05:52 UTC, bitsforthought requested changes
Missing test coverage, and maybe custom code too? Please ensure the ETag-related surface area for skillsets is at par with the other resources.

2019-11-14 05:52 UTC, brjohnstmsft commented on sdk/search/Microsoft.Azure.Search.Service/src/Customizations/DataSources/Models/DataSource.Customization.cs
Looks like you're missing access condition tests for skillsets.

2019-11-14 21:21 UTC, arv100kri commented
> Missing test coverage, and maybe custom code too? Please ensure the ETag-related surface area for skillsets is at par with the other resources.

Yup, just added some more tests and ensured that the surface area is consistent (compared with DataSource for example)

2019-11-14 22:03 UTC, bitsforthought approved these changes
Minor doc bug, otherwise looks good.

2019-11-14 22:03 UTC, brjohnstmsft commented on sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Skillsets/ISkillsetsOperations.Customization.cs
> +        /// The name of the data source.
skillset

2019-11-14 23:36 UTC, bitsforthought approved these changes

2019-11-19 22:40 UTC, bleroy approved these changes

2019-11-19 23:35 UTC, arv100kri commented on sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Skillsets/SkillsetsOperations.Customization.cs
> +        /// Additional parameters for the operation.
Right, this seems to be the case for other customizations as well, so I thought I'll just use it as-is... Doesn't seem too egregious, so I'll keep it

2019-11-19 23:35 UTC, arv100kri commented on sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Skillsets/SkillsetsOperations.Customization.cs
> +        /// Thrown when a required parameter is null.
Same - followed the pattern from elsewhere

2019-11-20 00:17 UTC, merged