[AzureSearch] Add new features to preview SDK
Azure/azure-sdk-for-net pull request #8909
Opened 2019-11-25 22:35 UTC by jadrefke

2019-11-26 19:17 UTC, bitsforthought reviewed
Not signing off only because I'm not too familiar with the new SDK features. Overall the test coverage looks sufficient.

2019-11-26 19:17 UTC, brjohnstmsft commented on sdk/search/Microsoft.Azure.Search/tests/SessionRecords/IndexingTests/CreateIndexerWithCacheReturnsCorrectDefinition.json
> +{
nit: It makes it easier to review if you make the session records changes in a separate commit.

2019-11-26 19:17 UTC, brjohnstmsft commented on sdk/search/Microsoft.Azure.Search/tests/Tests/IndexerTests.cs
> +                AzureOperationResponse<Indexer> response1 =
How about `cacheUpdateResponse` instead of `response1`?

2019-11-26 19:17 UTC, brjohnstmsft commented on sdk/search/Microsoft.Azure.Search/tests/Tests/SkillsetsTests.cs
> +            var projection2_tableSelector = new KnowledgeStoreTableProjectionSelector(
nit: Variable names should be `camelCase`

2019-12-02 19:04 UTC, arv100kri requested changes
Things LGTM, not really blocking.
Just waiting for the updated PR with the session records + tests and build passing.
I'll sign off then!

After that let's get the swagger PR checked in and update the metadata (regenerate from master) at which point I'll check this in

2020-01-27 18:04 UTC, closed without merging