Release the iotcentral sdk for the new sku name ST0, ST1, ST2
Azure/azure-sdk-for-net pull request #9074
Opened 2019-12-11 02:05 UTC by poanchen

2019-12-11 02:15 UTC, emgarten commented on sdk/iotcentral/Microsoft.Azure.Management.IotCentral/src/Microsoft.Azure.Management.IotCentral.csproj
> +        This release adds new sku name, ST0, ST1, ST2 for Microsoft.Azure.Management.IotCentral application.
nit: This release adds new skus: ST0, ST1, ST2 for Microsoft.Azure.Management.IotCentral.

2019-12-11 18:29 UTC, poanchen commented
Hey @erich-wang ,

Please review our PR and let us know what work we need to do in order to merge this PR.

2019-12-13 02:14 UTC, isra-fel requested changes
Hi @poanchen , please
- update `assemblyfileversion` in `assemblyinfo.cs`
- write tests to cover new operations
Thanks

2019-12-20 20:07 UTC, kawayiboy commented
> Hi @poanchen , please
> 
> * update `assemblyfileversion` in `assemblyinfo.cs`
> * write tests to cover new operations
>   Thanks

@isra-fel , the fix PR is here: https://github.com/Azure/azure-sdk-for-net/pull/9224, thanks

2019-12-23 01:59 UTC, isra-fel commented
@kawayiboy @poanchen I've merged #9224 , so closing this one as well.

I also realized the folder structure of your module is wrong... at least it is different from other modules -- 

Should be: `sdk/iotcentral/Microsoft.Azure.Management.IotCentral/src/Generated`
Actually is: `sdk/iotcentral/Microsoft.Azure.Management.IotCentral/src/IotCentral/Microsoft.Azure.Management.IotCentral/src/Generated/`

It doesn't make any difference in the sense of the final delivery package, but fixing this can prevent confusing PRs such as this one in the future. I'll raise the PR and assign you to review.

2019-12-23 01:59 UTC, closed without merging

2020-01-02 19:25 UTC, poanchen commented
@isra-fel in order to change the folder structure, do I simply move it from sdk/iotcentral/Microsoft.Azure.Management.IotCentral/src/IotCentral/Microsoft.Azure.Management.IotCentral/src/Generated/
to
sdk/iotcentral/Microsoft.Azure.Management.IotCentral/src/Generated?