Users/anutallu/cmkchanges
Azure/azure-sdk-for-net pull request #9202
Opened 2019-12-19 06:18 UTC by TalluriAnusha

2019-12-19 06:27 UTC, TalluriAnusha commented
Swagger approval is done. 
PR link : https://github.com/Azure/azure-rest-api-specs/pull/7961

2019-12-20 04:50 UTC, TalluriAnusha commented
https://github.com/Azure/azure-rest-api-specs/pull/7698
https://github.com/Azure/azure-rest-api-specs/pull/7982

2019-12-23 05:02 UTC, isra-fel requested changes
One line needs to be changed

2019-12-23 05:02 UTC, isra-fel commented on sdk/recoveryservices-siterecovery/Microsoft.Azure.Management.RecoveryServices.SiteRecovery/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("2.0.4.0")]
```suggestion
[assembly: AssemblyVersion("2.0.0.0")]
```
Keep assembly version unchanged until a breaking change

2019-12-23 05:08 UTC, isra-fel approved these changes

2019-12-23 05:47 UTC, merged