Add customization for Connection Monitor V1/V2 in SDK
Azure/azure-sdk-for-net pull request #9255
Opened 2019-12-26 20:17 UTC by hofattahMicrosoft

The following SDK code changes add a customization APIs that are to be used by powershell cmdlets that can keep the customers using the connection monitor V1 APIs. This is to keep backward compatibility for users if they want to use either connection monitor V1 or connection monitor V2.

2019-12-27 02:08 UTC, anton-evseev requested changes

2019-12-27 02:08 UTC, number213 commented on sdk/network/Microsoft.Azure.Management.Network/src/Microsoft.Azure.Management.Network.csproj
> +		<Version>20.0.0-preview</Version>
Please revert this change. We'll update SDK version later with the new release

2019-12-27 02:08 UTC, number213 commented on sdk/network/Microsoft.Azure.Management.Network/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("20.0.0.0")]
Please revert this change. We'll update SDK version later with the new release

2019-12-27 18:43 UTC, anton-evseev approved these changes

2019-12-27 18:58 UTC, hofattahMicrosoft commented
Hi Sdk team,

Can you approve this PR for SDK?

Thanks
Hossam

From: Anton Evseev <notifications@github.com>
Sent: Friday, December 27, 2019 10:43 AM
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Hossam Fattah <hofattah@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] Add customization for Connection Monitor V1/V2 in SDK (#9255)


@number213 approved this pull request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F9255%3Femail_source%3Dnotifications%26email_token%3DAMDHYAOMOD5W5PBDHQ3CKN3Q2ZEDRA5CNFSM4J7PSA22YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCQJ5JKY%23pullrequestreview-336843947&data=02%7C01%7Chofattah%40microsoft.com%7Cd211bd1a3f454ea376b508d78afc9bda%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637130689857626365&sdata=4BooYUUwnrwXcz2LMkIVbz0%2FqoRUga7lv5sTOBspMxM%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMDHYAJCPAWEI5AKSXCROMLQ2ZEDRANCNFSM4J7PSA2Q&data=02%7C01%7Chofattah%40microsoft.com%7Cd211bd1a3f454ea376b508d78afc9bda%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637130689857626365&sdata=c0dZi9nJwIv%2FykjYXJTmcdZ4ai8dH8V7yV74fd05gEU%3D&reserved=0>.

2019-12-27 19:00 UTC, hofattahMicrosoft commented
Hello Erich:

Can you please approve this SDK PR?

It has customization APIs for Connection monitors V1/V2?

https://github.com/Azure/azure-sdk-for-net/pull/9255

Thanks
Hossam

From: Anton Evseev <notifications@github.com>
Sent: Friday, December 27, 2019 10:43 AM
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Hossam Fattah <hofattah@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] Add customization for Connection Monitor V1/V2 in SDK (#9255)


@number213 approved this pull request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F9255%3Femail_source%3Dnotifications%26email_token%3DAMDHYAOMOD5W5PBDHQ3CKN3Q2ZEDRA5CNFSM4J7PSA22YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCQJ5JKY%23pullrequestreview-336843947&data=02%7C01%7Chofattah%40microsoft.com%7Cd211bd1a3f454ea376b508d78afc9bda%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637130689857626365&sdata=4BooYUUwnrwXcz2LMkIVbz0%2FqoRUga7lv5sTOBspMxM%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMDHYAJCPAWEI5AKSXCROMLQ2ZEDRANCNFSM4J7PSA2Q&data=02%7C01%7Chofattah%40microsoft.com%7Cd211bd1a3f454ea376b508d78afc9bda%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637130689857626365&sdata=c0dZi9nJwIv%2FykjYXJTmcdZ4ai8dH8V7yV74fd05gEU%3D&reserved=0>.

2019-12-30 08:02 UTC, isra-fel approved these changes

2019-12-30 08:02 UTC, merged

2020-01-04 01:47 UTC, hofattahMicrosoft commented
Hello Yeming,

Can you please approve this PR:

https://github.com/Azure/azure-sdk-for-net/pull/9313

It small change that removes validation not needed any more for CmV2.

Thanks
Hossam

From: Yeming Liu <notifications@github.com>
Sent: Monday, December 30, 2019 12:02 AM
To: Azure/azure-sdk-for-net <azure-sdk-for-net@noreply.github.com>
Cc: Hossam Fattah <hofattah@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/azure-sdk-for-net] Add customization for Connection Monitor V1/V2 in SDK (#9255)


Merged #9255<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F9255&data=02%7C01%7Chofattah%40microsoft.com%7C5f54be04b4b34569eefa08d78cfe9c41%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637132897484830745&sdata=2HHuBG92U5nC8vxE4XyZT0tbe%2B0PZwg6grfU9i7dMv8%3D&reserved=0> into master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F9255%3Femail_source%3Dnotifications%26email_token%3DAMDHYAM6TYJG3JFZ5NE4T3DQ3GTJFA5CNFSM4J7PSA22YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVWTQOMQ%23event-2913404722&data=02%7C01%7Chofattah%40microsoft.com%7C5f54be04b4b34569eefa08d78cfe9c41%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637132897484830745&sdata=Sbg22DdeZHHmB5c07%2BoQdVKmSmVifgg75%2Fpn3%2F5zKwU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMDHYAOGTKEID4BUHNYMNE3Q3GTJFANCNFSM4J7PSA2Q&data=02%7C01%7Chofattah%40microsoft.com%7C5f54be04b4b34569eefa08d78cfe9c41%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637132897484840739&sdata=uXHGilfn%2BQ1kEFgIffkI1doaSJYA6DwvCxI82uWYTGQ%3D&reserved=0>.