[Peering] create new api version 2020-01-01-preview
Azure/azure-sdk-for-net pull request #9654
Opened 2020-01-27 21:55 UTC by rileymckenna

Added Registered Asn
Added Legacy Peering filter by Asn
Added filter to peering service countries
Added Sku to peering type
Added type to direct peering enum
Changed how contact details are stored
Added Sku to peering service

[Awaiting PR Merge](https://github.com/Azure/azure-rest-api-specs/pull/8140)

2020-02-10 18:44 UTC, rileymckenna commented
SPEC PR merged

2020-02-11 13:53 UTC, isra-fel requested changes
Hi @rileymckenna please see my inline comments. Thanks!

2020-02-11 13:53 UTC, isra-fel commented on sdk/peering/Microsoft.Azure.Management.Peering/src/Microsoft.Azure.Management.Peering.csproj
> +		<PackageTags>Azure Peering;Peering_2020-01-01-preview;</PackageTags>
Tags of API version should be in your module's `AzSdk.RP.props` file

2020-02-11 13:53 UTC, isra-fel commented on sdk/peering/Microsoft.Azure.Management.Peering/src/Microsoft.Azure.Management.Peering.csproj
> +	<![CDATA[New features:   Adding Registered ASN operations. ]]>
Please list your change logs in one `<![CDATA[` ... `]]>`  block. You can take Network's csproj as an example

2020-02-11 13:53 UTC, isra-fel commented on sdk/peering/Microsoft.Azure.Management.Peering/src/Microsoft.Azure.Management.Peering.csproj
> +	<![CDATA[New features:   Adding Registered ASN operations. ]]>
Please list your change logs in one `<![CDATA[` ... `]]>`  block. You can take Network's csproj as an example

2020-02-11 13:53 UTC, isra-fel commented on sdk/peering/Microsoft.Azure.Management.Peering/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.13.0.0")]
Use the same version as in csproj
```suggestion
[assembly: AssemblyVersion("2.0.0.0")]
```

2020-02-11 13:53 UTC, isra-fel commented on sdk/peering/Microsoft.Azure.Management.Peering/src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("0.13.0.0")]
```suggestion
[assembly: AssemblyFileVersion("2.0.0.0")]
```

2020-02-11 13:53 UTC, isra-fel commented on src/SDKs/_metadata/peering_resource-manager.txt
> +2020-01-23 19:30:24 UTC
This file should be in `/eng/mgmt/mgmtmetadata/`
Please make sure you generate your code by running `generate.ps1` (not autorest directly). And if the problem still goes on, try [updating build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools)

2020-02-25 07:26 UTC, isra-fel approved these changes

2020-02-25 07:26 UTC, merged