Regenerate 2019-10-01 SDK for Tag API
Azure/azure-sdk-for-net pull request #9803
Opened 2020-02-04 22:36 UTC by Grayer123

Updated Generated code;
Updated tag related scenario tests;
Updated assembly version and release notes.

Links to the swagger spec review PR:
[Azure/azure-rest-api-specs#8258](https://github.com/Azure/azure-rest-api-specs/pull/8258) [Updating the descriptions of newly added tags API related operations for better docs]

2020-02-04 22:52 UTC, hamidtirmizi approved these changes

2020-02-05 01:52 UTC, isra-fel requested changes
Hi @Grayer123 , since you've changed the API version, please update the tags in [AzSdk.RP.props](https://github.com/Azure/azure-sdk-for-net/blob/d2b8316e98e526dd768b12f487ae44331c738a2b/sdk/resources/Microsoft.Azure.Management.Resource/AzSdk.RP.props) . Other changes look good to me. Thanks

2020-02-05 02:39 UTC, Grayer123 commented
> Hi @Grayer123 , since you've changed the API version, please update the tags in [AzSdk.RP.props](https://github.com/Azure/azure-sdk-for-net/blob/d2b8316e98e526dd768b12f487ae44331c738a2b/sdk/resources/Microsoft.Azure.Management.Resource/AzSdk.RP.props) . Other changes look good to me. Thanks

Hello @isra-fel, we did not change the API version this time:
It's just a small refinement related to this [pr:Dotnet SDK changes for 2019-10-01 Tags API for resources and subscriptions (changed API version here)](https://github.com/Azure/azure-sdk-for-net/pull/9345). 

We changed the assembly version is because there was a [pr: [Deployment Scripts] Update .NET SDK version](https://github.com/Azure/azure-sdk-for-net/pull/9788) in between, this one changed the assembly version to 3.2.

2020-02-05 06:26 UTC, isra-fel approved these changes
Looks good to me

2020-02-05 06:27 UTC, merged