Move Server Azure AD from 2014-04-01 to 2019-06-01-preview
Azure/azure-sdk-for-net pull request #9959
Opened 2020-02-13 19:39 UTC by amolagar5

Move Server Azure AD from 2014-04-01 to 2019-06-01-preview

2020-02-13 22:19 UTC, jsquire submitted a review, later dismissed

2020-02-13 22:19 UTC, jsquire commented on sdk/eventhub/Azure.Messaging.EventHubs/samples/Azure.Messaging.EventHubs.Samples.csproj
> +
This file appears to be very out of date.   These changes would cause issues and seem orthogonal to the stated purpose of the PR.   Please revert.

2020-02-13 22:19 UTC, jsquire commented on sdk/eventhub/Azure.Messaging.EventHubs/tests/Azure.Messaging.EventHubs.Tests.csproj
> +
This file appears to be very out of date.   These changes would cause issues and seem orthogonal to the stated purpose of the PR.   Please revert.

2020-02-14 20:34 UTC, jaredmoo approved these changes

2020-02-18 19:57 UTC, jsquire commented
Thanks!

2020-02-21 01:38 UTC, isra-fel reviewed
- Swagger needs to be merged first.
- After it's merged, please regenerate with the spec in the official repo. And make sure the metadata txt is checked in, more [(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

Thanks

2020-02-24 17:44 UTC, isra-fel requested changes
Hi @amolagar5 Just one thing: the changes to `sdk/appconfiguration/Azure.Data.AppConfiguration/src/Azure.Data.AppConfiguration.csproj` and `tools/PS-VSPrompt.lnk` should not be in this PR. Others look good to me.

Thanks

2020-02-24 17:44 UTC, isra-fel commented on sdk/appconfiguration/Azure.Data.AppConfiguration/src/Azure.Data.AppConfiguration.csproj
> +    <Version>1.0.0-preview</Version>
The file belongs to AppConfiguration. I don't suppose this change should be checked in.

2020-02-24 17:44 UTC, isra-fel commented on sdk/appconfiguration/Azure.Data.AppConfiguration/src/Azure.Data.AppConfiguration.csproj
> +    <Version>1.0.0-preview</Version>
It's `1.0.0` on master.

2020-02-25 07:36 UTC, isra-fel approved these changes

2020-02-25 08:25 UTC, isra-fel approved these changes
@amolagar5  After #10134 was merged master branch had conflict with this PR, mainly in the release notes of csproj file.
I've resolved the conflict, and we just need to wait for the CI to run again.

cc @emgu-ms

2020-02-25 09:19 UTC, isra-fel commented
/azp run net - mgmt - ci

2020-02-25 10:08 UTC, merged